hubSide/force-app/main/default/objects/Case/fields/Attente_client_final__c.field-meta.xml
<CustomField>
    <fullName>Attente_client_final__c</fullName>
    <formula>&apos;&apos; 
&amp;
IF(
    AND(TEXT(Asset.Etat_paiement__c) = &quot;unpaid&quot;, Pouss_par_Salesforce__c = false),
    IMAGE(&quot;/resource/AttentePaiement&quot;, &quot;Paiement&quot; , 32, 32) &amp; &apos; &apos;, 
    &apos;&apos;
) 
&amp;
IF(
    TEXT(Attente_Prime__c) = &quot;Oui&quot;,
    IMAGE(&quot;/resource/Franchise&quot;, &quot;Prime&quot;, 32, 32) &amp; &apos; &apos;, 
    &apos;&apos;
)
&amp;
IF(
    AND(TEXT(Attente_documents__c) != &quot;Valid&quot;,TEXT(Attente_documents__c) != &quot;Received&quot;),
    IMAGE(&quot;/resource/AttenteDocument&quot;, &quot;Document&quot;, 32, 32) &amp; &apos; &apos;,
    &apos;&apos;
) 
&amp;
IF(
    TEXT(Autre_attente__c) = &quot;Oui&quot;,
    IMAGE(&quot;/resource/AutreAttente&quot;, &quot;Autre&quot;, 32, 32),
    &apos;&apos;
)
&amp;
IF(
     Attente_colis__c  = True,
    IMAGE(&quot;/resource/Livraison&quot;, &quot;Livraison&quot;, 32, 32),
    &apos;&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attente client</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Attente_documents__c.field-meta.xml
<CustomField>
    <fullName>Attente_documents__c</fullName>
    <label>Attente documents</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
                <label>Reçu(s)</label>
            </value>
            <value>
                <fullName>Valid</fullName>
                <label>Valide(s)</label>
            </value>
            <value>
                <fullName>Expected</fullName>
                <default>true</default>
                <label>Attendu(s)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/TECH_MissingDocs__c.field-meta.xml
<CustomField>
    <fullName>TECH_MissingDocs__c</fullName>
    <description>Liste des pièces justificatives attendues</description>
    <label>TECH_MissingDocs</label>
    <length>2000</length>
    <type>Html</type>
</CustomField>

hubSide/force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/Piece_justificative_Sinistre__c.object-meta.xml
<CustomObject>
    <label>Pièce justificative Sinistre</label>
    <nameField>
        <label>Pièce justificative Sinistre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pièces justificatives Sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Technique Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document__c.Related_sinistre__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/LongTitle__c.field-meta.xml
<CustomField>
    <fullName>LongTitle__c</fullName>
    <description>Intitulé complet de la pièce justificative à destination des communications clients</description>
    <label>Intitulé</label>
    <length>400</length>
    <type>LongTextArea</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/NoTradable__c.field-meta.xml
<CustomField>
    <fullName>NoTradable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non négociable</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Validite_document__c.field-meta.xml
<CustomField>
    <fullName>Validite_document__c</fullName>
    <label>Validité du document</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expected</fullName>
                <default>true</default>
                <label>1-Attendue</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <label>2-Reçu</label>
            </value>
            <value>
                <fullName>Valid</fullName>
                <label>3-Valide</label>
            </value>
            <value>
                <fullName>NotNeeded</fullName>
                <label>4-Plus réclamé</label>
            </value>
            <value>
                <fullName>Invalid</fullName>
                <label>5-Non valide</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/classes/PieceJustificativeTriggerHelper.cls
/***
* @author Ariane Tanguy (GFI)
* @date 23/09/2020
* @description Helper class for PieceJustificative
*/

public class PieceJustificativeTriggerHelper {
    
    /***
	* @description Get the related case
	* @param newPJList - new pj lsit
	* @return Map<Id, Case>
	*/
    public static Map<Id, Case> getRelatedCase(List<Piece_justificative_Sinistre__c> newPJList){
        
        // Get the case ids
        Set<id> caseIdSet = new Set<id>();
        for(Piece_justificative_Sinistre__c p : newPJList){
            caseIdSet.add(p.Case__c);
        }
        
        Map<id, Case> relatedCaseIdMap = new Map<id, Case>([SELECT id, 
                                                            Attente_documents__c,
                                                            Attente_client_final__c, 
                                                            Status, 
                                                            TECH_MissingDocs__c
                                                            FROM Case
                                                            WHERE id IN: caseIdSet]);        
        return relatedCaseIdMap;
    }
    
    /***
	* @description Get the other related piece justificatives
	* @param newPJList - new pj list
	* @return Map<Id, Piece_justificative_Sinistre__c>
	*/
    public static Map<id, List<Piece_justificative_Sinistre__c>> getOtherRelatedPJ(List<Piece_justificative_Sinistre__c> newPJList){
        
        // Get the case ids
        Set<id> caseIdSet = new Set<id>();
        for(Piece_justificative_Sinistre__c p : newPJList){
            caseIdSet.add(p.Case__c);
        }
        
        List<Piece_justificative_Sinistre__c> relatedPJList = [SELECT id, LongTitle__c, Case__c, 
                                                               Validite_document__c, Name,NoTradable__c
                                                               FROM Piece_justificative_Sinistre__c
                                                               WHERE Case__c IN: caseIdSet
                                                               AND Validite_document__c = 'Expected'];
        
        // Map the other related pj to their case
        Map<id, List<Piece_justificative_Sinistre__c>> otherRelatedPJMap = new Map<id, List<Piece_justificative_Sinistre__c>>();
        for(Piece_justificative_Sinistre__c p : relatedPJList){
            if(!otherRelatedPJMap.keySet().contains(p.Case__c)){
                List<Piece_justificative_Sinistre__c> tmpList = new List<Piece_justificative_Sinistre__c>();
                otherRelatedPJMap.put(p.Case__c, tmpList);
            }
            otherRelatedPJMap.get(p.Case__c).add(p);
        }
        
        return otherRelatedPJMap;
    }
    
    /***
	* @description Get the related case info
	* @param newPJList - new pj lsit
	* @return Map<Id, Case>
	*/
    public static Map<Id, List<id>> getRelatedDocument(List<Piece_justificative_Sinistre__c> newPJList){
        
        // Get the case ids
        Set<id> documentIdSet = new Set<id>();
        for(Piece_justificative_Sinistre__c p : newPJList){
            if(p.Document__c != NULL){
            	documentIdSet.add(p.Document__c);
            }
        }
        
        return getRelatedContentDocument(documentIdSet);
    }
    
    /***
	* @description Get the related case info
	* @param newPJList - new pj lsit
	* @return Map<Id, Case>
	*/
    public static Map<Id, List<id>> getRelatedDocument(List<Piece_justificative_Sinistre__c> newPJList, 
                                                      Map<id, Piece_justificative_Sinistre__c> oldPJMap){
        
        // Get the case ids
        Set<id> documentIdSet = new Set<id>();
        for(Piece_justificative_Sinistre__c p : newPJList){
            if(p.Document__c != oldPJMap.get(p.id).Document__c && 
               p.Document__c != NULL){
                documentIdSet.add(p.Document__c);
            }
        }
        
        return getRelatedContentDocument(documentIdSet);
    }
    
    /***
	* @description Get the related case info
	* @param newPJList - new pj lsit
	* @return Map<Id, Case>
	*/
    private static Map<Id, List<id>> getRelatedContentDocument(Set<id> documentIdSet){
        
        Map<Id, List<id>> documentIdPjIdMap = new Map<Id, List<id>>();
        
        if(documentIdSet.size() > 0){
            
            // Find out the ContentDocumentIds
            List<ContentDocumentLink> cdLinkList = [SELECT id, ContentDocumentId, LinkedEntityId
                                                    FROM ContentDocumentLink 
                                                    WHERE LinkedEntityId IN: documentIdSet];
            
            // Find out the ContentVersionIds
            Set<id> contentDocumentIdSet = new Set<id>();
            for(ContentDocumentLink cdLink : cdLinkList){
                contentDocumentIdSet.add(cdLink.ContentDocumentId);
            }        
            List<ContentVersion> contentVersionList = [SELECT id, ContentDocumentId
                                                       FROM ContentVersion
                                                       WHERE ContentDocumentId IN: contentDocumentIdSet];
            
            // Map it to its contentDocumentId
            Map<id, ContentVersion> CDocIdCVMap = new Map<id, ContentVersion>();
            for(ContentVersion cv : contentVersionList){
                CDocIdCVMap.put(cv.ContentDocumentId, cv);
            }
            
            // Map the whole thing
            for(ContentDocumentLink cdLink : cdLinkList){
                if(!documentIdPjIdMap.keySet().contains(cdLink.LinkedEntityId)){
                    List<id> tmpList = new List<id>();
                    documentIdPjIdMap.put(cdLink.LinkedEntityId, tmpList);
                }
                documentIdPjIdMap.get(cdLink.LinkedEntityId).add(cdLink.ContentDocumentId);
                documentIdPjIdMap.get(cdLink.LinkedEntityId).add(CDocIdCVMap.get(cdLink.ContentDocumentId).id);
            }            
        }
        return documentIdPjIdMap;
    }
    
    /***
	* @description Get the piece jointes related to the case
	* @param newPJList - new pj
	* @param oldPJMap - old pj
	* @return Map<Id, String>
	*/
    public static List<Piece_justificative_Sinistre__c> getRelatedPJ(List<Piece_justificative_Sinistre__c> newPJList, 
                                                                     Map<id, Piece_justificative_Sinistre__c> oldPJMap){
        
        // Get only the changed status pj
        Set<id> changedPJList = new Set<id>();
        for(Piece_justificative_Sinistre__c p : newPJList){
            
            // If the validity is changed AND the it matches two status
            if(p.Validite_document__c != oldPJMap.get(p.id).Validite_document__c){
                changedPJList.add(p.Case__c);
            }
        }
                                                        
        system.debug('-- changedPJList ' + changedPJList);
        
        // Query the pj
        List<Piece_justificative_Sinistre__c> pjList = new List<Piece_justificative_Sinistre__c>();
        if(changedPJList.size() > 0){
            pjList = [SELECT id, Case__c, 
                      Validite_document__c,NoTradable__c
                      FROM Piece_justificative_Sinistre__c
                      WHERE Case__c IN: changedPJList];
        }
        
        pjList.addAll(newPJList);
        system.debug('-- pjList ' + pjList);
                                                                         
        return pjList;
    }
}