hubSide/force-app/main/default/objects/Case/fields/Attente_action_GS__c.field-meta.xml
<CustomField>
    <fullName>Attente_action_GS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attente d&apos;une action GS ?</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Document__c/fields/Related_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Related_sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Document__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attached</fullName>
                <label>Rattaché</label>
            </value>
            <value>
                <fullName>Codified</fullName>
                <label>Codifié</label>
            </value>
            <value>
                <fullName>Removed</fullName>
                <label>Supprimé</label>
            </value>
            <value>
                <fullName>Identifié</fullName>
                <isActive>false</isActive>
                <label>Identifié</label>
            </value>
            <value>
                <fullName>Scanned</fullName>
                <isActive>false</isActive>
                <label>Scanned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/classes/DocumentTriggerHelper.cls
/***
* @author Ariane Tanguy (GFI)
* @date 19/11/2020
* @description Helper class for DocumentTrigger
*/

public class DocumentTriggerHelper {
    
    /***
	* @description Get all the related cases
	* @param newDocumentList - list of document
	* @return Map<id, Case> - Map of the case and their id
	*/
    public static Map<id, Case> getRelatedCase(List<Document__c> newDocumentList){
        
        // List sinistre ids
        Set<id> sinistreIdSet = new Set<id>();
        for(Document__c d : newDocumentList){
            sinistreIdSet.add(d.Related_sinistre__c);
        }
        
        // Query the emprunts
        return new Map<id, Case>([SELECT id, Attente_action_GS__c
                                  FROM Case
                                  WHERE Id IN: sinistreIdSet
                                  AND Attente_action_GS__c = TRUE]);
    }
    
    /***
	* @description Get all the related cases
	* @param documentList - list of document
	* @return Map<id, Case> - Map of the case and their id
	*/
    public static List<Document__c> getRelatedDocument(List<Document__c> newDocumentList, Set<id> caseIdSet){
        
        // Query the documents
        List<Document__c> otherDocumentList = [SELECT id, Related_sinistre__c, Statut__c
                                               FROM Document__c
                                               WHERE Related_sinistre__c IN: caseIdSet
                                               AND id NOT IN: newDocumentList];
        otherDocumentList.addAll(newDocumentList);
        
        return otherDocumentList;
    }
}