hubSide/force-app/main/default/objects/Case/fields/Attente_action_GS__c.field-meta.xml
<CustomField>
    <fullName>Attente_action_GS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attente d&apos;une action GS ?</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Document__c/fields/Related_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Related_sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Document__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attached</fullName>
                <label>Rattaché</label>
            </value>
            <value>
                <fullName>Codified</fullName>
                <label>Codifié</label>
            </value>
            <value>
                <fullName>Removed</fullName>
                <label>Supprimé</label>
            </value>
            <value>
                <fullName>Identifié</fullName>
                <isActive>false</isActive>
                <label>Identifié</label>
            </value>
            <value>
                <fullName>Scanned</fullName>
                <isActive>false</isActive>
                <label>Scanned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/classes/DocumentTriggerHandler.cls
/***
* @author Ariane Tanguy (GFI)
* @date 19/11/2020
* @description Handler class for DocumentTrigger
*/

public class DocumentTriggerHandler {
    
    static final String STATUS_ATTACHED = 'Attached';
	static final String ORIGINDOCUMENT_MAIL = 'Courrier';
        
    /***
	* @description Update attente GS on case
	* @param newDocumentList - list of all new document
	* @param relatedCaseMap - Map of the related cases and their id
	*/
    public static void updateCaseOnUpdate(List<Document__c> newDocumentList, Map<id, Case> relatedCaseMap){
        
        // Map document to their sinistre
        Map<id, List<Document__c>> sinistreIdDocumentListMap = new Map<id, List<Document__c>>();
        for(Document__c d : newDocumentList){
            if(!sinistreIdDocumentListMap.keySet().contains(d.Related_sinistre__c)){
                List<Document__c> tmpList = new List<Document__c>();
                sinistreIdDocumentListMap.put(d.Related_sinistre__c, tmpList);
            }
            sinistreIdDocumentListMap.get(d.Related_sinistre__c).add(d);
        }
        
        // Check whether all the documents are codified
        List<Case> caseToUpdate = new List<Case>();
        for(Id sinistreId : sinistreIdDocumentListMap.keySet()){
            
            // Loop over all the documents in that sinistre
            Boolean allCodified = TRUE;
            for(Document__c d : sinistreIdDocumentListMap.get(sinistreId)){
                if(d.Statut__c != 'codified'){
                    allCodified = FALSE;
                }
            }
            
            // If all the documents are codified, update the flag
            if(allCodified 
               && relatedCaseMap.keySet().contains(sinistreId)){
                   relatedCaseMap.get(sinistreId).Attente_action_GS__c = FALSE;
                   caseToUpdate.add(relatedCaseMap.get(sinistreId));
               }
        }
        
        update caseToUpdate;
    }
    
    /***
	* @description delete content documents related to Document__c if removed status
	* @param newDocumentList - list of all new document
	*/
    public static void deleteContentDocumentIfRemovedStatus(List<Document__c> newDocumentList){
        for(Document__c d : newDocumentList){
            if (d.Statut__c == 'Removed') {
                // Find content document Ids
                List<ContentDocumentLink> cdLinkList = [SELECT ContentDocumentId
                                                        FROM ContentDocumentLink 
                                                        WHERE LinkedEntityId =: d.id];

                Set<id> contentDocumentIdSet = new Set<id>();
                for(ContentDocumentLink cdLink : cdLinkList){
                    contentDocumentIdSet.add(cdLink.ContentDocumentId);
                }
                
                // Find content documents
                List<ContentDocument> cdList = [SELECT Id
                                                FROM ContentDocument
                                                WHERE Id IN: contentDocumentIdSet];


                if (cdList.size() > 0) {
                    delete cdList;
                }
            }
        }        
    }
}