hubSide/force-app/main/default/objects/Case/fields/Date_reception__c.field-meta.xml
<CustomField>
    <fullName>Date_reception__c</fullName>
    <description>Date de réception côté SFAM du document papier.</description>
    <label>Date de réception</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>CASE(
    Record_Type_Name__c, 
    &apos;Sinistre&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;INS&quot; + &apos;&apos; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
        &quot;TMP&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;SinistreBApp&apos;, Num_sinistre_B_Appli__c,
    &apos;Sinistre clôturé&apos;, Subject, 
    &apos;Déclaration&apos;, CaseNumber, 
    &apos;SAV&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;SAV&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;), 
        &quot;DEM&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;Réclamation&apos;, &quot;REC&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
				&apos;Demande&apos;, &quot;DEM&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
    &apos;GED&apos; + &apos;&apos; + RIGHT(CaseNumber, 6)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro de la requête</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Colis__c/Colis__c.object-meta.xml
<CustomObject>
    <label>Colis</label>
    <nameField>
        <label>Colis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Colis__c/fields/Date_reception__c.field-meta.xml
<CustomField>
    <fullName>Date_reception__c</fullName>
    <label>Date réception</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Equipement_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Equipement_sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement sinistré</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Equipement_sinistre__c.Sinistre__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sinistre__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Equipement_sinistre__c</referenceTo>
    <relationshipLabel>Colis</relationshipLabel>
    <relationshipName>Colis</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Nom_transporteur__c.field-meta.xml
<CustomField>
    <fullName>Nom_transporteur__c</fullName>
    <label>Nom transporteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nom_transporteur</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>IF(
    OR(
        ISNULL(Sinistre__c), 
        ISBLANK(Sinistre__c)
    ), 
    &apos;&apos;, 
    Sinistre__r.Numero_sinistre__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro du sinistre</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Colis</relationshipLabel>
    <relationshipName>Colis</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Colis_Status</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/recordTypes/Colis_reception.recordType-meta.xml
<RecordType>
    <fullName>Colis_reception</fullName>
    <active>true</active>
    <description>Dédié à la réception des colis</description>
    <label>Colis réception</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>Sinistre__r.Numero_sinistre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro du sinistre</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sous_statut__c.field-meta.xml
<CustomField>
    <fullName>Sous_statut__c</fullName>
    <label>Sous-statut</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Statut_equipement__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>EquipSin_SousStatut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Statut_equipement__c.field-meta.xml
<CustomField>
    <fullName>Statut_equipement__c</fullName>
    <label>Statut equipement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EquipSin_Statut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Colis_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Reçu</fullName>
    </customValue>
    <customValue>
        <fullName>Transféré/Emis</fullName>
    </customValue>
    <customValue>
        <fullName>Transféré/Reçu</fullName>
    </customValue>
    <customValue>
        <fullName>Affecté</fullName>
    </customValue>
    <customValue>
        <fullName>Rattaché</fullName>
    </customValue>
    <customValue>
        <fullName>Non identifiable</fullName>
    </customValue>
    <customValue>
        <fullName>Invalid</fullName>
        <label>Invalidé</label>
    </customValue>
    <customValue>
        <fullName>Retourner colis</fullName>
    </customValue>
    <customValue>
        <fullName>Colis Retourné</fullName>
    </customValue>
    <masterLabel>Colis_Status</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/globalValueSets/EquipSin_SousStatut.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A stocker</fullName>
    </customValue>
    <customValue>
        <fullName>Stocké</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir - Retour client</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir - Retour SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir du stock</fullName>
    </customValue>
    <customValue>
        <fullName>Sortie PSM</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir PSM</fullName>
    </customValue>
    <customValue>
        <fullName>A retourner PSM</fullName>
    </customValue>
    <customValue>
        <fullName>A dispatcher</fullName>
    </customValue>
    <customValue>
        <fullName>En cours d&apos;expertise</fullName>
    </customValue>
    <customValue>
        <fullName>En attente GS</fullName>
    </customValue>
    <customValue>
        <fullName>En cours</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - A expédier</fullName>
    </customValue>
    <customValue>
        <fullName>Préparation</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - A conserver</fullName>
    </customValue>
    <customValue>
        <fullName>Retourné client</fullName>
    </customValue>
    <customValue>
        <fullName>Repaired</fullName>
        <label>Réparé</label>
    </customValue>
    <customValue>
        <fullName>Unrepairable</fullName>
        <label>Irréparable</label>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <label>Annulé</label>
    </customValue>
    <customValue>
        <fullName>Via prime</fullName>
    </customValue>
    <customValue>
        <fullName>Via prime magasin</fullName>
    </customValue>
    <customValue>
        <fullName>Réception client</fullName>
    </customValue>
    <customValue>
        <fullName>Conservé SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - à expédier (Irréparable)</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - à expédier (Annulé)</fullName>
    </customValue>
    <customValue>
        <fullName>Préparation - Irréparable/Annulé</fullName>
    </customValue>
    <customValue>
        <fullName>Retour Client</fullName>
    </customValue>
    <customValue>
        <fullName>Retour SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>Sorti PSM</fullName>
        <isActive>false</isActive>
        <label>Sorti PSM</label>
    </customValue>
    <description>Liste des sous-statuts de l&apos;équipement sinistré - Equipement sinistre sub status list</description>
    <masterLabel>EquipSin_SousStatut</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/globalValueSets/Nom_transporteur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ChronopostSav</fullName>
        <label>Chronopost - SAV</label>
    </customValue>
    <customValue>
        <fullName>ChronopostReparation</fullName>
        <label>Chronopost - Réparation</label>
    </customValue>
    <customValue>
        <fullName>LaPosteSav</fullName>
        <label>La Poste -  SAV</label>
    </customValue>
    <customValue>
        <fullName>LaPosteReparation</fullName>
        <label>La Poste -  Réparation</label>
    </customValue>
    <customValue>
        <fullName>BulkParcelsSav</fullName>
        <label>Colis en vrac - SAV</label>
    </customValue>
    <customValue>
        <fullName>BulkParcelsReparation</fullName>
        <label>Colis en vrac - Réparation</label>
    </customValue>
    <customValue>
        <fullName>Chronopost</fullName>
        <isActive>false</isActive>
        <label>Chronopost</label>
    </customValue>
    <customValue>
        <fullName>La Poste</fullName>
        <isActive>false</isActive>
        <label>La Poste</label>
    </customValue>
    <masterLabel>Nom transporteur</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/Flow_BarcodeScan.cls
/***
* @author Ariane Tanguy (GFI)
* @date 02/11/2020
* @description Lightning Component Controller
*/

public with sharing class Flow_BarcodeScan {
    
    /***
    * @description Create n chronopost colis + m other colis
    * @param barcodeString - List chronopost ids
    * @param colisQuantity - Number of other colis to create
    * @param receptionDate - reception date
    * @param newStats - new status
    * @return Integer - Number of chronopost colis created
    */
    @AuraEnabled
    public static integer processBarcode(String barcodeString, 
                                         integer colisQuantity, 
                                         date receptionDate, 
                                         string senderName, 
                                         string newStatus, 
                                         string newSousStatus,
                                         String newOwnerId){
        
        // Split the barcodes
        List<String> barcodeList = new List<String>();
        if(barcodeString != NULL){
         	barcodeList = barcodeString.split('\r\n');
        }

        // Check for duplicates
        Set<String> barcodeSet = new Set<String>();
		for(String b : barcodeList){
            barcodeSet.add(b);
        }
        
        // Check whether we need to create colis or to change status
        Integer numberObjectCreated = barcodeSet.size();
        if(!(newStatus == NULL ||
             newStatus == '')){
                 numberObjectCreated = updateStatus(barcodeSet, newStatus, newSousStatus);
             }
        if(!(newOwnerId == NULL ||
             newOwnerId == '')){
               numberObjectCreated = updateOwner(barcodeSet, newOwnerId);
           }
		createColis(barcodeSet, colisQuantity, receptionDate, senderName);

        return barcodeList.size() - numberObjectCreated;
    }
    
    /***
    * @description Create n chronopost colis + m other colis
    * @param barcodeString - List chronopost ids
    * @param colisQuantity - Number of other colis to create
    * @param receptionDate - reception date
    * @return Integer - Number of chronopost colis created
    */
    private static void createColis(Set<String> barcodeSet, integer colisQuantity, date receptionDate, string senderName){
        
        id receivedColisRT = UtilityClassHelper.getCreatedRecordType('Colis_reception');
        List<Colis__c> colisToInsert = new List<Colis__c>();
        
        // Loop over the barcodes
        for(String barcode : barcodeSet){
            Colis__c c = new Colis__c();
            c.Name = barcode;
            c.Date_reception__c = receptionDate;
            c.Nom_transporteur__c = senderName;
            c.RecordTypeId = receivedColisRT;
            colisToInsert.add(c);
        }
        
        // and over the colis to create
        for(integer i = 0; i<colisQuantity; i++){
            Colis__c c = new Colis__c();
            c.Name = receptionDate + senderName + i;
            c.Date_reception__c = receptionDate;
            c.Nom_transporteur__c = senderName;
            c.RecordTypeId = receivedColisRT;
            colisToInsert.add(c);
        }
        
        insert colisToInsert;
    }
    
    /***
    * @description Update n status
    * @param barcodeString - List chronopost ids
    * @param newStatus - new status
    * @return Integer - Number of object updated
    */
    private static integer updateStatus(Set<String> barcodeSet, string newStatus, string newSousStatus){
        
        // Query the Equipement Sinistre
        List<Equipement_sinistre__c> equipmentSinistreList = [SELECT id, Statut_equipement__c, Sous_statut__c
                                                              FROM Equipement_sinistre__c
                                                              WHERE Sinistre__r.Numero_sinistre__c IN: barcodeSet];
        
        // And change their status
        for(Equipement_sinistre__c e : equipmentSinistreList){
            e.Statut_equipement__c = newStatus;
            if(newSousStatus != NULL){
                e.Sous_statut__c = newSousStatus;
            }
        }
        
        update equipmentSinistreList;        
        return equipmentSinistreList.size();
    }
    
    /***
    * @description Update n status
    * @param barcodeString - List chronopost ids
    * @param newOwnerId - new owner id
    * @return Integer - Number of object updated
    */
    private static integer updateOwner(Set<String> barcodeSet, String newOwnerId){
        
        // Query the Equipement Sinistre
        List<Colis__c> colisList = [SELECT id, ownerId
                                    FROM Colis__c
                                    WHERE Name IN: barcodeSet];
        
        // And change their status
        for(Colis__c c : colisList){
            c.ownerId = newOwnerId;
            c.Statut__c = 'Affecté';
        }
        update colisList;        
        return colisList.size();
    }
}