hubSide/force-app/main/default/objects/Case/fields/Date_reception__c.field-meta.xml
<CustomField>
    <fullName>Date_reception__c</fullName>
    <description>Date de réception côté SFAM du document papier.</description>
    <label>Date de réception</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>CASE(
    Record_Type_Name__c, 
    &apos;Sinistre&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;INS&quot; + &apos;&apos; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
        &quot;TMP&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;SinistreBApp&apos;, Num_sinistre_B_Appli__c,
    &apos;Sinistre clôturé&apos;, Subject, 
    &apos;Déclaration&apos;, CaseNumber, 
    &apos;SAV&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;SAV&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;), 
        &quot;DEM&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;Réclamation&apos;, &quot;REC&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
				&apos;Demande&apos;, &quot;DEM&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
    &apos;GED&apos; + &apos;&apos; + RIGHT(CaseNumber, 6)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro de la requête</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Typologie_Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Typologie_Sinistre__c</fullName>
    <label>Typologie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Case_Typologie</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Colis__c/Colis__c.object-meta.xml
<CustomObject>
    <label>Colis</label>
    <nameField>
        <label>Colis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Colis__c/fields/Date_reception__c.field-meta.xml
<CustomField>
    <fullName>Date_reception__c</fullName>
    <label>Date réception</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Equipement_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Equipement_sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement sinistré</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Equipement_sinistre__c.Sinistre__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sinistre__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Equipement_sinistre__c</referenceTo>
    <relationshipLabel>Colis</relationshipLabel>
    <relationshipName>Colis</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Nom_transporteur__c.field-meta.xml
<CustomField>
    <fullName>Nom_transporteur__c</fullName>
    <label>Nom transporteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nom_transporteur</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>IF(
    OR(
        ISNULL(Sinistre__c), 
        ISBLANK(Sinistre__c)
    ), 
    &apos;&apos;, 
    Sinistre__r.Numero_sinistre__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro du sinistre</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Colis</relationshipLabel>
    <relationshipName>Colis</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/recordTypes/Colis_reception.recordType-meta.xml
<RecordType>
    <fullName>Colis_reception</fullName>
    <active>true</active>
    <description>Dédié à la réception des colis</description>
    <label>Colis réception</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>Sinistre__r.Numero_sinistre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro du sinistre</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Statut_equipement__c.field-meta.xml
<CustomField>
    <fullName>Statut_equipement__c</fullName>
    <label>Statut equipement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EquipSin_Statut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/recordTypes/Equipement_a_reparer.recordType-meta.xml
<RecordType>
    <fullName>Equipement_a_reparer</fullName>
    <active>true</active>
    <description>Equipement à réparer parce que cassé ou oxydé</description>
    <label>Equipement Réparation</label>
</RecordType>

hubSide/force-app/main/default/globalValueSets/Case_Typologie.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Broken</fullName>
        <label>Casse</label>
    </customValue>
    <customValue>
        <fullName>Pickpocketed</fullName>
        <label>Vol toute cause</label>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
        <label>Perte</label>
    </customValue>
    <customValue>
        <fullName>Oxidised</fullName>
        <label>Oxydation</label>
    </customValue>
    <customValue>
        <fullName>Robbed</fullName>
        <label>Vol Caractérisé</label>
    </customValue>
    <customValue>
        <fullName>ReturnedByCarrier</fullName>
        <label>Retour transporteur</label>
    </customValue>
    <customValue>
        <fullName>LostByCarrier</fullName>
        <label>Perte transporteur</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterRepair</fullName>
        <label>Dysfonctionnement suite à réparation</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterExchange</fullName>
        <label>Dysfonctionnement suite à échange</label>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <label>Autres</label>
    </customValue>
    <customValue>
        <fullName>ClaimCreation</fullName>
        <label>Création Réclamation</label>
    </customValue>
    <customValue>
        <fullName>ClaimFollowUp</fullName>
        <label>Suivi Réclamation</label>
    </customValue>
    <customValue>
        <fullName>AccidentCreation</fullName>
        <label>Création Sinistre</label>
    </customValue>
    <description>Liste de toutes les typologies possibles (Sinistre, SAV, Demande)</description>
    <masterLabel>Case_Typologie</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/globalValueSets/Nom_transporteur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ChronopostSav</fullName>
        <label>Chronopost - SAV</label>
    </customValue>
    <customValue>
        <fullName>ChronopostReparation</fullName>
        <label>Chronopost - Réparation</label>
    </customValue>
    <customValue>
        <fullName>LaPosteSav</fullName>
        <label>La Poste -  SAV</label>
    </customValue>
    <customValue>
        <fullName>LaPosteReparation</fullName>
        <label>La Poste -  Réparation</label>
    </customValue>
    <customValue>
        <fullName>BulkParcelsSav</fullName>
        <label>Colis en vrac - SAV</label>
    </customValue>
    <customValue>
        <fullName>BulkParcelsReparation</fullName>
        <label>Colis en vrac - Réparation</label>
    </customValue>
    <customValue>
        <fullName>Chronopost</fullName>
        <isActive>false</isActive>
        <label>Chronopost</label>
    </customValue>
    <customValue>
        <fullName>La Poste</fullName>
        <isActive>false</isActive>
        <label>La Poste</label>
    </customValue>
    <masterLabel>Nom transporteur</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/Flow_BarcodeScanTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 03/11/2020
* @description Flow_BarcodeScan test class
* @Class Flow_BarcodeScanTest
*/

@isTest
public class Flow_BarcodeScanTest {
    
    /***
	* @description From a barcode scan, create colis
	* @LightningComponent Flow_BarcodeScan
	*/
    @isTest
    public static void createColisTest(){
        
        // Play the flow
        Integer numberDuplicates = Flow_BarcodeScan.processBarcode(NULL, 1, system.today(), 'LaPosteSav', '', NULL, '');
        
        // Check the result
        List<Colis__c> colisList = [SELECT id FROM Colis__c];
        system.assertEquals(colisList.size(), 1, 
                           'The number of colis created is not the expected one - This is wrong');
    }
    
    /***
	* @description From a barcode, update a status
	* @LightningComponent Flow_BarcodeScan
	*/
    @isTest
    public static void updateStatusTest(){
        
        // Create a client
        Account a = TestFactory.createClient();
        insert a;
        
        // Create a sinistre
        id caseSinistreId = UtilityClassHelper.getCreatedRecordType('Sinistre');
        Case c = new Case();
        c.AccountId = a.id;
        c.Typologie_Sinistre__c = 'Broken';
        c.RecordTypeId = caseSinistreId;
        insert c;
        
        c = [SELECT Numero_sinistre__c FROM Case WHERE id =: c.id];
        
        // Create an equipement sinistré
        Equipement_sinistre__c e = new Equipement_sinistre__c();
        e.RecordTypeId = UtilityClassHelper.getCreatedRecordType('Equipement_a_reparer');
        e.Sinistre__c = c.id;
        insert e;    
                
        // Play the flow
        Integer numberDuplicates = Flow_BarcodeScan.processBarcode(c.Numero_sinistre__c, 0, NULL, NULL, 'En Attente Réception', '', '');
        
        e = [SELECT id, Statut_equipement__c FROM Equipement_sinistre__c WHERE id =: e.id];
        system.assertEquals(e.Statut_equipement__c, 'En Attente Réception', 
                           'The equipement status hasnt changed - This is wrong');
    }
    
    /***
	* @description From a barcode, update the owner
	* @LightningComponent Flow_BarcodeScan
	*/
    @isTest
    public static void updateOwnerTest(){
        
        // Create a colis
        id receivedColisRT = UtilityClassHelper.getCreatedRecordType('Colis_reception');
        Colis__c c = new Colis__c();
        c.Name = 'XREXWWE4584';
        c.Date_reception__c = system.today();
        c.Nom_transporteur__c = 'ChronopostSav';
        c.RecordTypeId = receivedColisRT;
        insert c;
        
        // Create a fake user
        User u = TestFactory.createUser();
        u.ProfileId = [SELECT Id
                       FROM Profile
                       WHERE Name =: 'SFAM Expertise'].id;
        insert u;        
        
        // Play the flow
        Integer numberDuplicates = Flow_BarcodeScan.processBarcode('XREXWWE4584', NULL, NULL, NULL, NULL, NULL, u.id);
        
        c = [SELECT id, ownerId, owner.Name FROM Colis__c WHERE id =: c.id];
        system.assertEquals(c.OwnerId, u.id, 
                           'The colis owner hasnt changed - This is wrong ' + c.owner.Name);
    }
    
}