hubSide/force-app/main/default/objects/Case/fields/Equipement_client__c.field-meta.xml
<CustomField>
    <fullName>Equipement_client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement client</label>
    <referenceTo>vlocity_ins__AssetInsuredItem__c</referenceTo>
    <relationshipLabel>Demandes associées</relationshipLabel>
    <relationshipName>Demandes_associees</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>CASE(
    Record_Type_Name__c, 
    &apos;Sinistre&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;INS&quot; + &apos;&apos; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
        &quot;TMP&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;SinistreBApp&apos;, Num_sinistre_B_Appli__c,
    &apos;Sinistre clôturé&apos;, Subject, 
    &apos;Déclaration&apos;, CaseNumber, 
    &apos;SAV&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;SAV&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;), 
        &quot;DEM&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;Réclamation&apos;, &quot;REC&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
				&apos;Demande&apos;, &quot;DEM&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
    &apos;GED&apos; + &apos;&apos; + RIGHT(CaseNumber, 6)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro de la requête</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/TECH_CheckChoixClientValidate__c.field-meta.xml
<CustomField>
    <fullName>TECH_CheckChoixClientValidate__c</fullName>
    <formula>IF(OR(TECH_NumberIndemEch__c==0,
					AND(TECH_NumberIndemEch__c&gt;0,
     NOT(ISBLANK(TECH_ExchangeDateChoosed__c)),
	    NOT(ISBLANK(TECH_MatriceCoutChoiceExchange__c)))
						),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_CheckChoixClientValidate</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/TECH_ExchangeDateChoosed__c.field-meta.xml
<CustomField>
    <fullName>TECH_ExchangeDateChoosed__c</fullName>
    <description>Use to save the date of equipement sinistre</description>
    <label>TECH_ExchangeDateChoosed</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/TECH_MatriceCoutChoiceExchange__c.field-meta.xml
<CustomField>
    <fullName>TECH_MatriceCoutChoiceExchange__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use to know if the customer have validate exchange (link to TECH_CheckChoixClientValidate__c)</description>
    <label>TECH_MatriceCoutChoiceExchange</label>
    <referenceTo>Matrice_cout_equipement__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/TECH_NumberAlertWaiting__c.field-meta.xml
<CustomField>
    <fullName>TECH_NumberAlertWaiting__c</fullName>
    <label>TECH_NumberAlertWaiting</label>
    <summaryFilterItems>
        <field>Alert__c.Status__c</field>
        <operation>equals</operation>
        <value>Waiting</value>
    </summaryFilterItems>
    <summaryForeignKey>Alert__c.Case__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/TECH_NumberIndemToProcess__c.field-meta.xml
<CustomField>
    <fullName>TECH_NumberIndemToProcess__c</fullName>
    <formula>TECH_NumberIndemApprob__c +  TECH_NumberIndemCreated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_NumberIndemToProcess</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Typologie_Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Typologie_Sinistre__c</fullName>
    <label>Typologie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Case_Typologie</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Brand_not_recognized__c.field-meta.xml
<CustomField>
    <fullName>Brand_not_recognized__c</fullName>
    <description>Stores the name of the brand if BrandId__c is blank</description>
    <label>Nom de la marque non reconnu</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Category_not_recognized__c.field-meta.xml
<CustomField>
    <fullName>Category_not_recognized__c</fullName>
    <description>Stores the category if Product2Id__c is blank</description>
    <label>Catégorie du modèle non reconnu</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>itemCategory</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Equipement_client__c.field-meta.xml
<CustomField>
    <fullName>Equipement_client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement client</label>
    <referenceTo>vlocity_ins__AssetInsuredItem__c</referenceTo>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/IMEI_non_identifiable__c.field-meta.xml
<CustomField>
    <fullName>IMEI_non_identifiable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IMEI non identifiable</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Name_not_recognized__c.field-meta.xml
<CustomField>
    <fullName>Name_not_recognized__c</fullName>
    <description>Stores the name of the model if Product2Id__c is blank</description>
    <label>Nom du modèle non reconnu</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>Sinistre__r.Numero_sinistre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro du sinistre</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <description>Telephony operator</description>
    <label>Opérateur</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OperatorCountry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Operators</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/OperatorCountry__c.field-meta.xml
<CustomField>
    <fullName>OperatorCountry__c</fullName>
    <label>Pays de l&apos;opérateur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>vlocity_ins__Country</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>L&apos;équipement produit unique associé</description>
    <label>Catalogue équipement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.vlocity_ins__RecordTypeName__c</field>
            <operation>equals</operation>
            <value>itemCatalog</value>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.IsInsurance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Equipement sinistre</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/recordTypes/Equipement_vole_perdu.recordType-meta.xml
<RecordType>
    <fullName>Equipement_vole_perdu</fullName>
    <active>true</active>
    <description>Equipement non réparable car volé ou perdu</description>
    <label>Equipement Echange</label>
</RecordType>

hubSide/force-app/main/default/objects/Matrice_cout_equipement__c/Matrice_cout_equipement__c.object-meta.xml
<CustomObject>
    <label>Matrice coût equipement</label>
    <nameField>
        <label>Matrice coût equipement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matrice coût equipements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Matrice_cout_equipement__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Catalogue équipement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.vlocity_ins__RecordTypeName__c</field>
            <operation>equals</operation>
            <value>itemCatalog</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Matrice coût equipements</relationshipLabel>
    <relationshipName>Matrice_co_t_equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/Mouvements_financiers__c.object-meta.xml
<CustomObject>
    <label>Calcul Indemnisation</label>
    <nameField>
        <label>Nom du mouvement financier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calcul Indemnisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Calcul Indemnisations</relationshipLabel>
    <relationshipName>Mouvements_financiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Cout_choisi__c.field-meta.xml
<CustomField>
    <fullName>Cout_choisi__c</fullName>
    <label>Coût choisi</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primes</fullName>
            </value>
            <value>
                <fullName>Echange</fullName>
            </value>
            <value>
                <fullName>Réparation</fullName>
            </value>
            <value>
                <fullName>Règlement par le client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Libelle__c.field-meta.xml
<CustomField>
    <fullName>Libelle__c</fullName>
    <description>Libéllé libre à saisir par le TC ou le GS</description>
    <label>Libellé</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <description>Identification du montant du mouvement</description>
    <label>Montant</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crée</fullName>
                <default>true</default>
                <label>Crée</label>
            </value>
            <value>
                <fullName>En cours d&apos;approbation</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Demande en cours</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Rejeté</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Terminé</label>
            </value>
            <value>
                <fullName>Invalidated</fullName>
                <label>Invalidé</label>
            </value>
            <value>
                <fullName>En attente d&apos;approbation</fullName>
                <isActive>false</isActive>
                <label>En attente d&apos;approbation</label>
            </value>
            <value>
                <fullName>Encaissé</fullName>
                <isActive>false</isActive>
                <label>Encaissé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Case_Typologie.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Broken</fullName>
        <label>Casse</label>
    </customValue>
    <customValue>
        <fullName>Pickpocketed</fullName>
        <label>Vol toute cause</label>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
        <label>Perte</label>
    </customValue>
    <customValue>
        <fullName>Oxidised</fullName>
        <label>Oxydation</label>
    </customValue>
    <customValue>
        <fullName>Robbed</fullName>
        <label>Vol Caractérisé</label>
    </customValue>
    <customValue>
        <fullName>ReturnedByCarrier</fullName>
        <label>Retour transporteur</label>
    </customValue>
    <customValue>
        <fullName>LostByCarrier</fullName>
        <label>Perte transporteur</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterRepair</fullName>
        <label>Dysfonctionnement suite à réparation</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterExchange</fullName>
        <label>Dysfonctionnement suite à échange</label>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <label>Autres</label>
    </customValue>
    <customValue>
        <fullName>ClaimCreation</fullName>
        <label>Création Réclamation</label>
    </customValue>
    <customValue>
        <fullName>ClaimFollowUp</fullName>
        <label>Suivi Réclamation</label>
    </customValue>
    <customValue>
        <fullName>AccidentCreation</fullName>
        <label>Création Sinistre</label>
    </customValue>
    <description>Liste de toutes les typologies possibles (Sinistre, SAV, Demande)</description>
    <masterLabel>Case_Typologie</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/globalValueSets/itemCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessory</fullName>
        <label>Accessoire</label>
    </customValue>
    <customValue>
        <fullName>HomeAppliance</fullName>
        <label>Electroménager</label>
    </customValue>
    <customValue>
        <fullName>Multimedia</fullName>
    </customValue>
    <customValue>
        <fullName>Telephony</fullName>
        <label>Téléphonie</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <default>true</default>
        <label>Autre</label>
    </customValue>
    <description>List of every category for an item catalog</description>
    <masterLabel>Catégorie de l&apos;équipement</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/globalValueSets/Operators.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BASE</fullName>
    </customValue>
    <customValue>
        <fullName>BEANDYOU</fullName>
        <label>BE AND  YOU</label>
    </customValue>
    <customValue>
        <fullName>BOUYGUES</fullName>
    </customValue>
    <customValue>
        <fullName>CORIOLIS</fullName>
    </customValue>
    <customValue>
        <fullName>CREDITMUTUEL</fullName>
        <label>CREDIT MUTUEL</label>
    </customValue>
    <customValue>
        <fullName>FREE</fullName>
    </customValue>
    <customValue>
        <fullName>JOMOBILE</fullName>
    </customValue>
    <customValue>
        <fullName>LAPOSTEMOBILE</fullName>
        <label>LA POSTE MOBILE</label>
    </customValue>
    <customValue>
        <fullName>NRJ</fullName>
    </customValue>
    <customValue>
        <fullName>ORANGE</fullName>
    </customValue>
    <customValue>
        <fullName>REDSFR</fullName>
        <label>RED SFR</label>
    </customValue>
    <customValue>
        <fullName>SFR</fullName>
    </customValue>
    <customValue>
        <fullName>SIMPLEO</fullName>
    </customValue>
    <customValue>
        <fullName>SOSH</fullName>
    </customValue>
    <customValue>
        <fullName>VIRGIN</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER</fullName>
        <label>AUTRE</label>
    </customValue>
    <description>Telephony operators</description>
    <masterLabel>Operators</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/EquipementSinistreTriggerHelper.cls
/***
* @author Nicolas Brancato (GFI)
* @date 19/02/2020
* @description Helper class for EquipementSinistreTrigger
*/

public class EquipementSinistreTriggerHelper {    
    
    static final String DAMAGEDEQUIPMENTRECORDTYPE_ECHANGE = 'Equipement_vole_perdu';
    static final String BAPPLISTOCKNAME_SFAMRESA = 'SFAM 3';
    
    /***
	* @description Get the related case
	* @param newEquipSinList - list of new Equipement_sinistre__c
	* @return Map<id, Case>
	*/
    public Map<id, Case> getRelatedCase(List<Equipement_sinistre__c> newEquipSinList){
        
        Set<id> relatedCaseIdSet = new Set<id>();
        for(Equipement_sinistre__c e : newEquipSinList){
            relatedCaseIdSet.add(e.Sinistre__c);
        }
        
        Map<id, Case> relatedCaseMap = new Map<id, Case>([SELECT id, 
                                                          Numero_sinistre__c,
                                                          TECH_CheckChoixClientValidate__c, 
                                                          TECH_NumberIndemToProcess__c,
                                                          TECH_NumberAlertWaiting__c,
                                                          TECH_ExchangeDateChoosed__c,
                                                          TECH_MatriceCoutChoiceExchange__c, 
                                                          Typologie_sinistre__c,
                                                          Record_type_Name__c
                                                          FROM Case
                                                          WHERE id IN: relatedCaseIdSet]);
        return relatedCaseMap;
    }
    
    /***
	* @description Get the related case
	* @param newEquipSinList - list of new Equipement_sinistre__c
	* @return Map<id, Case>
	*/
    public Map<Id, Equipement_sinistre__c> getRelatedEquipSin(List<Equipement_sinistre__c> newEquipSinList){
        
        Set<id> relatedCaseIdSet = new Set<id>();
        for(Equipement_sinistre__c e : newEquipSinList){
            relatedCaseIdSet.add(e.Sinistre__c);
        }
        
        List<Equipement_sinistre__c> relatedEquipSin = [SELECT id, Sinistre__c
                                                        FROM Equipement_sinistre__c
                                                        WHERE Sinistre__c IN: relatedCaseIdSet
                                                        AND id NOT IN: newEquipSinList];
        
        Map<Id, Equipement_sinistre__c> relatedEquipSinMap = new Map<Id, Equipement_sinistre__c>();
        for(Equipement_sinistre__c e : relatedEquipSin){
            relatedEquipSinMap.put(e.Sinistre__c, e);
        }
        return relatedEquipSinMap;
    }
    
    /***
	* @description Get the related insured item
	* @param newEquipSinList - list of new Equipement_sinistre__c
	* @return Map<id, vlocity_ins__AssetInsuredItem__c>
	*/
    public Map<id, vlocity_ins__AssetInsuredItem__c> getRelatedInsuredItem(List<Equipement_sinistre__c> newEquipSinList){
        
        Set<id> relatedInsuredItemIdSet = new Set<id>();
        for(Equipement_sinistre__c e : newEquipSinList){
            relatedInsuredItemIdSet.add(e.Equipement_client__c);
        }
        
        Map<id, vlocity_ins__AssetInsuredItem__c> relatedInsuredItempMap = 
            new Map<id, vlocity_ins__AssetInsuredItem__c>([SELECT id, Name, Date_achat__c, 
                                                           Brand_not_recognized__c, Category_not_recognized__c, 
                                                           Dernier_sinistre__c, Etat__c, Famille_produit_sinistre__c, 
                                                           LastReparationDate__c, Motif__c, Name_not_recognized__c, 
                                                           Numero_de_serie__c, IMEI_non_identifiable__c, 
                                                           Operator__c, OperatorCountry__c, Product2Id__c, 
                                                           RecordTypeId, ReparationCount__c,  
                                                           vlocity_ins__PolicyAssetId__c
                                                           FROM vlocity_ins__AssetInsuredItem__c
                                                           WHERE id IN: relatedInsuredItemIdSet]);
        return relatedInsuredItempMap;
    }
    
    /***
	* @description Get the related calcul indemnisation
	* @param newEquipSinList - list of new Equipement_sinistre__c
	* @return Map<id, Case>
	*/
    public Map<id, List<Mouvements_financiers__c>> getRelatedCalcIndemn(List<Equipement_sinistre__c> newEquipSinList){
        
        Set<id> relatedCaseIdSet = new Set<id>();
        for(Equipement_sinistre__c e : newEquipSinList){
            relatedCaseIdSet.add(e.Sinistre__c);
        }
        
        List<Mouvements_financiers__c> calcIndemnList = [SELECT id, Case__c, Statut__c, Cout_choisi__c, 
                                                         Libelle__c, Montant__c, Type_mouvement__c
                                                         FROM Mouvements_financiers__c
                                                         WHERE Case__c IN: relatedCaseIdSet
                                                         AND (Cout_choisi__c = 'Réparation' 
                                                              OR Cout_choisi__c = 'Echange')
                                                         AND Statut__c != 'Completed' 
                                                         AND Statut__c != 'Rejected'
                                                         AND Statut__c != 'Invalidated'];
        
        Map<id, List<Mouvements_financiers__c>> relatedCalcIndemnMap = new Map<id, List<Mouvements_financiers__c>>();
        for(Mouvements_financiers__c c : calcIndemnList){
            if(!relatedCalcIndemnMap.keySet().contains(c.Case__c)){
                List<Mouvements_financiers__c> tmpList = new List<Mouvements_financiers__c>();
                relatedCalcIndemnMap.put(c.Case__c, tmpList);
            }
            relatedCalcIndemnMap.get(c.Case__c).add(c);
        }
        
        return relatedCalcIndemnMap;
    }

    /***
	* @description Get the related calcul indemnisation
	* @param newEquipSinList - list of new Equipement_sinistre__c
	* @return Map<id, Case>
	*/
    public Map<id, List<Mouvements_financiers__c>> getRelatedCalcIndemnRepa(List<Equipement_sinistre__c> newEquipSinList){
        
        Set<id> relatedCaseIdSet = new Set<id>();
        for(Equipement_sinistre__c e : newEquipSinList){
            relatedCaseIdSet.add(e.Sinistre__c);
        }
        
        List<Mouvements_financiers__c> calcIndemnList = [SELECT id, Case__c, Statut__c, Cout_choisi__c, 
                                                         Libelle__c, Montant__c, Type_mouvement__c
                                                         FROM Mouvements_financiers__c
                                                         WHERE Case__c IN: relatedCaseIdSet
                                                         AND Statut__c != 'Completed' 
                                                         AND Statut__c != 'Rejected'
                                                         AND Statut__c != 'Invalidated'];
        
        Map<id, List<Mouvements_financiers__c>> relatedCalcIndemnMap = new Map<id, List<Mouvements_financiers__c>>();
        for(Mouvements_financiers__c c : calcIndemnList){
            if(!relatedCalcIndemnMap.keySet().contains(c.Case__c)){
                List<Mouvements_financiers__c> tmpList = new List<Mouvements_financiers__c>();
                relatedCalcIndemnMap.put(c.Case__c, tmpList);
            }
            relatedCalcIndemnMap.get(c.Case__c).add(c);
        }
        
        return relatedCalcIndemnMap;
    }
    
    /***
	* @description Get the related calcul indemnisation
	* @param newEquipSinList - list of new Equipement_sinistre__c
	* @return Map<id, Case>
	*/
    public Map<id, Product2> getRelatedCatalogueProduit(List<Equipement_sinistre__c> newEquipSinList){
        
        Set<id> relatedMCEIdSet = new Set<id>();
        for(Equipement_sinistre__c e : newEquipSinList){
            relatedMCEIdSet.add(e.ChooseEqp__c);
        }
        
        List<Product2> relatedCatalogueList = [SELECT id, MatriceId__c, CreatedDate
                                               FROM Product2
                                               WHERE MatriceId__c IN: relatedMCEIdSet];
        
        Map<id, Product2> relatedCatalogueProduitMap = new Map<id, Product2>();
        for(Product2 p : relatedCatalogueList){
            if(!relatedCatalogueProduitMap.keySet().contains(p.MatriceId__c) ||
               (relatedCatalogueProduitMap.keySet().contains(p.MatriceId__c) 
                && p.CreatedDate < relatedCatalogueProduitMap.get(p.MatriceId__c).CreatedDate)){
                    relatedCatalogueProduitMap.put(p.MatriceId__c, p);
                }
        }
        
        return relatedCatalogueProduitMap;
    }
     
    /***
	* @description Trigger callout to Bappli stock after reception of the order. 
	* This method is called from the flow NewActionEquipSin when the value "Destockage sur stock Réservé" is selected
	* @param List<id> eqsId eqsId set in the flow NewActionEquipSin
	* @return null
	*/
    @InvocableMethod(label = 'Get Stock From Bappli' 
                     description = 'Trigger callout to Bappli to check stock')
    public static void getStockAfterOrderReception(List<id> eqsId){
        
        Equipement_sinistre__c eqs;
        eqs = [SELECT Id, ChooseEqp__r.Id_externe__c, Grade__c, Operator__c, Sinistre__c, ClientChoiceDate__c 
               FROM Equipement_sinistre__c
               WHERE Id =: eqsId[0]
               AND RecordType.DeveloperName =: DAMAGEDEQUIPMENTRECORDTYPE_ECHANGE];
        if(eqs != null){
        	BAppliCallout.getFromStock(BAPPLISTOCKNAME_SFAMRESA, eqs.ChooseEqp__r.Id_externe__c, eqs.Grade__c, eqs.Operator__c, eqs.Id, eqs.Sinistre__c);
        }
    }
}