hubSide/force-app/main/default/objects/Case/fields/Equipement_client__c.field-meta.xml
<CustomField>
    <fullName>Equipement_client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement client</label>
    <referenceTo>vlocity_ins__AssetInsuredItem__c</referenceTo>
    <relationshipLabel>Demandes associées</relationshipLabel>
    <relationshipName>Demandes_associees</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>CASE(
    Record_Type_Name__c, 
    &apos;Sinistre&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;INS&quot; + &apos;&apos; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
        &quot;TMP&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;SinistreBApp&apos;, Num_sinistre_B_Appli__c,
    &apos;Sinistre clôturé&apos;, Subject, 
    &apos;Déclaration&apos;, CaseNumber, 
    &apos;SAV&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;SAV&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;), 
        &quot;DEM&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;Réclamation&apos;, &quot;REC&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
				&apos;Demande&apos;, &quot;DEM&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
    &apos;GED&apos; + &apos;&apos; + RIGHT(CaseNumber, 6)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro de la requête</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/TECH_ExchangeDateChoosed__c.field-meta.xml
<CustomField>
    <fullName>TECH_ExchangeDateChoosed__c</fullName>
    <description>Use to save the date of equipement sinistre</description>
    <label>TECH_ExchangeDateChoosed</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/TECH_MatriceCoutChoiceExchange__c.field-meta.xml
<CustomField>
    <fullName>TECH_MatriceCoutChoiceExchange__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use to know if the customer have validate exchange (link to TECH_CheckChoixClientValidate__c)</description>
    <label>TECH_MatriceCoutChoiceExchange</label>
    <referenceTo>Matrice_cout_equipement__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Typologie_Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Typologie_Sinistre__c</fullName>
    <label>Typologie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Case_Typologie</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/SAV.recordType-meta.xml
<RecordType>
    <fullName>SAV</fullName>
    <active>true</active>
    <businessProcess>SAV</businessProcess>
    <description>Case créé après un sinistre, dans le cas où l&apos;équipement sinistré n&apos;ait pas été correctement réparé/remplacé.</description>
    <label>SAV</label>
</RecordType>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Overwritten by the flow &quot;InsuredItem_Name&quot;</description>
    <label>Catégorie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>itemCategory</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/ChooseEqp__c.field-meta.xml
<CustomField>
    <fullName>ChooseEqp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modèle-choisi</label>
    <referenceTo>Matrice_cout_equipement__c</referenceTo>
    <relationshipLabel>Equipement sinistre (Equipement C)</relationshipLabel>
    <relationshipName>Equipement_sinistre1</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/ChosenEquip__c.field-meta.xml
<CustomField>
    <fullName>ChosenEquip__c</fullName>
    <description>Matrice coût équipement choisie par le client - Matrice chosen by the client</description>
    <label>Choix client</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Choix 1</fullName>
            </value>
            <value>
                <fullName>Choix 2</fullName>
            </value>
            <value>
                <fullName>Choix 3</fullName>
            </value>
            <value>
                <fullName>RefusingProposals</fullName>
                <label>Refus des propositions</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/ClientChoiceDate__c.field-meta.xml
<CustomField>
    <fullName>ClientChoiceDate__c</fullName>
    <label>Date choix client</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Equipement_client__c.field-meta.xml
<CustomField>
    <fullName>Equipement_client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement client</label>
    <referenceTo>vlocity_ins__AssetInsuredItem__c</referenceTo>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/EquipmentAmount__c.field-meta.xml
<CustomField>
    <fullName>EquipmentAmount__c</fullName>
    <label>Valeur Echange</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/ExpeditionDate__c.field-meta.xml
<CustomField>
    <fullName>ExpeditionDate__c</fullName>
    <label>Date d&apos;expédition</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>Sinistre__r.Numero_sinistre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro du sinistre</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>L&apos;équipement produit unique associé</description>
    <label>Catalogue équipement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.vlocity_ins__RecordTypeName__c</field>
            <operation>equals</operation>
            <value>itemCatalog</value>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.IsInsurance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Equipement sinistre</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/RealCost__c.field-meta.xml
<CustomField>
    <fullName>RealCost__c</fullName>
    <label>Coût Réel</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/serialNumberType__c.field-meta.xml
<CustomField>
    <fullName>serialNumberType__c</fullName>
    <label>Type du numéro de série</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>serialNumberType</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/SerieNumberEC__c.field-meta.xml
<CustomField>
    <fullName>SerieNumberEC__c</fullName>
    <label>Numero de serie (IMEI)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Statut_equipement__c.field-meta.xml
<CustomField>
    <fullName>Statut_equipement__c</fullName>
    <label>Statut equipement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EquipSin_Statut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Valeur_reparation__c.field-meta.xml
<CustomField>
    <fullName>Valeur_reparation__c</fullName>
    <label>Valeur réparation</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/recordTypes/Equipement_a_reparer.recordType-meta.xml
<RecordType>
    <fullName>Equipement_a_reparer</fullName>
    <active>true</active>
    <description>Equipement à réparer parce que cassé ou oxydé</description>
    <label>Equipement Réparation</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/recordTypes/Equipement_vole_perdu.recordType-meta.xml
<RecordType>
    <fullName>Equipement_vole_perdu</fullName>
    <active>true</active>
    <description>Equipement non réparable car volé ou perdu</description>
    <label>Equipement Echange</label>
</RecordType>

hubSide/force-app/main/default/objects/Matrice_cout_equipement__c/Matrice_cout_equipement__c.object-meta.xml
<CustomObject>
    <label>Matrice coût equipement</label>
    <nameField>
        <label>Matrice coût equipement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matrice coût equipements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Matrice_cout_equipement__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Catalogue équipement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.vlocity_ins__RecordTypeName__c</field>
            <operation>equals</operation>
            <value>itemCatalog</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Matrice coût equipements</relationshipLabel>
    <relationshipName>Matrice_co_t_equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Matrice_cout_equipement__c/fields/Valeur_reparation__c.field-meta.xml
<CustomField>
    <fullName>Valeur_reparation__c</fullName>
    <label>Valeur réparation</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/Mouvements_financiers__c.object-meta.xml
<CustomObject>
    <label>Calcul Indemnisation</label>
    <nameField>
        <label>Nom du mouvement financier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calcul Indemnisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Cout_choisi__c.field-meta.xml
<CustomField>
    <fullName>Cout_choisi__c</fullName>
    <label>Coût choisi</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primes</fullName>
            </value>
            <value>
                <fullName>Echange</fullName>
            </value>
            <value>
                <fullName>Réparation</fullName>
            </value>
            <value>
                <fullName>Règlement par le client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crée</fullName>
                <default>true</default>
                <label>Crée</label>
            </value>
            <value>
                <fullName>En cours d&apos;approbation</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Demande en cours</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Rejeté</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Terminé</label>
            </value>
            <value>
                <fullName>Invalidated</fullName>
                <label>Invalidé</label>
            </value>
            <value>
                <fullName>En attente d&apos;approbation</fullName>
                <isActive>false</isActive>
                <label>En attente d&apos;approbation</label>
            </value>
            <value>
                <fullName>Encaissé</fullName>
                <isActive>false</isActive>
                <label>Encaissé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Case_Typologie.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Broken</fullName>
        <label>Casse</label>
    </customValue>
    <customValue>
        <fullName>Pickpocketed</fullName>
        <label>Vol toute cause</label>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
        <label>Perte</label>
    </customValue>
    <customValue>
        <fullName>Oxidised</fullName>
        <label>Oxydation</label>
    </customValue>
    <customValue>
        <fullName>Robbed</fullName>
        <label>Vol Caractérisé</label>
    </customValue>
    <customValue>
        <fullName>ReturnedByCarrier</fullName>
        <label>Retour transporteur</label>
    </customValue>
    <customValue>
        <fullName>LostByCarrier</fullName>
        <label>Perte transporteur</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterRepair</fullName>
        <label>Dysfonctionnement suite à réparation</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterExchange</fullName>
        <label>Dysfonctionnement suite à échange</label>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <label>Autres</label>
    </customValue>
    <customValue>
        <fullName>ClaimCreation</fullName>
        <label>Création Réclamation</label>
    </customValue>
    <customValue>
        <fullName>ClaimFollowUp</fullName>
        <label>Suivi Réclamation</label>
    </customValue>
    <customValue>
        <fullName>AccidentCreation</fullName>
        <label>Création Sinistre</label>
    </customValue>
    <description>Liste de toutes les typologies possibles (Sinistre, SAV, Demande)</description>
    <masterLabel>Case_Typologie</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/globalValueSets/itemCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessory</fullName>
        <label>Accessoire</label>
    </customValue>
    <customValue>
        <fullName>HomeAppliance</fullName>
        <label>Electroménager</label>
    </customValue>
    <customValue>
        <fullName>Multimedia</fullName>
    </customValue>
    <customValue>
        <fullName>Telephony</fullName>
        <label>Téléphonie</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <default>true</default>
        <label>Autre</label>
    </customValue>
    <description>List of every category for an item catalog</description>
    <masterLabel>Catégorie de l&apos;équipement</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/globalValueSets/serialNumberType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>imei</fullName>
        <label>IMEI</label>
    </customValue>
    <customValue>
        <fullName>other</fullName>
        <label>Autre</label>
    </customValue>
    <masterLabel>Type du numéro de série</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/EquipementSinistreTriggerHandler.cls
/***
* @author Nicolas Brancato (GFI)
* @date 19/02/2020
* @description Handler class for EquipementSinistreTrigger
*/

public class EquipementSinistreTriggerHandler {
    
    static final String RT_REPARATION = 'Equipement_a_reparer';
    static final String RT_ECHANGE = 'Equipement_vole_perdu';
    
    /***
    * @description method to handle all before insert automatisms
    * @param newEquipSinList list of new Equipement_sinistre__c
    * @return null
    * @exception none
    */
    public void handleBeforeInsert(List<Equipement_sinistre__c> newEquipSinList, 
                                   Map<id, Case> relatedCaseMap, 
                                   Map<id, Equipement_sinistre__c> relatedEquipSinMap){
        
        Id reparationRT, echangeRT = NULL;
        
        for(Equipement_sinistre__c e : newEquipSinList){
            
            // Update the name
            e.Name = relatedCaseMap.get(e.Sinistre__c).Numero_sinistre__c + '-' + e.Name;
            
            // Check whether the RT is correct
            if(!relatedEquipSinMap.keySet().contains(e.Sinistre__c) &&
               relatedCaseMap.keySet().contains(e.Sinistre__c) && 
               relatedCaseMap.get(e.Sinistre__c).Record_type_name__c != 'SAV'){
                   
                   if(relatedCaseMap.get(e.Sinistre__c).Typologie_sinistre__c == 'Broken' ||
                      relatedCaseMap.get(e.Sinistre__c).Typologie_sinistre__c == 'Oxydised'){
                          if(reparationRT == NULL){
                              reparationRT = UtilityClassHelper.getCreatedRecordType(RT_REPARATION);
                          }
                          e.RecordTypeId = reparationRT;
                      } else {
                          if(echangeRT == NULL){
                              echangeRT = UtilityClassHelper.getCreatedRecordType(RT_ECHANGE);
                          }
                          e.RecordTypeId = echangeRT;
                      }
               }
        }
    }
    
    /***
    * @description Update Valeur reparation on realCost change
    * And update the status when the client made his choice
    * @param newEquipSinList - list of new Equipement_sinistre__c
    * @param oldEquipSinMap - map of old Equipement_sinistre__c
    * @return null
    * @exception none
    */
    public void handleBeforeUpdate(List<Equipement_sinistre__c> newEquipSinList, 
                                   Map<id, Equipement_sinistre__c> oldEquipSinMap, 
                                   Map<id, Case> relatedCaseMap, 
                                   Map<id, vlocity_ins__AssetInsuredItem__c> relatedInsuredItemMap){

        Id DamagedEquipmentRTIdRep = [SELECT id 
                                      FROM Recordtype WHERE 
                                      DeveloperName =: RT_REPARATION].id;

        for(Equipement_sinistre__c e : newEquipSinList){
            
            // Update the name
            if(relatedCaseMap.keySet().contains(e.Sinistre__c) && 
               relatedInsuredItemMap.keySet().contains(e.Equipement_client__c)){
                   e.Name = relatedCaseMap.get(e.Sinistre__c).Numero_sinistre__c + '-' + relatedInsuredItemMap.get(e.Equipement_client__c).Name;
               }
            
            // Check whether the real cost has been updated
            if(e.RealCost__c != null && 
               e.RealCost__c != oldEquipSinMap.get(e.id).RealCost__c && 
               e.RecordTypeId == DamagedEquipmentRTIdRep){
                   
                   // Update the valeur reparation
                   e.Valeur_reparation__c = e.RealCost__c;	
               }
            
            // Check whether the client has made his choice
            if(e.ClientChoiceDate__c != NULL &&
               e.ClientChoiceDate__c != oldEquipSinMap.get(e.id).ClientChoiceDate__c &&
               e.RecordTypeId != DamagedEquipmentRTIdRep && e.ChosenEquip__c != 'RefusingProposals' && e.Statut_equipement__c != 'En commmande' && e.Statut_equipement__c != 'En destockage'){
                   e.Statut_equipement__c = 'Choix client échange';
               }
        }
    }
    
    /***
    * @description Update related InsuredItem + CalcIndemn on equipSin update
    * @param newEquipSinList - list of new Equipement_sinistre__c
    * @param oldEquipSinMap - map of old Equipement_sinistre__c
    * @param relatedInsuredItemMap - related insured item map
    * @return null
    * @exception none
    */
    public void handleEquipSinReparation(List<Equipement_sinistre__c> newEquipSinList, 
                                         Map<id, Equipement_sinistre__c> oldEquipSinMap, 
                                         Map<id, vlocity_ins__AssetInsuredItem__c> relatedInsuredItemMap, 
                                         Map<id, List<Mouvements_financiers__c>> relatedCalcIndemnMap, 
                                         Map<id, Product2> relatedCatalogueProduitMap, 
                                         Map<id, Case> relatedCaseMap){
        
		List<vlocity_ins__AssetInsuredItem__c> insuredItemToUpsertList = new List<vlocity_ins__AssetInsuredItem__c>();
		List<Mouvements_financiers__c> calcIndemToUpdate = new List<Mouvements_financiers__c>();
        Boolean createInsuredItem = false;
        Boolean isEquiSinReparation =false;

        // Loop over the new equipement sinistre
        for(Equipement_sinistre__c e : newEquipSinList){
            
            // Do 
            if(relatedCaseMap.keySet().contains(e.Sinistre__c) && 
               (relatedCaseMap.get(e.Sinistre__c).Record_Type_Name__c == 'Sinistre' ||
                relatedCaseMap.get(e.Sinistre__c).Record_Type_Name__c == 'SAV')){
                    
                    // Check whether the statut got updated
                    if((e.Statut_equipement__c == 'CustomerReception' ||
                        e.Statut_equipement__c == 'Réparé Réception client') &&
                       oldEquipSinMap.get(e.id).Statut_equipement__c != e.Statut_equipement__c &&
                       relatedInsuredItemMap.keySet().contains(e.Equipement_client__c)){                           
                           
                           system.debug('-- e ' + e);
                           
                           // Get the related insured item
                           vlocity_ins__AssetInsuredItem__c i = relatedInsuredItemMap.get(e.Equipement_client__c);

                           if(e.Record_Type_Name__c == 'Equipement_a_reparer'){
                                isEquiSinReparation = true;
                           }
                           else{
                                isEquiSinReparation = false;
                           }
                           
                           // Check the related calcul indemnisation
                           if(relatedCalcIndemnMap.keySet().contains(e.Sinistre__c)){
                               createInsuredItem = false;
                               for(Mouvements_financiers__c m : relatedCalcIndemnMap.get(e.Sinistre__c)){
                                   
                                   // If it's a reparation
                                   if(m.Cout_choisi__c == 'Réparation' && isEquiSinReparation){
                                       m.Statut__c = m.Statut__c != 'Rejected' ? 'Completed' : 'Rejected';
                                       calcIndemToUpdate.add(m);
                                       i.Etat__c = e.Statut_equipement__c == 'CustomerReception' ? 'inactive' : 'Active';
                                       i.Motif__c = 'Réparation';
                                   } else if(!isEquiSinReparation && (m.Cout_choisi__c == 'Echange' || m.Cout_choisi__c == 'Primes')){
                                       // If it's an echange
                                       m.Statut__c = 'Completed';
                                       calcIndemToUpdate.add(m);
                                       i.Etat__c = 'inactive';
                                       i.Motif__c = 'Echange';
                                       createInsuredItem = true;
                                   }
                               }
                           }
                           
                           i.Dernier_sinistre__c = e.Sinistre__c;
                           i.LastReparationDate__c = e.ExpeditionDate__c;
                           i.ReparationCount__c += 1;
                           insuredItemToUpsertList.add(i);
                           
                           if (createInsuredItem) {                           
                               // Create a new insured item
                               vlocity_ins__AssetInsuredItem__c newI = i.clone(false, true, false, false);
                               newI.Category__c = e.Category__c;
                               newI.Date_achat__c = e.ExpeditionDate__c;
                               newI.Dernier_sinistre__c = e.Sinistre__c;
                               newI.Etat__c = 'Active';
                               newI.Famille_produit_sinistre__c = i.Famille_produit_sinistre__c;
                               newI.Origine_equipement__c = 'replacedBySFAM';
                               newI.Matrice_cout_equipement__c = e.ChooseEqp__c;
                               if(relatedCatalogueProduitMap.keySet().contains(e.ChooseEqp__c) && 
                                  e.ChooseEqp__c != NULL){
                                      newI.Product2Id__c = relatedCatalogueProduitMap.get(e.ChooseEqp__c).id; 
                                  }
                               newI.ReparationCount__c = 0;
                               newI.serialNumberType__c = e.serialNumberType__c;
                               newI.Numero_de_serie__c = e.SerieNumberEC__c; // serialNumberType__c;
                               newI.Statut_equipement__c = 'Actif';
                               insuredItemToUpsertList.add(newI);
                           }
                       }
                }
        }
		update calcIndemToUpdate;
        upsert insuredItemToUpsertList;
    }    
    
    /***
    * @description method to handle all after update automatisms
    * @param newEquipSinList list of new Equipement_sinistre__c
    * @param oldEquipSinMap map of old Equipement_sinistre__c
    * @return nul
    * @exception none
    */
    public void handleAfterUpdate(List<Equipement_sinistre__c> newEquipSinList, Map<id, Equipement_sinistre__c> oldEquipSinMap, 
                                         Map<id, List<Mouvements_financiers__c>> relatedCalcIndemnMap){

        Map<Id, Case> mapCase = new Map<Id, Case>();
        List<Equipement_sinistre__c> lstEqs = new List<Equipement_sinistre__c>();
        List<Equipement_sinistre__c> equipSinEchangeList = new List<Equipement_sinistre__c>();
        List<Equipement_sinistre__c> equipSinReparationList = new List<Equipement_sinistre__c>();
        
        for(integer i = 0; i < newEquipSinList.size(); i++){
            
            // Check if the equipement sinistre have a choice date and a matrice equipement 
            if(newEquipSinList[i].ClientChoiceDate__c != null &&
               newEquipSinList[i].ChooseEqp__c != null && 
               newEquipSinList[i].Sinistre__c != null &&
               (oldEquipSinMap.get(newEquipSinList[i].id).ClientChoiceDate__c == null && oldEquipSinMap.get(newEquipSinList[i].id).ChooseEqp__c == null) ||
               (oldEquipSinMap.get(newEquipSinList[i].id).ClientChoiceDate__c != null && oldEquipSinMap.get(newEquipSinList[i].id).ChooseEqp__c == null) ||
               (oldEquipSinMap.get(newEquipSinList[i].id).ClientChoiceDate__c == null && oldEquipSinMap.get(newEquipSinList[i].id).ChooseEqp__c != null)) {
                   Case currentCase = new Case();
                   currentCase.Id = newEquipSinList[i].Sinistre__c;
                   currentCase.TECH_ExchangeDateChoosed__c = newEquipSinList[i].ClientChoiceDate__c;
                   currentCase.TECH_MatriceCoutChoiceExchange__c = newEquipSinList[i].ChooseEqp__c;
                   mapCase.put(newEquipSinList[i].Sinistre__c,currentCase);
                   lstEqs.add(newEquipSinList[i]);
               }
            
            // Check whether the Valeur Echange has changed
            if((newEquipSinList[i].EquipmentAmount__c != null && 
               newEquipSinList[i].EquipmentAmount__c != oldEquipSinMap.get(newEquipSinList[i].id).EquipmentAmount__c) || 
			   newEquipSinList[i].RealCost__c != oldEquipSinMap.get(newEquipSinList[i].id).RealCost__c) { 
                   equipSinEchangeList.add(newEquipSinList[i]);
               }
            
            // Check whether the Valeur Reparation has changed
            if(newEquipSinList[i].Valeur_reparation__c != null && 
               newEquipSinList[i].Valeur_reparation__c != oldEquipSinMap.get(newEquipSinList[i].id).Valeur_reparation__c) { 
                   equipSinReparationList.add(newEquipSinList[i]);
               }
        }
        
        if(!mapCase.isEmpty()){
            update mapCase.values();
            EquipementSinistreTriggerHelper helper = new EquipementSinistreTriggerHelper();
            Map<Id,Case> mapCaseUpdated = helper.getRelatedCase(lstEqs);
            Flow.Interview flow = new Flow.Interview.CASE_Manage_PaiementVersement(new map<String,Object> 
                                                                                   {'VAR_ListCase' => mapCaseUpdated.values()});     
            flow.start();
        }
        
        List<Mouvements_financiers__c> calcIndemnToUpdateList = new List<Mouvements_financiers__c>();
        system.debug('--equipementEchange : '+equipSinEchangeList);
        system.debug('--newEquipSinList : '+newEquipSinList);
                                             
        // Check the Echange calc indemn
        if(!equipSinEchangeList.isEmpty()){
            
            // Check whether there's a calc indemn to update
            // (Only one Equipement_sinistre__c row can be updated at a time)
            if(relatedCalcIndemnMap.keySet().contains(equipSinEchangeList[0].Sinistre__c)){
                for(Mouvements_financiers__c m : relatedCalcIndemnMap.get(equipSinEchangeList[0].Sinistre__c)){
                    if(m.Type_mouvement__c == CalculIndemnisationTriggerHandler.COSTTYPE_INTERNCOSTEXCHANGE){
                           m.Montant__c = equipSinEchangeList[0].RealCost__c == NULL ? equipSinEchangeList[0].EquipmentAmount__c 
                               : equipSinEchangeList[0].RealCost__c;
                           if(m.Statut__c == CalculIndemnisationTriggerHandler.STATUS_DEMANDINPROGRESS) {
                              m.Libelle__c = m.Libelle__c + '\r\n' + 'Mise à jour suite à remontée de stock';
                           }
                          
                           calcIndemnToUpdateList.add(m);
                           break;
                       }
                }
            }
        }
        
        // Check the Reparation calc indemn
        if(!equipSinReparationList.isEmpty()){
            
            // Check whether there's a calc indemn to update
            // (Only one Equipement_sinistre__c row can be updated at a time)
            if(relatedCalcIndemnMap.keySet().contains(equipSinReparationList[0].Sinistre__c)){
                for(Mouvements_financiers__c m : relatedCalcIndemnMap.get(equipSinReparationList[0].Sinistre__c)){
                    if(m.Statut__c == CalculIndemnisationTriggerHandler.STATUS_DEMANDINPROGRESS &&
                       m.Type_mouvement__c == CalculIndemnisationTriggerHandler.COSTTYPE_REPAIR){
                           m.Montant__c = equipSinReparationList[0].RealCost__c == NULL ? 
                               equipSinReparationList[0].Valeur_reparation__c : equipSinReparationList[0].RealCost__c;
                           calcIndemnToUpdateList.add(m);
                           break;
                       }
                }
            }
        }
        
        if(calcIndemnToUpdateList.size() > 0){
            update calcIndemnToUpdateList;
        }
    }
}