hubSide/force-app/main/default/objects/Case/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <description>Id externe pour l&apos;intégration API</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Demande.recordType-meta.xml
<RecordType>
    <fullName>Demande</fullName>
    <active>true</active>
    <businessProcess>Demande</businessProcess>
    <description>Demande relative à de nouveaux documents client</description>
    <label>Demande</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/ChooseEqp__c.field-meta.xml
<CustomField>
    <fullName>ChooseEqp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modèle-choisi</label>
    <referenceTo>Matrice_cout_equipement__c</referenceTo>
    <relationshipLabel>Equipement sinistre (Equipement C)</relationshipLabel>
    <relationshipName>Equipement_sinistre1</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GradeEquipSin</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Id externe pour l&apos;intégration API qui est l&apos;Id du Case parent via le Web et est alimenté en post default value à Id si vide</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <description>Telephony operator</description>
    <label>Opérateur</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OperatorCountry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Operators</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Matrice_cout_equipement__c/Matrice_cout_equipement__c.object-meta.xml
<CustomObject>
    <label>Matrice coût equipement</label>
    <nameField>
        <label>Matrice coût equipement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matrice coût equipements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Matrice_cout_equipement__c/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <description>Utilisé pour la jointure avec le catalogue équipement et par les API sortants de Déstockage.</description>
    <externalId>true</externalId>
    <label>Id Externe B-appli Equipement Echange</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/Mouvements_financiers__c.object-meta.xml
<CustomObject>
    <label>Calcul Indemnisation</label>
    <nameField>
        <label>Nom du mouvement financier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calcul Indemnisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Calcul Indemnisations</relationshipLabel>
    <relationshipName>Mouvements_financiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Cout_choisi__c.field-meta.xml
<CustomField>
    <fullName>Cout_choisi__c</fullName>
    <label>Coût choisi</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primes</fullName>
            </value>
            <value>
                <fullName>Echange</fullName>
            </value>
            <value>
                <fullName>Réparation</fullName>
            </value>
            <value>
                <fullName>Règlement par le client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <description>Identification du montant du mouvement</description>
    <label>Montant</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crée</fullName>
                <default>true</default>
                <label>Crée</label>
            </value>
            <value>
                <fullName>En cours d&apos;approbation</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Demande en cours</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Rejeté</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Terminé</label>
            </value>
            <value>
                <fullName>Invalidated</fullName>
                <label>Invalidé</label>
            </value>
            <value>
                <fullName>En attente d&apos;approbation</fullName>
                <isActive>false</isActive>
                <label>En attente d&apos;approbation</label>
            </value>
            <value>
                <fullName>Encaissé</fullName>
                <isActive>false</isActive>
                <label>Encaissé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Type_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Type_mouvement__c</fullName>
    <label>Type Coût</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cout_choisi__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prime pour echange</fullName>
                <label>Prime pour échange</label>
            </value>
            <value>
                <fullName>Geste commercial</fullName>
            </value>
            <value>
                <fullName>Indemnite retard suite à expertise</fullName>
                <label>Indemnité retard suite à expertise</label>
            </value>
            <value>
                <fullName>Prime pour reparation par le client</fullName>
                <label>Prime pour réparation par le client</label>
            </value>
            <value>
                <fullName>Prime pour communication frauduleuse</fullName>
            </value>
            <value>
                <fullName>Cout interne reparation</fullName>
                <label>Coût interne réparation</label>
            </value>
            <value>
                <fullName>Cout interne d&apos;echange</fullName>
                <label>Coût interne d&apos;échange</label>
            </value>
            <value>
                <fullName>Franchise</fullName>
            </value>
            <value>
                <fullName>Cout prime magasin</fullName>
                <label>Coût prime magasin</label>
            </value>
            <value>
                <fullName>Complément réparation</fullName>
            </value>
            <value>
                <fullName>Cout forfait de reparation</fullName>
                <isActive>false</isActive>
                <label>Coût forfait de réparation</label>
            </value>
            <value>
                <fullName>Remboursement client</fullName>
                <isActive>false</isActive>
                <label>Remboursement client</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/globalValueSets/GradeEquipSin.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NEUF</fullName>
        <label>Neuf</label>
    </customValue>
    <customValue>
        <fullName>GRADE1</fullName>
        <label>Grade 1</label>
    </customValue>
    <customValue>
        <fullName>GRADE2</fullName>
        <label>Grade 2</label>
    </customValue>
    <customValue>
        <fullName>GRADE3</fullName>
        <label>Grade 3</label>
    </customValue>
    <customValue>
        <fullName>Grade 2temp</fullName>
        <isActive>false</isActive>
        <label>Grade 2temp</label>
    </customValue>
    <customValue>
        <fullName>Grade 1temp</fullName>
        <isActive>false</isActive>
        <label>Grade 1temp</label>
    </customValue>
    <customValue>
        <fullName>Neuftemp</fullName>
        <isActive>false</isActive>
        <label>Neuftemp</label>
    </customValue>
    <customValue>
        <fullName>Grade 3temp</fullName>
        <isActive>false</isActive>
        <label>Grade 3temp</label>
    </customValue>
    <description>Grades des équipements sinistrés - Equipement rank values</description>
    <masterLabel>Grade équipement sinistré</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/globalValueSets/Operators.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BASE</fullName>
    </customValue>
    <customValue>
        <fullName>BEANDYOU</fullName>
        <label>BE AND  YOU</label>
    </customValue>
    <customValue>
        <fullName>BOUYGUES</fullName>
    </customValue>
    <customValue>
        <fullName>CORIOLIS</fullName>
    </customValue>
    <customValue>
        <fullName>CREDITMUTUEL</fullName>
        <label>CREDIT MUTUEL</label>
    </customValue>
    <customValue>
        <fullName>FREE</fullName>
    </customValue>
    <customValue>
        <fullName>JOMOBILE</fullName>
    </customValue>
    <customValue>
        <fullName>LAPOSTEMOBILE</fullName>
        <label>LA POSTE MOBILE</label>
    </customValue>
    <customValue>
        <fullName>NRJ</fullName>
    </customValue>
    <customValue>
        <fullName>ORANGE</fullName>
    </customValue>
    <customValue>
        <fullName>REDSFR</fullName>
        <label>RED SFR</label>
    </customValue>
    <customValue>
        <fullName>SFR</fullName>
    </customValue>
    <customValue>
        <fullName>SIMPLEO</fullName>
    </customValue>
    <customValue>
        <fullName>SOSH</fullName>
    </customValue>
    <customValue>
        <fullName>VIRGIN</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER</fullName>
        <label>AUTRE</label>
    </customValue>
    <description>Telephony operators</description>
    <masterLabel>Operators</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/CalculIndemnisationTriggerHandler.cls
/***
* @author Nicolas Brancato (GFI)
* @date 11/02/2020
* @description Handler class for CalculIndemnisationTrigger
*/

public class CalculIndemnisationTriggerHandler {    
    
    public static final String STATUS_VALIDATED = 'Validé';    
    public static final String STATUS_DEMANDINPROGRESS = 'Demande en cours';
    public static final String COSTTYPE_INTERNCOSTEXCHANGE = 'Cout interne d\'echange';
    public static final String COSTTYPE_STOREPRIMECOST = 'Cout prime magasin';
    public static final String COSTTYPE_REPAIR = 'Cout interne reparation';
    public static final String COSTTYPE_FRANCHISE = 'Franchise';
    static final String BAPPLISTOCKNAME_SFAM = 'SFAM';

    /***
    * @description method to handle all before delete automatisms
    * @param lstOldCal list of old Mouvements_financiers__c
    */
    public void handleBeforeDelete(List<Mouvements_financiers__c> lstOldCal){
        CalculIndemnisationTriggerHelper.blockDeleteCalculIndemStatusCreated(lstOldCal);
    }

    /***
    * @description method to handle all before update automatisms
    * @param lstNewCal list of new Mouvements_financiers__c
    * @param mapOldCal map of old Mouvements_financiers__c
    */
    public void handleBeforeUpdate(List<Mouvements_financiers__c> lstNewCal, Map<id,Mouvements_financiers__c> mapOldCal){
        
        // Update related case on closed CalcIndem
        Map<id, List<Mouvements_financiers__c>> caseIdMFMap = CalculIndemnisationTriggerHelper.getOtherCalcIndem(Trigger.new);
        CalculIndemnisationTriggerHelper.updateRelatedCase(lstNewCal, mapOldCal, caseIdMFMap);
    }

    /***
    * @description method to handle all after insert automatisms
    * @param lstNewCal list of new Mouvements_financiers__c
    */
    public void handleAfterInsert(List<Mouvements_financiers__c> lstNewCal){
        updateCaseAmount(lstNewCal);
    }  

    /***
    * @description method to handle all after delete automatisms
    * @param lstOldCal list of old Mouvements_financiers__c
    */
    public void handleAfterDelete(List<Mouvements_financiers__c> lstOldCal){
        updateCaseAmount(lstOldCal);
        updateEquipSinistreChoice(lstOldCal);
    }

    /***
    * @description method to handle all after update automatisms
    * @param lstNewCal list of new Mouvements_financiers__c
    * @param mapOldCal map of old Mouvements_financiers__c
    */
    public void handleAfterUpdate(List<Mouvements_financiers__c> lstNewCal, Map<id,Mouvements_financiers__c> mapOldCal){
        processCalculIndemStatusDemande(lstNewCal,mapOldCal);
        updateCaseAmountUpdate(lstNewCal,mapOldCal);
    }
    
    /***
    * @description update amount Case
    * @param lstNewCal list of new Mouvements_financiers__c
    * @return nul
    * @exception none
    */
    public void updateCaseAmount(List<Mouvements_financiers__c> lstNewCal){
        Set<id> idSin = new Set<Id>();
        for(integer i=0; i<lstNewCal.size(); i++){
			idSin.add(lstNewCal[i].Case__c);
        }

        if(!idSin.isEmpty()){
 			CalculIndemnisationTriggerHelper.SumCalculIndemAmount(idSin);
        }
    }

    /***
    * @description update amount Case
    * @param lstNewCal list of new Mouvements_financiers__c
    * @return nul
    * @exception none
    */
    public void updateEquipSinistreChoice(List<Mouvements_financiers__c> lstOldCal){
        Set<id> idSin = new Set<Id>();
        for(integer i=0; i<lstOldCal.size(); i++){
            if(lstOldCal[i].Cout_choisi__c == 'Echange' && lstOldCal[i].Case__c != null){
                idSin.add(lstOldCal[i].Case__c);
            }
        }

        if(!idSin.isEmpty()){
 			CalculIndemnisationTriggerHelper.updateEquipeSinistreChoice(idSin);
        }
    }

    /***
    * @description update amount Case
    * @param lstNewCal list of new Mouvements_financiers__c
    * @return nul
    * @exception none
    */
    public void updateCaseAmountUpdate(List<Mouvements_financiers__c> lstNewCal,Map<id,Mouvements_financiers__c> mapOldCal){
        Set<id> idSin = new Set<Id>();
        for(integer i=0; i<lstNewCal.size(); i++){
			if(lstNewCal[i].Montant__c != mapOldCal.get(lstNewCal[i].id).Montant__c || 
                lstNewCal[i].Statut__c != mapOldCal.get(lstNewCal[i].id).Statut__c){
            	
                    idSin.add(lstNewCal[i].Case__c);    
            }
        }
        
        if(!idSin.isEmpty()){
 			CalculIndemnisationTriggerHelper.SumCalculIndemAmount(idSin);
        }
    }

    /***
    * @description method to handle all after update automatisms
    * @param lstNewCal list of new Mouvements_financiers__c
    * @param mapOldCal map of old Mouvements_financiers__c
    * @return nul
    * @exception none
    */
    public void processCalculIndemStatusDemande(List<Mouvements_financiers__c> lstNewCal, Map<id,Mouvements_financiers__c> mapOldCal){
        
        Set<id> idSin = new Set<Id>();
        Equipement_sinistre__c eqs;
        List<Equipement_sinistre__c> lstEquToUpdate;
        List<Mouvements_financiers__c> lstCal = new List<Mouvements_financiers__c>();
        List<Mouvements_financiers__c> lstCalforStoreCostPrime = new List<Mouvements_financiers__c>();
        Set<Id> lstIdCaseRepair = new Set<Id>();
        for(integer i=0; i<lstNewCal.size(); i++){
            // Choose Calcul Indem type exchange
            if( lstNewCal[i].Statut__c == STATUS_DEMANDINPROGRESS && 
                mapOldCal.get(lstNewCal[i].id).Statut__c != STATUS_DEMANDINPROGRESS && 
                lstNewCal[i].Type_mouvement__c == COSTTYPE_INTERNCOSTEXCHANGE) { 
                
                    lstCal.add(lstNewCal[i]);
            }
            // Choose Calcul Indem type prime store (magasin)
            if(lstNewCal[i].Statut__c == STATUS_DEMANDINPROGRESS 
               && mapOldCal.get(lstNewCal[i].id).Statut__c != STATUS_DEMANDINPROGRESS 
               && lstNewCal[i].Type_mouvement__c == COSTTYPE_STOREPRIMECOST) { 
                
                    lstCalforStoreCostPrime.add(lstNewCal[i]);
            }
            // Choose Calcul Indem type repair
            if(lstNewCal[i].Statut__c == STATUS_DEMANDINPROGRESS 
               && mapOldCal.get(lstNewCal[i].id).Statut__c != STATUS_DEMANDINPROGRESS 
               && lstNewCal[i].Type_mouvement__c == COSTTYPE_REPAIR) { 
                
                lstIdCaseRepair.add(lstNewCal[i].Case__c);
            }
        }

        // Process Calcul Indem type exchange
        if(!lstCal.isEmpty()){
            eqs = CalculIndemnisationTriggerHelper.GetDatasToTriggerDestockToBAppli(lstCal[0]);
            if(eqs != null){
                BAppliCallout.getFromStock(BAPPLISTOCKNAME_SFAM, eqs.ChooseEqp__r.Id_externe__c, eqs.Grade__c, eqs.Operator__c, eqs.Id, eqs.Sinistre__c);    
            }
        }
        // Process Calcul Indem type prime store
        if(!lstCalforStoreCostPrime.isEmpty()){
 			CalculIndemnisationTriggerHelper.sendEmailToCustomerAndDealer(lstCalforStoreCostPrime);
        }
        // Process Calcul Indem type repair
        if(!lstIdCaseRepair.isEmpty()){
            lstEquToUpdate = CalculIndemnisationTriggerHelper.GetEquipSinistreRepair(lstIdCaseRepair);
            if(lstEquToUpdate != null){
                // Update Status EquipSinistre
                CalculIndemnisationTriggerHelper.updateEquipeSinistreStatus(lstEquToUpdate);
                // Create Task To Owner EquipSinistre to start repair
                CalculIndemnisationTriggerHelper.createHistoToStartRepair(lstEquToUpdate);
            }
       }
    }
}