hubSide/force-app/main/default/objects/Case/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>CASE(
    Record_Type_Name__c, 
    &apos;Sinistre&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;INS&quot; + &apos;&apos; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
        &quot;TMP&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;SinistreBApp&apos;, Num_sinistre_B_Appli__c,
    &apos;Sinistre clôturé&apos;, Subject, 
    &apos;Déclaration&apos;, CaseNumber, 
    &apos;SAV&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;SAV&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;), 
        &quot;DEM&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;Réclamation&apos;, &quot;REC&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
				&apos;Demande&apos;, &quot;DEM&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
    &apos;GED&apos; + &apos;&apos; + RIGHT(CaseNumber, 6)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro de la requête</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/LastStatus__c.field-meta.xml
<CustomField>
    <fullName>LastStatus__c</fullName>
    <description>Last status of the equipment.</description>
    <label>LastStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/LastStatusModification__c.field-meta.xml
<CustomField>
    <fullName>LastStatusModification__c</fullName>
    <label>LastStatusModification</label>
    <type>DateTime</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>Sinistre__r.Numero_sinistre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro du sinistre</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sous_statut__c.field-meta.xml
<CustomField>
    <fullName>Sous_statut__c</fullName>
    <label>Sous-statut</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Statut_equipement__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>EquipSin_SousStatut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Statut_equipement__c.field-meta.xml
<CustomField>
    <fullName>Statut_equipement__c</fullName>
    <label>Statut equipement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EquipSin_Statut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Name__c/Name__c.object-meta.xml
<CustomObject>
    <label>Historique</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historique</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Name__c/fields/Equipement_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Equipement_sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement sinistré</label>
    <referenceTo>Equipement_sinistre__c</referenceTo>
    <relationshipLabel>Historique</relationshipLabel>
    <relationshipName>Historique</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/globalValueSets/EquipSin_SousStatut.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A stocker</fullName>
    </customValue>
    <customValue>
        <fullName>Stocké</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir - Retour client</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir - Retour SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir du stock</fullName>
    </customValue>
    <customValue>
        <fullName>Sortie PSM</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir PSM</fullName>
    </customValue>
    <customValue>
        <fullName>A retourner PSM</fullName>
    </customValue>
    <customValue>
        <fullName>A dispatcher</fullName>
    </customValue>
    <customValue>
        <fullName>En cours d&apos;expertise</fullName>
    </customValue>
    <customValue>
        <fullName>En attente GS</fullName>
    </customValue>
    <customValue>
        <fullName>En cours</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - A expédier</fullName>
    </customValue>
    <customValue>
        <fullName>Préparation</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - A conserver</fullName>
    </customValue>
    <customValue>
        <fullName>Retourné client</fullName>
    </customValue>
    <customValue>
        <fullName>Repaired</fullName>
        <label>Réparé</label>
    </customValue>
    <customValue>
        <fullName>Unrepairable</fullName>
        <label>Irréparable</label>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <label>Annulé</label>
    </customValue>
    <customValue>
        <fullName>Via prime</fullName>
    </customValue>
    <customValue>
        <fullName>Via prime magasin</fullName>
    </customValue>
    <customValue>
        <fullName>Réception client</fullName>
    </customValue>
    <customValue>
        <fullName>Conservé SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - à expédier (Irréparable)</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - à expédier (Annulé)</fullName>
    </customValue>
    <customValue>
        <fullName>Préparation - Irréparable/Annulé</fullName>
    </customValue>
    <customValue>
        <fullName>Retour Client</fullName>
    </customValue>
    <customValue>
        <fullName>Retour SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>Sorti PSM</fullName>
        <isActive>false</isActive>
        <label>Sorti PSM</label>
    </customValue>
    <description>Liste des sous-statuts de l&apos;équipement sinistré - Equipement sinistre sub status list</description>
    <masterLabel>EquipSin_SousStatut</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/Sinistre_BordereauEquipSinController.cls
/***
* @author Ariane Tanguy (GFI)
* @date 27/11/2020
* @description Lightning Component Controller
*/

public class Sinistre_BordereauEquipSinController {
    
    private final String newStatus;
    private final String newSousStatus;
    private final String saisieSinistre;
    private final Integer nbColis;
    private final List<Equipement_sinistre__c> sinistreColumn1, sinistreColumn2, sinistreColumn3;
    private Boolean preValidation = false;
    private List<Equipement_sinistre__c> equipSinList;
   
    /***
	* @description VFP Init
	*/
    public Sinistre_BordereauEquipSinController() {        
        
        // Get the equipement sinistre
        newStatus = ApexPages.currentPage().getParameters().get('newStatus');
        newSousStatus = ApexPages.currentPage().getParameters().get('newSousStatus');
        saisieSinistre = ApexPages.currentPage().getParameters().get('numSinistre');
        
        if(saisieSinistre != null) {
            preValidation = true;
            equipSinList = [SELECT id, Statut_equipement__c,  Sinistre__r.Numero_sinistre__c, Sous_statut__c
                            FROM Equipement_Sinistre__c
                            WHERE Numero_sinistre__c IN: saisieSinistre.split(' ')];
        } else {
            equipSinList = [SELECT id, Sinistre__r.Numero_sinistre__c
                                                     FROM Equipement_Sinistre__c
                                                     WHERE Statut_equipement__c =: newStatus
                                                     AND Sous_statut__c =: newSousStatus
                                                     AND Id In (SELECT Equipement_sinistre__c From Name__c Where CreatedDate = TODAY)];


            List<Name__c> allThatHistory = [SELECT ID,Equipement_sinistre__c, CreatedDate, Name FROM NAME__c WHERE Equipement_sinistre__c IN: equipSinList Order by CreatedDate DESC];
            System.debug(allThatHistory.size());
            setLastStatuses(equipSinList, allThatHistory);
        }
        
        nbColis = equipSinList.size();
        
        sinistreColumn1 = new List<Equipement_sinistre__c>();
        sinistreColumn2 = new List<Equipement_sinistre__c>();
        sinistreColumn3 = new List<Equipement_sinistre__c>();
        Integer i = 0;
        for(Equipement_sinistre__c e : equipSinList){
            switch on math.mod(i, 3) {
                when 0 {
                    sinistreColumn1.add(e);
                }
                when 1 {
                    sinistreColumn2.add(e);
                }
                when 2 {
                    sinistreColumn3.add(e);
                }
            }
            i = i + 1;
        }
    }
    
    // Return newStatus
    public String getNewStatus() {
        return newStatus;
    }
    
    // Return newSousStatus
    public String getNewSousStatus() {
        return newSousStatus;
    }
    
    // Return nbColis
    public Integer getNbColis() {
        return nbColis;
    }

    public Boolean getPrevalidation(){ 
        return preValidation;
    }
    
    // Return sinistre1
    public List<Equipement_sinistre__c> getSinistreColumn1() {
        return sinistreColumn1;
    }
    
    // Return sinistre2
    public List<Equipement_sinistre__c> getSinistreColumn2() {
        return sinistreColumn2;
    }
    
    // Return sinistre3
    public List<Equipement_sinistre__c> getSinistreColumn3() {
        return sinistreColumn3;
    }

    public List<Equipement_sinistre__c> getEquipSinList() {
        return equipSinList;
    }

    private void setLastStatuses(List<Equipement_sinistre__c> equipSinistre, List<Name__c> history){
        for(Equipement_sinistre__c eq : equipSinistre) {
            Integer findSecond = 0;
            for(Name__c hist : history) {
                if(hist.Equipement_sinistre__c.equals(eq.Id)) {
                    eq.LastStatus__c = hist.Name;
                    eq.LastStatusModification__c = hist.CreatedDate;
                    if (findSecond == 1)
                        break;
                    findSecond ++;
                }
            }
        }
    }
}