hubSide/force-app/main/default/objects/Case/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>CASE(
    Record_Type_Name__c, 
    &apos;Sinistre&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;INS&quot; + &apos;&apos; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
        &quot;TMP&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;SinistreBApp&apos;, Num_sinistre_B_Appli__c,
    &apos;Sinistre clôturé&apos;, Subject, 
    &apos;Déclaration&apos;, CaseNumber, 
    &apos;SAV&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;SAV&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;), 
        &quot;DEM&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;Réclamation&apos;, &quot;REC&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
				&apos;Demande&apos;, &quot;DEM&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
    &apos;GED&apos; + &apos;&apos; + RIGHT(CaseNumber, 6)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro de la requête</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Adresse_de_livraison__c.field-meta.xml
<CustomField>
    <fullName>Adresse_de_livraison__c</fullName>
    <label>Adresse de livraison</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>Sinistre__r.Numero_sinistre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro du sinistre</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/classes/Flow_BarcodeScanInvokableTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 11/02/2021
* @description Flow_BarcodeScanInvokable test class
* @class Flow_BarcodeScanInvokable
*/

@isTest
public class Flow_BarcodeScanInvokableTest {
    
    /***
    * @description Split flow string into workable barcode strings
    * @see splitBarcode
    */
    @isTest
    public static void splitBarcodeTest(){
        
        // Create a case
        Case s = TestFactory.createSinistre();
        insert s;
        
        // Create an equipement sinistre
        Equipement_Sinistre__c e = new Equipement_Sinistre__c();
        e.sinistre__c = s.id;
        insert e;
        
        // Mock the flow inputs
        Flow_BarcodeScanInvokable.FlowInputs fInput = new Flow_BarcodeScanInvokable.FlowInputs();        
        fInput.fieldToUpdate = 'Adresse_de_livraison__c';
        fInput.objectToQuery = 'Equipement_sinistre__c';
        fInput.fieldToQuery = 'Numero_sinistre__c';
        fInput.barcodeString = 'INS000001';
        fInput.valueToUpdate = '12 rue 132';
        
        List<Flow_BarcodeScanInvokable.FlowInputs> fInputList = new List<Flow_BarcodeScanInvokable.FlowInputs>();
        fInputList.add(fInput);
        
        List<Flow_BarcodeScanInvokable.FlowOutputs> fOutputList = Flow_BarcodeScanInvokable.splitBarcode(fInputList);
        system.assertEquals(1, fOutputList.size(), 'There should be only one output - This is wrong');
        system.assertEquals(1, fOutputList[0].barcodeList.size(), 'There should be two barcodes - This is wrong');
        system.assertEquals('INS000001', fOutputList[0].barcodeList[0], 'The first barcode should be INS000001 - This is wrong');
        
        e = [SELECT Adresse_de_livraison__c FROM Equipement_sinistre__c WHERE id =: e.id];
        system.assertEquals(fInput.valueToUpdate, e.Adresse_de_livraison__c);
    }
}