hubSide/force-app/main/default/objects/Case/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>CASE(
    Record_Type_Name__c, 
    &apos;Sinistre&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;INS&quot; + &apos;&apos; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
        &quot;TMP&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;SinistreBApp&apos;, Num_sinistre_B_Appli__c,
    &apos;Sinistre clôturé&apos;, Subject, 
    &apos;Déclaration&apos;, CaseNumber, 
    &apos;SAV&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;SAV&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;), 
        &quot;DEM&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;Réclamation&apos;, &quot;REC&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
				&apos;Demande&apos;, &quot;DEM&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
    &apos;GED&apos; + &apos;&apos; + RIGHT(CaseNumber, 6)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro de la requête</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>Sinistre__r.Numero_sinistre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro du sinistre</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Statut_equipement__c.field-meta.xml
<CustomField>
    <fullName>Statut_equipement__c</fullName>
    <label>Statut equipement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EquipSin_Statut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Name__c/Name__c.object-meta.xml
<CustomObject>
    <label>Historique</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historique</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Name__c/fields/Equipement_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Equipement_sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement sinistré</label>
    <referenceTo>Equipement_sinistre__c</referenceTo>
    <relationshipLabel>Historique</relationshipLabel>
    <relationshipName>Historique</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/classes/Sinistre_BordereauEquipSinControllerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 27/11/2020
* @description Sinistre_BordereauEquipSinController test class
* @VFP Sinistre_BordereauEquipementSinistre
*/

@isTest
public class Sinistre_BordereauEquipSinControllerTest {
    
    /***
	* @description Check whether the custom controller does the job
	* @see Sinistre_BordereauColis
	*/
    @isTest
    public static void Sinistre_BordereauEquipSinTest(){
        
        // Create three sinistre
        List<Case> caseList = new List<Case>();
        for(integer i=0; i<3; i++){
            Case c = TestFactory.createSinistre();
            caseList.add(c);
        }
        insert caseList;
        
        // Create three equipement sinistre
        List<Equipement_sinistre__c> equipList = new List<Equipement_sinistre__c>();
        for(integer i=0; i<3; i++){
            Equipement_sinistre__c e = new Equipement_sinistre__c();
            e.Name = 'Apple-Iphone6';
            e.Sinistre__c = caseList[i].id;
            equipList.add(e);
        }
        insert equipList;
        
        List<Name__c> equipHistory = new List<Name__c>();
        for(integer i=0; i<3; i++){
            Name__c hist = new Name__c();
            hist.Name = 'Old Status';
            hist.Equipement_sinistre__c = equipList.get(i).id;
            equipHistory.add(hist);
        }
        insert equipHistory;
        
        Equipement_sinistre__c e = [SELECT Statut_equipement__c
                                    FROM Equipement_sinistre__c
                                    WHERE id =: equipList[0].id];
        system.assertEquals('En Analyse', e.Statut_equipement__c);
        
        // Create a VFP
        PageReference pageRef = Page.Sinistre_BordereauEquipementSinistre;
        Test.setCurrentPage(pageRef);
        
        Sinistre_BordereauEquipSinController sC = new Sinistre_BordereauEquipSinController();
        system.assertEquals(0, sC.getSinistreColumn1().size(), 
                           'There should be no returned sinistre - This is wrong');
        
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('newStatus', 'En Analyse');
        sC = new Sinistre_BordereauEquipSinController();
        
        system.assertEquals('En Analyse', sC.getNewStatus(), 
                           'The new status shouldve been updated - This is wrong');
        system.assertEquals(NULL, sC.getNewSousStatus(), 
                           'The new sous status should be null - This is wrong');
        
        // Check the display column
        system.assertEquals('INS000002', sC.getSinistreColumn2()[0].Sinistre__r.Numero_Sinistre__c, 
                           'The display column should contain the created sinistre - This is wrong');
        system.assertEquals('INS000003', sC.getSinistreColumn3()[0].Sinistre__r.Numero_Sinistre__c, 
                           'The third display column should contain the created sinistre - This is wrong');
        
    }
}