hubSide/force-app/main/default/objects/Case/fields/Typologie_Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Typologie_Sinistre__c</fullName>
    <label>Typologie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Case_Typologie</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Affectation_document.recordType-meta.xml
<RecordType>
    <fullName>Affectation_document</fullName>
    <active>true</active>
    <businessProcess>Affectation Document</businessProcess>
    <description>Record type pour l&apos;affectation manuelle des documents sans case associé.</description>
    <label>Affectation document</label>
</RecordType>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Document__c/fields/Related_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Related_sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/Piece_justificative_Sinistre__c.object-meta.xml
<CustomObject>
    <label>Pièce justificative Sinistre</label>
    <nameField>
        <label>Pièce justificative Sinistre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pièces justificatives Sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Technique Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document__c.Related_sinistre__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Types_piece_justificative__c.field-meta.xml
<CustomField>
    <fullName>Types_piece_justificative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Types pièce justificative</label>
    <referenceTo>Types_piece_justificative__c</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Validite_document__c.field-meta.xml
<CustomField>
    <fullName>Validite_document__c</fullName>
    <label>Validité du document</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expected</fullName>
                <default>true</default>
                <label>1-Attendue</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <label>2-Reçu</label>
            </value>
            <value>
                <fullName>Valid</fullName>
                <label>3-Valide</label>
            </value>
            <value>
                <fullName>NotNeeded</fullName>
                <label>4-Plus réclamé</label>
            </value>
            <value>
                <fullName>Invalid</fullName>
                <label>5-Non valide</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/Types_piece_justificative__c.object-meta.xml
<CustomObject>
    <label>Types pièce justificative</label>
    <nameField>
        <label>Types pièce justificative name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types pièce justificative</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/fields/Perte__c.field-meta.xml
<CustomField>
    <fullName>Perte__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Perte</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Case_Typologie.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Broken</fullName>
        <label>Casse</label>
    </customValue>
    <customValue>
        <fullName>Pickpocketed</fullName>
        <label>Vol toute cause</label>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
        <label>Perte</label>
    </customValue>
    <customValue>
        <fullName>Oxidised</fullName>
        <label>Oxydation</label>
    </customValue>
    <customValue>
        <fullName>Robbed</fullName>
        <label>Vol Caractérisé</label>
    </customValue>
    <customValue>
        <fullName>ReturnedByCarrier</fullName>
        <label>Retour transporteur</label>
    </customValue>
    <customValue>
        <fullName>LostByCarrier</fullName>
        <label>Perte transporteur</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterRepair</fullName>
        <label>Dysfonctionnement suite à réparation</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterExchange</fullName>
        <label>Dysfonctionnement suite à échange</label>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <label>Autres</label>
    </customValue>
    <customValue>
        <fullName>ClaimCreation</fullName>
        <label>Création Réclamation</label>
    </customValue>
    <customValue>
        <fullName>ClaimFollowUp</fullName>
        <label>Suivi Réclamation</label>
    </customValue>
    <customValue>
        <fullName>AccidentCreation</fullName>
        <label>Création Sinistre</label>
    </customValue>
    <description>Liste de toutes les typologies possibles (Sinistre, SAV, Demande)</description>
    <masterLabel>Case_Typologie</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/GEDControllerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 11/02/2021
* @description GEDController
* @LWC showPdfRelatedToRecordId
* @LWC showPJList
*/

@isTest
public class GEDControllerTest {
    
    /***
    * @description Get the current user profile
    * @see getUserProfile
    */
    @isTest
    public static void getUserProfileTest(){
        
        system.assert(GEDController.getUserProfile(), 
                      'The sys admin should have access - This is wrong');
        
        User u = TestFactory.createUser();
        u.ProfileId = [SELECT Id FROM Profile WHERE name =: 'SFAM TC'].Id;
        insert u;
        
        system.runAs(u){
            system.assert(!GEDController.getUserProfile(), 
                      'The TC shouldnt have access - This is wrong');
        }
    }
    
    /***
    * @description Get all the case related files
    * @see getRelatedFilesByRecordId
    */
    @isTest
    public static void getRelatedFilesByRecordIdTest(){
        
        // Create a case GED
        Case c = new Case();
        c.RecordTypeId = UtilityClassHelper.getCreatedRecordType('Affectation_document');
        insert c;
        
        // Create an EmailMessage
        EmailMessage em = new EmailMessage();
        em.ParentId = c.id;
        insert em;
        
        // Create a new content version
        ContentVersion cv = new ContentVersion();
        cv.Title = 'TestDocument';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('TestContent');
        cv.IsMajorVersion = true;
        cv.FirstPublishLocationId = em.id;
        insert cv;
        
        // Get all the related contentDocument ids
        Map<String, String> mapIdTitle = GEDController.getRelatedFilesByRecordId(c.id);
        system.assertEquals(1, mapIdTitle.keySet().size(), 'There should be one document mapped - This is wrong');
    }
    
    /***
    * @description Get all the case related piece justificatives
    * + Update PJ on the fly
    * @see getPJMap + getPJList + updatePJTest
    */
    @isTest
    public static void getPJTest(){
        
        // Create a type de piece justificative
        Types_piece_justificative__c t = new Types_piece_justificative__c();
        t.Perte__c = TRUE;
        t.Name = 'Permis de chasse';
        insert t;
        
        // Create a sinistre
        Case c = new Case();
        c.RecordTypeId = UtilityClassHelper.getCreatedRecordType('Sinistre');
        c.Typologie_Sinistre__c = 'lost';
        insert c;
        
        // Create a document
        Document__c d = new Document__c();
        d.Related_sinistre__c = c.id;
        insert d;
        
        // Get all the related contentDocument ids
        List<Piece_justificative_Sinistre__c> pjList = GEDController.getPJList(d.id);
        system.assertEquals(t.Name, pjList[0].Name, 'The pj should be Permis de chasse - This is wrong');
        
        Map<String, String> pjNameValidityMap = GEDController.getPJMap(d.id);
        system.assertEquals(1, pjNameValidityMap.keySet().size(), 'There should be one pj mapped - This is wrong');
        
        // Get the created PJ
        Piece_justificative_Sinistre__c pj = [SELECT Id, Validite_document__c, Document__c
                                              FROM Piece_justificative_Sinistre__c
                                              WHERE Case__c =: c.id];
        
        GEDController.updatePJ(pj.id, 'Received', d.id);
        
        pj = [SELECT Id, Validite_document__c, Document__c
              FROM Piece_justificative_Sinistre__c
              WHERE Case__c =: c.id];
        
        system.assertEquals('Received', pj.Validite_document__c, 'The pj validity shouldve been updated - This is wrong');
    }
    
    /***
    * @description Get the validité document picklist values
    * @see getPicklistValues + getPJOptions
    */
    @isTest
    public static void getPJOptionsTest(){
        
        // Get all the related contentDocument ids
        Map<String, String> pjOptionMap = GEDController.getPJOptions();
        system.assertEquals(5, pjOptionMap.keySet().size(), 'There should be 5 pj status - This is wrong');
        system.assert(pjOptionMap.keySet().contains('1-Attendue'), 'There should be an expected status - This is wrong');
    }
}