hubSide/force-app/main/default/objects/Case/fields/Typologie_Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Typologie_Sinistre__c</fullName>
    <label>Typologie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Case_Typologie</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Statut_equipement__c.field-meta.xml
<CustomField>
    <fullName>Statut_equipement__c</fullName>
    <label>Statut equipement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EquipSin_Statut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/recordTypes/Equipement_a_reparer.recordType-meta.xml
<RecordType>
    <fullName>Equipement_a_reparer</fullName>
    <active>true</active>
    <description>Equipement à réparer parce que cassé ou oxydé</description>
    <label>Equipement Réparation</label>
</RecordType>

hubSide/force-app/main/default/globalValueSets/Case_Typologie.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Broken</fullName>
        <label>Casse</label>
    </customValue>
    <customValue>
        <fullName>Pickpocketed</fullName>
        <label>Vol toute cause</label>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
        <label>Perte</label>
    </customValue>
    <customValue>
        <fullName>Oxidised</fullName>
        <label>Oxydation</label>
    </customValue>
    <customValue>
        <fullName>Robbed</fullName>
        <label>Vol Caractérisé</label>
    </customValue>
    <customValue>
        <fullName>ReturnedByCarrier</fullName>
        <label>Retour transporteur</label>
    </customValue>
    <customValue>
        <fullName>LostByCarrier</fullName>
        <label>Perte transporteur</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterRepair</fullName>
        <label>Dysfonctionnement suite à réparation</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterExchange</fullName>
        <label>Dysfonctionnement suite à échange</label>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <label>Autres</label>
    </customValue>
    <customValue>
        <fullName>ClaimCreation</fullName>
        <label>Création Réclamation</label>
    </customValue>
    <customValue>
        <fullName>ClaimFollowUp</fullName>
        <label>Suivi Réclamation</label>
    </customValue>
    <customValue>
        <fullName>AccidentCreation</fullName>
        <label>Création Sinistre</label>
    </customValue>
    <description>Liste de toutes les typologies possibles (Sinistre, SAV, Demande)</description>
    <masterLabel>Case_Typologie</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/Flow_ChangementStatutEquipSinTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 28/04/2021
* @description Flow_ChangementStatutEquipSin test class
* @class Flow_ChangementStatutEquipSin
*/

@isTest
public class Flow_ChangementStatutEquipSinTest {
    
    /***
    * @description Update EquipSin status
    * @see updateEquipSinStatus
    */
    @isTest
    public static void updateEquipSinStatusTest(){
        
        // Create a case
        Case s = TestFactory.createSinistre();
        s.Typologie_Sinistre__c = 'Broken';
        insert s;
        
        // Create an equipement sinistre
        Equipement_Sinistre__c e = new Equipement_Sinistre__c();
        e.sinistre__c = s.id;
        insert e;
        
        e = [SELECT id, RecordTypeId FROM Equipement_Sinistre__c WHERE id =: e.id];
        system.assert(e.RecordTypeId == UtilityClassHelper.getCreatedRecordType('Equipement_a_reparer'));
        
        // Get the current status
        
        // Mock the flow inputs
        List<Flow_ChangementStatutEquipSin.FlowInputs> fInputList = new List<Flow_ChangementStatutEquipSin.FlowInputs>();
        Flow_ChangementStatutEquipSin.FlowInputs fInput = new Flow_ChangementStatutEquipSin.FlowInputs();
        fInput.barcodeString = 'INS000001';
        fInput.selectedRT = e.RecordTypeId;
        fInput.getCurrentStatus = true;
        fInputList.add(fInput);
        
        // And play the flow
        List<Flow_ChangementStatutEquipSin.FlowOutputs> fOutputList = Flow_ChangementStatutEquipSin.updateEquipSinStatus(fInputList);
        system.assertEquals(1, fOutputList.size(), 'There should be only one output - This is wrong');
        system.assertEquals(1, fOutputList[0].barcodeCount, 'There should be one barcode - This is wrong');
        system.assert(fOutputList[0].currentStatusString.contains('En Analyse'), 
                            'The current status should be En analyse - This is wrong');
        
        // Now update the status
        fInput.getCurrentStatus = false;
        fInput.newStatus = 'Irréparable';
        
        // Play the flow again
        fOutputList = Flow_ChangementStatutEquipSin.updateEquipSinStatus(fInputList);
        system.assertEquals(1, fOutputList.size(), 'There should be only one output - This is wrong');
        system.assertEquals(1, fOutputList[0].barcodeCount, 'There should be one barcode - This is wrong');
        system.assertEquals(false, fOutputList[0].isErrorRT, 'The status shouldve have been changed successfully');
        
        e = [SELECT id, Statut_equipement__c FROM Equipement_Sinistre__c WHERE id =: e.id];
        system.assertEquals(fInput.newStatus = 'Irréparable', e.Statut_equipement__c, 'The status shouldve have been changed to Irréparable');
        
        // Actually, go directly to the final status
        fInput.setFinalStatus = true;
        
        // Play the flow again
        fOutputList = Flow_ChangementStatutEquipSin.updateEquipSinStatus(fInputList);
        
        e = [SELECT id, Statut_equipement__c FROM Equipement_Sinistre__c WHERE id =: e.id];
        system.assertEquals(fInput.newStatus = 'Irréparable', e.Statut_equipement__c, 
                            'The status shouldve have been changed to Irréparable');
    }
}