hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Document__c/fields/Related_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Related_sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/Piece_justificative_Sinistre__c.object-meta.xml
<CustomObject>
    <label>Pièce justificative Sinistre</label>
    <nameField>
        <label>Pièce justificative Sinistre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pièces justificatives Sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Technique Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document__c.Related_sinistre__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Types_piece_justificative__c.field-meta.xml
<CustomField>
    <fullName>Types_piece_justificative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Types pièce justificative</label>
    <referenceTo>Types_piece_justificative__c</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/Types_piece_justificative__c.object-meta.xml
<CustomObject>
    <label>Types pièce justificative</label>
    <nameField>
        <label>Types pièce justificative name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types pièce justificative</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/classes/LWC_PJManageStatusTest.cls
/***
* @author Pierre-Mickael BARRAL (INETUM)
* @date 15/07/2021
* @description LWC_PJManageStatusTest
* DATE          DEV         DESCRIPTION
* 15/07/2021    PMB         Inital version
*/
@isTest
public with sharing class LWC_PJManageStatusTest {
    @testSetup static void init() {
        
        // Create two types de piece justificative
        Types_piece_justificative__c t = TestFactory.createTypePJ('CNI');
        insert t;
        
        // Create a sinistre
        Case c = TestFactory.createSinistre();
        insert c;

        Piece_justificative_Sinistre__c pj = TestFactory.createPJ(t);
        pj.Case__c = c.id;
        insert pj;
        
        // Create a document
        Document__c d = new Document__c();
        d.Related_sinistre__c = c.id;
        insert d;
        
        // Create a new content version
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        cv.FirstPublishLocationId = d.id;
        insert cv;
        
        
    }

    @isTest
    public static void getPJTest(){
        Document__c doc = [SELECT Id FROM Document__c];
        List<Piece_justificative_Sinistre__c> lstPiece = [SELECT Id FROM Piece_justificative_Sinistre__c];
        
        test.startTest();
        system.assertEquals(LWC_PJManageStatus.getPJ(doc.Id).size(), lstPiece.size(), 
                                'No piece found');
        test.stopTest();
    }

    @isTest
    public static void updatPJTest(){
        Document__c doc = [SELECT Id FROM Document__c];
        List<Piece_justificative_Sinistre__c> lstPiece = [SELECT Id FROM Piece_justificative_Sinistre__c];
        List<LWC_PJManageStatus.WrapperManageStatus> listwrapperUpdated = new List<LWC_PJManageStatus.WrapperManageStatus>();
        List<LWC_PJManageStatus.WrapperManageStatus> listwrapper = LWC_PJManageStatus.getPJ(doc.Id);
        test.startTest();
        for(LWC_PJManageStatus.WrapperManageStatus wr : listwrapper){
            wr.status = 'Valid';
            listwrapperUpdated.add(wr);
        }
        system.assertEquals(LWC_PJManageStatus.updatePJ(listwrapperUpdated,doc.Id), 'OK', 
                                'Piece not updated');
        test.stopTest();
    }
}