hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/Mouvements_financiers__c.object-meta.xml
<CustomObject>
    <label>Calcul Indemnisation</label>
    <nameField>
        <label>Nom du mouvement financier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calcul Indemnisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Calcul Indemnisations</relationshipLabel>
    <relationshipName>Mouvements_financiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <description>Identification du montant du mouvement</description>
    <label>Montant</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Paiement_Versement__c.field-meta.xml
<CustomField>
    <fullName>Paiement_Versement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paiement Versement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Paiement_Versement__c.Case__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Paiement_Versement__c</referenceTo>
    <relationshipName>Mouvements_financiers</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crée</fullName>
                <default>true</default>
                <label>Crée</label>
            </value>
            <value>
                <fullName>En cours d&apos;approbation</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Demande en cours</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Rejeté</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Terminé</label>
            </value>
            <value>
                <fullName>Invalidated</fullName>
                <label>Invalidé</label>
            </value>
            <value>
                <fullName>En attente d&apos;approbation</fullName>
                <isActive>false</isActive>
                <label>En attente d&apos;approbation</label>
            </value>
            <value>
                <fullName>Encaissé</fullName>
                <isActive>false</isActive>
                <label>Encaissé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/Paiement_Versement__c.object-meta.xml
<CustomObject>
    <label>Paiement Versement</label>
    <nameField>
        <label>Paiement Versement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paiement Versement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Paiement Versement</relationshipLabel>
    <relationshipName>Paiement_Versement</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demande Paiement</fullName>
            </value>
            <value>
                <fullName>Payé Client</fullName>
            </value>
            <value>
                <fullName>Demande Versement</fullName>
            </value>
            <value>
                <fullName>Versé Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/classes/PaiementVersementTriggerHandlerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 27/04/2021
* @description Paiement Versement test class
* @Object Paiement Versement
*/

@isTest
public class PaiementVersementTriggerHandlerTest {

    /***
    * @description Update related MF after insert
    * @see updateRelatedMF
    */
    @isTest
    public static void updateRelatedMFTest(){
        
        // Create a sinistre
        Case c = TestFactory.createSinistre();
        insert c;
        
        // Create an indemnisation
        Mouvements_financiers__c m = TestFactory.createMouvementFinancier(c.id);
        insert m;
        
        // Approve the indemn
        m.Statut__c = 'Validé';
        update m;
        
        // And create a paiement versement
        Paiement_Versement__c p = new Paiement_Versement__c();
        p.Case__c = c.id;
        p.Montant__c = m.Montant__c;
        insert p;
        
        m = [SELECT id, Paiement_Versement__c 
             FROM Mouvements_financiers__c
             WHERE id =: m.id];
        
        system.assertEquals(p.id, m.Paiement_Versement__c, 
                            'The paiement versement shoulve been updated - This is wrong');
    }
}