hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Document__c/fields/Related_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Related_sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Document__c/fields/Valideur__c.field-meta.xml
<CustomField>
    <fullName>Valideur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Id du valideur</description>
    <label>Valideur</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/Piece_justificative_Sinistre__c.object-meta.xml
<CustomObject>
    <label>Pièce justificative Sinistre</label>
    <nameField>
        <label>Pièce justificative Sinistre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pièces justificatives Sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Technique Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document__c.Related_sinistre__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/ValidationDate__c.field-meta.xml
<CustomField>
    <fullName>ValidationDate__c</fullName>
    <description>Date à laquelle la pièce justificative a été considérée valide - Field saving the date when the Piece justificative was marked as valid</description>
    <label>Date de validation</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Valideur__c.field-meta.xml
<CustomField>
    <fullName>Valideur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Personne ayant validé le document</description>
    <label>Valideur</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Validite_document__c.field-meta.xml
<CustomField>
    <fullName>Validite_document__c</fullName>
    <label>Validité du document</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expected</fullName>
                <default>true</default>
                <label>1-Attendue</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <label>2-Reçu</label>
            </value>
            <value>
                <fullName>Valid</fullName>
                <label>3-Valide</label>
            </value>
            <value>
                <fullName>NotNeeded</fullName>
                <label>4-Plus réclamé</label>
            </value>
            <value>
                <fullName>Invalid</fullName>
                <label>5-Non valide</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/classes/GEDController.cls
/***
* @author Ariane Tanguy (GFI)
* @date 14/10/2020
* @description GED LWC Controller
*/
public with sharing class GEDController {

    /***
    * @description Get the current user profile
    * @return boolean - true if the profile can edit the picklist
    */
    @AuraEnabled(cacheable=true)
    public static boolean getUserProfile() {
        
        boolean canEdit = true;
        
        // Get the related sinistre id
        User u = [SELECT Profile.Name 
                  FROM User
                  WHERE id =: system.UserInfo.getUserId()];
        
        if(u.Profile.Name == 'SFAM TC'){
            canEdit = false;
        }
        return canEdit;
    }
    
    /***
    * @description Get all the case related files
    * @param caseId - case id
    * @return Map<String, String> - contentDocument DistributionPublicUrl mapped to the document title
    */
    @AuraEnabled(cacheable=true)
    public static Map<String, String> getRelatedFilesByRecordId(String caseId) {
        
        // Check whether the case has an email
        List<EmailMessage> emailMessageList = [SELECT id
                                               FROM EmailMessage
                                               WHERE RelatedToId =: caseId];
        
        Set<id> linkedIdSet = new Set<id>();
        linkedIdSet.add(caseId);
        for(EmailMessage em : emailMessageList){
            linkedIdSet.add(em.id);
        }
        
        // Get all the related contentDocument ids
        List<ContentDocumentLink> cdLinkList = [SELECT ContentDocumentId
                                                FROM ContentDocumentLink 
                                                WHERE LinkedEntityId IN :linkedIdSet];
        
        Set<ID> cdIdSet = new Set<ID>();
        for (ContentDocumentLink cdLink : cdLinkList) {
            cdIdSet.add(cdLink.ContentDocumentId);
        }
        
        // Filter PDF files 
        List<ContentVersion> CVList = [SELECT ContentDocumentId, FileExtension, Title 
                                       FROM ContentVersion 
                                       WHERE ContentDocumentId IN : cdIdSet 
                                       AND FileExtension = 'pdf'];
        
        // And add the other file types 
        List<ContentDistribution> cdList = [SELECT id, DistributionPublicUrl, Name, ContentVersionId
                                            FROM ContentDistribution
                                            WHERE ContentDocumentId IN: cdIdSet];
        
        Map<String, String> mapIdTitle = new Map<String, String>();
        Set<id> ContentVersionIdSet = new Set<id>();
        for (ContentDistribution cd : cdList) {
            if(!ContentVersionIdSet.contains(cd.ContentVersionId)){
                mapIdTitle.put(cd.DistributionPublicUrl, cd.Name.substringBefore(' '));
                ContentVersionIdSet.add(cd.ContentVersionId);
            }
        }
        
        return mapIdTitle;
    }

    /***
    * @description Get all the case related piece justificatives
    * @param documentId - document__c id
    * @return Map<String, String> - pj id mapped to pj name
    */
    @AuraEnabled(cacheable=true)
    public static Map<String, String> getPJMap(String documentId) {
        
        // Get the related sinistre id
        id sinistreId = [SELECT Related_sinistre__c 
                         FROM Document__c
                         WHERE id =: documentId].Related_sinistre__c;
        
        Map<String, String> pjNameValidityMap = new Map<String, String>();
        for(Piece_justificative_Sinistre__c pj : [SELECT Id, Name, Validite_document__c
                                                  FROM Piece_justificative_Sinistre__c
                                                  WHERE Case__c =: sinistreId
                                                  AND Validite_document__c != 'invalid']){
                                                      pjNameValidityMap.put(pj.Id, pj.Name);                                                      
                                                  }
        return pjNameValidityMap;
    }

    /***
    * @description Get all the case related piece justificatives
    * @param documentId - document__c id
    * @return List<Piece_justificative_Sinistre__c> - Related pj list
    */
    @AuraEnabled(cacheable=true)
    public static List<Piece_justificative_Sinistre__c> getPJList(String documentId) {
        
        // Get the related sinistre id
        id sinistreId = [SELECT Related_sinistre__c 
                         FROM Document__c
                         WHERE id =: documentId].Related_sinistre__c;
        
        List<Piece_justificative_Sinistre__c> pjList = [SELECT Id, Name, Validite_document__c
                                                        FROM Piece_justificative_Sinistre__c
                                                        WHERE Case__c =: sinistreId
                                                        AND Validite_document__c != 'invalid'];
        return pjList;
    }

    /***
    * @description Get the validité document picklist values
    * @param - NA
    * @return Map<String, String> - picklist label mapped to picklist values
    */
    @AuraEnabled(cacheable=true)
    public static Map<String, String> getPJOptions() {
        
        return(getPicklistValues(new Piece_justificative_Sinistre__c(), 
                                 'Validite_document__c'));
    }
    
    /***
	* @description Get the picklist values of an object
	* @param sObj
	* @param picklistField
	* @return Map<String, String>
	*/
    private static Map<String, String> getPicklistValues(SObject sObj, String picklistField){
        
        // Get a map of fields for the SObject
        Map<String, Schema.SObjectField> fieldMap = sObj.getSObjectType().getDescribe().fields.getMap();       
        
        // Get the list of picklist values for this field.
        List<Schema.PicklistEntry> picklistValueList = fieldMap.get(picklistField).getDescribe().getPickListValues();
        
        // Map these values
        Map<String, String> picklistValueMap = new Map<String, String>();
        for (Schema.PicklistEntry p : picklistValueList){ 
            picklistValueMap.put(p.getLabel(), p.getValue()); 
        }
        
        return picklistValueMap;
    }
    
    /***
	* @description Update PJ on the fly
	* @param pjId - pj id
	* @param newValidity - new picklist value
	* @return void
	*/
    @AuraEnabled
    public static void updatePJ(String pjId, String newValidity, String documentId) {
        
		// Get PJ
        Piece_justificative_Sinistre__c pj = [SELECT Id, Validite_document__c, Document__c
                                              FROM Piece_justificative_Sinistre__c
                                              WHERE id =: pjId.substringBefore('-')];
        
        // Unlink the document if the pj is not there anymore
        if(newValidity == 'expected'){
            pj.Document__c = NULL;
        } else {
            pj.Document__c = documentId;
        }
        
        if(newValidity == 'Valid'){
            pj.ValidationDate__c = system.today();
        } 
        
        pj.Validite_document__c = newValidity;
        pj.Valideur__c = system.UserInfo.getUserId();
        update pj;
    }
}