hubSide/force-app/main/default/objects/Emprunt__c/Emprunt__c.object-meta.xml
<CustomObject>
    <label>Emprunt</label>
    <nameField>
        <displayFormat>EMP-{000000}</displayFormat>
        <label>Emprunt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emprunts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Caution_recue__c.field-meta.xml
<CustomField>
    <fullName>Caution_recue__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Caution reçue</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client empruntant l&apos;objet</description>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Le client doit être du type Person Account.</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Emprunts (Client)</relationshipLabel>
    <relationshipName>Emprunts_client</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_retour_prevu__c.field-meta.xml
<CustomField>
    <fullName>Date_retour_prevu__c</fullName>
    <description>Date prévisionnelle de retour pour vérifier le nombre de jours possible et gérer les stocks glissants par la suite</description>
    <label>Date du retour prévu</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <description>Date d&apos;emprunt de l&apos;objet</description>
    <label>Date de sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Heure_retour_prevue__c.field-meta.xml
<CustomField>
    <fullName>Heure_retour_prevue__c</fullName>
    <label>Heure de retour prevue</label>
    <type>Time</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Heure_sortie__c.field-meta.xml
<CustomField>
    <fullName>Heure_sortie__c</fullName>
    <description>Heure de sortie de l&apos;objet emprunté</description>
    <label>Heure de sortie</label>
    <type>Time</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En magasin</fullName>
                <default>true</default>
                <label>En magasin</label>
            </value>
            <value>
                <fullName>Sortie</fullName>
            </value>
            <value>
                <fullName>Retourné</fullName>
                <label>Retour sans défaut</label>
            </value>
            <value>
                <fullName>Retour avec défaut</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
                <isActive>false</isActive>
                <label>Annulé</label>
            </value>
            <value>
                <fullName>Label.Location_StatusEmprunt1</fullName>
                <isActive>false</isActive>
                <label>Label.Location_StatusEmprunt1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/recordTypes/Emprunt.recordType-meta.xml
<RecordType>
    <fullName>Emprunt</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet emprunt une fois créé</description>
    <label>Emprunt</label>
</RecordType>

hubSide/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Objets Réservés sur le web / en boutique</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Numero de reservation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Reservation__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reservations (Nom du client)</relationshipLabel>
    <relationshipName>Reservations_Client</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Date_retrait__c.field-meta.xml
<CustomField>
    <fullName>Date_retrait__c</fullName>
    <description>Date de début d’emprunt</description>
    <label>Date de début de location souhaitée</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Duree_emprunt__c.field-meta.xml
<CustomField>
    <fullName>Duree_emprunt__c</fullName>
    <description>Nombre de jours de l&apos;emprunt</description>
    <label>Duree de l&apos;emprunt (jours)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Motif_pre_reservation__c.field-meta.xml
<CustomField>
    <fullName>Motif_pre_reservation__c</fullName>
    <description>Contient la justification du statut pré-réservé.</description>
    <label>Motif pré-réservation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Défaut de gamme</fullName>
            </value>
            <value>
                <fullName>Hors stock</fullName>
            </value>
            <value>
                <fullName>Prospect à qualifier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Produit_reserve__c.field-meta.xml
<CustomField>
    <fullName>Produit_reserve__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Produit réservé</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Stock_produit__c.Statut__c</field>
            <operation>equals</operation>
            <value>En stock, Sortie client, Réservé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Stock_produit__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Réservé</fullName>
            </value>
            <value>
                <fullName>Réservation_convertie</fullName>
                <label>Réservation convertie</label>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>Pré-réservé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/recordTypes/Reservation.recordType-meta.xml
<RecordType>
    <fullName>Reservation</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet Reservation</description>
    <label>Reservation</label>
</RecordType>

hubSide/force-app/main/default/objects/Reservation__c/recordTypes/Reservation_convertie.recordType-meta.xml
<RecordType>
    <fullName>Reservation_convertie</fullName>
    <active>true</active>
    <description>Layout Read-Only pour les réservations converties</description>
    <label>Reservation convertie</label>
</RecordType>

hubSide/force-app/main/default/objects/Stock_produit__c/Stock_produit__c.object-meta.xml
<CustomObject>
    <label>Stock magasin</label>
    <nameField>
        <label>Stock magasin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks magasin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_retrait_souhaitee__c.field-meta.xml
<CustomField>
    <fullName>Date_retrait_souhaitee__c</fullName>
    <description>Date de retrait souhaitée pour la réservation.</description>
    <label>Date de retrait souhaitée</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <label>Date sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Prochaine_reservation__c.field-meta.xml
<CustomField>
    <fullName>Prochaine_reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pointe vers la plus proche réservation à venir.</description>
    <label>Prochaine réservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Stocks magasin</relationshipLabel>
    <relationshipName>Stocks_magasin</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/classes/ReservationTriggerHandlerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 05/05/2020
* @description ReservationTrigger test class
* @Object Reservation__c
*/

@isTest
public class ReservationTriggerHandlerTest {
    
    /***
	* @description When creating a reservation, check the record type
	* @see updateRecordTypeOnCreation
	*/
    @isTest
    public static void updateRecordTypeOnCreationTest(){
        
        // Create a new Contract
        Reservation__c r = TestFactory.createReservation();
        insert r;
        
        // Query the reservation and check whether the record type has been correctly updated
        r = [SELECT id, RecordType.DeveloperName FROM Reservation__c WHERE id =: r.id];
        
        system.assertEquals('Reservation', r.RecordType.DeveloperName, 
                            'The record type should have been updated on the reservation - This is wrong');
    }
    
    /***
	* @description When converting a reservation, check the record type
	* @see updateRecordTypeOnUpdate
	*/
    @isTest
    public static void updateRecordTypeOnUpdateTest(){
        
        // Create a new Contract
        Reservation__c r = TestFactory.createReservation();
        insert r;
        
        // Convert the reservation
        r.Status__c = 'Réservation_convertie';
        update r;
        
        // Query the reservation and check whether the record type has been correctly updated
        r = [SELECT id, RecordType.DeveloperName FROM Reservation__c WHERE id =: r.id];
        
        system.assertEquals('Reservation_convertie', r.RecordType.DeveloperName, 
                            'The record type should have been updated on the converted reservation - This is wrong');
    }

    /***
	* @description When creating a reservation, check whether there isn't already a reservation or an emprunt
	* @see checkStockPlanning
	*/
    @isTest
    public static void checkStockPlanningTest(){
        
        // Create a contract
        Asset c = TestFactory.createContract();
        insert c;
        
        // Create a stock
        Stock_Produit__c s = TestFactory.createStock();
        insert s;
        
        // Create an emprunt
        Emprunt__c e = TestFactory.createEmprunt(c, s);
        e.Client__c = c.AccountId;
        e.Date_sortie__c = system.today();
        e.Date_retour_prevu__c = system.today() + 1;
        e.Heure_sortie__c = system.now().time();
        e.Heure_retour_prevue__c = system.now().time();
        insert e;
        
        e.Status__c = 'Sortie';
        e.Caution_recue__c = TRUE;
        update e;
        
        test.startTest();
        
        // Create a new reservation
        Reservation__c r = TestFactory.createReservation(s);
        r.Date_retrait__c = system.today() + 5;
        r.Duree_emprunt__c = 1;
        insert r;
        
        // Create another reservation
        Reservation__c newRes = TestFactory.createReservation(s);
        newRes.Date_retrait__c = system.today() + 3;
        newRes.Duree_emprunt__c = 2;
        
        // Try to insert it
        try{
            insert newRes;
            system.assert(false, 'This reservation shouldnt have been successfully inserted - This is wrong');
        } catch(Exception ex){
            system.assertEquals(TRUE, ex.getMessage().contains('pas disponible sur la'), ex.getMessage());
        }
        
        // Change the reservation
        newRes.Duree_emprunt__c = 1;
        insert newRes;
        
        List<Reservation__c> reservationList = [SELECT id FROM Reservation__c WHERE Produit_reserve__c =: s.id];
        system.assertEquals(2, reservationList.size(), 
                            'This reservation should have been successfully inserted - This is wrong');
        
        test.stopTest();
    }
    
    /***
	* @description When creating a pre reservation, check whether it should'nt be a reservation
	* @see updatePreReservation
	*/
    @isTest
    public static void updatePreReservationTest(){
        
        // Create a new reservation
        Reservation__c r = TestFactory.createReservation();
        r.Status__c = 'Pré-réservé';
        r.Date_retrait__c = system.today() + 5;
        r.Duree_emprunt__c = 1;
        insert r;
        
        r = [SELECT Client__c, Status__c, Motif_pre_reservation__c FROM Reservation__c WHERE id =: r.id];
        system.assertEquals('Pré-réservé', r.Status__c, 
                           'The status should have been pre reserved - This is wrong');
        system.assertEquals('Prospect à qualifier', r.Motif_pre_reservation__c, 
                           'The motif should have been Prospect à qualifier - This is wrong');
        
        // Create a contract on that account
        Asset a = TestFactory.createContract(r.Client__c);
        insert a;
        
        test.startTest();
        
        // Create another reservation
        Reservation__c newRes = TestFactory.createReservation(r.Client__c);
        newRes.Status__c = 'Pré-réservé';
        newRes.Date_retrait__c = system.today() + 31;
        newRes.Duree_emprunt__c = 1;
        insert newRes;
        
        newRes = [SELECT Status__c, Produit_reserve__c FROM Reservation__c WHERE id =: newRes.id];
        system.assertEquals('Réservé', newRes.Status__c, 
                           'The status should have been reserved - This is wrong');
        
        // Create yet another reservation
        Reservation__c anotherRes = TestFactory.createReservation(r.Client__c, newRes.Produit_reserve__c);
        anotherRes.Status__c = 'Pré-réservé';
        anotherRes.Date_retrait__c = system.today() + 31;
        anotherRes.Duree_emprunt__c = 1;
        insert anotherRes;
        
        anotherRes = [SELECT Status__c, Motif_pre_reservation__c FROM Reservation__c WHERE id =: anotherRes.id];
        system.assertEquals('Pré-réservé', anotherRes.Status__c, 
                           'The status should have been pre reserved again - This is wrong');
        system.assertEquals('Hors stock', anotherRes.Motif_pre_reservation__c, 
                           'The motif should have been Hors stock - This is wrong');
        
        test.stopTest();
    }
    
    /***
	* @description When creating a reservation, update the stock if needed
	* @see updateRelatedStock
	*/
    @isTest
    public static void updateRelatedStockTest(){
        
        test.startTest();
        
        // Create a stock
        Stock_produit__c s = TestFactory.createStock();
        insert s;
        
        system.assertEquals(NULL, s.Prochaine_reservation__c, 
                           'That stock shouldnt have a next reservation already - This is wrong');
        
        // Create a new reservation
        Reservation__c r = TestFactory.createReservation(s);
        r.Date_retrait__c = system.today() + 5;
        r.Duree_emprunt__c = 1;
        insert r;
        
        // Check the stock
        s = [SELECT Prochaine_reservation__c, Date_retrait_souhaitee__c FROM Stock_produit__c WHERE id =: s.id];
        system.assertEquals(r.Date_retrait__c, s.Date_retrait_souhaitee__c, 
                           'The stock next reservation date shouldve been updated - This is wrong');
        system.assertEquals(r.id, s.Prochaine_reservation__c, 
                           'The stock next reservation shouldve been updated - This is wrong');
        
        // Update the reservation
        r.Date_retrait__c = system.today() + 10;
        update r;
        
        test.stopTest();
        
        // Check the stock
        s = [SELECT Prochaine_reservation__c, Date_retrait_souhaitee__c FROM Stock_produit__c WHERE id =: s.id];
        system.assertEquals(r.Date_retrait__c, s.Date_retrait_souhaitee__c, 
                           'The stock next reservation date shouldve been updated again - This is wrong');
        
        // Create another reservation
        Reservation__c r1 = TestFactory.createReservation(s);
        r1.Date_retrait__c = system.today() + 4;
        r1.Duree_emprunt__c = 1;
        insert r1;
        
        // Check the stock
        s = [SELECT Prochaine_reservation__c, Date_retrait_souhaitee__c FROM Stock_produit__c WHERE id =: s.id];
        system.assertEquals(r1.Date_retrait__c, s.Date_retrait_souhaitee__c, 
                           'The stock next reservation date shouldve been updated with the new reservation - This is wrong');
        system.assertEquals(r1.id, s.Prochaine_reservation__c, 
                           'The stock next reservation shouldve been updated  with the new reservation - This is wrong');
    }
}