hubSide/force-app/main/default/objects/Emprunt__c/Emprunt__c.object-meta.xml
<CustomObject>
    <label>Emprunt</label>
    <nameField>
        <displayFormat>EMP-{000000}</displayFormat>
        <label>Emprunt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emprunts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_retour_prevu__c.field-meta.xml
<CustomField>
    <fullName>Date_retour_prevu__c</fullName>
    <description>Date prévisionnelle de retour pour vérifier le nombre de jours possible et gérer les stocks glissants par la suite</description>
    <label>Date du retour prévu</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <description>Date d&apos;emprunt de l&apos;objet</description>
    <label>Date de sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Nombre_jours_depassement__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_depassement__c</fullName>
    <formula>IF(
    Nombre_jours_imputes__c - Nombre_de_jours_consommation__c - Contrat__r.Code_formule__r.Nombre_jours_carence__c &gt; 0,
    Nombre_jours_imputes__c - Nombre_de_jours_consommation__c - Contrat__r.Code_formule__r.Nombre_jours_carence__c,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours en dépassement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Produit_emprunte__c.field-meta.xml
<CustomField>
    <fullName>Produit_emprunte__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Produit emprunté</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2 OR 3 OR 4)</booleanFilter>
        <errorMessage>Le produit emprunté doit être disponible pour être sélectionné.</errorMessage>
        <filterItems>
            <field>Stock_produit__c.Statut__c</field>
            <operation>equals</operation>
            <value>En stock, Réservé, Sortie client</value>
        </filterItems>
        <filterItems>
            <field>Stock_produit__c.Emprunt_actuel__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Reservation_origine__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Retour sans défaut, Retour avec défaut</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Stock_produit__c</referenceTo>
    <relationshipLabel>Emprunts</relationshipLabel>
    <relationshipName>Emprunts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En magasin</fullName>
                <default>true</default>
                <label>En magasin</label>
            </value>
            <value>
                <fullName>Sortie</fullName>
            </value>
            <value>
                <fullName>Retourné</fullName>
                <label>Retour sans défaut</label>
            </value>
            <value>
                <fullName>Retour avec défaut</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
                <isActive>false</isActive>
                <label>Annulé</label>
            </value>
            <value>
                <fullName>Label.Location_StatusEmprunt1</fullName>
                <isActive>false</isActive>
                <label>Label.Location_StatusEmprunt1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Stock_disponible__c.field-meta.xml
<CustomField>
    <fullName>Stock_disponible__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Vérifie la disponibilité du stock selectionné (back end)</description>
    <label>Stock disponible sur la période ?</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/recordTypes/Emprunt.recordType-meta.xml
<RecordType>
    <fullName>Emprunt</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet emprunt une fois créé</description>
    <label>Emprunt</label>
</RecordType>

hubSide/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Objets Réservés sur le web / en boutique</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Numero de reservation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Reservation__c/fields/Date_retrait__c.field-meta.xml
<CustomField>
    <fullName>Date_retrait__c</fullName>
    <description>Date de début d’emprunt</description>
    <label>Date de début de location souhaitée</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Duree_emprunt__c.field-meta.xml
<CustomField>
    <fullName>Duree_emprunt__c</fullName>
    <description>Nombre de jours de l&apos;emprunt</description>
    <label>Duree de l&apos;emprunt (jours)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Motif_pre_reservation__c.field-meta.xml
<CustomField>
    <fullName>Motif_pre_reservation__c</fullName>
    <description>Contient la justification du statut pré-réservé.</description>
    <label>Motif pré-réservation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Défaut de gamme</fullName>
            </value>
            <value>
                <fullName>Hors stock</fullName>
            </value>
            <value>
                <fullName>Prospect à qualifier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Produit_reserve__c.field-meta.xml
<CustomField>
    <fullName>Produit_reserve__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Produit réservé</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Stock_produit__c.Statut__c</field>
            <operation>equals</operation>
            <value>En stock, Sortie client, Réservé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Stock_produit__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Réservé</fullName>
            </value>
            <value>
                <fullName>Réservation_convertie</fullName>
                <label>Réservation convertie</label>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>Pré-réservé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Stock_disponible__c.field-meta.xml
<CustomField>
    <fullName>Stock_disponible__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Vérifie la disponibilité du stock selectionné (back end)</description>
    <label>Stock disponible sur la période ?</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/recordTypes/Reservation.recordType-meta.xml
<RecordType>
    <fullName>Reservation</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet Reservation</description>
    <label>Reservation</label>
</RecordType>

hubSide/force-app/main/default/objects/Reservation__c/recordTypes/Reservation_convertie.recordType-meta.xml
<RecordType>
    <fullName>Reservation_convertie</fullName>
    <active>true</active>
    <description>Layout Read-Only pour les réservations converties</description>
    <label>Reservation convertie</label>
</RecordType>

hubSide/force-app/main/default/objects/Reservation__c/recordTypes/Reservation_pre_reservee.recordType-meta.xml
<RecordType>
    <fullName>Reservation_pre_reservee</fullName>
    <active>true</active>
    <label>Réservation pré-réservée</label>
</RecordType>

hubSide/force-app/main/default/objects/Stock_produit__c/Stock_produit__c.object-meta.xml
<CustomObject>
    <label>Stock magasin</label>
    <nameField>
        <label>Stock magasin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks magasin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_retrait_souhaitee__c.field-meta.xml
<CustomField>
    <fullName>Date_retrait_souhaitee__c</fullName>
    <description>Date de retrait souhaitée pour la réservation.</description>
    <label>Date de retrait souhaitée</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <label>Date sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Prochaine_reservation__c.field-meta.xml
<CustomField>
    <fullName>Prochaine_reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pointe vers la plus proche réservation à venir.</description>
    <label>Prochaine réservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Stocks magasin</relationshipLabel>
    <relationshipName>Stocks_magasin</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/classes/ReservationTriggerHandler.cls
/***
* @author Ariane Tanguy (GFI)
* @date 05/05/2020
* @description Handler class for ReservationTrigger
*/

public class ReservationTriggerHandler {
    
    private static id createdReservationRecordType = UtilityClassHelper.getCreatedRecordType('Reservation');
    private static id tempResRecordType = UtilityClassHelper.getCreatedRecordType('Reservation_pre_reservee');
    
    /***
	* @description Update the record type
	* @param newReservationList - list of reservation
	* @return NA
	*/
    public static void updateRecordTypeOnCreation(List<Reservation__c> newReservationList){
        
        for(Reservation__c r : newReservationList){
            if(r.Status__c == 'Pré-réservé'){
                r.RecordTypeId = tempResRecordType;
            } else {
                r.RecordTypeId = createdReservationRecordType;
            }
        }
    }
    
    /***
	* @description Update the pre-reservation depending of the client infos
	* @param newReservationList - list of reservation
	* @param canMap - map of boolean
	* @return NA
	*/
    public static void updatePreReservation(List<Reservation__c> newReservationList, Map<id, String> cannotMap){
        
        // Loop over all the new reservations
        for(Reservation__c r : newReservationList){
            
            // If that particular reservation isnt authorized by rules 1 and 2
            if(cannotMap.keySet().contains(r.id)){
                r.Motif_pre_reservation__c = cannotMap.get(r.id);
            } else {
                if(r.Status__c == 'Pré-réservé'){
                    r.Status__c = 'Réservé';
                    r.RecordTypeId = createdReservationRecordType;
                }
            }
        }
    }
    
    /***
	* @description Update the record type
	* @param newReservationList - list of reservation
	* @param reservationRecordType - previously queried record type
	* @return NA
	*/
    public static void updateRecordTypeOnUpdate(List<Reservation__c> newReservationList, Map<id, Reservation__c> oldReservationMap){
        
        for(Reservation__c r : newReservationList){
            if(r.Status__c != oldReservationMap.get(r.Id).Status__c){
                if(r.Status__c == 'Réservation_convertie' || r.Status__c == 'Annulé'){
                   r.RecordTypeId = UtilityClassHelper.getCreatedRecordType('Reservation_convertie');
               }
                if(r.Status__c == 'Réservé'){
                    r.RecordTypeId = createdReservationRecordType;
                }
            }
        }
    }
    
    /***
	* @description When creating a reservation, check whether there isn't already an emprunt or a reservation.
	* @param newReservationList - list of new reservation
	* @param currentEmpruntList - current emprunt list
	* @param plannedReservationList - already planned reservation
	* @return NA
	*/
    public static void checkStockPlanning(List<Reservation__c> newReservationList, List<Emprunt__c> currentEmpruntList, List<Reservation__c> plannedReservationList){
                
        // Loop over the new reservation
        for(Reservation__c r : newReservationList){
            
            system.debug('-- here r ' + r);
            
            r.Stock_disponible__c = TRUE;
            
            if(r.Date_retrait__c == NULL || r.Duree_emprunt__c == NULL){
                break;
            }
            
            system.debug('-- here currentEmpruntList ' + currentEmpruntList);
            
            // Then over the current emprunt
            for(Emprunt__c currentEmprunt : currentEmpruntList){
                
                system.debug('-- here currentEmprunt ' + currentEmprunt);
                
                if(UtilityClassHelper.compareDate(currentEmprunt.Date_sortie__c, 
                                                  currentEmprunt.Date_retour_prevu__c, 
                                                  r.Date_retrait__c, 
                                                  r.Date_retrait__c.addDays((Integer)r.Duree_emprunt__c)) && 
                   r.Produit_reserve__c == currentEmprunt.Produit_emprunte__c &&
                   currentEmprunt.Nombre_jours_depassement__c < 0){
                       r.Stock_disponible__c = FALSE;
                       system.debug('--- FALSE');
                       break;
                   }
            }
            
            // And finally over the reservation, if the stock is still not taken
            if(r.Stock_disponible__c){
                
                system.debug('-- here plannedReservationList ' + plannedReservationList);
                
                for(Reservation__c plannedRes : plannedReservationList){
                    
                    system.debug('-- here plannedRes ' + plannedRes);
                    
                    if(UtilityClassHelper.compareDate(plannedRes.Date_retrait__c, 
                                                      plannedRes.Date_retrait__c.addDays((integer)r.Duree_emprunt__c), 
                                                      r.Date_retrait__c, 
                                                      r.Date_retrait__c.addDays((Integer)r.Duree_emprunt__c)) && 
                       plannedRes.Produit_reserve__c == r.Produit_reserve__c){
                           r.Stock_disponible__c = FALSE;
                               system.debug('--- FALSE');                        
                           break;
                       }
                }
            }
            // If the date was 30 days + away from today's date, create it anyway, and may the odds be in your favor
            if(!r.Stock_disponible__c &&
               r.Date_retrait__c > system.today() + 30){
                   r.Status__c = 'Pré-réservé';
                   r.RecordTypeId = tempResRecordType;
                   r.Motif_pre_reservation__c = 'Hors stock';
                   r.Stock_disponible__c = TRUE;
               }
        }
    }
    
    /***
	* @description Update the related stock
	* @param newReservationList - list of reservation
	* @param reservationRecordType - previously queried record type
	* @return NA
	*/
    public static void updateRelatedStock(List<Reservation__c> newReservationList, List<Stock_produit__c> relatedStockList){
                
        // Map the reservation to their stock
        Map<id, List<Reservation__c>> stockIdReservationMap = new Map<id, List<Reservation__c>>();
        for(Reservation__c r : newReservationList){
            if(!stockIdReservationMap.keySet().contains(r.Produit_reserve__c)){
                List<Reservation__c> tmpList = new List<Reservation__c>();
                stockIdReservationMap.put(r.Produit_reserve__c, tmpList);
            }
            stockIdReservationMap.get(r.Produit_reserve__c).add(r);
        }
        
        // Loop over the stocks to update them
        for(Stock_produit__c s : relatedStockList){
            
            if(stockIdReservationMap.keySet().contains(s.id)){
                
                // Loop over the related reservations
                for(Reservation__c r : stockIdReservationMap.get(s.id)){
                    
                    if(s.Prochaine_reservation__c == r.id && 
                       s.Date_retrait_souhaitee__c != r.Date_retrait__c){
                           s.Date_retrait_souhaitee__c = r.Date_retrait__c;
                       }
                    
                    if(s.Date_retrait_souhaitee__c > r.Date_retrait__c ||
                       s.Date_retrait_souhaitee__c == NULL){
                           s.Prochaine_reservation__c = r.id;
                           s.Date_retrait_souhaitee__c = r.Date_retrait__c;
                       }
                }                
            }
        }
        
        update relatedStockList;
    }
}