hubSide/force-app/main/default/objects/Asset/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Id_contrat_B_appli__c.field-meta.xml
<CustomField>
    <fullName>Id_contrat_B_appli__c</fullName>
    <label>Id contrat B-appli</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/AssociatedCost__c/AssociatedCost__c.object-meta.xml
<CustomObject>
    <description>This object allows to link a cost to the damaged equipment.</description>
    <label>Coût Associé</label>
    <nameField>
        <label>Objet Associé</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coûts Associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/AssociatedCost__c/fields/DamagedEquipment__c.field-meta.xml
<CustomField>
    <fullName>DamagedEquipment__c</fullName>
    <label>Equipement Sinistré</label>
    <referenceTo>Equipement_sinistre__c</referenceTo>
    <relationshipLabel>Coûts Associés</relationshipLabel>
    <relationshipName>AssociatedCosts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Demande.recordType-meta.xml
<RecordType>
    <fullName>Demande</fullName>
    <active>true</active>
    <businessProcess>Demande</businessProcess>
    <description>Demande relative à de nouveaux documents client</description>
    <label>Demande</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/BAppliStockFluctuationRef__c.field-meta.xml
<CustomField>
    <fullName>BAppliStockFluctuationRef__c</fullName>
    <label>Numéro de mouvement de stock BAppli</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/EquipmentAmount__c.field-meta.xml
<CustomField>
    <fullName>EquipmentAmount__c</fullName>
    <label>Valeur Echange</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GradeEquipSin</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/OrderDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDate__c</fullName>
    <label>Date de commande</label>
    <type>DateTime</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/RealCost__c.field-meta.xml
<CustomField>
    <fullName>RealCost__c</fullName>
    <label>Coût Réel</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/SerieNumberEC__c.field-meta.xml
<CustomField>
    <fullName>SerieNumberEC__c</fullName>
    <label>Numero de serie (IMEI)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Statut_equipement__c.field-meta.xml
<CustomField>
    <fullName>Statut_equipement__c</fullName>
    <label>Statut equipement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EquipSin_Statut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/FlowConfiguration__mdt/FlowConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>Flow Configuration</label>
    <pluralLabel>Flow Configurations</pluralLabel>
</CustomObject>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/Mouvements_financiers__c.object-meta.xml
<CustomObject>
    <label>Calcul Indemnisation</label>
    <nameField>
        <label>Nom du mouvement financier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calcul Indemnisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Calcul Indemnisations</relationshipLabel>
    <relationshipName>Mouvements_financiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <description>Identification du montant du mouvement</description>
    <label>Montant</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Paiement_Versement__c.field-meta.xml
<CustomField>
    <fullName>Paiement_Versement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paiement Versement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Paiement_Versement__c.Case__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Paiement_Versement__c</referenceTo>
    <relationshipName>Mouvements_financiers</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Type_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Type_mouvement__c</fullName>
    <label>Type Coût</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cout_choisi__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prime pour echange</fullName>
                <label>Prime pour échange</label>
            </value>
            <value>
                <fullName>Geste commercial</fullName>
            </value>
            <value>
                <fullName>Indemnite retard suite à expertise</fullName>
                <label>Indemnité retard suite à expertise</label>
            </value>
            <value>
                <fullName>Prime pour reparation par le client</fullName>
                <label>Prime pour réparation par le client</label>
            </value>
            <value>
                <fullName>Prime pour communication frauduleuse</fullName>
            </value>
            <value>
                <fullName>Cout interne reparation</fullName>
                <label>Coût interne réparation</label>
            </value>
            <value>
                <fullName>Cout interne d&apos;echange</fullName>
                <label>Coût interne d&apos;échange</label>
            </value>
            <value>
                <fullName>Franchise</fullName>
            </value>
            <value>
                <fullName>Cout prime magasin</fullName>
                <label>Coût prime magasin</label>
            </value>
            <value>
                <fullName>Complément réparation</fullName>
            </value>
            <value>
                <fullName>Cout forfait de reparation</fullName>
                <isActive>false</isActive>
                <label>Coût forfait de réparation</label>
            </value>
            <value>
                <fullName>Remboursement client</fullName>
                <isActive>false</isActive>
                <label>Remboursement client</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/Paiement_Versement__c.object-meta.xml
<CustomObject>
    <label>Paiement Versement</label>
    <nameField>
        <label>Paiement Versement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paiement Versement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/BAppliEventId__c.field-meta.xml
<CustomField>
    <fullName>BAppliEventId__c</fullName>
    <externalId>true</externalId>
    <label>BAppliEventId</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Paiement Versement</relationshipLabel>
    <relationshipName>Paiement_Versement</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/globalValueSets/GradeEquipSin.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NEUF</fullName>
        <label>Neuf</label>
    </customValue>
    <customValue>
        <fullName>GRADE1</fullName>
        <label>Grade 1</label>
    </customValue>
    <customValue>
        <fullName>GRADE2</fullName>
        <label>Grade 2</label>
    </customValue>
    <customValue>
        <fullName>GRADE3</fullName>
        <label>Grade 3</label>
    </customValue>
    <customValue>
        <fullName>Grade 2temp</fullName>
        <isActive>false</isActive>
        <label>Grade 2temp</label>
    </customValue>
    <customValue>
        <fullName>Grade 1temp</fullName>
        <isActive>false</isActive>
        <label>Grade 1temp</label>
    </customValue>
    <customValue>
        <fullName>Neuftemp</fullName>
        <isActive>false</isActive>
        <label>Neuftemp</label>
    </customValue>
    <customValue>
        <fullName>Grade 3temp</fullName>
        <isActive>false</isActive>
        <label>Grade 3temp</label>
    </customValue>
    <description>Grades des équipements sinistrés - Equipement rank values</description>
    <masterLabel>Grade équipement sinistré</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/BAppliCallout.cls
/***
* @author Nicolas Brancato (GFI)
* @date 07/01/2021
* @description Callout class for outbound call with BAppli services
*/
public class BAppliCallout {
    
    static final String EXTERNALSYSTEM_BAPPLI = 'BAppli';
    static final String ENDPOINTNAME_PAYMENT = 'payment';
    static final String ENDPOINTNAME_STOCK = 'getFromStock';
    static final Integer STATUSCODE_200 = 200;
    static final Integer STATUSCODE_400 = 400;
    static final Integer STATUSCODE_404 = 404;
    static final Integer STATUSCODE_500 = 500;
    public static final String DAMAGEDEQUIPMENTSTATUS_DESTOCK = 'En destockage';
    public static final String DAMAGEDEQUIPMENTSTATUS_ORDER = 'En commmande';
    public static final String ASSOCIATEDCOSTOBJECT_EQUIPMENTEXCHANGE = 'Equipement Echangé';
    static final String BAPPLISTOCKNAME_SFAM = 'SFAM';
    
    /***
    * @description Trigger payment to BAppli when a Paiement_Versement__c record is created with status "Demande Versement"
    * @param id caseId Case id linked to the Paiement_Versement__c
    * @param id payId Paiement_Versement__c id
    * @param string BAppliContractId Value of the BAppli Contract Id stored in the field Id_contrat_B_appli__c in the linked asset
    * @param decimal amount Amount stored in the field Montant__c in the Paiement_Versement__c
    * @return null
    */
    @future(callout=true)
    public static void sendPayment (id caseId, id payId, string BAppliContractId, decimal amount) {
        
        FlowConfiguration__mdt flowConfig = [SELECT Endpoint__c, Username__c
                                             FROM FlowConfiguration__mdt
                                             WHERE Label =: EXTERNALSYSTEM_BAPPLI
                                             LIMIT 1];
        
        string body = '{"type":"claim_bonus","contractNumber":"' + BAppliContractId + 
            '","amount":' + amount + 
            ',"userId":"' + UserInfo.getUserEmail() + 
            '"}';
        HTTPResponse res = new HTTPResponse();
        
        try {
            
            // payment request
            HttpRequest req = new HttpRequest();
            req.setEndpoint(flowConfig.Endpoint__c + 'admin/api/claim/' + ENDPOINTNAME_PAYMENT);
            req.setMethod('POST');
            req.setTimeout(2 * 60 * 1000);
            String authorizationHeader = 'Bearer ' + flowConfig.Username__c;
            req.setHeader('Authorization', authorizationHeader);
            req.setBody(body);
            
            system.debug('body >> ' + body);
            
            Http http = new Http();
            res = http.send(req);
            
            System.debug('answer payment' + res.getBody());
                        
            switch on res.getStatusCode() {
                when 200 {
                    Paiement_Versement__c payToUpdate = new Paiement_Versement__c(id = payId,BAppliEventId__c = res.getBody());
                    update payToUpdate;
                    System.debug('payToUpdate' + payToUpdate);
                    LogCallout.logSuccess(EXTERNALSYSTEM_BAPPLI + ' ' + ENDPOINTNAME_PAYMENT, caseId, null, payId, body, res);
                }
                when else {
                    LogCallout.logError(EXTERNALSYSTEM_BAPPLI + ' ' + ENDPOINTNAME_PAYMENT, caseId, null, payId, body, res, null);
                }
            }
            
        } catch (Exception e) {
            system.debug('exception sendPayment' + String.valueOf(e));
            LogCallout.logError(EXTERNALSYSTEM_BAPPLI + ' ' + ENDPOINTNAME_PAYMENT, caseId, null, payId, body, res, String.valueOf(e));
        } 
    }
    
    /***
    * @description Trigger destock to BAppli
    * @param string stockName Constante value to reach the appropriate stock
    * @param string IdExterneBAppliEquipementEchange External id of the exchange equipment
    * @param string grade Grade of the chosen equipment
    * @param string operator Operator of the damaged equipment
    * @param id eqsId id of the Equipement_sinistre__c
    * @param id caseId id of linked case
    * @return null
    */
    @future(callout=true)
    public static void getFromStock (string stockName, string IdExterneBAppliEquipementEchange, string grade, string operator, id eqsId, id caseId) {
        
        FlowConfiguration__mdt flowConfig = [SELECT Endpoint__c, Username__c
                                             FROM FlowConfiguration__mdt
                                             WHERE Label =: EXTERNALSYSTEM_BAPPLI
                                             LIMIT 1];
        
        string operatorSent = 'Tout opérateur';
        if(operator != null && operator != ''){
            operatorSent = operator;    
        } 
        
         Case caseObject = [SELECT Subject
            FROM Case
            WHERE id =: caseId
            LIMIT 1];
        
        // Pending us rework to change Grade__c api name to set BAppli value
        string body = '{"stockName":"' + stockName + 
            '","modelCode":"' + IdExterneBAppliEquipementEchange + 
            '","grade":"' + grade + 
            '","operator":"' + operatorSent + 
            '","comment":"' + caseObject.Subject + 
            '"}';
        
        system.debug('-- bodysent ' +body);
        HTTPResponse res = new HTTPResponse();
        try {
            // destock request
            HttpRequest req = new HttpRequest();
            req.setEndpoint(flowConfig.Endpoint__c + 'admin/api/claim/' + ENDPOINTNAME_STOCK);
            req.setMethod('POST');
            req.setTimeout(2 * 60 * 1000);
            String authorizationHeader = 'Bearer ' + flowConfig.Username__c;
            req.setHeader('Authorization', authorizationHeader);
            req.setBody(body);
            Http http = new Http();
            MockToDev mock = new MockToDev(200, '', 
                        '{"imei":"355328086961253","stockFluctuationRef":"NUM_99999999","cost":"100"}', 
                        new Map<String,String>{'Keep-Alive' => 'yes'});
           
            //if dev2 environnnement get Mock
            if(URL.getSalesforceBaseUrl().toExternalForm().contains('dev2') && !System.test.isRunningTest()){              
                res = mock.respond();
            } else{
                res = http.send(req);
            }
            
            System.debug('-- answer destock ' + res.getBody());
            Integer AnswerStatus = res.getStatusCode();
            
            if(AnswerStatus == STATUSCODE_200){
                
                Map<String, object> answerAsMap = (Map<String, object>)JSON.deserializeUntyped(res.getBody());
                
                System.debug('-- answer imei ' + answerAsMap.get('imei'));
                System.debug('-- answer stockFluctuationRef ' + answerAsMap.get('stockFluctuationRef'));
                
                Equipement_sinistre__c eqsToUpdate = new Equipement_sinistre__c(id = eqsId, 
                                                                                Statut_equipement__c = DAMAGEDEQUIPMENTSTATUS_DESTOCK, 
                                                                                SerieNumberEC__c = string.valueOf(answerAsMap.get('imei')), 
                                                                                BAppliStockFluctuationRef__c = string.valueOf(answerAsMap.get('stockFluctuationRef')));
                
                if(string.valueOf(answerAsMap.get('cost')) != null || 
                   string.valueOf(answerAsMap.get('cost')) != ''){
                       
                       AssociatedCost__c assCostToInsert = new AssociatedCost__c(Name = ASSOCIATEDCOSTOBJECT_EQUIPMENTEXCHANGE, 
                                                                                 UnitCost__c = decimal.valueOf(string.valueOf(answerAsMap.get('cost'))), 
                                                                                 DamagedEquipment__c = eqsId);
                       insert assCostToInsert;
                       
                       decimal realCost = [SELECT RealCost__c 
                                           FROM Equipement_sinistre__c 
                                           WHERE id =: eqsId].RealCost__c;
                       
                       eqsToUpdate.RealCost__c = realCost <> null ? 
                           realCost + decimal.valueOf(string.valueOf(answerAsMap.get('cost'))) : decimal.valueOf(string.valueOf(answerAsMap.get('cost')));
                       eqsToUpdate.EquipmentAmount__c = eqsToUpdate.RealCost__c;                       
                       
                       if(eqsToUpdate.RealCost__c != null){
                           List<Mouvements_financiers__c> calIndemExchange = [SELECT id, Montant__c 
                                                                              FROM Mouvements_financiers__c 
                                                                              WHERE Case__c =: caseId 
                                                                              AND Type_mouvement__c =: CalculIndemnisationTriggerHandler.COSTTYPE_INTERNCOSTEXCHANGE];
                           
                           if(calIndemExchange.size() > 0){
                               /*if(eqsToUpdate.RealCost__c < calIndemExchange[0].Montant__c){*/
                               
                               calIndemExchange[0].Montant__c = eqsToUpdate.RealCost__c;
                               update calIndemExchange[0];
                               
                               system.debug('-- calIndemExchange[0] ' + calIndemExchange[0]);
                               //}
                           }
                       }
                   }
                
                system.debug('-- eqsToUpdate ' + eqsToUpdate);
                update eqsToUpdate;
                
                LogCallout.logSuccess(EXTERNALSYSTEM_BAPPLI + ' ' + ENDPOINTNAME_STOCK, caseId, null, null, body, res);
                
            } else if (AnswerStatus == STATUSCODE_404){
                
                Equipement_sinistre__c eqsToUpdate = new Equipement_sinistre__c(id = eqsId);
                
                if(stockName == BAPPLISTOCKNAME_SFAM){
                    eqsToUpdate.Statut_equipement__c = DAMAGEDEQUIPMENTSTATUS_ORDER;
                    eqsToUpdate.OrderDate__c = Datetime.now();                     
                }
                
                eqsToUpdate.SerieNumberEC__c = 'Déstockage Ko le ' + string.valueOf(Datetime.now());
                update eqsToUpdate; 
                LogCallout.logError(EXTERNALSYSTEM_BAPPLI + ' ' + ENDPOINTNAME_STOCK, caseId, null, null, body, res, null);
                
            } else if (AnswerStatus == STATUSCODE_500){
                LogCallout.logError(EXTERNALSYSTEM_BAPPLI + ' ' + ENDPOINTNAME_STOCK, caseId, null, null, body, res, null);
            }
        } catch (Exception e) {
            system.debug('-- exception getFromStock' + String.valueOf(e));
            LogCallout.logError(EXTERNALSYSTEM_BAPPLI + ' ' + ENDPOINTNAME_STOCK, caseId, null, null, body, res, String.valueOf(e));
        }  
    }

    public class MockToDev {
        protected Integer code {get;set;}
        protected String status {get;set;}
        protected String body {get;set;}
        protected Map<String, String> responseHeaders {get;set;}

        public MockToDev(Integer code, String status, String body, Map<String, String> responseHeaders) {
            this.code = code;
            this.status = status;
            this.body = body;
            this.responseHeaders = responseHeaders;
        }

        public HTTPResponse respond() {
            HttpResponse res = new HttpResponse();
            for (String key : this.responseHeaders.keySet()) {
                res.setHeader(key, this.responseHeaders.get(key));
            }
            res.setBody(this.body);
            res.setStatusCode(this.code);
            res.setStatus(this.status);
            return res;
        }
    }
}