hubSide/force-app/main/default/objects/Asset/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Id_contrat_B_appli__c.field-meta.xml
<CustomField>
    <fullName>Id_contrat_B_appli__c</fullName>
    <label>Id contrat B-appli</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Demande.recordType-meta.xml
<RecordType>
    <fullName>Demande</fullName>
    <active>true</active>
    <businessProcess>Demande</businessProcess>
    <description>Demande relative à de nouveaux documents client</description>
    <label>Demande</label>
</RecordType>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/Mouvements_financiers__c.object-meta.xml
<CustomObject>
    <label>Calcul Indemnisation</label>
    <nameField>
        <label>Nom du mouvement financier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calcul Indemnisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Calcul Indemnisations</relationshipLabel>
    <relationshipName>Mouvements_financiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Cout_choisi__c.field-meta.xml
<CustomField>
    <fullName>Cout_choisi__c</fullName>
    <label>Coût choisi</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primes</fullName>
            </value>
            <value>
                <fullName>Echange</fullName>
            </value>
            <value>
                <fullName>Réparation</fullName>
            </value>
            <value>
                <fullName>Règlement par le client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <description>Identification du montant du mouvement</description>
    <label>Montant</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Paiement_Versement__c.field-meta.xml
<CustomField>
    <fullName>Paiement_Versement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paiement Versement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Paiement_Versement__c.Case__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Paiement_Versement__c</referenceTo>
    <relationshipName>Mouvements_financiers</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crée</fullName>
                <default>true</default>
                <label>Crée</label>
            </value>
            <value>
                <fullName>En cours d&apos;approbation</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Demande en cours</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Rejeté</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Terminé</label>
            </value>
            <value>
                <fullName>Invalidated</fullName>
                <label>Invalidé</label>
            </value>
            <value>
                <fullName>En attente d&apos;approbation</fullName>
                <isActive>false</isActive>
                <label>En attente d&apos;approbation</label>
            </value>
            <value>
                <fullName>Encaissé</fullName>
                <isActive>false</isActive>
                <label>Encaissé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/Paiement_Versement__c.object-meta.xml
<CustomObject>
    <label>Paiement Versement</label>
    <nameField>
        <label>Paiement Versement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paiement Versement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Paiement Versement</relationshipLabel>
    <relationshipName>Paiement_Versement</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demande Paiement</fullName>
            </value>
            <value>
                <fullName>Payé Client</fullName>
            </value>
            <value>
                <fullName>Demande Versement</fullName>
            </value>
            <value>
                <fullName>Versé Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/classes/PaiementVersementTriggerHelper.cls
/***
* @author Nicolas Brancato (GFI)
* @date 07/01/2020
* @description Helper class for PaiementVersementTrigger
*/

public class PaiementVersementTriggerHelper {

    /***
	* @description Get related Mouvements_financiers__c
	* @param newPVList list of new Paiement_Versement__c 
	* @return Map<id, List<Mouvements_financiers__c>> map of related MF
	*/
    public static Map<id, List<Mouvements_financiers__c>> getRelatedMF(List<Paiement_Versement__c> newPVList){
        
        Set<id> caseIdSet = new Set<id>();
        for(Paiement_Versement__c pv : newPVList){
            caseIdSet.add(pv.Case__c);
        }
        
        List<Mouvements_financiers__c> relatedMFList = [SELECT id, Case__c, Paiement_Versement__c
                                                        FROM Mouvements_financiers__c
                                                        WHERE Case__c IN: caseIdSet
                                                        AND Statut__c = 'Validé'
                                                        AND Cout_choisi__c IN ('Primes','Règlement par le client')];
        
        Map<id, List<Mouvements_financiers__c>> relatedMFMap = new Map<id, List<Mouvements_financiers__c>>();
        for(Mouvements_financiers__c mf : relatedMFList){
            if(!relatedMFMap.keySet().contains(mf.Case__c)){
                List<Mouvements_financiers__c> tmpList = new List<Mouvements_financiers__c>();
                relatedMFMap.put(mf.Case__c, tmpList);
            }
            relatedMFMap.get(mf.Case__c).add(mf);
        }
        
        return relatedMFMap;
    }
    
    /***
	* @description Get Id_contrat_B_appli__c to trigger payment to BAppli
	* @param lstPay list of Paiement_Versement__c with status equal to "Demande Versement"
	* @return List<Paiement_Versement__c> List of Paiement_Versement__c with the Id_contrat_B_appli__c from the parent asset
	*/
    public static List<Paiement_Versement__c> GetDatasToTriggerPaymentToBAppli(List<Paiement_Versement__c> lstPay){
        
        return new list<Paiement_Versement__c>([SELECT id, Case__c, Case__r.Asset.Name, Montant__c
                                                FROM Paiement_Versement__c
                                                WHERE Id IN: lstPay]);
    }
}