hubSide/force-app/main/default/objects/Asset/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Demande.recordType-meta.xml
<RecordType>
    <fullName>Demande</fullName>
    <active>true</active>
    <businessProcess>Demande</businessProcess>
    <description>Demande relative à de nouveaux documents client</description>
    <label>Demande</label>
</RecordType>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/Mouvements_financiers__c.object-meta.xml
<CustomObject>
    <label>Calcul Indemnisation</label>
    <nameField>
        <label>Nom du mouvement financier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calcul Indemnisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Calcul Indemnisations</relationshipLabel>
    <relationshipName>Mouvements_financiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <description>Identification du montant du mouvement</description>
    <label>Montant</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Paiement_Versement__c.field-meta.xml
<CustomField>
    <fullName>Paiement_Versement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paiement Versement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Paiement_Versement__c.Case__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Paiement_Versement__c</referenceTo>
    <relationshipName>Mouvements_financiers</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crée</fullName>
                <default>true</default>
                <label>Crée</label>
            </value>
            <value>
                <fullName>En cours d&apos;approbation</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Demande en cours</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Rejeté</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Terminé</label>
            </value>
            <value>
                <fullName>Invalidated</fullName>
                <label>Invalidé</label>
            </value>
            <value>
                <fullName>En attente d&apos;approbation</fullName>
                <isActive>false</isActive>
                <label>En attente d&apos;approbation</label>
            </value>
            <value>
                <fullName>Encaissé</fullName>
                <isActive>false</isActive>
                <label>Encaissé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/Paiement_Versement__c.object-meta.xml
<CustomObject>
    <label>Paiement Versement</label>
    <nameField>
        <label>Paiement Versement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paiement Versement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Paiement Versement</relationshipLabel>
    <relationshipName>Paiement_Versement</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demande Paiement</fullName>
            </value>
            <value>
                <fullName>Payé Client</fullName>
            </value>
            <value>
                <fullName>Demande Versement</fullName>
            </value>
            <value>
                <fullName>Versé Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/classes/PaiementVersementTriggerHandler.cls
/***
* @author Nicolas Brancato (GFI)
* @date 07/01/2020
* @description Handler class for PaiementVersementTrigger
*/

public class PaiementVersementTriggerHandler {    
    
    static final String STATUS_TRANSFER = 'Demande Versement';
    
    /***
    * @description Update related MF after insert
    * @param newPVList list of new Paiement_Versement__c
    * @return null
    * @exception none
    */
    public void updateRelatedMF(List<Paiement_Versement__c> newPVList, Map<id, List<Mouvements_financiers__c>> relatedMFMap){
        
        List<Mouvements_financiers__c> MFToUpdate = new List<Mouvements_financiers__c>();
        for(Paiement_Versement__c pv : newPVList){
            if(relatedMFMap.keySet().contains(pv.Case__c)){
                for(Mouvements_financiers__c mf : relatedMFMap.get(pv.Case__c)){
                    MFToUpdate.add(new Mouvements_financiers__c(id = mf.id, 
                                                                Paiement_Versement__c = pv.id));
                }
            }
        }
        update MFToUpdate;
    }
    
    /***
    * @description method to handle all after insert automatisms
    * @param lstNewPay list of new Paiement_Versement__c
    * @return nul
    * @exception none
    */
    public void handleAfterInsert(List<Paiement_Versement__c> lstNewPay){
        
        List<Paiement_Versement__c> lstPay = new List<Paiement_Versement__c>();
        for(integer i=0; i<lstNewPay.size(); i++){
            if(lstNewPay[i].Statut__c == STATUS_TRANSFER){ 
                lstPay.add(lstNewPay[i]);
            }
        }
        List<Paiement_Versement__c>listPayWithBAppliContractId = PaiementVersementTriggerHelper.GetDatasToTriggerPaymentToBAppli(lstPay);
        
        for(integer i=0; i<listPayWithBAppliContractId.size(); i++){
            BAppliCallout.sendPayment(listPayWithBAppliContractId[i].Case__c, listPayWithBAppliContractId[i].id, listPayWithBAppliContractId[i].Case__r.Asset.Name, listPayWithBAppliContractId[i].Montant__c);
            
        }
    }
}