hubSide/force-app/main/default/objects/Asset/fields/Casse__c.field-meta.xml
<CustomField>
    <fullName>Casse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Casse</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Communication_frauduleuse__c.field-meta.xml
<CustomField>
    <fullName>Communication_frauduleuse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Communication frauduleuse</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Formule__c.field-meta.xml
<CustomField>
    <fullName>Formule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Formule</label>
    <referenceTo>vlocity_ins__AssetCoverage__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <description>Id Externe utilisé par les interfaces pour l&apos;Upsert et stocké l&apos;Id du sytème source</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Nombre_echanges__c.field-meta.xml
<CustomField>
    <fullName>Nombre_echanges__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Nombre d’échanges autorisés sur une période de 1 an</description>
    <label>Nombre d&apos;échanges</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Nombre_mobiles_couverts__c.field-meta.xml
<CustomField>
    <fullName>Nombre_mobiles_couverts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Nombre de mobiles couverts par le contrat</description>
    <label>Nombre de mobiles couverts</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Nombre_produits_assures__c.field-meta.xml
<CustomField>
    <fullName>Nombre_produits_assures__c</fullName>
    <label>Nombre de produits assurés</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nombre_de_produits_assures</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Nombre_produits_multimedia_couverts__c.field-meta.xml
<CustomField>
    <fullName>Nombre_produits_multimedia_couverts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Nombre de produits multimédia couverts par le contrat</description>
    <label>Nombre de produits multimédia couverts</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Oxydation__c.field-meta.xml
<CustomField>
    <fullName>Oxydation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Oxydation</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Pertes_avec_franchise__c.field-meta.xml
<CustomField>
    <fullName>Pertes_avec_franchise__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pertes avec franchise</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Plafond__c.field-meta.xml
<CustomField>
    <fullName>Plafond__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Plafond</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/vlocity_ins__Type__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__Type__c</fullName>
    <description>The type of policy or financial account such as term life, auto, homeowners, variable annuity, 401(k), IRA, or money market. More detailed than the line of business.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Option</fullName>
            </value>
            <value>
                <fullName>Formula</fullName>
                <label>Formule</label>
            </value>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>Boatowners</fullName>
            </value>
            <value>
                <fullName>Business Owners</fullName>
            </value>
            <value>
                <fullName>Condominium</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>Equity−indexed annuity</fullName>
            </value>
            <value>
                <fullName>Fixed Annuity</fullName>
            </value>
            <value>
                <fullName>General Liability</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Inland Marine</fullName>
            </value>
            <value>
                <fullName>Ocean Marine</fullName>
            </value>
            <value>
                <fullName>Permanent Life</fullName>
            </value>
            <value>
                <fullName>Pers/Scheduled Property</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Renters</fullName>
            </value>
            <value>
                <fullName>Term Life</fullName>
            </value>
            <value>
                <fullName>Umbrella Liability</fullName>
            </value>
            <value>
                <fullName>Unit Linked Life</fullName>
            </value>
            <value>
                <fullName>Universal Life</fullName>
            </value>
            <value>
                <fullName>Universal Variable Life</fullName>
            </value>
            <value>
                <fullName>Variable Annuity</fullName>
            </value>
            <value>
                <fullName>Variable Life</fullName>
            </value>
            <value>
                <fullName>Workers Compensation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Vol_Caracterise__c.field-meta.xml
<CustomField>
    <fullName>Vol_Caracterise__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vol Caractérisé</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Vol_toute_cause__c.field-meta.xml
<CustomField>
    <fullName>Vol_toute_cause__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vol toute cause</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Franchise__c.field-meta.xml
<CustomField>
    <fullName>Franchise__c</fullName>
    <label>Franchise</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/FranchiseAmount1__c.field-meta.xml
<CustomField>
    <fullName>FranchiseAmount1__c</fullName>
    <label>Franchise Amount Level 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/FranchiseAmount2__c.field-meta.xml
<CustomField>
    <fullName>FranchiseAmount2__c</fullName>
    <label>Franchise Amount Level 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/FranchiseAmount3__c.field-meta.xml
<CustomField>
    <fullName>FranchiseAmount3__c</fullName>
    <label>Franchise Amount Level 3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/FranchiseLevel1__c.field-meta.xml
<CustomField>
    <fullName>FranchiseLevel1__c</fullName>
    <label>Franchise Level 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/FranchiseLevel2__c.field-meta.xml
<CustomField>
    <fullName>FranchiseLevel2__c</fullName>
    <label>Franchise Level 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/FranchiseLevel3__c.field-meta.xml
<CustomField>
    <fullName>FranchiseLevel3__c</fullName>
    <label>Franchise Level 3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Gamme_formule__c.field-meta.xml
<CustomField>
    <fullName>Gamme_formule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Gamme offre</description>
    <label>Gamme formule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Gamme__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Gamme formule</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Gamme__c</referenceTo>
    <relationshipLabel>Offres location</relationshipLabel>
    <relationshipName>Products_offre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <description>Id externe pour l&apos;intégration API</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/NbMounthKPIContract__c.field-meta.xml
<CustomField>
    <fullName>NbMounthKPIContract__c</fullName>
    <label>Nb mois pour les indicateurs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Nombre_echanges__c.field-meta.xml
<CustomField>
    <fullName>Nombre_echanges__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Nombre d’échanges autorisés sur une période de 1 an</inlineHelpText>
    <label>Nombre d&apos;échanges</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Nombre_jours_inclus__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_inclus__c</fullName>
    <description>Nombre de jours inclus dans l&apos;offre</description>
    <label>Nombre de jours inclus</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Nombre_mobiles_couverts__c.field-meta.xml
<CustomField>
    <fullName>Nombre_mobiles_couverts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Nombre de mobiles couverts par la formule</description>
    <label>Nombre de mobiles couverts</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Nombre_produits_multimedia_couverts__c.field-meta.xml
<CustomField>
    <fullName>Nombre_produits_multimedia_couverts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Nombre de produits multimédia couverts par la formule</description>
    <label>Nombre de produits multimédia couverts</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Perte__c.field-meta.xml
<CustomField>
    <fullName>Perte__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Perte</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Pertes_valeur_achat__c.field-meta.xml
<CustomField>
    <fullName>Pertes_valeur_achat__c</fullName>
    <label>Pertes valeur achat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Plafond__c.field-meta.xml
<CustomField>
    <fullName>Plafond__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Montant du plafond de dédommagement</inlineHelpText>
    <label>Plafond</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Reparation__c.field-meta.xml
<CustomField>
    <fullName>Reparation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Réparation</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Tout_risques__c.field-meta.xml
<CustomField>
    <fullName>Tout_risques__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tous risques</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Type_produit__c.field-meta.xml
<CustomField>
    <fullName>Type_produit__c</fullName>
    <label>Type de produit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_produit</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/vlocity_ins__Type__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Vision</fullName>
            </value>
            <value>
                <fullName>Medical Savings Account</fullName>
            </value>
            <value>
                <fullName>Formula</fullName>
                <label>Formule</label>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Nombre_de_produits_assures.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <default>true</default>
        <label>0</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>+3</fullName>
    </customValue>
    <customValue>
        <fullName>Famille</fullName>
    </customValue>
    <customValue>
        <fullName>Un seul</fullName>
        <isActive>false</isActive>
        <label>Un seul</label>
    </customValue>
    <description>Nombre de produits assurés dans la policy</description>
    <masterLabel>Nombre de produits assurés</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/globalValueSets/Type_produit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Telephony</fullName>
        <label>Téléphonie</label>
    </customValue>
    <customValue>
        <fullName>Multimedia</fullName>
        <label>Multimédia</label>
    </customValue>
    <customValue>
        <fullName>HomeAppliance</fullName>
        <label>Electroménager</label>
    </customValue>
    <customValue>
        <fullName>TelMultiHomeApp</fullName>
        <label>Téléphonie/multimédia/électroménager</label>
    </customValue>
    <customValue>
        <fullName>Location</fullName>
    </customValue>
    <customValue>
        <fullName>ServiceProvision</fullName>
        <label>Prestation de service</label>
    </customValue>
    <customValue>
        <fullName>Various</fullName>
        <label>Divers</label>
    </customValue>
    <customValue>
        <fullName>Téléphone &amp; Multimédia</fullName>
        <isActive>false</isActive>
        <label>Téléphone &amp; Multimédia</label>
    </customValue>
    <masterLabel>Type de produit</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/PolicyCoverageTriggerHelper.cls
/***
* @author Ariane Tanguy (GFI)
* @date 10/07/2020
* @description Helper class for PolicyCoverage
*/

public class PolicyCoverageTriggerHelper {
    
    /***
	* @description Get the assets with previous policies
	* @param newFormuleList - list of all new policies
	* @return Map<id, Asset>
	*/
    public static List<vlocity_ins__AssetCoverage__c> getPreviousPolicies(List<vlocity_ins__AssetCoverage__c> newFormuleList){
        
        // For all newly open inserted formula, get the related asset id
        Set<id> relatedAssetSet = new Set<id>();
        for(vlocity_ins__AssetCoverage__c f : newFormuleList){
            if(f.Statut__c == 'open'){
                relatedAssetSet.add(f.vlocity_ins__PolicyAssetId__c);
            }
        }
        
        // Get the formules
        return [SELECT id, 
                Name, 
                Statut__c,
                Formule_options__c, 
                vlocity_ins__PolicyAssetId__c, 
                vlocity_ins__Type__c, 
                RecordTypeId,
                CreatedDate
                FROM vlocity_ins__AssetCoverage__c
                WHERE vlocity_ins__PolicyAssetId__c IN: relatedAssetSet];
    }
    
    /***
	* @description Get the assets with previous policies
	* @param newFormuleList - list of all new policies
	* @return Map<id, Asset>
	*/
    public static List<vlocity_ins__AssetCoverage__c> getPreviousPolicies(List<vlocity_ins__AssetCoverage__c> newFormuleList, 
                                                                          Map<id, vlocity_ins__AssetCoverage__c> oldFormuleMap){
        
        // For all newly open inserted formula, get the related asset id
        Set<id> relatedAssetSet = new Set<id>();
        for(vlocity_ins__AssetCoverage__c f : newFormuleList){
            if(f.Statut__c != 'open' &&
               oldFormuleMap.get(f.id).Statut__c != f.Statut__c){
                   relatedAssetSet.add(f.vlocity_ins__PolicyAssetId__c);
               }
        }
        
        // Get the formules
        return [SELECT id, 
                Name, 
                Statut__c,
                Formule_options__c, 
                vlocity_ins__PolicyAssetId__c, 
                vlocity_ins__Type__c, 
                RecordTypeId,
                CreatedDate
                FROM vlocity_ins__AssetCoverage__c
                WHERE vlocity_ins__PolicyAssetId__c IN: relatedAssetSet
                AND id NOT IN : oldFormuleMap.keySet()];
    }
    
    /***
	* @description Get the assets with previous formules
	* @param formuleList - list of previous policies
	* @return Map<id, Asset>
	*/
    public static Map<id, vlocity_ins__AssetCoverage__c> mapPreviousFormules(List<vlocity_ins__AssetCoverage__c> formuleList){
        
        // And map them (the most recent one) to their contracts
        Map<id, vlocity_ins__AssetCoverage__c> assetIdFormuleMap = new Map<id, vlocity_ins__AssetCoverage__c>();
        for(vlocity_ins__AssetCoverage__c f : formuleList){
            if(f.vlocity_ins__Type__c == 'Formula'){
                if(!assetIdFormuleMap.keySet().contains(f.vlocity_ins__PolicyAssetId__c)){
                    assetIdFormuleMap.put(f.vlocity_ins__PolicyAssetId__c, f);
                } else {
                    if(f.CreatedDate > assetIdFormuleMap.get(f.vlocity_ins__PolicyAssetId__c).CreatedDate){
                        assetIdFormuleMap.put(f.vlocity_ins__PolicyAssetId__c, f);
                    }
                }
            }
        }
        
        return assetIdFormuleMap;
    }
    
    /***
	* @description Get the assets with previous options
	* @param formuleList - list of previous policies
	* @return Map<id, Asset>
	*/
    public static Map<id, List<vlocity_ins__AssetCoverage__c>> mapPreviousOptions(List<vlocity_ins__AssetCoverage__c> formuleList){        
        
        // And map them (them with the same name) to their contracts
        Map<id, List<vlocity_ins__AssetCoverage__c>> assetIdOptionMap = new Map<id, List<vlocity_ins__AssetCoverage__c>>();
        for(vlocity_ins__AssetCoverage__c f : formuleList){
            if(f.vlocity_ins__Type__c == 'Option'){
                if(!assetIdOptionMap.keySet().contains(f.vlocity_ins__PolicyAssetId__c)){
                    List<vlocity_ins__AssetCoverage__c> tmpList = new List<vlocity_ins__AssetCoverage__c>();
                    assetIdOptionMap.put(f.vlocity_ins__PolicyAssetId__c, tmpList);
                }
                assetIdOptionMap.get(f.vlocity_ins__PolicyAssetId__c).add(f);
            }
        }
        return assetIdOptionMap;
    }
    
    /***
	* @description Get the formule (product2)
	* @param newFormuleList - list of all new formule
	* @return Map<id, Product2>
	*/
    public static Map<id, Product2> getRelatedProductFormule(List<vlocity_ins__AssetCoverage__c> newFormuleList, 
                                                            List<vlocity_ins__AssetCoverage__c> previousPolicyList){
        
        Set<id> product2IdSet = new Set<id>();
        for(vlocity_ins__AssetCoverage__c f : newFormuleList){
            product2IdSet.add(f.Formule_options__c);
        }
        for(vlocity_ins__AssetCoverage__c f : previousPolicyList){
            product2IdSet.add(f.Formule_options__c);
        }
        
        return new Map<id, Product2>([SELECT id, 
                                      Name, 
                                      Gamme_Formule__r.Name, 
                                      Nombre_jours_inclus__c, 
                                      Id_externe__c, 
                                      Casse__c, 
                                      Communication_frauduleuse__c, 
                                      FranchiseAmount1__c, 
                                      FranchiseAmount2__c, 
                                      FranchiseAmount3__c, 
                                      FranchiseLevel1__c, 
                                      FranchiseLevel2__c, 
                                      FranchiseLevel3__c, 
                                      Franchise__c, 
                                      Nombre_echanges__c, 
                                      Nombre_mobiles_couverts__c,
                                      Nombre_produits_assures__c, 
                                      Nombre_produits_multimedia_couverts__c,
                                      Oxydation__c, 
                                      Perte__c, 
                                      Pertes_avec_franchise__c, 
                                      Pertes_valeur_achat__c, 
                                      Plafond__c, 
                                      Reparation__c, 
                                      Tout_risques__c, 
                                      Type_produit__c, 
                                      vlocity_ins__Type__c,
                                      Vol_Caracterise__c, 
                                      Vol_toute_cause__c,
                                      NbMounthKPIContract__c
                                      FROM Product2
                                      WHERE id IN: product2IdSet]);
    }
    
    /***
	* @description Get the asset
	* @param newFormuleList - list of all new formule
	* @return Map<id, Asset>
	*/
    public static Map<id, Asset> getRelatedAsset(List<vlocity_ins__AssetCoverage__c> newFormuleList){
        
        Set<id> assetIdSet = new Set<id>();
        for(vlocity_ins__AssetCoverage__c f : newFormuleList){
            assetIdSet.add(f.vlocity_ins__PolicyAssetId__c);
        }
        return queryAsset(assetIdSet);
    }
    
    /***
	* @description Get the asset
	* @param newFormuleList - list of all new formule
	* @return Map<id, Asset>
	*/
    public static Map<id, Asset> getRelatedAsset(List<vlocity_ins__AssetCoverage__c> newFormuleList, 
                                                 Map<id, vlocity_ins__AssetCoverage__c> oldFormuleMap){
        
        Set<id> assetIdSet = new Set<id>();
        for(vlocity_ins__AssetCoverage__c f : newFormuleList){
            if(f.Statut__c != 'open' &&
               oldFormuleMap.get(f.id).Statut__c != f.Statut__c){
                   assetIdSet.add(f.vlocity_ins__PolicyAssetId__c);
               }
        }
        return queryAsset(assetIdSet);
    }
    
    /***
	* @description Query assets
	* @param assetIdSet - set of asset ids
	* @return Map<id, Asset>
	*/
    private static Map<id, Asset> queryAsset(Set<id> assetIdSet){
        
        return new Map<id, Asset>([SELECT id, 
                                   Name, 
                                   Casse__c, 
                                   Communication_frauduleuse__c, 
                                   Formule__c, 
                                   Nombre_echanges__c, 
                                   Nombre_mobiles_couverts__c, 
                                   Nombre_produits_assures__c, 
                                   Nombre_produits_multimedia_couverts__c, 
                                   Oxydation__c, 
                                   Perte__c, 
                                   Pertes_avec_franchise__c, 
                                   Plafond__c, 
                                   Record_Type_Name__c, 
                                   Reparation__c, 
                                   Tout_risques__c, 
                                   Type_de_contrat__c, 
                                   Vol_Caracterise__c, 
                                   Vol_toute_cause__c,
                                   vlocity_ins__Type__c,
                                   Date_debut_contrat__c,
                                   TECH_CalculatorIndicLastChange__c,
                                   TECH_LastBirthDayContract__c
                                   FROM Asset
                                   WHERE id IN: assetIdSet]);
    }
    
    /***
	* @description Get the facture for the asset with previous formules
	* @param newFormuleList - list of all new formule
	* @param relatedAssetMap - related location assets
	* @return Map<id, vlocity_ins__AssetCoverage__c>
	*/
    public static Map<id, Facture__c> getRelatedFacture(List<vlocity_ins__AssetCoverage__c> newFormuleList, id formuleLocationId){
        
        // For all newly inserted location policy coverages (formule), get the related asset id
        Set<id> relatedAssetSet = new Set<id>();
        for(vlocity_ins__AssetCoverage__c f : newFormuleList){
            
            if(f.Statut__c == 'open' && 
               f.vlocity_ins__Type__c == 'Formula' &&
               f.RecordTypeId == formuleLocationId){
                   relatedAssetSet.add(f.vlocity_ins__PolicyAssetId__c);
               }            
        }
        
        // Get the factures
        List<Facture__c> factureList = [SELECT id, 
                                        Contrat__c, 
                                        Date_debut_periode__c, 
                                        Nombre_jours_restants__c, 
                                        Nombre_jours_formule__c 
                                        FROM Facture__c
                                        WHERE Contrat__c IN: relatedAssetSet
                                        AND Facture_active__c = TRUE];
        
        // And map them to their contracts
        Map<id, Facture__c> assetIdFactureMap = new Map<id, Facture__c>();
        for(Facture__c f : factureList){
            if(assetIdFactureMap.keySet().contains(f.Contrat__c)){
                system.assert(false, 'There are two facture active on this asset - This is wrong');
            } else {
                assetIdFactureMap.put(f.Contrat__c, f);
            }
        }
        return assetIdFactureMap;
    }
}