hubSide/force-app/main/default/objects/Asset/fields/Code_formule__c.field-meta.xml
<CustomField>
    <fullName>Code_formule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Offre choisie dans le contrat</description>
    <label>Code formule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Formule location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contrats de location</relationshipLabel>
    <relationshipName>Contrats_location</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/Emprunt__c.object-meta.xml
<CustomObject>
    <label>Emprunt</label>
    <nameField>
        <displayFormat>EMP-{000000}</displayFormat>
        <label>Emprunt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emprunts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client empruntant l&apos;objet</description>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Le client doit être du type Person Account.</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Emprunts (Client)</relationshipLabel>
    <relationshipName>Emprunts_client</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Coefficient_decompte__c.field-meta.xml
<CustomField>
    <fullName>Coefficient_decompte__c</fullName>
    <label>Coefficient de décompte</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_retour_prevu__c.field-meta.xml
<CustomField>
    <fullName>Date_retour_prevu__c</fullName>
    <description>Date prévisionnelle de retour pour vérifier le nombre de jours possible et gérer les stocks glissants par la suite</description>
    <label>Date du retour prévu</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <description>Date d&apos;emprunt de l&apos;objet</description>
    <label>Date de sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Gamme_formule__c.field-meta.xml
<CustomField>
    <fullName>Gamme_formule__c</fullName>
    <formula>Contrat__r.Code_formule__r.Gamme_formule__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gamme formule</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Gamme_produit__c.field-meta.xml
<CustomField>
    <fullName>Gamme_produit__c</fullName>
    <formula>Produit_emprunte__r.Produit__r.Gamme_produit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gamme produit</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Nombre_jours_depassement__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_depassement__c</fullName>
    <formula>IF(
    Nombre_jours_imputes__c - Nombre_de_jours_consommation__c - Contrat__r.Code_formule__r.Nombre_jours_carence__c &gt; 0,
    Nombre_jours_imputes__c - Nombre_de_jours_consommation__c - Contrat__r.Code_formule__r.Nombre_jours_carence__c,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours en dépassement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Produit_emprunte__c.field-meta.xml
<CustomField>
    <fullName>Produit_emprunte__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Produit emprunté</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2 OR 3 OR 4)</booleanFilter>
        <errorMessage>Le produit emprunté doit être disponible pour être sélectionné.</errorMessage>
        <filterItems>
            <field>Stock_produit__c.Statut__c</field>
            <operation>equals</operation>
            <value>En stock, Réservé, Sortie client</value>
        </filterItems>
        <filterItems>
            <field>Stock_produit__c.Emprunt_actuel__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Reservation_origine__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Retour sans défaut, Retour avec défaut</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Stock_produit__c</referenceTo>
    <relationshipLabel>Emprunts</relationshipLabel>
    <relationshipName>Emprunts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En magasin</fullName>
                <default>true</default>
                <label>En magasin</label>
            </value>
            <value>
                <fullName>Sortie</fullName>
            </value>
            <value>
                <fullName>Retourné</fullName>
                <label>Retour sans défaut</label>
            </value>
            <value>
                <fullName>Retour avec défaut</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
                <isActive>false</isActive>
                <label>Annulé</label>
            </value>
            <value>
                <fullName>Label.Location_StatusEmprunt1</fullName>
                <isActive>false</isActive>
                <label>Label.Location_StatusEmprunt1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/recordTypes/Emprunt.recordType-meta.xml
<RecordType>
    <fullName>Emprunt</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet emprunt une fois créé</description>
    <label>Emprunt</label>
</RecordType>

hubSide/force-app/main/default/objects/Product2/fields/Code_formule__c.field-meta.xml
<CustomField>
    <fullName>Code_formule__c</fullName>
    <description>Code offre Salesforce</description>
    <displayFormat>SFID-FS{000}</displayFormat>
    <label>Code formule</label>
    <type>AutoNumber</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Gamme_formule__c.field-meta.xml
<CustomField>
    <fullName>Gamme_formule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Gamme offre</description>
    <label>Gamme formule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Gamme__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Gamme formule</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Gamme__c</referenceTo>
    <relationshipLabel>Offres location</relationshipLabel>
    <relationshipName>Products_offre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Gamme_produit__c.field-meta.xml
<CustomField>
    <fullName>Gamme_produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Gamme produit</description>
    <label>Gamme produit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Gamme__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Gamme produit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Gamme__c</referenceTo>
    <relationshipLabel>Produits location</relationshipLabel>
    <relationshipName>Products_produit</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Objets Réservés sur le web / en boutique</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Numero de reservation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Reservation__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reservations (Nom du client)</relationshipLabel>
    <relationshipName>Reservations_Client</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Date_retrait__c.field-meta.xml
<CustomField>
    <fullName>Date_retrait__c</fullName>
    <description>Date de début d’emprunt</description>
    <label>Date de début de location souhaitée</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Duree_emprunt__c.field-meta.xml
<CustomField>
    <fullName>Duree_emprunt__c</fullName>
    <description>Nombre de jours de l&apos;emprunt</description>
    <label>Duree de l&apos;emprunt (jours)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Produit_reserve__c.field-meta.xml
<CustomField>
    <fullName>Produit_reserve__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Produit réservé</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Stock_produit__c.Statut__c</field>
            <operation>equals</operation>
            <value>En stock, Sortie client, Réservé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Stock_produit__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Réservé</fullName>
            </value>
            <value>
                <fullName>Réservation_convertie</fullName>
                <label>Réservation convertie</label>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>Pré-réservé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/recordTypes/Reservation.recordType-meta.xml
<RecordType>
    <fullName>Reservation</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet Reservation</description>
    <label>Reservation</label>
</RecordType>

hubSide/force-app/main/default/objects/Stock_produit__c/Stock_produit__c.object-meta.xml
<CustomObject>
    <label>Stock magasin</label>
    <nameField>
        <label>Stock magasin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks magasin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <label>Date sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Gamme_produit__c.field-meta.xml
<CustomField>
    <fullName>Gamme_produit__c</fullName>
    <formula>Produit__r.Gamme_produit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gamme produit</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Produit location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks magasin</relationshipLabel>
    <relationshipName>Stock_produits</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Table_decompte__c/Table_decompte__c.object-meta.xml
<CustomObject>
    <label>Table décompte</label>
    <nameField>
        <displayFormat>TD-{0000}</displayFormat>
        <label>Table décompte Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tables décompte</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Table_decompte__c/fields/Gamme_formule__c.field-meta.xml
<CustomField>
    <fullName>Gamme_formule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gamme formule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Gamme__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Gamme formule</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Gamme__c</referenceTo>
    <relationshipLabel>Tables décompte (Gamme formule)</relationshipLabel>
    <relationshipName>Tables_decompte_formule</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Table_decompte__c/fields/Gamme_produit__c.field-meta.xml
<CustomField>
    <fullName>Gamme_produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gamme produit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Gamme__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Gamme_produit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Gamme__c</referenceTo>
    <relationshipLabel>Tables décompte (Gamme produit)</relationshipLabel>
    <relationshipName>Tables_decompte_produit</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/classes/ReservationTriggerHelper.cls
/***
* @author Ariane Tanguy (GFI)
* @date 05/05/2020
* @description Helper class for ReservationTrigger
*/

public class ReservationTriggerHelper {
    
    /***
	* @description Get all the emprunt which are already out there with a client
	* @param newReservationList - list of the new reservation
	* @return List<Emprunt__c> - List of the emprunt out
	*/
    public static List<Emprunt__c> getCurrentEmprunt(List<Reservation__c> newReservationList){
        
        // Get all the related stock ids
        List<id> wishedStockIdList = new List<id>();
        for(Reservation__c r : newReservationList){
            wishedStockIdList.add(r.Produit_reserve__c);
        }
        
        // Query the emprunts
        List<Emprunt__c> currentEmpruntList = [SELECT id, Date_sortie__c, Date_retour_prevu__c, 
                                               Produit_emprunte__c, Nombre_jours_depassement__c
                                               FROM Emprunt__c
                                               WHERE Status__c IN ('Sortie', 'En magasin')
                                               AND Produit_emprunte__c IN : wishedStockIdList
                                               AND Date_sortie__c != NULL
                                               AND Date_retour_prevu__c != NULL];
        return currentEmpruntList;
    }
    
    /***
	* @description Get all the planned reservations
	* @param newReservationList - list of the new reservation
	* @return List<Reservation__c> - List of the planned reservations
	*/
    public static List<Reservation__c> getPlannedReservation(List<Reservation__c> newReservationList){
        
        // Get all the related stock ids
        Set<id> wishedStockIdSet = new Set<id>();
        Set<id> reservationIdSet = new Set<id>();
        for(Reservation__c r : newReservationList){
            wishedStockIdSet.add(r.Produit_reserve__c);
            reservationIdSet.add(r.Id);
        }
        
        List<Reservation__c> plannedReservationList = [SELECT id, Date_retrait__c, Duree_emprunt__c, 
                                                       Produit_reserve__c
                                                       FROM Reservation__c
                                                       WHERE Status__c = 'Réservé'
                                                       AND Produit_reserve__c IN : wishedStockIdSet
                                                       AND id NOT IN: reservationIdSet
                                                       AND Date_retrait__c != NULL
                                                       AND Duree_emprunt__c != NULL];
        return plannedReservationList;
    }
    
    /***
	* @description Get all the related coef de decompte
	* @param newReservationList - list of the new reservation
	* @return Map<id, Boolean> - Tells whether the reservation needs to be converted back into the Reserve status
	*/
    public static Map<id, String> getRelatedDecompte(List<Reservation__c> newReservationList){
        
        // Get all the related client ids
        Set<id> relatedStockIdSet = new Set<id>();
        Set<id> relatedClientIdSet = new Set<id>();
        for(Reservation__c r : newReservationList){
            if(r.Status__c == 'Pré-réservé'){
                relatedStockIdSet.add(r.Produit_reserve__c);
                relatedClientIdSet.add(r.Client__c);
            }
        }
        
        // Query the assets
        List<Asset> relatedAssetList = [SELECT id, AccountId, Code_formule__r.Gamme_formule__c
                                        FROM Asset
                                        WHERE AccountId IN: relatedClientIdSet
                                        AND Status = 'valid'];
        
        // Map them to their accounts
        Map<id, List<Asset>> accountIdAssetMap = new Map<id, List<Asset>>();
        for(Asset a : relatedAssetList){
            if(!accountIdAssetMap.keySet().contains(a.accountId)){
                List<Asset> tmpList = new List<Asset>();
                accountIdAssetMap.put(a.AccountId, tmpList);
            }
            accountIdAssetMap.get(a.AccountId).add(a);
        }
        
        // Query the assets
        Map<id, Stock_produit__c> relatedStockMap = new Map<id, Stock_produit__c>([SELECT id, Produit__r.Gamme_produit__c
                                                                                   FROM Stock_produit__c
                                                                                   WHERE Id IN: relatedStockIdSet]);
        
        // Map both gammes to their related reservations
        Set<id> gammeFormuleIdSet = new Set<id>();
        Set<id> gammeStockIdSet = new Set<id>();
        for(Reservation__c r : newReservationList){
            if(accountIdAssetMap.keySet().contains(r.Client__c) &&
               relatedStockMap.keySet().contains(r.Produit_reserve__c)){
                   for(Asset a : accountIdAssetMap.get(r.Client__c)){
                       gammeFormuleIdSet.add(a.Code_formule__r.Gamme_formule__c);
                   }
                   gammeStockIdSet.add(relatedStockMap.get(r.Produit_reserve__c).Produit__r.Gamme_produit__c);
               }
        }
        
        // Query the coefficient de decompte
        List<Table_decompte__c> coefDecList = [SELECT Gamme_formule__c, Gamme_produit__c, Coefficient_decompte__c
                                               FROM Table_decompte__c
                                               WHERE Gamme_formule__c IN: gammeFormuleIdSet
                                               AND Gamme_produit__c IN: gammeStockIdSet];
        
        // Loop again over the reservations
        Map<id, String> cannotMap = new Map<id, String>();
        for(Reservation__c r : newReservationList){
            
            // Rule 3 : no active contract
            if(!accountIdAssetMap.keySet().contains(r.Client__c) &&
               r.Status__c == 'Pré-réservé'){
                   cannotMap.put(r.id, 'Prospect à qualifier');
                   continue;
               }
            
            // Rule 2 : gamme default
            if(accountIdAssetMap.keySet().contains(r.Client__c) &&
               relatedStockMap.keySet().contains(r.Produit_reserve__c)){
                   
                   // Get the related coef de decompte
                   for(Table_decompte__c t : coefDecList){
                       
                       // If the gammes are the same as the current reservation ones
                       if(t.Gamme_produit__c == relatedStockMap.get(r.Produit_reserve__c).Produit__r.Gamme_produit__c){
                           
                           // Check the coef de decompte
                           Boolean gammeOk = false;
                           for(Asset a : accountIdAssetMap.get(r.Client__c)){
                               if(t.Gamme_formule__c == a.Code_formule__r.Gamme_formule__c){
                                   if(t.Coefficient_decompte__c > 0){
                                       gammeOk = true;
                                       break;
                                   }
                               }
                           }
                           if(!gammeOk){
                               cannotMap.put(r.id, 'Défaut de gamme');
                           }
                       }
                   }
                if(cannotMap.keySet().contains(r.id)){
                    break;
                }
            }
        }
        
        return cannotMap;
    }
    
    /***
	* @description Get the related stock
	* @param newReservationList - list of the new reservation
	* @return List<Stock_Produit__c>
	*/
    public static List<Stock_Produit__c> getRelatedStock(List<Reservation__c> newReservationList){
        
        // Get all the related stock ids
        Set<id> stockIdSet = new Set<id>();
        for(Reservation__c r : newReservationList){
            stockIdSet.add(r.Produit_reserve__c);
        }
        
        return [SELECT id, Date_retrait_souhaitee__c, Prochaine_reservation__c
                FROM Stock_produit__c
                WHERE id IN: stockIdSet];
    }
    
    /***
	* @description Get the related stock
	* @param newReservationList - list of the new reservation
	* @return List<Stock_Produit__c>
	*/
    public static List<Stock_Produit__c> getRelatedStock(List<Reservation__c> newReservationList, Map<id, Reservation__c> oldReservationMap){
        
        // Get all the related stock ids
        Set<id> stockIdSet = new Set<id>();
        for(Reservation__c r : newReservationList){
            if(r.Date_retrait__c != oldReservationMap.get(r.id).Date_retrait__c ||
               r.Produit_reserve__c != oldReservationMap.get(r.id).Produit_reserve__c){
                   stockIdSet.add(r.Produit_reserve__c);
               }
        }
        
        if(stockIdSet.size() == 0){
            return new List<Stock_Produit__c>();
        }
        
        return [SELECT id, Date_retrait_souhaitee__c, Prochaine_reservation__c
                FROM Stock_produit__c
                WHERE id IN: stockIdSet];
    }
}