hubSide/force-app/main/default/objects/Asset/fields/Code_formule__c.field-meta.xml
<CustomField>
    <fullName>Code_formule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Offre choisie dans le contrat</description>
    <label>Code formule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Formule location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contrats de location</relationshipLabel>
    <relationshipName>Contrats_location</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Date_cloture__c.field-meta.xml
<CustomField>
    <fullName>Date_cloture__c</fullName>
    <description>Date résiliation souhaitée par le client</description>
    <inlineHelpText>Date résiliation souhaitée par le client</inlineHelpText>
    <label>Date de cloture</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Facture__c.field-meta.xml
<CustomField>
    <fullName>Facture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consommation</label>
    <referenceTo>Facture__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Nombre_jours_consommes__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_consommes__c</fullName>
    <formula>Facture__r.Nombre_jours_consommes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours consommés</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/Emprunt__c.object-meta.xml
<CustomObject>
    <label>Emprunt</label>
    <nameField>
        <displayFormat>EMP-{000000}</displayFormat>
        <label>Emprunt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emprunts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contrat lié à l&apos;emprunt</description>
    <label>Contrat</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3 OR 5) AND 4</booleanFilter>
        <errorMessage>Il n&apos;y a pas de contrat pour ce client, ou alors le contrat en question a déjà un emprunt actif.</errorMessage>
        <filterItems>
            <field>Asset.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contrat location</value>
        </filterItems>
        <filterItems>
            <field>Asset.Emprunt_en_cours__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Asset.Emprunt_en_cours__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Asset.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Client__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Retour sans défaut, Retour avec défaut</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Emprunts</relationshipLabel>
    <relationshipName>Emprunts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_retour_prevu__c.field-meta.xml
<CustomField>
    <fullName>Date_retour_prevu__c</fullName>
    <description>Date prévisionnelle de retour pour vérifier le nombre de jours possible et gérer les stocks glissants par la suite</description>
    <label>Date du retour prévu</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <description>Date d&apos;emprunt de l&apos;objet</description>
    <label>Date de sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Facture__c.field-meta.xml
<CustomField>
    <fullName>Facture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Facture liée à l&apos;emprunt en cours</description>
    <label>Facture</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Facture__c.Contrat__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contrat__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Facture__c</referenceTo>
    <relationshipLabel>Emprunts</relationshipLabel>
    <relationshipName>Emprunts</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Montant_facture__c.field-meta.xml
<CustomField>
    <fullName>Montant_facture__c</fullName>
    <formula>Montant_depassement__c - Montant_geste_commercial__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Montant facturé</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Nombre_jours_depassement__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_depassement__c</fullName>
    <formula>IF(
    Nombre_jours_imputes__c - Nombre_de_jours_consommation__c - Contrat__r.Code_formule__r.Nombre_jours_carence__c &gt; 0,
    Nombre_jours_imputes__c - Nombre_de_jours_consommation__c - Contrat__r.Code_formule__r.Nombre_jours_carence__c,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours en dépassement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Nombre_jours_restants__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_restants__c</fullName>
    <formula>IF(
    (Nombre_de_jours_consommation__c - Nombre_jours_imputes__c) &gt; 0,
    Nombre_de_jours_consommation__c - Nombre_jours_imputes__c,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours restants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En magasin</fullName>
                <default>true</default>
                <label>En magasin</label>
            </value>
            <value>
                <fullName>Sortie</fullName>
            </value>
            <value>
                <fullName>Retourné</fullName>
                <label>Retour sans défaut</label>
            </value>
            <value>
                <fullName>Retour avec défaut</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
                <isActive>false</isActive>
                <label>Annulé</label>
            </value>
            <value>
                <fullName>Label.Location_StatusEmprunt1</fullName>
                <isActive>false</isActive>
                <label>Label.Location_StatusEmprunt1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/recordTypes/Emprunt.recordType-meta.xml
<RecordType>
    <fullName>Emprunt</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet emprunt une fois créé</description>
    <label>Emprunt</label>
</RecordType>

hubSide/force-app/main/default/objects/Facture__c/Facture__c.object-meta.xml
<CustomObject>
    <description>Historique par période du nombre de jour consommé et des dépassements occasionnels. Justification historique facture client</description>
    <label>Consommation</label>
    <nameField>
        <displayFormat>FAC-{00000000}</displayFormat>
        <label>Facture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consommations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Facture__c/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contrat lié à la facture en cours</description>
    <label>Contrat</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contrat location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Consommations</relationshipLabel>
    <relationshipName>Consommations</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Contrat_actif__c.field-meta.xml
<CustomField>
    <fullName>Contrat_actif__c</fullName>
    <formula>IF(
    ISNULL(Contrat__r.Date_cloture__c), 
    TRUE, 
    Contrat__r.Date_cloture__c &gt; TODAY()
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contrat actif ?</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Date_debut_periode__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_periode__c</fullName>
    <description>Date de début de période, initialisant les compteurs à 0.</description>
    <label>Date de début de période</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Date_fin_periode__c.field-meta.xml
<CustomField>
    <fullName>Date_fin_periode__c</fullName>
    <label>Date de fin de période</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Montant_facture__c.field-meta.xml
<CustomField>
    <fullName>Montant_facture__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Montant total facturé sur la période</description>
    <label>Montant facturé</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Nombre_jours_consommes__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_consommes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Nombre total de jours consommés dans la période</description>
    <label>Jours consommés</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Nombre_jours_depassement__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_depassement__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Nombre de jours hors formule</description>
    <label>Nombre de jours en dépassement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Nombre_jours_formule__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_formule__c</fullName>
    <description>Nombre de jours de la formule souscrite.</description>
    <label>Nombre de jours formule</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Nombre_jours_reportes__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_reportes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Nombre de jours restant de la facture précédente et reportés sur la facture actuelle</description>
    <label>Nombre de jours reportés</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Nombre_jours_restants__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_restants__c</fullName>
    <formula>IF(
    ( Nombre_jours_disponibles__c - Nombre_jours_consommes__c) &gt; 0,
    Nombre_jours_disponibles__c - Nombre_jours_consommes__c,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours restants</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/classes/batch_createNewFacture.cls
global class batch_createNewFacture implements Database.Batchable<sObject>, Database.Stateful {
    
    // instance member to retain state across transactions
    global Integer recordsProcessed = 0;
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        // Get all factures which last day was today
        return Database.getQueryLocator(
            'SELECT id, ' +
            'Contrat__c, ' +
            'Contrat__r.Code_formule__r.Nombre_jours_inclus__c, ' +
            'Contrat__r.Code_formule__r.Report_maximum__c, ' +
            'Contrat__r.Date_cloture__c, ' +
            'Date_debut_periode__c, ' +
            'Date_fin_periode__c, ' +
            'Montant_facture__c, ' +
            'Nombre_jours_consommes__c, ' +
            'Nombre_jours_depassement__c, ' +
            'Nombre_jours_reportes__c, ' + 
            'Nombre_jours_restants__c ' +
            'FROM Facture__c ' +
            'WHERE Date_fin_periode__c = TODAY ' + 
            'AND Contrat_actif__c = TRUE'
        );
    }
    
    global void execute(Database.BatchableContext bc, List<Facture__c> factureToRenewList){
        
        // Query all current emprunt existing on the facture
        List<Emprunt__c> currentEmpruntList = [SELECT id, Date_Sortie__c, Date_retour_prevu__c, 
                                               Facture__c, Nombre_jours_depassement__c
                                               FROM Emprunt__c 
                                               WHERE Facture__c IN: factureToRenewList
                                               AND Date_retour_prevu__c > TODAY
                                               AND Status__c = 'Sortie'];
        
        // Map the emprunt to their current facture
        Map<id, Emprunt__c> factureIdEmpruntMap = new Map<id, Emprunt__c>();
        for(Emprunt__c e : currentEmpruntList){
            factureIdEmpruntMap.put(e.Facture__c, e);
        }
        
        List<Facture__c> factureToUpsertList = new List<Facture__c>();
        for(Facture__c f : factureToRenewList){            
            
            // Create the new Facture
            Facture__c newFacture = new Facture__c();
            newFacture.Contrat__c = f.Contrat__c;
            newFacture.Date_debut_periode__c = f.Date_fin_periode__c.addDays(1);
            newFacture.Nombre_jours_formule__c = f.Contrat__r.Code_formule__r.Nombre_jours_inclus__c;
            
            // Handle the contract resiliation if there was one
            if(f.Contrat__r.Date_cloture__c < f.Date_debut_periode__c.addMonths(1) - 1){
                newFacture.Date_fin_periode__c = f.Contrat__r.Date_cloture__c;
            } else {
                newFacture.Date_fin_periode__c = newFacture.Date_debut_periode__c.addMonths(1) - 1;
            }
            
            newFacture.Nombre_jours_reportes__c = f.Nombre_jours_restants__c <= f.Contrat__r.Code_formule__r.Report_maximum__c ?
                f.Nombre_jours_restants__c : f.Contrat__r.Code_formule__r.Report_maximum__c;
            
            // Check whether there is an already running emprunt
            if(factureIdEmpruntMap.keySet().contains(f.id)){
                
                // Remove the number of days on the current facture, and compensate the new one.
                Integer daysNewFacture = system.today().daysBetween(factureIdEmpruntMap.get(f.id).Date_retour_prevu__c);
                Integer daysPreviousFacture = factureIdEmpruntMap.get(f.id).Date_Sortie__c.daysBetween(system.today());
                
                system.debug('-- here daysPreviousFacture ' + daysPreviousFacture);
                system.debug('-- here daysNewFacture ' + daysNewFacture);
                
                f.Nombre_jours_consommes__c -= daysNewFacture;
                
                Decimal nombreJoursRestants = f.Contrat__r.Code_formule__r.Nombre_jours_inclus__c + f.Nombre_jours_reportes__c - f.Nombre_jours_consommes__c;
                nombreJoursRestants = nombreJoursRestants > 0 ? nombreJoursRestants : 0;
                newFacture.Nombre_jours_reportes__c = nombreJoursRestants <= f.Contrat__r.Code_formule__r.Report_maximum__c ?
                    nombreJoursRestants : f.Contrat__r.Code_formule__r.Report_maximum__c;
                
                newFacture.Nombre_jours_consommes__c = daysNewFacture;
                
                system.debug('-- here f.Nombre_jours_consommes__c ' + f.Nombre_jours_consommes__c);
                system.debug('-- here newFacture.Nombre_jours_reportes__c ' + newFacture.Nombre_jours_reportes__c);
                system.debug('-- here newFacture.Nombre_jours_consommes__c ' + newFacture.Nombre_jours_consommes__c);
                
                // If the emprunt was short on days, remove some days on the next facture
                if(f.Nombre_jours_depassement__c - daysNewFacture > 0){
                    f.Nombre_jours_consommes__c -= (f.Nombre_jours_depassement__c - daysNewFacture);
                    f.Nombre_jours_depassement__c = 0;
                    f.Montant_facture__c = 0;
                    newFacture.Nombre_jours_reportes__c -= factureIdEmpruntMap.get(f.id).Nombre_jours_depassement__c;
                    //newFacture.Nombre_jours_consommes__c += factureIdEmpruntMap.get(f.id).Nombre_jours_depassement__c;
                }
                
                factureToUpsertList.add(f);
            }
            
            factureToUpsertList.add(newFacture);
        }
        
        if(factureToUpsertList.size() > 0 ){
            upsert factureToUpsertList;
        }
    }
    
    global void finish(Database.BatchableContext bc){
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
                            JobItemsProcessed,
                            TotalJobItems, CreatedBy.Email
                            FROM AsyncApexJob
                            WHERE Id = :bc.getJobId()];
    }    
}