hubSide/force-app/main/default/objects/Asset/fields/Date_debut_contrat__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_contrat__c</fullName>
    <description>Date de début du contrat souscrit par le client.</description>
    <label>Date de début du contrat</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Facture__c.field-meta.xml
<CustomField>
    <fullName>Facture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consommation</label>
    <referenceTo>Facture__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Nombre_jours_consommes__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_consommes__c</fullName>
    <formula>Facture__r.Nombre_jours_consommes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours consommés</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/Emprunt__c.object-meta.xml
<CustomObject>
    <label>Emprunt</label>
    <nameField>
        <displayFormat>EMP-{000000}</displayFormat>
        <label>Emprunt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emprunts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Caution_recue__c.field-meta.xml
<CustomField>
    <fullName>Caution_recue__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Caution reçue</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_retour_prevu__c.field-meta.xml
<CustomField>
    <fullName>Date_retour_prevu__c</fullName>
    <description>Date prévisionnelle de retour pour vérifier le nombre de jours possible et gérer les stocks glissants par la suite</description>
    <label>Date du retour prévu</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <description>Date d&apos;emprunt de l&apos;objet</description>
    <label>Date de sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Facture__c.field-meta.xml
<CustomField>
    <fullName>Facture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Facture liée à l&apos;emprunt en cours</description>
    <label>Facture</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Facture__c.Contrat__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contrat__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Facture__c</referenceTo>
    <relationshipLabel>Emprunts</relationshipLabel>
    <relationshipName>Emprunts</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Nombre_jours_restants__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_restants__c</fullName>
    <formula>IF(
    (Nombre_de_jours_consommation__c - Nombre_jours_imputes__c) &gt; 0,
    Nombre_de_jours_consommation__c - Nombre_jours_imputes__c,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours restants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En magasin</fullName>
                <default>true</default>
                <label>En magasin</label>
            </value>
            <value>
                <fullName>Sortie</fullName>
            </value>
            <value>
                <fullName>Retourné</fullName>
                <label>Retour sans défaut</label>
            </value>
            <value>
                <fullName>Retour avec défaut</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
                <isActive>false</isActive>
                <label>Annulé</label>
            </value>
            <value>
                <fullName>Label.Location_StatusEmprunt1</fullName>
                <isActive>false</isActive>
                <label>Label.Location_StatusEmprunt1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/recordTypes/Emprunt.recordType-meta.xml
<RecordType>
    <fullName>Emprunt</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet emprunt une fois créé</description>
    <label>Emprunt</label>
</RecordType>

hubSide/force-app/main/default/objects/Facture__c/Facture__c.object-meta.xml
<CustomObject>
    <description>Historique par période du nombre de jour consommé et des dépassements occasionnels. Justification historique facture client</description>
    <label>Consommation</label>
    <nameField>
        <displayFormat>FAC-{00000000}</displayFormat>
        <label>Facture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consommations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Facture__c/fields/Contrat_actif__c.field-meta.xml
<CustomField>
    <fullName>Contrat_actif__c</fullName>
    <formula>IF(
    ISNULL(Contrat__r.Date_cloture__c), 
    TRUE, 
    Contrat__r.Date_cloture__c &gt; TODAY()
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contrat actif ?</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Date_debut_periode__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_periode__c</fullName>
    <description>Date de début de période, initialisant les compteurs à 0.</description>
    <label>Date de début de période</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Date_fin_periode__c.field-meta.xml
<CustomField>
    <fullName>Date_fin_periode__c</fullName>
    <label>Date de fin de période</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Facture_active__c.field-meta.xml
<CustomField>
    <fullName>Facture_active__c</fullName>
    <formula>AND(
    OR(
        Date_debut_periode__c &lt; TODAY(), 
        TODAY() == Date_debut_periode__c
    ), 
    OR(
        TODAY() &lt; Date_fin_periode__c, 
        TODAY() == Date_fin_periode__c
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Periode en cours</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Nombre_jours_consommes__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_consommes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Nombre total de jours consommés dans la période</description>
    <label>Jours consommés</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Nombre_jours_reportes__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_reportes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Nombre de jours restant de la facture précédente et reportés sur la facture actuelle</description>
    <label>Nombre de jours reportés</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Nombre_jours_restants__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_restants__c</fullName>
    <formula>IF(
    ( Nombre_jours_disponibles__c - Nombre_jours_consommes__c) &gt; 0,
    Nombre_jours_disponibles__c - Nombre_jours_consommes__c,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours restants</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/Stock_produit__c.object-meta.xml
<CustomObject>
    <label>Stock magasin</label>
    <nameField>
        <label>Stock magasin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks magasin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <label>Date sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/classes/batch_createNewFactureTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 03/06/2020
* @description batch_createNewFacture test class
* @see batch_createNewFacture
*/

@isTest 
public class batch_createNewFactureTest {
    
    @testSetup 
    public static void testSetup(){    
        
        // Create a contract
        Asset c = TestFactory.createContract();
        c.Date_debut_contrat__c = date.newInstance(system.today().year(), system.today().month() - 1, system.today().day() + 1);
        insert c;
        
        // Create a stock
        Stock_Produit__c s = TestFactory.createStock();
        insert s;
        
        // Create an emprunt
        Emprunt__c e = TestFactory.createEmprunt(c, s);
        e.Date_sortie__c = system.today() - 2;
        e.Date_retour_prevu__c = system.today() + 2;
        insert e;
        
        e.Caution_recue__c = TRUE;
        e.Status__c = 'Sortie';
        update e;
    }
    
    static testMethod void launchBatchTest() {
        
        Facture__c f = [SELECT id, Nombre_jours_consommes__c, Date_fin_periode__c, Date_debut_periode__c, Contrat_actif__c
                        FROM Facture__c];
        system.assertEquals(2, f.Nombre_jours_consommes__c, 
                            'There should be 2 days spent on the old facture - This is wrong');
        system.assertEquals(date.newInstance(system.today().year(), system.today().month() - 1, system.today().day() + 1), 
                            f.Date_debut_periode__c, 
                            'Date_debut_periode__c');
        
        // Handle the end of the month scenario
        if(system.today() != f.Date_fin_periode__c){
            f.Date_fin_periode__c = system.today();
            update f;
        }
        
        system.assertEquals(system.today(), f.Date_fin_periode__c, 
                            'Date_fin_periode__c');
         
        // Night has come, time to create the new factures
        test.startTest();
        batch_createNewFacture newFactureBatch = new batch_createNewFacture();
        DataBase.executeBatch(newFactureBatch);        
        test.stopTest();
        
        // Check whether a new facture was created
        List<Facture__c> factureList = [SELECT id, Nombre_jours_consommes__c, Nombre_jours_reportes__c, 
                                        Facture_active__c, Nombre_jours_restants__c
                                        FROM Facture__c];
        system.assertEquals(2, factureList.size(), 
                            'There should be another facture created - This is wrong');
        
        Facture__c oldFacture = factureList[0];
        system.assertEquals(TRUE, oldFacture.Facture_active__c, 'Wrong facture mutterpinder');
        Facture__c newFacture = factureList[1];
        
        // Check the old facture
        system.assertEquals(0, oldFacture.Nombre_jours_consommes__c, 
                            'The number of used days in the old facture should be maximum the formule s - This is wrong');
        system.assertEquals(4, oldFacture.Nombre_jours_restants__c, 
                            'The number of remaining days in the old facture should be same as the formule - This is wrong');
        
        // Check the new facture
        system.assertEquals(0, newFacture.Nombre_jours_reportes__c, 
                            'The number of days added in the new facture should be same as the formule - This is wrong');
    }
}