hubSide/force-app/main/default/objects/Asset/fields/Date_debut_contrat__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_contrat__c</fullName>
    <description>Date de début du contrat souscrit par le client.</description>
    <label>Date de début du contrat</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Facture__c.field-meta.xml
<CustomField>
    <fullName>Facture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consommation</label>
    <referenceTo>Facture__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/Emprunt__c.object-meta.xml
<CustomObject>
    <label>Emprunt</label>
    <nameField>
        <displayFormat>EMP-{000000}</displayFormat>
        <label>Emprunt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emprunts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Caution_recue__c.field-meta.xml
<CustomField>
    <fullName>Caution_recue__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Caution reçue</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client empruntant l&apos;objet</description>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Le client doit être du type Person Account.</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Emprunts (Client)</relationshipLabel>
    <relationshipName>Emprunts_client</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Coefficient_decompte__c.field-meta.xml
<CustomField>
    <fullName>Coefficient_decompte__c</fullName>
    <label>Coefficient de décompte</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contrat lié à l&apos;emprunt</description>
    <label>Contrat</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3 OR 5) AND 4</booleanFilter>
        <errorMessage>Il n&apos;y a pas de contrat pour ce client, ou alors le contrat en question a déjà un emprunt actif.</errorMessage>
        <filterItems>
            <field>Asset.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contrat location</value>
        </filterItems>
        <filterItems>
            <field>Asset.Emprunt_en_cours__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Asset.Emprunt_en_cours__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Asset.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Client__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Retour sans défaut, Retour avec défaut</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Emprunts</relationshipLabel>
    <relationshipName>Emprunts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_retour_prevu__c.field-meta.xml
<CustomField>
    <fullName>Date_retour_prevu__c</fullName>
    <description>Date prévisionnelle de retour pour vérifier le nombre de jours possible et gérer les stocks glissants par la suite</description>
    <label>Date du retour prévu</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <description>Date d&apos;emprunt de l&apos;objet</description>
    <label>Date de sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Etat_retour__c.field-meta.xml
<CustomField>
    <fullName>Etat_retour__c</fullName>
    <description>Etat du produit emprunté lors de son retour</description>
    <label>Etat retour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Etat_produit</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Etat_sortie__c.field-meta.xml
<CustomField>
    <fullName>Etat_sortie__c</fullName>
    <label>Etat sortie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Facture__c.field-meta.xml
<CustomField>
    <fullName>Facture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Facture liée à l&apos;emprunt en cours</description>
    <label>Facture</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Facture__c.Contrat__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contrat__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Facture__c</referenceTo>
    <relationshipLabel>Emprunts</relationshipLabel>
    <relationshipName>Emprunts</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Heure_retour__c.field-meta.xml
<CustomField>
    <fullName>Heure_retour__c</fullName>
    <description>Heure de retour de l&apos;objet emprunté</description>
    <label>Heure de retour</label>
    <type>Time</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Heure_retour_prevue__c.field-meta.xml
<CustomField>
    <fullName>Heure_retour_prevue__c</fullName>
    <label>Heure de retour prevue</label>
    <type>Time</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Heure_sortie__c.field-meta.xml
<CustomField>
    <fullName>Heure_sortie__c</fullName>
    <description>Heure de sortie de l&apos;objet emprunté</description>
    <label>Heure de sortie</label>
    <type>Time</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Montant_geste_commercial__c.field-meta.xml
<CustomField>
    <fullName>Montant_geste_commercial__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Montant du geste commercial dans le cas d&apos;un dépassement.</description>
    <label>Montant du geste commercial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Motif_geste_commercial__c.field-meta.xml
<CustomField>
    <fullName>Motif_geste_commercial__c</fullName>
    <label>Motif du geste commercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bon client</fullName>
            </value>
            <value>
                <fullName>Retard</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Nombre_de_jours_consommation__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_jours_consommation__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Valeur fixe, initialisée au début de l&apos;emprunt par le nombre de jour restant dans la consommation sur la période en cours.</description>
    <label>Nombre de jours consommation</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Nombre_jours_restants__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_restants__c</fullName>
    <formula>IF(
    (Nombre_de_jours_consommation__c - Nombre_jours_imputes__c) &gt; 0,
    Nombre_de_jours_consommation__c - Nombre_jours_imputes__c,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours restants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Point_de_vente_retour__c.field-meta.xml
<CustomField>
    <fullName>Point_de_vente_retour__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Point de vente retour de l&apos;objet emprunté</description>
    <label>Point de vente retour</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Le point de vente de retour doit être du type Business Account.</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Emprunts (retour)</relationshipLabel>
    <relationshipName>Emprunts_retour</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/recordTypes/Emprunt.recordType-meta.xml
<RecordType>
    <fullName>Emprunt</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet emprunt une fois créé</description>
    <label>Emprunt</label>
</RecordType>

hubSide/force-app/main/default/objects/Facture__c/Facture__c.object-meta.xml
<CustomObject>
    <description>Historique par période du nombre de jour consommé et des dépassements occasionnels. Justification historique facture client</description>
    <label>Consommation</label>
    <nameField>
        <displayFormat>FAC-{00000000}</displayFormat>
        <label>Facture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consommations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Facture__c/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contrat lié à la facture en cours</description>
    <label>Contrat</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contrat location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Consommations</relationshipLabel>
    <relationshipName>Consommations</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Nombre_jours_restants__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_restants__c</fullName>
    <formula>IF(
    ( Nombre_jours_disponibles__c - Nombre_jours_consommes__c) &gt; 0,
    Nombre_jours_disponibles__c - Nombre_jours_consommes__c,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours restants</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Objets Réservés sur le web / en boutique</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Numero de reservation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Reservation__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reservations (Nom du client)</relationshipLabel>
    <relationshipName>Reservations_Client</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contrat permettant de faire une réservation</description>
    <label>Contrat</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Client__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/recordTypes/Reservation.recordType-meta.xml
<RecordType>
    <fullName>Reservation</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet Reservation</description>
    <label>Reservation</label>
</RecordType>

hubSide/force-app/main/default/objects/Stock_produit__c/Stock_produit__c.object-meta.xml
<CustomObject>
    <label>Stock magasin</label>
    <nameField>
        <label>Stock magasin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks magasin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <label>Date sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Table_decompte__c/Table_decompte__c.object-meta.xml
<CustomObject>
    <label>Table décompte</label>
    <nameField>
        <displayFormat>TD-{0000}</displayFormat>
        <label>Table décompte Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tables décompte</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Table_decompte__c/fields/Coefficient_decompte__c.field-meta.xml
<CustomField>
    <fullName>Coefficient_decompte__c</fullName>
    <label>Coefficient de décompte</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Etat_produit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Neuf</fullName>
    </customValue>
    <customValue>
        <fullName>Bon état</fullName>
    </customValue>
    <customValue>
        <fullName>Rayé</fullName>
    </customValue>
    <description>Etat du produit emprunté lors de sa sortie ou de son retour en boutique</description>
    <masterLabel>Etat produit</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/EmpruntTriggerHandlerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 05/05/2020
* @description EmpruntTrigger test class
* @Object Emprunt__c
*/

@isTest
public class EmpruntTriggerHandlerTest {
    
    /***
	* @description Update the related facture when an emprunt is created
	* @see setFactureOnEmprunt
	*/
    @isTest
    public static void setFactureOnEmpruntTest(){
        
        // Create a contract
        Asset c = TestFactory.createContract();
        insert c;
        
        // Create an emprunt
        Emprunt__c e = TestFactory.createEmprunt(c);
        e.Client__c = c.AccountId;
        insert e;
        
        // Query the related facture and 
        // check whether the Emprunt has been correctly updated
        Facture__c f = [SELECT id, Nombre_jours_restants__c
                        FROM Facture__c WHERE Contrat__c =: c.id];
        e = [SELECT id, Facture__c
             FROM Emprunt__c WHERE Contrat__c =: c.id];
        
        system.assertEquals(e.Facture__c, f.id,
                            'The facture field should have been updated on the emprunt - This is wrong');
    }
    
    /***
	* @description Update the remaining number of days when an emprunt is created and updated
	* @see setRemainingDays
	*/
    @isTest
    public static void setRemainingDaysTest(){
        
        // Create a contract
        Asset c = TestFactory.createContract();
        insert c;
        
        // Create an emprunt
        Emprunt__c e = TestFactory.createEmprunt(c);
        e.Client__c = c.AccountId;
        insert e;
        
        // Query the related facture and 
        // check whether the Emprunt has been correctly updated
        Facture__c f = [SELECT id, Nombre_jours_restants__c
                        FROM Facture__c WHERE Contrat__c =: c.id];
        e = [SELECT id, Nombre_de_jours_consommation__c
             FROM Emprunt__c WHERE Contrat__c =: c.id];
        
        system.assertEquals(e.Nombre_de_jours_consommation__c, f.Nombre_jours_restants__c,
                            'The remaining number of days should have been updated on the emprunt - This is wrong');
    }
    
    /***
	* @description Update the record type
	* @see updateRecordTypeOnCreation
	*/
    @isTest
    public static void updateRecordTypeOnCreationTest(){
        
        // Create a contract
        Asset c = TestFactory.createContract();
        insert c;
        
        // Create an emprunt
        Emprunt__c e = TestFactory.createEmprunt(c);
        insert e;
        
        // Query emprunt and check whether the record type has been correctly updated
        e = [SELECT id, RecordType.DeveloperName FROM Emprunt__c WHERE id =: e.id];
        
        system.assertEquals('Emprunt', e.RecordType.DeveloperName, 
                            'The record type should have been updated on the emprunt - This is wrong');
    }
    
    /***
	* @description Update the coefficient de decompte
	* @see updateCoefdeDecompte
	*/
    @isTest
    public static void updateCoefdeDecompteTest(){
        
        // Create a contract
        Asset c = TestFactory.createContract();
        insert c;
        
        // Create an emprunt
        Emprunt__c e = TestFactory.createEmprunt(c);
        insert e;
        
        // Query emprunt and check whether the coef has been correctly updated
        e = [SELECT id, Coefficient_decompte__c FROM Emprunt__c WHERE id =: e.id];
        
        // Query the related table de decompte
        Table_decompte__c t = [SELECT Coefficient_decompte__c FROM Table_decompte__c];
        
        system.assertEquals(t.Coefficient_decompte__c, e.Coefficient_decompte__c, 
                            'The coef should have been updated on the emprunt - This is wrong');
    }
    
    /***
	* @description Sum the emprunt fields and update them on the facture 
	* @see updateFacture
	*/
    @isTest
    public static void updateFactureTest(){
        
        // Create a contract
        Asset c = TestFactory.createContract();
        c.Date_debut_contrat__c = system.today() - 10;
        insert c;
        
        // Create an emprunt
        Emprunt__c e = TestFactory.createEmprunt(c);
        e.Date_retour_prevu__c = system.today();
        e.Montant_geste_commercial__c = 10;
        e.Motif_geste_commercial__c = 'Retard';
        insert e;
        
        // Mock an old emprunt
        e.Date_sortie__c = system.today() - 2;
        e.Heure_sortie__c = system.now().time();
        e.Heure_retour_prevue__c = system.now().time();
        e.Caution_recue__c = true;
        update e;
        
        test.startTest();
        
        e.Heure_retour__c = system.now().time();
        e.Etat_retour__c = e.Etat_sortie__c;
        e.Point_de_vente_retour__c = e.Point_de_vente_sortie__c;
        e.Caution_restituee__c = e.Caution_recue__c;
        e.Status__c = 'Retourné';
        update e;
        
        // Query the emprunt to check the number of days imputed
        e = [SELECT Duree_location__c, Nombre_jours_imputes__c, 
             Nombre_de_jours_consommation__c, Jours_consommes__c FROM Emprunt__c WHERE id =: e.id];
        
        system.assertEquals(4, e.Nombre_de_jours_consommation__c, 
                            'There should be 4 days - This is wrong');
        system.assertEquals(2, e.Jours_consommes__c, 
                            'There should be 2 consummed days - This is wrong');
        system.assertEquals(2, e.Nombre_jours_imputes__c, 
                            'There should be 2 imputed days - This is wrong');
        
        // Query the facture and check whether the number of days spent has been updated
        List<Facture__c> factureList = [SELECT Montant_facture__c, Nombre_jours_consommes__c
                                        FROM Facture__c
                                        WHERE Contrat__c =: c.id];
        
        system.assertEquals(2, factureList[0].Nombre_jours_consommes__c, 
                            'The number of days spent hasnt been updated - This is wrong');
        system.assertEquals(-10, factureList[0].Montant_facture__c, 
                            'The total invoiced hasnt been updated - This is wrong');
        
        // Create another emprunt
        Emprunt__c newEmprunt = TestFactory.createEmprunt(c);
        newEmprunt.Date_retour_prevu__c = system.today();
        newEmprunt.Montant_geste_commercial__c = 100;
        newEmprunt.Motif_geste_commercial__c = 'Retard';
        insert newEmprunt;
        
        // Mock an old emprunt
        newEmprunt.Date_sortie__c = system.today() - 1;
        update newEmprunt;
        
        // Query the facture and check whether the number of days spent has been updated
        factureList = [SELECT Montant_facture__c, Nombre_jours_consommes__c
                       FROM Facture__c
                       WHERE Contrat__c =: c.id];
        
        // Query the emprunt to check the number of days imputed
        newEmprunt = [SELECT Nombre_jours_imputes__c
                      FROM Emprunt__c WHERE id =: newEmprunt.id];
        
        system.assertEquals(e.Nombre_jours_imputes__c + newEmprunt.Nombre_jours_imputes__c, factureList[0].Nombre_jours_consommes__c, 
                            'The number of days spent hasnt been updated after another emprunt created - This is wrong');
        system.assertEquals(-110, factureList[0].Montant_facture__c, 
                            'The Montant Facture hasnt been updated after another emprunt created - This is wrong');
        
        // Update the emprunt
        newEmprunt.Date_sortie__c = system.today() - 2;
        newEmprunt.Montant_geste_commercial__c = 10;
        update newEmprunt;
        
        // Query the facture and check whether the number of days spent has been updated
        factureList = [SELECT Montant_facture__c, Nombre_jours_consommes__c, Nombre_jours_depassement__c
                       FROM Facture__c
                       WHERE Contrat__c =: c.id];
        
        // Query the emprunt to check the number of days imputed
        newEmprunt = [SELECT Nombre_jours_imputes__c
                      FROM Emprunt__c WHERE id =: newEmprunt.id];
        
        system.assertEquals(e.Nombre_jours_imputes__c + newEmprunt.Nombre_jours_imputes__c, factureList[0].Nombre_jours_consommes__c, 
                            'The number of days spent hasnt been updated after emprunt update - This is wrong');
        system.assertEquals(-20, factureList[0].Montant_facture__c, 
                            'The Montant facturé hasnt been updated after emprunt update - This is wrong');
        
        test.stopTest();
    }
    
    /***
	* @description Substract the fields from deleted emprunt on the facture
	* @see cleanFactureOnDelete
	*/
    @isTest
    public static void cleanFactureOnDeleteTest(){
        
        // Create a contract
        Asset c = TestFactory.createContract();
        insert c;
        
        // Create an emprunt
        Emprunt__c e = TestFactory.createEmprunt(c);
        e.Date_sortie__c = system.today();
        e.Date_retour_prevu__c = system.today() + 2;
        e.Montant_geste_commercial__c = 10;
        e.Motif_geste_commercial__c = 'Retard';
        insert e;
        
        // On second thoughts - delete it
        delete e;
        
        // Query the facture and check whether the number of days spent has been updated
        List<Facture__c> factureList = [SELECT Montant_facture__c, Nombre_jours_consommes__c
                                       FROM Facture__c
                                       WHERE Contrat__c =: c.id];
        
        system.assertEquals(0, factureList[0].Nombre_jours_consommes__c, 
                            'The number of days spent hasnt been updated after deletion - This is wrong');
        system.assertEquals(0, factureList[0].Montant_facture__c, 
                            'The Montant geste co hasnt been updated after deletion - This is wrong');
    }
    
    /***
	* @description When creating an emprunt, check whether there isn't already a reservation.
	* @see checkStockPlanning
	*/
    @isTest
    public static void checkStockPlanningTest(){
        
        // Create a contract
        Asset c = TestFactory.createContract();
        insert c;
        
        // Create a stock
        Stock_Produit__c s = TestFactory.createStock();
        insert s;
        
        test.startTest();
        
        // Create a new reservation
        Reservation__c r = TestFactory.createReservation(c.AccountId, s.id);
        r.Date_retrait__c = system.today();
        r.Duree_emprunt__c = 1;
        insert r;
        
        // Create an emprunt
        Emprunt__c e = TestFactory.createEmprunt(c, s);
        e.Date_sortie__c = system.today() + 1;
        e.Date_retour_prevu__c = system.today() + 2;
        
        // Try to insert it
        try{
            insert e;
            system.assert(false, 'This emprunt shouldnt have been successfully inserted - This is wrong');
        } catch(Exception ex){
            system.assertEquals(TRUE, ex.getMessage().contains('pas disponible sur la'), ex.getMessage());
        }
        
        // Change the reservation
        r.Date_retrait__c = system.today() + 4;
        r.Duree_emprunt__c = 1;
        update r;
        
        // And insert the emprunt again
        insert e;
        
        test.stopTest();
    }
    
    /***
	* @description Check whether the emprutn status is well automated
	* @see automateEmpruntStatus
	*/
    @isTest
    public static void automateEmpruntStatusTest(){
        
        // Create a contract
        Asset c = TestFactory.createContract();
        insert c;
        
        // Create a distributeur
        Account d = TestFactory.createDistributeur();
        insert d;
        
        // Create an emprunt
        Emprunt__c e = TestFactory.createEmprunt(c);
        e.Date_sortie__c = system.today() + 1;
        e.Date_retour_prevu__c = system.today() + 2;
        e.Point_de_vente_retour__c = d.id;
        e.Point_de_vente_sortie__c = d.id;
        insert e;
        
        Test.startTest();
        
        // Take it out
        e.Heure_sortie__c = system.now().time();
        e.Heure_retour_prevue__c = system.now().time();
        e.Etat_sortie__c = 'Neuf';
        e.Montant_caution_sortie__c = 100;
        e.Caution_recue__c = true;
        update e;
        
        // Check whether the status got updated
        e = [SELECT Status__c FROM Emprunt__c WHERE id =: e.id];
        system.assertEquals('Sortie', e.Status__c, 
                           'The emprunt status hasnt been updated - This is wrong');
        
        // Bring it back 
        e.Date_retour__c = system.today() + 2;
        e.Heure_retour__c = system.now().time();
        e.Etat_retour__c = 'Bon état';
        e.Montant_caution_retour__c = 100;
        e.Caution_restituee__c = TRUE;
        update e;
        
        // Check whether the status got updated
        e = [SELECT Status__c FROM Emprunt__c WHERE id =: e.id];
        system.assertEquals('Retourné', e.Status__c, 
                           'The emprunt status hasnt been updated - This is wrong');
        
        // Wait, actually there was a scratch, let's play it again
        e.Caution_restituee__c = FALSE;
        e.Status__c = 'Sortie';
        update e;
        
        // Update teh emprunt again
        e.Caution_restituee__c = TRUE;
        e.Etat_retour__c = 'Rayé';
        e.Montant_a_deduire__c = 10;
        e.Default__c = 'Rayé';
        update e;
        
        Test.stopTest();
        
        // Check whether the status got updated
        e = [SELECT Status__c FROM Emprunt__c WHERE id =: e.id];
        system.assertEquals('Retour avec défaut', e.Status__c, 
                           'The emprunt status hasnt been correctly updated - This is wrong');
    }
    
}