hubSide/force-app/main/default/objects/Asset/fields/Date_debut_contrat__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_contrat__c</fullName>
    <description>Date de début du contrat souscrit par le client.</description>
    <label>Date de début du contrat</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Formule__c.field-meta.xml
<CustomField>
    <fullName>Formule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Formule</label>
    <referenceTo>vlocity_ins__AssetCoverage__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Plafond__c.field-meta.xml
<CustomField>
    <fullName>Plafond__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Plafond</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/TECH_CalculatorIndicLastChange__c.field-meta.xml
<CustomField>
    <fullName>TECH_CalculatorIndicLastChange__c</fullName>
    <label>TECH_CalculatorIndicLastChange</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/TECH_CalculatorIndicNextChange__c.field-meta.xml
<CustomField>
    <fullName>TECH_CalculatorIndicNextChange__c</fullName>
    <formula>DATE(    YEAR(ADDMONTHS(TECH_CalculatorIndicLastChange__c,Formule__r.Formule_options__r.NbMounthKPIContract__c)),
         MONTH(ADDMONTHS(TECH_CalculatorIndicLastChange__c,Formule__r.Formule_options__r.NbMounthKPIContract__c)),
		 DAY(ADDMONTHS(TECH_CalculatorIndicLastChange__c,Formule__r.Formule_options__r.NbMounthKPIContract__c)))-1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_CalculatorIndicNextChange</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/TECH_LastBirthDayContract__c.field-meta.xml
<CustomField>
    <fullName>TECH_LastBirthDayContract__c</fullName>
    <label>TECH_LastBirthDayContract</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/TECH_PreviousAmountIndem__c.field-meta.xml
<CustomField>
    <fullName>TECH_PreviousAmountIndem__c</fullName>
    <label>Montant indemnisation période -1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Date_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Date_sinistre__c</fullName>
    <description>JJ/MM/AAAA</description>
    <label>Date du sinistre</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Montant_geste_co__c.field-meta.xml
<CustomField>
    <fullName>Montant_geste_co__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Montant du geste commercial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Montant_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Montant_sinistre__c</fullName>
    <label>Coût global</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/classes/BatchAssetCalculator.cls
public class BatchAssetCalculator implements Database.Batchable<sObject> {
    Date dateNow = System.now().date();
    public String query = 'SELECT Id, '+
        'AssetId, Date_sinistre__c, ' + 
        'IsDeleted, Montant_sinistre__c, ' +
        'Montant_geste_co__c, Status, ' +
        'Asset.Formule__r.Formule_options__r.NbMounthKPIContract__c, ' +
        'Asset.Plafond__c, '+
        'Asset.TECH_CalculatorIndicLastChange__c,' +
        'Asset.TECH_CalculatorIndicNextChange__c,' +
        'Asset.TECH_PreviousAmountIndem__c,' +
        'Asset.TECH_LastBirthDayContract__c,' +
        'Asset.Date_debut_contrat__c ' +
        'FROM Case '+
        'WHERE Record_Type_Name__c LIKE \'Sinistre%\' ' + 
        'AND Asset.TECH_CalculatorIndicLastChange__c =:dateNow ' + 
        'ORDER BY LastModifiedDate DESC ' + 
        'ALL ROWS';
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
  
    public void execute(Database.BatchableContext BC, List<Case> scope){
        UtilityClassHelper.assetKPICalculator(scope,null);
    }
  
    public void finish(Database.BatchableContext BC){
    }
 }