hubSide/force-app/main/default/objects/Asset/fields/Date_debut_contrat__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_contrat__c</fullName>
    <description>Date de début du contrat souscrit par le client.</description>
    <label>Date de début du contrat</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Facture__c.field-meta.xml
<CustomField>
    <fullName>Facture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consommation</label>
    <referenceTo>Facture__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/Facture__c.object-meta.xml
<CustomObject>
    <description>Historique par période du nombre de jour consommé et des dépassements occasionnels. Justification historique facture client</description>
    <label>Consommation</label>
    <nameField>
        <displayFormat>FAC-{00000000}</displayFormat>
        <label>Facture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consommations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Facture__c/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contrat lié à la facture en cours</description>
    <label>Contrat</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contrat location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Consommations</relationshipLabel>
    <relationshipName>Consommations</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Date_debut_periode__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_periode__c</fullName>
    <description>Date de début de période, initialisant les compteurs à 0.</description>
    <label>Date de début de période</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/classes/FactureTriggerHandlerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 11/06/2020
* @description FactureTrigger test class
* @Object Facture__c
*/

@isTest
public class FactureTriggerHandlerTest {
    
    /***
    * @description Update the date for the contract starting in the past
    * @see updateRelatedFacture
    */
    @isTest
    public static void updateRelatedFactureTest(){
        
        // Create a new Contract
        Asset c = TestFactory.createContract();
        c.Date_debut_contrat__c = Date.newInstance(system.today().year() - 4, 
                                                   system.today().month() - 4, 
                                                   system.today().day() - 2);
        insert c;
        
        // Query the facture
        Facture__c f = [SELECT id, Date_debut_periode__c FROM Facture__c WHERE Contrat__c =: c.id];
                
        system.assertEquals(system.today(), f.Date_debut_periode__c, 
                            'The facture start date is not the one expected - This is wrong');
        
        // Create another contract
        Asset c1 = TestFactory.createContract();
        c1.Date_debut_contrat__c = system.today() - 2;
        insert c1;
        
        // Query the facture
        Facture__c f1 = [SELECT id, Date_debut_periode__c FROM Facture__c WHERE Contrat__c =: c1.id];
                
        system.assertEquals(c1.Date_debut_contrat__c, f1.Date_debut_periode__c, 
                            'The facture start date is not the one expected - This is wrong');
    }
    
    
}