hubSide/force-app/main/default/objects/Asset/fields/Facture__c.field-meta.xml
<CustomField>
    <fullName>Facture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consommation</label>
    <referenceTo>Facture__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Nombre_jours_consommes__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_consommes__c</fullName>
    <formula>Facture__r.Nombre_jours_consommes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours consommés</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/Emprunt__c.object-meta.xml
<CustomObject>
    <label>Emprunt</label>
    <nameField>
        <displayFormat>EMP-{000000}</displayFormat>
        <label>Emprunt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emprunts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contrat lié à l&apos;emprunt</description>
    <label>Contrat</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3 OR 5) AND 4</booleanFilter>
        <errorMessage>Il n&apos;y a pas de contrat pour ce client, ou alors le contrat en question a déjà un emprunt actif.</errorMessage>
        <filterItems>
            <field>Asset.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contrat location</value>
        </filterItems>
        <filterItems>
            <field>Asset.Emprunt_en_cours__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Asset.Emprunt_en_cours__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Asset.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Client__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Retour sans défaut, Retour avec défaut</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Emprunts</relationshipLabel>
    <relationshipName>Emprunts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_retour__c.field-meta.xml
<CustomField>
    <fullName>Date_retour__c</fullName>
    <description>Date effective de retour</description>
    <label>Date de retour</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_retour_prevu__c.field-meta.xml
<CustomField>
    <fullName>Date_retour_prevu__c</fullName>
    <description>Date prévisionnelle de retour pour vérifier le nombre de jours possible et gérer les stocks glissants par la suite</description>
    <label>Date du retour prévu</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <description>Date d&apos;emprunt de l&apos;objet</description>
    <label>Date de sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/ExternalCons_EquivDaysNumber__c.field-meta.xml
<CustomField>
    <fullName>ExternalCons_EquivDaysNumber__c</fullName>
    <description>SFAMI-2160 : Nombre de jours de consommation externe équivalant un montant de remise chez un partenaire</description>
    <inlineHelpText>Chaque jour saisi dans ce champs doit correpondre au montant de remise du Voucher partenaire :
•	1 Jour Pass’Loc = 50 € de réduction sur le Voucher
•	Limite de 10 J après les 3 premiers mois du contrat
•	Limite de 20 J par an ( soit 1000€/an )</inlineHelpText>
    <label>Equivalent Jours du voucher</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Facture__c.field-meta.xml
<CustomField>
    <fullName>Facture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Facture liée à l&apos;emprunt en cours</description>
    <label>Facture</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Facture__c.Contrat__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contrat__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Facture__c</referenceTo>
    <relationshipLabel>Emprunts</relationshipLabel>
    <relationshipName>Emprunts</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Gamme_formule__c.field-meta.xml
<CustomField>
    <fullName>Gamme_formule__c</fullName>
    <formula>Contrat__r.Code_formule__r.Gamme_formule__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gamme formule</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Montant_facture__c.field-meta.xml
<CustomField>
    <fullName>Montant_facture__c</fullName>
    <formula>Montant_depassement__c - Montant_geste_commercial__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Montant facturé</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Nombre_jours_depassement__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_depassement__c</fullName>
    <formula>IF(
    Nombre_jours_imputes__c - Nombre_de_jours_consommation__c - Contrat__r.Code_formule__r.Nombre_jours_carence__c &gt; 0,
    Nombre_jours_imputes__c - Nombre_de_jours_consommation__c - Contrat__r.Code_formule__r.Nombre_jours_carence__c,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours en dépassement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Nombre_jours_restants__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_restants__c</fullName>
    <formula>IF(
    (Nombre_de_jours_consommation__c - Nombre_jours_imputes__c) &gt; 0,
    Nombre_de_jours_consommation__c - Nombre_jours_imputes__c,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours restants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En magasin</fullName>
                <default>true</default>
                <label>En magasin</label>
            </value>
            <value>
                <fullName>Sortie</fullName>
            </value>
            <value>
                <fullName>Retourné</fullName>
                <label>Retour sans défaut</label>
            </value>
            <value>
                <fullName>Retour avec défaut</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
                <isActive>false</isActive>
                <label>Annulé</label>
            </value>
            <value>
                <fullName>Label.Location_StatusEmprunt1</fullName>
                <isActive>false</isActive>
                <label>Label.Location_StatusEmprunt1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/recordTypes/Emprunt.recordType-meta.xml
<RecordType>
    <fullName>Emprunt</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet emprunt une fois créé</description>
    <label>Emprunt</label>
</RecordType>

hubSide/force-app/main/default/objects/Facture__c/Facture__c.object-meta.xml
<CustomObject>
    <description>Historique par période du nombre de jour consommé et des dépassements occasionnels. Justification historique facture client</description>
    <label>Consommation</label>
    <nameField>
        <displayFormat>FAC-{00000000}</displayFormat>
        <label>Facture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consommations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Facture__c/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contrat lié à la facture en cours</description>
    <label>Contrat</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contrat location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Consommations</relationshipLabel>
    <relationshipName>Consommations</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Facture_active__c.field-meta.xml
<CustomField>
    <fullName>Facture_active__c</fullName>
    <formula>AND(
    OR(
        Date_debut_periode__c &lt; TODAY(), 
        TODAY() == Date_debut_periode__c
    ), 
    OR(
        TODAY() &lt; Date_fin_periode__c, 
        TODAY() == Date_fin_periode__c
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Periode en cours</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Montant_facture__c.field-meta.xml
<CustomField>
    <fullName>Montant_facture__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Montant total facturé sur la période</description>
    <label>Montant facturé</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Nombre_jours_consommes__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_consommes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Nombre total de jours consommés dans la période</description>
    <label>Jours consommés</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Nombre_jours_depassement__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_depassement__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Nombre de jours hors formule</description>
    <label>Nombre de jours en dépassement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Nombre_jours_restants__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_restants__c</fullName>
    <formula>IF(
    ( Nombre_jours_disponibles__c - Nombre_jours_consommes__c) &gt; 0,
    Nombre_jours_disponibles__c - Nombre_jours_consommes__c,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours restants</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Objets Réservés sur le web / en boutique</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Numero de reservation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Reservation__c/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contrat permettant de faire une réservation</description>
    <label>Contrat</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Client__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Réservé</fullName>
            </value>
            <value>
                <fullName>Réservation_convertie</fullName>
                <label>Réservation convertie</label>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>Pré-réservé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/Stock_produit__c.object-meta.xml
<CustomObject>
    <label>Stock magasin</label>
    <nameField>
        <label>Stock magasin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks magasin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_retour__c.field-meta.xml
<CustomField>
    <fullName>Date_retour__c</fullName>
    <description>Date de retour de l&apos;emprunt actuel, si emprunt il y a.</description>
    <label>Date de retour</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <label>Date sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/classes/EmpruntTriggerHelper.cls
/***
* @author Ariane Tanguy (GFI)
* @date 05/05/2020
* @description Helper class for EmpruntTrigger
*/

public class EmpruntTriggerHelper {
    
    /***
	* @description Get all the factures related to the newly created emprunt
	* @param newEmpruntList - list of emprunt
	* @return List<Facture__c>
	*/
    public static List<Facture__c> getAllRelatedFacture(List<Emprunt__c> newEmpruntList){
        
        // Get the related contract ids
        Set<id> contractIdSet = new Set<Id>();
        for(Emprunt__c e : newEmpruntList){
            contractIdSet.add(e.Contrat__c);
        }
        
        // Query the related factures
        return queryFacture(contractIdSet);
    }
    
    /***
	* @description Get all the factures related to the updated emprunt
	* @param oldEmpruntMap - map of the old emprunt with their ids
	* @param newEmpruntList - list of the new emprunt
	* @return List<Facture__c>
	*/
    public static List<Facture__c> getRelatedFactureOnEmpruntChange(Map<id, Emprunt__c> oldEmpruntMap, List<Emprunt__c> newEmpruntList){
        
        // Get the related contract ids
        Set<id> contractIdSet = new Set<Id>();
        for(Emprunt__c e : newEmpruntList){
            if(e.Date_retour_prevu__c != oldEmpruntMap.get(e.id).Date_retour_prevu__c ||
               e.Date_retour__c != oldEmpruntMap.get(e.id).Date_retour__c ||
               e.Date_sortie__c != oldEmpruntMap.get(e.id).Date_sortie__c ||
               e.Status__c != oldEmpruntMap.get(e.id).Status__c||
               //SFAMI-2160 : update facture on external consumption change>
               e.ExternalCons_EquivDaysNumber__c != oldEmpruntMap.get(e.id).ExternalCons_EquivDaysNumber__c){
               //<SFAMI-2160
                    contractIdSet.add(e.Contrat__c);
               }
        }
        
        // Query the related factures
        return queryFacture(contractIdSet);
    }
    
    /***
	* @description Backend function to get the facture
	* @param contractIdSet - list of the related contrat id
	* @return List<Facture__c> List queried factures
	*/
    private static List<Facture__c> queryFacture(Set<id> contractIdSet){
        
        if(contractIdSet.size() == 0){
            return new List<Facture__c>();
        }
        
        return new List<Facture__c>([SELECT id, Contrat__c, 
                                     Montant_facture__c, 
                                     Nombre_jours_consommes__c, 
                                     Nombre_jours_depassement__c, 
                                     Nombre_jours_restants__c
                                     FROM Facture__c
                                     WHERE Contrat__c IN :contractIdSet
                                     AND Facture_active__c = TRUE]);
    }
    
    /***
	* @description Get all the table de decompte related to the newly created emprunt
	* @param newEmpruntList - list of the new emprunt
	* @return Map<List<String>, Decimal> (map a list of gamme with the related coef de decompte)
	*/
    public static Map<List<String>, Decimal> getRelatedTableDecompte(List<Emprunt__c> newEmpruntList){
        
        // Get the related gamme names
        Set<String> gammeProduit = new Set<String>();
        Set<String> gammeFormule = new Set<String>();
        for(Emprunt__c e : newEmpruntList){
            gammeFormule.add(e.Gamme_formule__c);
            gammeProduit.add(e.Gamme_produit__c);
        }
        
        // Query the related table de decompte
        List<Table_decompte__c> tableDecompteList = [SELECT Gamme_formule__r.Name, Gamme_Produit__r.Name, 
                                                     Coefficient_decompte__c
                                                     FROM Table_decompte__c
                                                     WHERE Gamme_formule__r.Name IN : gammeFormule
                                                     AND Gamme_Produit__r.Name IN : gammeProduit];
        
        // Map the whole thing
        Map<List<String>, Decimal> tableDecompteMap = new Map<List<String>, Decimal>();
        for(Table_decompte__c t : tableDecompteList){
            List<String> gammeNameList = new List<String>{t.Gamme_formule__r.Name, t.Gamme_Produit__r.Name};
                tableDecompteMap.put(gammeNameList, t.Coefficient_decompte__c);
        }
        
        return tableDecompteMap;
    }
    
    /***
	* @description Get all the planned reservations
	* @param newEmpruntList - list of the new emprunt
	* @return List<Reservation__c> - List of the planned reservations
	*/
    public static List<Reservation__c> getPlannedReservation(List<Emprunt__c> newEmpruntList){
        
        // Get all the related stock ids
        List<id> wishedStockIdList = new List<id>();
        for(Emprunt__c e : newEmpruntList){
            wishedStockIdList.add(e.Produit_emprunte__c);
        }
        
        return queryReservation(wishedStockIdList);
    }
    
    /***
	* @description Get all the planned reservations
	* @param newEmpruntList - list of the new emprunt
	* @return List<Reservation__c> - List of the planned reservations
	*/
    public static List<Reservation__c> getPlannedReservation(Map<id, Emprunt__c> oldEmpruntMap, List<Emprunt__c> newEmpruntList){
        
        // Get all the related stock ids
        List<id> wishedStockIdList = new List<id>();
        for(Emprunt__c e : newEmpruntList){
            if(e.Produit_emprunte__c != oldEmpruntMap.get(e.Id).Produit_emprunte__c){
                wishedStockIdList.add(e.Produit_emprunte__c);
            }
        }
        
        return queryReservation(wishedStockIdList);
    }
    
    /***
	* @description Backend function to get the facture
	* @param contractIdSet - list of the related contrat id
	* @return List<Facture__c> List queried factures
	*/
    public static List<Reservation__c> queryReservation(List<id> wishedStockIdList){
        
        if(wishedStockIdList.size() == 0){
            return new List<Reservation__c>();
        }
        
        return new List<Reservation__c>([SELECT id, Date_retrait__c, Duree_emprunt__c, 
                                         Produit_reserve__c
                                         FROM Reservation__c
                                         WHERE Status__c = 'Réservé'
                                         AND Produit_reserve__c IN : wishedStockIdList]);
    }
    
    /***
	* @description Get the related contract
	* @param newEmpruntList - list of the new emprunt
	* @return List<Asset> List queried assets
	*/
    public static List<Asset> getRelatedAsset(List<Emprunt__c> newEmpruntList){
                        
        // Map the emprunt to their contrat
        Set<id> contratIdSet = new Set<id>();
        for(Emprunt__c e : newEmpruntList){
            contratIdSet.add(e.Contrat__c);
        }
        
        List<Asset> queriedContratList = [SELECT Code_formule__r.Nombre_jours_carence__c, 
                                          Code_formule__r.Tarif_depassement__c, 
                                          AccountId, 
                                          Account.Email_connexion__c, 
                                          Facture__c
                                          FROM Asset
                                          WHERE id IN: contratIdSet];

        return queriedContratList;
    }
    
    /***
	* @description Get the related stock info
	* @param newEmpruntList - list of the new emprunt
	* @return List<Stock_Produit__c> List queried stock
	*/
    public static List<Stock_Produit__c> getRelatedStock(List<Emprunt__c> newEmpruntList){
                        
        // Map the emprunt to their contrat
        Set<id> stockIdSet = new Set<id>();
        for(Emprunt__c e : newEmpruntList){
            stockIdSet.add(e.Produit_emprunte__c);
        }
        
        List<Stock_Produit__c> relatedStockList = [SELECT Etat__c, 
                                                   Produit__r.Caution__c, 
                                                   Observation__c
                                                   FROM Stock_Produit__c
                                                   WHERE id IN: stockIdSet];

        return relatedStockList;
    }
}