hubSide/force-app/main/default/objects/SFAMConfig__c/SFAMConfig__c.object-meta.xml
<CustomObject>
    <description>Custom object defining the permission / profile / role to assign to a user when created.</description>
    <label>Config SFAM</label>
    <nameField>
        <label>Config SFAM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configs SFAM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserPermissionSet__c.field-meta.xml
<CustomField>
    <fullName>UserPermissionSet__c</fullName>
    <description>Permission set tel que défini dans Salesforce - Permission Set as defined in Salesforce</description>
    <label>Utilisateur - Permission set</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>API_Only</fullName>
            </value>
            <value>
                <fullName>cases_Permisssion_Set</fullName>
            </value>
            <value>
                <fullName>ManagerDirectionLogistique</fullName>
            </value>
            <value>
                <fullName>PS_ADM_agent</fullName>
            </value>
            <value>
                <fullName>PS_ADM_Manager</fullName>
            </value>
            <value>
                <fullName>PS_Back_Agent</fullName>
            </value>
            <value>
                <fullName>PS_Back_Manager</fullName>
            </value>
            <value>
                <fullName>PS_Direction_QualiteSinistre</fullName>
            </value>
            <value>
                <fullName>PS_FEA_ReportDsh</fullName>
            </value>
            <value>
                <fullName>PS_GSIN_Gestionnaire</fullName>
            </value>
            <value>
                <fullName>PS_GSIN_Manager</fullName>
            </value>
            <value>
                <fullName>PS_LOG_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXP_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXP_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXPD_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXPD_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_LOG_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_LOG_REC</fullName>
            </value>
            <value>
                <fullName>PS_ManagerGSQualite</fullName>
            </value>
            <value>
                <fullName>PS_REP_ADM_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_REP_ADM_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_REP_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_TCSIN_MANAGER</fullName>
            </value>
            <value>
                <fullName>SFAM_creation_Produit</fullName>
            </value>
            <value>
                <fullName>SFAM_Read_Only</fullName>
            </value>
            <value>
                <fullName>SFAMGestionnaireJuridique</fullName>
            </value>
            <value>
                <fullName>SFAMManagerQualite</fullName>
            </value>
            <value>
                <fullName>SFAMTCQualite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserProfile__c.field-meta.xml
<CustomField>
    <fullName>UserProfile__c</fullName>
    <description>Profil tel que défini dans salesforce - Profile as defined in Salesforce</description>
    <label>Utilisateur - Profil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SFAM Expertise</fullName>
            </value>
            <value>
                <fullName>SFAM Stock</fullName>
            </value>
            <value>
                <fullName>SFAM Reparation</fullName>
            </value>
            <value>
                <fullName>SFAM Logistique</fullName>
            </value>
            <value>
                <fullName>SFAM API</fullName>
            </value>
            <value>
                <fullName>SFAM GS</fullName>
            </value>
            <value>
                <fullName>SFAM Qualite</fullName>
            </value>
            <value>
                <fullName>SFAM TC</fullName>
            </value>
            <value>
                <fullName>SFAM Vendeur TC</fullName>
            </value>
            <value>
                <fullName>Profil TC</fullName>
            </value>
            <value>
                <fullName>Profil GS</fullName>
            </value>
            <value>
                <fullName>SFAM ADM</fullName>
            </value>
            <value>
                <fullName>SFAM Vendeur</fullName>
            </value>
            <value>
                <fullName>SFAM Manager</fullName>
            </value>
            <value>
                <fullName>SFAM Admin Produit</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Standard User</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserRole__c.field-meta.xml
<CustomField>
    <fullName>UserRole__c</fullName>
    <description>Role tel que défini dans Salesforce - Role as defined in Salesforce</description>
    <label>Utilisateur - Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Admin_Enseigne</fullName>
                <label>Admin Enseigne</label>
            </value>
            <value>
                <fullName>Direction_ADM</fullName>
                <label>Direction ADM</label>
            </value>
            <value>
                <fullName>Direction_Back_up</fullName>
                <label>Direction Back-up</label>
            </value>
            <value>
                <fullName>Direction_Exp_dition</fullName>
                <label>Direction Expédition</label>
            </value>
            <value>
                <fullName>Direction_Expertise_SAV_suite_change</fullName>
                <label>Direction Expertise - SAV suite à échange</label>
            </value>
            <value>
                <fullName>Direction_Gestion_Sinistre</fullName>
                <label>Direction Gestion Sinistre</label>
            </value>
            <value>
                <fullName>Direction_GS_Qualit</fullName>
                <label>Direction GS Qualité</label>
            </value>
            <value>
                <fullName>Direction_Logistique</fullName>
                <label>Direction Logistique</label>
            </value>
            <value>
                <fullName>Direction_R_ception_colis</fullName>
                <label>Direction Réception colis</label>
            </value>
            <value>
                <fullName>Direction_R_paration</fullName>
                <label>Direction Réparation</label>
            </value>
            <value>
                <fullName>Direction_R_paration_ADM</fullName>
                <label>Direction Réparation ADM</label>
            </value>
            <value>
                <fullName>Direction_TC_Qualit</fullName>
                <label>Direction TC Qualité</label>
            </value>
            <value>
                <fullName>Direction_Teleconseiller_Sinistre</fullName>
                <label>Direction Téléconseiller Sinistre</label>
            </value>
            <value>
                <fullName>Equipe_1_ADM</fullName>
                <label>Equipe 1 ADM</label>
            </value>
            <value>
                <fullName>Equipe_1_Back_up</fullName>
                <label>Equipe 1 Back-up</label>
            </value>
            <value>
                <fullName>Equipe_1_Exp_dition</fullName>
                <label>Equipe 1 Expédition</label>
            </value>
            <value>
                <fullName>Equipe_1_EXP_SAV_suite_change</fullName>
                <label>Equipe 1 EXP - SAV suite à échange</label>
            </value>
            <value>
                <fullName>Equipe_1_GS</fullName>
                <label>Equipe 1 GS</label>
            </value>
            <value>
                <fullName>Equipe_1_GS_Qualit</fullName>
                <label>Equipe 1 GS Qualité</label>
            </value>
            <value>
                <fullName>Equipe_1_Logistique</fullName>
                <label>Equipe 1 Logistique</label>
            </value>
            <value>
                <fullName>Equipe_1_R_ception_colis</fullName>
                <label>Equipe 1 Réception colis</label>
            </value>
            <value>
                <fullName>Equipe_1_R_paration</fullName>
                <label>Equipe 1 Réparation</label>
            </value>
            <value>
                <fullName>Equipe_1_R_paration_ADM</fullName>
                <label>Equipe 1 Réparation ADM</label>
            </value>
            <value>
                <fullName>Equipe_1_TC</fullName>
                <label>Equipe 1 TC</label>
            </value>
            <value>
                <fullName>Equipe_1_TC_Qualit</fullName>
                <label>Equipe 1 TC Qualité</label>
            </value>
            <value>
                <fullName>Equipe_2_ADM</fullName>
                <label>Equipe 2 ADM</label>
            </value>
            <value>
                <fullName>Equipe_2_Back_up</fullName>
                <label>Equipe 2 Back-up</label>
            </value>
            <value>
                <fullName>Equipe_2_Exp_dition</fullName>
                <label>Equipe 2 Expédition</label>
            </value>
            <value>
                <fullName>Equipe_2_EXP_SAV_suite_change</fullName>
                <label>Equipe 2 EXP - SAV suite à échange</label>
            </value>
            <value>
                <fullName>Equipe_2_GS</fullName>
                <label>Equipe 2 GS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/classes/SFAMConfigTriggerHelper.cls
/***
* @author Ariane Tanguy (GFI)
* @date 31/03/2021
* @description Helper class for SFAMConfigTrigger
*/

public class SFAMConfigTriggerHelper {
    
    /***
	* @description Get the missing profiles
	* @param newConfigList - list of new config
	* @return Map<id, Profile>
	*/
    public static Map<String, Profile> getMissingProfile(List<SFAMConfig__c> newConfigList){
        
        // Get the profile names
        Set<String> profileNameSet = new Set<String>();
        for(SFAMConfig__c c : newConfigList){
            profileNameSet.add(c.UserProfile__c);
        }
        
        Map<String, Profile> relatedProfileMap = new Map<String, Profile>();
        if(profileNameSet.size() > 0){
            List<Profile> relatedProfileList = [SELECT id, Name FROM Profile WHERE Name IN: profileNameSet];
            for(Profile p : relatedProfileList){
                relatedProfileMap.put(p.Name, p);
            }
        }
        
        return relatedProfileMap;
    }
    
    /***
	* @description Get the missing profiles
	* @param newConfigList - list of new config
	* @param oldConfigMap - map of old config
	* @return Map<id, Profile>
	*/
    public static Map<String, Profile> getMissingProfile(List<SFAMConfig__c> newConfigList, Map<id, SFAMConfig__c> oldConfigMap){
        
        // Get the profile names
        Set<String> profileNameSet = new Set<String>();
        for(SFAMConfig__c c : newConfigList){
            if(c.UserProfile__c != oldConfigMap.get(c.id).UserProfile__c){
                profileNameSet.add(c.UserProfile__c);
            }
        }
        
        Map<String, Profile> relatedProfileMap = new Map<String, Profile>();
        if(profileNameSet.size() > 0){
            List<Profile> relatedProfileList = [SELECT id, Name FROM Profile WHERE Name IN: profileNameSet];
            for(Profile p : relatedProfileList){
                relatedProfileMap.put(p.Name, p);
            }
        }        
        
        return relatedProfileMap;
    }
    
    /***
	* @description Get the missing roles
	* @param newConfigList - list of new config
	* @return Map<id, UserRole>
	*/
    public static Map<String, UserRole> getMissingRole(List<SFAMConfig__c> newConfigList){
        
        // Get the role names
        Set<String> roleNameSet = new Set<String>();
        for(SFAMConfig__c c : newConfigList){
            roleNameSet.add(c.UserRole__c);
        }
        
        Map<String, UserRole> relatedRoleMap = new Map<String, UserRole>();
        if(roleNameSet.size() > 0){
            List<UserRole> relatedRoleList = [SELECT id, DeveloperName FROM UserRole WHERE DeveloperName IN: roleNameSet];
            for(UserRole p : relatedRoleList){
                relatedRoleMap.put(p.DeveloperName, p);
            }
        }
        
        return relatedRoleMap;
    }
    
    /***
	* @description Get the missing roles
	* @param newConfigList - list of new config
	* @param oldConfigMap - map of old config
	* @return Map<id, UserRole>
	*/
    public static Map<String, UserRole> getMissingRole(List<SFAMConfig__c> newConfigList, Map<id, SFAMConfig__c> oldConfigMap){
        
        // Get the role names
        Set<String> roleNameSet = new Set<String>();
        for(SFAMConfig__c c : newConfigList){
            if(c.UserRole__c != oldConfigMap.get(c.id).UserRole__c){
                roleNameSet.add(c.UserRole__c);
            }
        }
        
        Map<String, UserRole> relatedRoleMap = new Map<String, UserRole>();
        if(roleNameSet.size() > 0){
            List<UserRole> relatedRoleList = [SELECT id, DeveloperName FROM UserRole WHERE DeveloperName IN: roleNameSet];
        
            for(UserRole p : relatedRoleList){
                relatedRoleMap.put(p.DeveloperName, p);
            }
        }
        
        return relatedRoleMap;
    }
    
    /***
	* @description Get the missing permission sets
	* @param newConfigList - list of new config
	* @return Map<id, PermissionSet>
	*/
    public static Map<String, PermissionSet> getMissingPermissionSet(List<SFAMConfig__c> newConfigList){
        
        // Get the permission set names
        Set<String> permNameSet = new Set<String>();
        for(SFAMConfig__c c : newConfigList){
            if(c.UserPermissionSet__c != NULL){
                permNameSet.addAll(c.UserPermissionSet__c.split(';'));
            }
        }
        
        Map<String, PermissionSet> relatedPermMap = new Map<String, PermissionSet>();
        if(permNameSet.size() > 0){
            List<PermissionSet> relatedPermList = [SELECT id, Name FROM PermissionSet WHERE Name IN: permNameSet];
            for(PermissionSet p : relatedPermList){
                relatedPermMap.put(p.Name, p);
            }
        }
        
        return relatedPermMap;
    }
    
    /***
	* @description Get the missing permission sets
	* @param newConfigList - list of new config
	* @param oldConfigMap - map of old config
	* @return Map<id, PermissionSet>
	*/
    public static Map<String, PermissionSet> getMissingPermissionSet(List<SFAMConfig__c> newConfigList, Map<id, SFAMConfig__c> oldConfigMap){
        
        // Get the permission set names
        Set<String> permNameSet = new Set<String>();
        for(SFAMConfig__c c : newConfigList){
            if(c.UserPermissionSet__c != oldConfigMap.get(c.id).UserPermissionSet__c &&
               c.UserPermissionSet__c != NULL){
                   permNameSet.addAll(c.UserPermissionSet__c.split(';'));
               }
        }
        
        Map<String, PermissionSet> relatedPermMap = new Map<String, PermissionSet>();
        if(permNameSet.size() > 0){
            List<PermissionSet> relatedPermList = [SELECT id, Name FROM PermissionSet WHERE Name IN: permNameSet];
            for(PermissionSet p : relatedPermList){
                relatedPermMap.put(p.Name, p);
            }
        }
        
        return relatedPermMap;
    }
}