hubSide/force-app/main/default/objects/SFAMConfig__c/SFAMConfig__c.object-meta.xml
<CustomObject>
    <description>Custom object defining the permission / profile / role to assign to a user when created.</description>
    <label>Config SFAM</label>
    <nameField>
        <label>Config SFAM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configs SFAM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserBusinessProfile__c.field-meta.xml
<CustomField>
    <fullName>UserBusinessProfile__c</fullName>
    <description>Profil métier - User&apos;s business profile</description>
    <label>Utilisateur - Profil métier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UserBusinessProfile</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserPermissionSet__c.field-meta.xml
<CustomField>
    <fullName>UserPermissionSet__c</fullName>
    <description>Permission set tel que défini dans Salesforce - Permission Set as defined in Salesforce</description>
    <label>Utilisateur - Permission set</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>API_Only</fullName>
            </value>
            <value>
                <fullName>cases_Permisssion_Set</fullName>
            </value>
            <value>
                <fullName>ManagerDirectionLogistique</fullName>
            </value>
            <value>
                <fullName>PS_ADM_agent</fullName>
            </value>
            <value>
                <fullName>PS_ADM_Manager</fullName>
            </value>
            <value>
                <fullName>PS_Back_Agent</fullName>
            </value>
            <value>
                <fullName>PS_Back_Manager</fullName>
            </value>
            <value>
                <fullName>PS_Direction_QualiteSinistre</fullName>
            </value>
            <value>
                <fullName>PS_FEA_ReportDsh</fullName>
            </value>
            <value>
                <fullName>PS_GSIN_Gestionnaire</fullName>
            </value>
            <value>
                <fullName>PS_GSIN_Manager</fullName>
            </value>
            <value>
                <fullName>PS_LOG_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXP_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXP_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXPD_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXPD_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_LOG_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_LOG_REC</fullName>
            </value>
            <value>
                <fullName>PS_ManagerGSQualite</fullName>
            </value>
            <value>
                <fullName>PS_REP_ADM_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_REP_ADM_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_REP_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_TCSIN_MANAGER</fullName>
            </value>
            <value>
                <fullName>SFAM_creation_Produit</fullName>
            </value>
            <value>
                <fullName>SFAM_Read_Only</fullName>
            </value>
            <value>
                <fullName>SFAMGestionnaireJuridique</fullName>
            </value>
            <value>
                <fullName>SFAMManagerQualite</fullName>
            </value>
            <value>
                <fullName>SFAMTCQualite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserPermissionSetId__c.field-meta.xml
<CustomField>
    <fullName>UserPermissionSetId__c</fullName>
    <description>Id de la permission set assignée à l&apos;utilisateur - User&apos;s Salesforce permission set id</description>
    <label>Utilisateur - Permission set id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserProfile__c.field-meta.xml
<CustomField>
    <fullName>UserProfile__c</fullName>
    <description>Profil tel que défini dans salesforce - Profile as defined in Salesforce</description>
    <label>Utilisateur - Profil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SFAM Expertise</fullName>
            </value>
            <value>
                <fullName>SFAM Stock</fullName>
            </value>
            <value>
                <fullName>SFAM Reparation</fullName>
            </value>
            <value>
                <fullName>SFAM Logistique</fullName>
            </value>
            <value>
                <fullName>SFAM API</fullName>
            </value>
            <value>
                <fullName>SFAM GS</fullName>
            </value>
            <value>
                <fullName>SFAM Qualite</fullName>
            </value>
            <value>
                <fullName>SFAM TC</fullName>
            </value>
            <value>
                <fullName>SFAM Vendeur TC</fullName>
            </value>
            <value>
                <fullName>Profil TC</fullName>
            </value>
            <value>
                <fullName>Profil GS</fullName>
            </value>
            <value>
                <fullName>SFAM ADM</fullName>
            </value>
            <value>
                <fullName>SFAM Vendeur</fullName>
            </value>
            <value>
                <fullName>SFAM Manager</fullName>
            </value>
            <value>
                <fullName>SFAM Admin Produit</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Standard User</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserProfileId__c.field-meta.xml
<CustomField>
    <fullName>UserProfileId__c</fullName>
    <description>Id Salesforce du profil utilisateur - User&apos;s Salesforce profile id</description>
    <label>Utilisateur - Id profil</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserRole__c.field-meta.xml
<CustomField>
    <fullName>UserRole__c</fullName>
    <description>Role tel que défini dans Salesforce - Role as defined in Salesforce</description>
    <label>Utilisateur - Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Admin_Enseigne</fullName>
                <label>Admin Enseigne</label>
            </value>
            <value>
                <fullName>Direction_ADM</fullName>
                <label>Direction ADM</label>
            </value>
            <value>
                <fullName>Direction_Back_up</fullName>
                <label>Direction Back-up</label>
            </value>
            <value>
                <fullName>Direction_Exp_dition</fullName>
                <label>Direction Expédition</label>
            </value>
            <value>
                <fullName>Direction_Expertise_SAV_suite_change</fullName>
                <label>Direction Expertise - SAV suite à échange</label>
            </value>
            <value>
                <fullName>Direction_Gestion_Sinistre</fullName>
                <label>Direction Gestion Sinistre</label>
            </value>
            <value>
                <fullName>Direction_GS_Qualit</fullName>
                <label>Direction GS Qualité</label>
            </value>
            <value>
                <fullName>Direction_Logistique</fullName>
                <label>Direction Logistique</label>
            </value>
            <value>
                <fullName>Direction_R_ception_colis</fullName>
                <label>Direction Réception colis</label>
            </value>
            <value>
                <fullName>Direction_R_paration</fullName>
                <label>Direction Réparation</label>
            </value>
            <value>
                <fullName>Direction_R_paration_ADM</fullName>
                <label>Direction Réparation ADM</label>
            </value>
            <value>
                <fullName>Direction_TC_Qualit</fullName>
                <label>Direction TC Qualité</label>
            </value>
            <value>
                <fullName>Direction_Teleconseiller_Sinistre</fullName>
                <label>Direction Téléconseiller Sinistre</label>
            </value>
            <value>
                <fullName>Equipe_1_ADM</fullName>
                <label>Equipe 1 ADM</label>
            </value>
            <value>
                <fullName>Equipe_1_Back_up</fullName>
                <label>Equipe 1 Back-up</label>
            </value>
            <value>
                <fullName>Equipe_1_Exp_dition</fullName>
                <label>Equipe 1 Expédition</label>
            </value>
            <value>
                <fullName>Equipe_1_EXP_SAV_suite_change</fullName>
                <label>Equipe 1 EXP - SAV suite à échange</label>
            </value>
            <value>
                <fullName>Equipe_1_GS</fullName>
                <label>Equipe 1 GS</label>
            </value>
            <value>
                <fullName>Equipe_1_GS_Qualit</fullName>
                <label>Equipe 1 GS Qualité</label>
            </value>
            <value>
                <fullName>Equipe_1_Logistique</fullName>
                <label>Equipe 1 Logistique</label>
            </value>
            <value>
                <fullName>Equipe_1_R_ception_colis</fullName>
                <label>Equipe 1 Réception colis</label>
            </value>
            <value>
                <fullName>Equipe_1_R_paration</fullName>
                <label>Equipe 1 Réparation</label>
            </value>
            <value>
                <fullName>Equipe_1_R_paration_ADM</fullName>
                <label>Equipe 1 Réparation ADM</label>
            </value>
            <value>
                <fullName>Equipe_1_TC</fullName>
                <label>Equipe 1 TC</label>
            </value>
            <value>
                <fullName>Equipe_1_TC_Qualit</fullName>
                <label>Equipe 1 TC Qualité</label>
            </value>
            <value>
                <fullName>Equipe_2_ADM</fullName>
                <label>Equipe 2 ADM</label>
            </value>
            <value>
                <fullName>Equipe_2_Back_up</fullName>
                <label>Equipe 2 Back-up</label>
            </value>
            <value>
                <fullName>Equipe_2_Exp_dition</fullName>
                <label>Equipe 2 Expédition</label>
            </value>
            <value>
                <fullName>Equipe_2_EXP_SAV_suite_change</fullName>
                <label>Equipe 2 EXP - SAV suite à échange</label>
            </value>
            <value>
                <fullName>Equipe_2_GS</fullName>
                <label>Equipe 2 GS</label>
            </value>
            <value>
                <fullName>Vendeur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserRoleId__c.field-meta.xml
<CustomField>
    <fullName>UserRoleId__c</fullName>
    <description>Id du role utilisateur - Salesforce role id</description>
    <label>Utilisateur - Id Role</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/classes/SFAMConfigTriggerHandlerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 01/04/2021
* @description SFAMConfigTrigger test class
* @Object SFAMConfig__c
*/

@isTest
public class SFAMConfigTriggerHandlerTest {
    
    /***
    * @description Update permission ids on insert and update
    * @see updatePermissionIdOnInsert + updatePermissionIdOnUpdate
    */
    @isTest
    public static void updatePermissionIdTest(){
        
        // Create a new SFAMConfig record
        SFAMConfig__c c = new SFAMConfig__c();
        c.UserBusinessProfile__c = 'DirectionQualiteSinistre';
        c.UserProfile__c = 'SFAM Stock';
        c.UserRole__c = 'Admin_Enseigne';
        c.UserPermissionSet__c = 'PS_GSIN_Manager';
        insert c;
        
        c = [SELECT UserProfileId__c, UserRoleId__c, UserPermissionSetId__c
            FROM SFAMConfig__c
            WHERE id =: c.id];
        
        system.assertEquals([SELECT Id FROM Profile WHERE Name = 'SFAM Stock'].id, 
                            c.UserProfileId__c, 
                           'The profile id shouldve been udpated - This is wrong');
        system.assertEquals([SELECT Id FROM UserRole WHERE Name = 'Admin Enseigne'].id, 
                            c.UserRoleId__c, 
                           'The role id shouldve been udpated - This is wrong');
        system.assertEquals([SELECT Id FROM PermissionSet WHERE Name = 'PS_GSIN_Manager'].id, 
                            c.UserPermissionSetId__c, 
                           'The permission set id shouldve been udpated - This is wrong');
        
        // On second thought, update it
        c.UserProfile__c = 'SFAM Reparation';
        c.UserRole__c = 'Vendeur';
        c.UserPermissionSet__c = 'PS_GSIN_Manager;PS_ADM_Manager';
        update c;
        
        c = [SELECT UserProfileId__c FROM SFAMConfig__c WHERE id =: c.id];        
        system.assertEquals([SELECT Id FROM Profile WHERE Name = 'SFAM Reparation'].id, 
                            c.UserProfileId__c, 
                           'The profile id shouldve been udpated - This is wrong');
    }
}