hubSide/force-app/main/default/objects/SFAMConfig__c/SFAMConfig__c.object-meta.xml
<CustomObject>
    <description>Custom object defining the permission / profile / role to assign to a user when created.</description>
    <label>Config SFAM</label>
    <nameField>
        <label>Config SFAM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configs SFAM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserBusinessProfile__c.field-meta.xml
<CustomField>
    <fullName>UserBusinessProfile__c</fullName>
    <description>Profil métier - User&apos;s business profile</description>
    <label>Utilisateur - Profil métier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UserBusinessProfile</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserPermissionSet__c.field-meta.xml
<CustomField>
    <fullName>UserPermissionSet__c</fullName>
    <description>Permission set tel que défini dans Salesforce - Permission Set as defined in Salesforce</description>
    <label>Utilisateur - Permission set</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>API_Only</fullName>
            </value>
            <value>
                <fullName>cases_Permisssion_Set</fullName>
            </value>
            <value>
                <fullName>ManagerDirectionLogistique</fullName>
            </value>
            <value>
                <fullName>PS_ADM_agent</fullName>
            </value>
            <value>
                <fullName>PS_ADM_Manager</fullName>
            </value>
            <value>
                <fullName>PS_Back_Agent</fullName>
            </value>
            <value>
                <fullName>PS_Back_Manager</fullName>
            </value>
            <value>
                <fullName>PS_Direction_QualiteSinistre</fullName>
            </value>
            <value>
                <fullName>PS_FEA_ReportDsh</fullName>
            </value>
            <value>
                <fullName>PS_GSIN_Gestionnaire</fullName>
            </value>
            <value>
                <fullName>PS_GSIN_Manager</fullName>
            </value>
            <value>
                <fullName>PS_LOG_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXP_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXP_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXPD_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXPD_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_LOG_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_LOG_REC</fullName>
            </value>
            <value>
                <fullName>PS_ManagerGSQualite</fullName>
            </value>
            <value>
                <fullName>PS_REP_ADM_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_REP_ADM_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_REP_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_TCSIN_MANAGER</fullName>
            </value>
            <value>
                <fullName>SFAM_creation_Produit</fullName>
            </value>
            <value>
                <fullName>SFAM_Read_Only</fullName>
            </value>
            <value>
                <fullName>SFAMGestionnaireJuridique</fullName>
            </value>
            <value>
                <fullName>SFAMManagerQualite</fullName>
            </value>
            <value>
                <fullName>SFAMTCQualite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserProfile__c.field-meta.xml
<CustomField>
    <fullName>UserProfile__c</fullName>
    <description>Profil tel que défini dans salesforce - Profile as defined in Salesforce</description>
    <label>Utilisateur - Profil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SFAM Expertise</fullName>
            </value>
            <value>
                <fullName>SFAM Stock</fullName>
            </value>
            <value>
                <fullName>SFAM Reparation</fullName>
            </value>
            <value>
                <fullName>SFAM Logistique</fullName>
            </value>
            <value>
                <fullName>SFAM API</fullName>
            </value>
            <value>
                <fullName>SFAM GS</fullName>
            </value>
            <value>
                <fullName>SFAM Qualite</fullName>
            </value>
            <value>
                <fullName>SFAM TC</fullName>
            </value>
            <value>
                <fullName>SFAM Vendeur TC</fullName>
            </value>
            <value>
                <fullName>Profil TC</fullName>
            </value>
            <value>
                <fullName>Profil GS</fullName>
            </value>
            <value>
                <fullName>SFAM ADM</fullName>
            </value>
            <value>
                <fullName>SFAM Vendeur</fullName>
            </value>
            <value>
                <fullName>SFAM Manager</fullName>
            </value>
            <value>
                <fullName>SFAM Admin Produit</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Standard User</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserRole__c.field-meta.xml
<CustomField>
    <fullName>UserRole__c</fullName>
    <description>Role tel que défini dans Salesforce - Role as defined in Salesforce</description>
    <label>Utilisateur - Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Admin_Enseigne</fullName>
                <label>Admin Enseigne</label>
            </value>
            <value>
                <fullName>Direction_ADM</fullName>
                <label>Direction ADM</label>
            </value>
            <value>
                <fullName>Direction_Back_up</fullName>
                <label>Direction Back-up</label>
            </value>
            <value>
                <fullName>Direction_Exp_dition</fullName>
                <label>Direction Expédition</label>
            </value>
            <value>
                <fullName>Direction_Expertise_SAV_suite_change</fullName>
                <label>Direction Expertise - SAV suite à échange</label>
            </value>
            <value>
                <fullName>Direction_Gestion_Sinistre</fullName>
                <label>Direction Gestion Sinistre</label>
            </value>
            <value>
                <fullName>Direction_GS_Qualit</fullName>
                <label>Direction GS Qualité</label>
            </value>
            <value>
                <fullName>Direction_Logistique</fullName>
                <label>Direction Logistique</label>
            </value>
            <value>
                <fullName>Direction_R_ception_colis</fullName>
                <label>Direction Réception colis</label>
            </value>
            <value>
                <fullName>Direction_R_paration</fullName>
                <label>Direction Réparation</label>
            </value>
            <value>
                <fullName>Direction_R_paration_ADM</fullName>
                <label>Direction Réparation ADM</label>
            </value>
            <value>
                <fullName>Direction_TC_Qualit</fullName>
                <label>Direction TC Qualité</label>
            </value>
            <value>
                <fullName>Direction_Teleconseiller_Sinistre</fullName>
                <label>Direction Téléconseiller Sinistre</label>
            </value>
            <value>
                <fullName>Equipe_1_ADM</fullName>
                <label>Equipe 1 ADM</label>
            </value>
            <value>
                <fullName>Equipe_1_Back_up</fullName>
                <label>Equipe 1 Back-up</label>
            </value>
            <value>
                <fullName>Equipe_1_Exp_dition</fullName>
                <label>Equipe 1 Expédition</label>
            </value>
            <value>
                <fullName>Equipe_1_EXP_SAV_suite_change</fullName>
                <label>Equipe 1 EXP - SAV suite à échange</label>
            </value>
            <value>
                <fullName>Equipe_1_GS</fullName>
                <label>Equipe 1 GS</label>
            </value>
            <value>
                <fullName>Equipe_1_GS_Qualit</fullName>
                <label>Equipe 1 GS Qualité</label>
            </value>
            <value>
                <fullName>Equipe_1_Logistique</fullName>
                <label>Equipe 1 Logistique</label>
            </value>
            <value>
                <fullName>Equipe_1_R_ception_colis</fullName>
                <label>Equipe 1 Réception colis</label>
            </value>
            <value>
                <fullName>Equipe_1_R_paration</fullName>
                <label>Equipe 1 Réparation</label>
            </value>
            <value>
                <fullName>Equipe_1_R_paration_ADM</fullName>
                <label>Equipe 1 Réparation ADM</label>
            </value>
            <value>
                <fullName>Equipe_1_TC</fullName>
                <label>Equipe 1 TC</label>
            </value>
            <value>
                <fullName>Equipe_1_TC_Qualit</fullName>
                <label>Equipe 1 TC Qualité</label>
            </value>
            <value>
                <fullName>Equipe_2_ADM</fullName>
                <label>Equipe 2 ADM</label>
            </value>
            <value>
                <fullName>Equipe_2_Back_up</fullName>
                <label>Equipe 2 Back-up</label>
            </value>
            <value>
                <fullName>Equipe_2_Exp_dition</fullName>
                <label>Equipe 2 Expédition</label>
            </value>
            <value>
                <fullName>Equipe_2_EXP_SAV_suite_change</fullName>
                <label>Equipe 2 EXP - SAV suite à échange</label>
            </value>
            <value>
                <fullName>Equipe_2_GS</fullName>
                <label>Equipe 2 GS</label>
            </value>
            <value>
                <fullName>Vendeur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/User/fields/BusinessProfile__c.field-meta.xml
<CustomField>
    <fullName>BusinessProfile__c</fullName>
    <description>Profil métier - User&apos;s business profile</description>
    <label>Profil métier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UserBusinessProfile</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/classes/UserTriggerHandlerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 27/08/2020
* @description User test class
* @Object User
*/

@isTest
public class UserTriggerHandlerTest {
    
    /***
    * @description Check the username before insert
    * @see checkUsernameBeforeInsert
    */
    @isTest
    public static void checkUsernameBeforeInsertTest(){
        
        //replace Community Plus License by Community License >
        //id passLocProfileId = [SELECT Id FROM Profile WHERE Name = 'Passloc Customer community Plus Login User'].id;
        id passLocProfileId = [SELECT Id FROM Profile WHERE Name = 'Passloc Customer community Login User'].id;
        // <
        
        // Create an account and a contact
        Account a = TestFactory.createClient();
        insert a;        
        Contact c = [SELECT id FROM Contact WHERE AccountId =: a.id];
        
        // Create a user
        User u = TestFactory.createUser();
        u.ProfileId = passLocProfileId;
        u.ContactId = c.id;
        u.username = 'michael.jockson@123.com';
        insert u;
        
        u = [SELECT id, username FROM User WHERE id =: u.id];
        system.assert(u.username == 'michael.jockson@123.com');
        
        // Create another account + contact + user
        Account a1 = TestFactory.createClient();
        insert a1;        
        Contact c1 = [SELECT id FROM Contact WHERE AccountId =: a1.id];
        
        User u1 = TestFactory.createUser();
        u1.ProfileId = passLocProfileId;
        u1.ContactId = c1.id;
        u1.username = 'michael.jockson@123.com';
        insert u1;
        
        u1 = [SELECT username FROM User WHERE id =: u1.id];
        system.assertEquals('michael.jockson@123.comdup', u1.username, 
                           'The username shouldve been changed - This is wrong');
        
        // Create another account + contact + user
        Account a2 = TestFactory.createClient();
        insert a2;        
        Contact c2 = [SELECT id FROM Contact WHERE AccountId =: a2.id];
        
        User u2 = TestFactory.createUser();
        u2.ProfileId = passLocProfileId;
        u2.ContactId = c2.id;
        u2.username = 'michael.jockson@123.com';
        insert u2;
        
        u2 = [SELECT username FROM User WHERE id =: u2.id];
        system.assertEquals('michael.jockson@123.comdupdup', u2.username, 
                           'The username shouldve been changed - This is wrong');
    }
    
    /***
    * @description Check the username before insert
    * @see checkUsernameBeforeInsert
    */
    @isTest
    public static void updateUserPermissionOnInsert(){
        
        // Create two SFAMConfig 
        SFAMConfig__c c = new SFAMConfig__c();
        c.UserBusinessProfile__c = 'DirectionQualiteSinistre';
        c.UserProfile__c = 'SFAM Stock';
        c.UserRole__c = 'Admin_Enseigne';
        c.UserPermissionSet__c = 'PS_GSIN_Manager';
        
        SFAMConfig__c s = new SFAMConfig__c();
        s.UserBusinessProfile__c = 'ManagerTCQualite';
        s.UserProfile__c = 'SFAM Stock';
        s.UserRole__c = 'Vendeur';
        s.UserPermissionSet__c = 'PS_GSIN_Manager';
        
        List<SFAMConfig__c> listConfig = new List<SFAMConfig__c>{c, s};
        insert listConfig;
        
        // Create a user
        User u = TestFactory.createUser();
        u.ProfileId = [SELECT Id FROM Profile WHERE Name = 'SFAM Stock'].id;
        u.username = 'michael.jockson@123.com';
        u.BusinessProfile__c = 'DirectionQualiteSinistre';
        Test.startTest();
        insert u;
        Test.stopTest();
        
        u = [SELECT id, profileId, userRoleId FROM User WHERE id =: u.id];
        system.assertEquals([SELECT Id FROM Profile WHERE Name = 'SFAM Stock'].id, 
                            u.profileId, 
                           'The profile id shouldve been udpated - This is wrong');
        system.assertEquals([SELECT Id FROM UserRole WHERE DeveloperName = 'Admin_Enseigne'].id, 
                            u.userRoleId, 
                           'The role id shouldve been udpated - This is wrong');
        
        system.assertEquals([SELECT PermissionSetId 
                             FROM PermissionSetAssignment 
                             WHERE AssigneeId =: u.id
                             AND PermissionSet.Name = 'PS_GSIN_Manager'].PermissionSetId, 
                            [SELECT id FROM PermissionSet WHERE Name = 'PS_GSIN_Manager'].id, 
                            'The permission set id shouldve been udpated - This is wrong');
    }
}