hubSide/force-app/main/default/objects/SFAMConfig__c/SFAMConfig__c.object-meta.xml
<CustomObject>
    <description>Custom object defining the permission / profile / role to assign to a user when created.</description>
    <label>Config SFAM</label>
    <nameField>
        <label>Config SFAM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configs SFAM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserBusinessProfile__c.field-meta.xml
<CustomField>
    <fullName>UserBusinessProfile__c</fullName>
    <description>Profil métier - User&apos;s business profile</description>
    <label>Utilisateur - Profil métier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UserBusinessProfile</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserPermissionSetId__c.field-meta.xml
<CustomField>
    <fullName>UserPermissionSetId__c</fullName>
    <description>Id de la permission set assignée à l&apos;utilisateur - User&apos;s Salesforce permission set id</description>
    <label>Utilisateur - Permission set id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserProfileId__c.field-meta.xml
<CustomField>
    <fullName>UserProfileId__c</fullName>
    <description>Id Salesforce du profil utilisateur - User&apos;s Salesforce profile id</description>
    <label>Utilisateur - Id profil</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserRoleId__c.field-meta.xml
<CustomField>
    <fullName>UserRoleId__c</fullName>
    <description>Id du role utilisateur - Salesforce role id</description>
    <label>Utilisateur - Id Role</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/User/fields/BusinessProfile__c.field-meta.xml
<CustomField>
    <fullName>BusinessProfile__c</fullName>
    <description>Profil métier - User&apos;s business profile</description>
    <label>Profil métier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UserBusinessProfile</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/classes/UserTriggerHelper.cls
/***
* @author Ariane Tanguy (GFI)
* @date 27/08/2020
* @description Helper class for UserTrigger
*/

public class UserTriggerHelper {
    
    /***
	* @description Get all already used email / username
	* @param newUserList - list of user
	* @return Set<String>
	*/
    public static Set<String> getAlreadyUsedUsername(List<User> newUserList){
        
        // List of created username
        Set<String> newUsernameSet = new Set<String>();
        for(User u : newUserList){
            newUsernameSet.add(u.Username + '%');
        }
        
        // Check whether those usernames aren't already taken
        List<User> alreadyCreatedUser = [SELECT id, Username
                                         FROM User
                                         WHERE Username LIKE: newUsernameSet];
        
        Set<String> alreadyUsedUsername = new Set<String>();
        for(User u : alreadyCreatedUser){
            alreadyUsedUsername.add(u.username);
        }
        
        return alreadyUsedUsername;
    }
    
    /***
	* @description Get the related custom metadata
	* @param newUserList - list of user
	* @return Map<String, List<SFAMConfig__c>>
	*/
    public static Map<String, SFAMConfig__c> getRelatedConfigSFAM(List<User> newUserList){
        
        // List of created username
        Set<String> businessProfileSet = new Set<String>();
        for(User u : newUserList){
            businessProfileSet.add(u.BusinessProfile__c);
        }
        
        // Check whether those usernames aren't already taken
        Map<String, SFAMConfig__c> userPermissionMap = new Map<String, SFAMConfig__c>();
        if(businessProfileSet.size() > 0){
            List<SFAMConfig__c> relatedPermissionList = [SELECT id, 
                                                         UserBusinessProfile__c, 
                                                         UserProfileId__c, UserRoleId__c, UserPermissionSetId__c  
                                                         FROM SFAMConfig__c
                                                         WHERE UserBusinessProfile__c IN: businessProfileSet];
            
            // Map the custom permission to their business profile
            for(SFAMConfig__c c : relatedPermissionList){
                userPermissionMap.put(c.UserBusinessProfile__c, c);
            }
        }
        
        return userPermissionMap;
    }
}