hubSide/force-app/main/default/objects/SFAMConfig__c/SFAMConfig__c.object-meta.xml
<CustomObject>
    <description>Custom object defining the permission / profile / role to assign to a user when created.</description>
    <label>Config SFAM</label>
    <nameField>
        <label>Config SFAM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configs SFAM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserPermissionSet__c.field-meta.xml
<CustomField>
    <fullName>UserPermissionSet__c</fullName>
    <description>Permission set tel que défini dans Salesforce - Permission Set as defined in Salesforce</description>
    <label>Utilisateur - Permission set</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>API_Only</fullName>
            </value>
            <value>
                <fullName>cases_Permisssion_Set</fullName>
            </value>
            <value>
                <fullName>ManagerDirectionLogistique</fullName>
            </value>
            <value>
                <fullName>PS_ADM_agent</fullName>
            </value>
            <value>
                <fullName>PS_ADM_Manager</fullName>
            </value>
            <value>
                <fullName>PS_Back_Agent</fullName>
            </value>
            <value>
                <fullName>PS_Back_Manager</fullName>
            </value>
            <value>
                <fullName>PS_Direction_QualiteSinistre</fullName>
            </value>
            <value>
                <fullName>PS_FEA_ReportDsh</fullName>
            </value>
            <value>
                <fullName>PS_GSIN_Gestionnaire</fullName>
            </value>
            <value>
                <fullName>PS_GSIN_Manager</fullName>
            </value>
            <value>
                <fullName>PS_LOG_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXP_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXP_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXPD_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_LOG_EXPD_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_LOG_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_LOG_REC</fullName>
            </value>
            <value>
                <fullName>PS_ManagerGSQualite</fullName>
            </value>
            <value>
                <fullName>PS_REP_ADM_AGENT</fullName>
            </value>
            <value>
                <fullName>PS_REP_ADM_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_REP_MANAGER</fullName>
            </value>
            <value>
                <fullName>PS_TCSIN_MANAGER</fullName>
            </value>
            <value>
                <fullName>SFAM_creation_Produit</fullName>
            </value>
            <value>
                <fullName>SFAM_Read_Only</fullName>
            </value>
            <value>
                <fullName>SFAMGestionnaireJuridique</fullName>
            </value>
            <value>
                <fullName>SFAMManagerQualite</fullName>
            </value>
            <value>
                <fullName>SFAMTCQualite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserPermissionSetId__c.field-meta.xml
<CustomField>
    <fullName>UserPermissionSetId__c</fullName>
    <description>Id de la permission set assignée à l&apos;utilisateur - User&apos;s Salesforce permission set id</description>
    <label>Utilisateur - Permission set id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserProfile__c.field-meta.xml
<CustomField>
    <fullName>UserProfile__c</fullName>
    <description>Profil tel que défini dans salesforce - Profile as defined in Salesforce</description>
    <label>Utilisateur - Profil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SFAM Expertise</fullName>
            </value>
            <value>
                <fullName>SFAM Stock</fullName>
            </value>
            <value>
                <fullName>SFAM Reparation</fullName>
            </value>
            <value>
                <fullName>SFAM Logistique</fullName>
            </value>
            <value>
                <fullName>SFAM API</fullName>
            </value>
            <value>
                <fullName>SFAM GS</fullName>
            </value>
            <value>
                <fullName>SFAM Qualite</fullName>
            </value>
            <value>
                <fullName>SFAM TC</fullName>
            </value>
            <value>
                <fullName>SFAM Vendeur TC</fullName>
            </value>
            <value>
                <fullName>Profil TC</fullName>
            </value>
            <value>
                <fullName>Profil GS</fullName>
            </value>
            <value>
                <fullName>SFAM ADM</fullName>
            </value>
            <value>
                <fullName>SFAM Vendeur</fullName>
            </value>
            <value>
                <fullName>SFAM Manager</fullName>
            </value>
            <value>
                <fullName>SFAM Admin Produit</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Standard User</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserProfileId__c.field-meta.xml
<CustomField>
    <fullName>UserProfileId__c</fullName>
    <description>Id Salesforce du profil utilisateur - User&apos;s Salesforce profile id</description>
    <label>Utilisateur - Id profil</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserRole__c.field-meta.xml
<CustomField>
    <fullName>UserRole__c</fullName>
    <description>Role tel que défini dans Salesforce - Role as defined in Salesforce</description>
    <label>Utilisateur - Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Admin_Enseigne</fullName>
                <label>Admin Enseigne</label>
            </value>
            <value>
                <fullName>Direction_ADM</fullName>
                <label>Direction ADM</label>
            </value>
            <value>
                <fullName>Direction_Back_up</fullName>
                <label>Direction Back-up</label>
            </value>
            <value>
                <fullName>Direction_Exp_dition</fullName>
                <label>Direction Expédition</label>
            </value>
            <value>
                <fullName>Direction_Expertise_SAV_suite_change</fullName>
                <label>Direction Expertise - SAV suite à échange</label>
            </value>
            <value>
                <fullName>Direction_Gestion_Sinistre</fullName>
                <label>Direction Gestion Sinistre</label>
            </value>
            <value>
                <fullName>Direction_GS_Qualit</fullName>
                <label>Direction GS Qualité</label>
            </value>
            <value>
                <fullName>Direction_Logistique</fullName>
                <label>Direction Logistique</label>
            </value>
            <value>
                <fullName>Direction_R_ception_colis</fullName>
                <label>Direction Réception colis</label>
            </value>
            <value>
                <fullName>Direction_R_paration</fullName>
                <label>Direction Réparation</label>
            </value>
            <value>
                <fullName>Direction_R_paration_ADM</fullName>
                <label>Direction Réparation ADM</label>
            </value>
            <value>
                <fullName>Direction_TC_Qualit</fullName>
                <label>Direction TC Qualité</label>
            </value>
            <value>
                <fullName>Direction_Teleconseiller_Sinistre</fullName>
                <label>Direction Téléconseiller Sinistre</label>
            </value>
            <value>
                <fullName>Equipe_1_ADM</fullName>
                <label>Equipe 1 ADM</label>
            </value>
            <value>
                <fullName>Equipe_1_Back_up</fullName>
                <label>Equipe 1 Back-up</label>
            </value>
            <value>
                <fullName>Equipe_1_Exp_dition</fullName>
                <label>Equipe 1 Expédition</label>
            </value>
            <value>
                <fullName>Equipe_1_EXP_SAV_suite_change</fullName>
                <label>Equipe 1 EXP - SAV suite à échange</label>
            </value>
            <value>
                <fullName>Equipe_1_GS</fullName>
                <label>Equipe 1 GS</label>
            </value>
            <value>
                <fullName>Equipe_1_GS_Qualit</fullName>
                <label>Equipe 1 GS Qualité</label>
            </value>
            <value>
                <fullName>Equipe_1_Logistique</fullName>
                <label>Equipe 1 Logistique</label>
            </value>
            <value>
                <fullName>Equipe_1_R_ception_colis</fullName>
                <label>Equipe 1 Réception colis</label>
            </value>
            <value>
                <fullName>Equipe_1_R_paration</fullName>
                <label>Equipe 1 Réparation</label>
            </value>
            <value>
                <fullName>Equipe_1_R_paration_ADM</fullName>
                <label>Equipe 1 Réparation ADM</label>
            </value>
            <value>
                <fullName>Equipe_1_TC</fullName>
                <label>Equipe 1 TC</label>
            </value>
            <value>
                <fullName>Equipe_1_TC_Qualit</fullName>
                <label>Equipe 1 TC Qualité</label>
            </value>
            <value>
                <fullName>Equipe_2_ADM</fullName>
                <label>Equipe 2 ADM</label>
            </value>
            <value>
                <fullName>Equipe_2_Back_up</fullName>
                <label>Equipe 2 Back-up</label>
            </value>
            <value>
                <fullName>Equipe_2_Exp_dition</fullName>
                <label>Equipe 2 Expédition</label>
            </value>
            <value>
                <fullName>Equipe_2_EXP_SAV_suite_change</fullName>
                <label>Equipe 2 EXP - SAV suite à échange</label>
            </value>
            <value>
                <fullName>Equipe_2_GS</fullName>
                <label>Equipe 2 GS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserRoleId__c.field-meta.xml
<CustomField>
    <fullName>UserRoleId__c</fullName>
    <description>Id du role utilisateur - Salesforce role id</description>
    <label>Utilisateur - Id Role</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/classes/SFAMConfigTriggerHandler.cls
/***
* @author Ariane Tanguy (GFI)
* @date 31/03/2021
* @description Handler class for SFAMConfigTrigger
*/

public class SFAMConfigTriggerHandler {
    
    /***
	* @description Update permission ids on insert
	* @param newConfigList - list of new config
	* @param relatedProfileMap - map of related profile
	* @param relatedRoleMap - map of related role
	* @param relatedPermSetMap - map of related permission set
	* @return NA
	*/
    public static void updatePermissionIdOnInsert(List<SFAMConfig__c> newConfigList, 
                                                  Map<String, Profile> relatedProfileMap, 
                                                  Map<String, UserRole> relatedRoleMap, 
                                                  Map<String, PermissionSet> relatedPermSetMap){
        
        // Loop through the config
        for(SFAMConfig__c c : newConfigList){
            
            // Update the profile
            if(c.UserProfile__c != NULL
               && relatedProfileMap.keySet().contains(c.UserProfile__c)){
                   c.UserProfileId__c = relatedProfileMap.get(c.UserProfile__c).id;
               }
            
            // Update the role
            if(c.UserRole__c != NULL
               && relatedRoleMap.keySet().contains(c.UserRole__c)){
                   c.UserRoleId__c = relatedRoleMap.get(c.UserRole__c).id;
               }
            
            // Update the permission set
            if(c.UserPermissionSet__c != NULL){
                
                // If there is more than one permission set
                List<String> permissionList = c.UserPermissionSet__c.contains(';') ? 
                       c.UserPermissionSet__c.split(';') : new List<String>{c.UserPermissionSet__c};
                
                c.UserPermissionSetId__c = '';
                for(String s : permissionList){
                    if(relatedPermSetMap.keySet().contains(s)){
                        c.UserPermissionSetId__c += relatedPermSetMap.get(s).id + ';';
                    }
                }
                c.UserPermissionSetId__c = c.UserPermissionSetId__c.Substring(0, c.UserPermissionSetId__c.length() - 1);
            }
        }
    }
    
    /***
	* @description Update permission ids on insert
	* @param newConfigList - list of new config
	* @param oldConfigMap - map of old config
	* @param relatedProfileMap - map of related profile
	* @param relatedRoleMap - map of related role
	* @param relatedPermSetMap - map of related permission set
	* @return NA
	*/
    public static void updatePermissionIdOnUpdate(List<SFAMConfig__c> newConfigList, 
                                                  Map<id, SFAMConfig__c> oldConfigMap, 
                                                  Map<String, Profile> relatedProfileMap, 
                                                  Map<String, UserRole> relatedRoleMap, 
                                                  Map<String, PermissionSet> relatedPermSetMap){
        
        // Loop through the config
        for(SFAMConfig__c c : newConfigList){
            
            // Update the profile
            if(c.UserProfile__c != NULL
               && c.UserProfile__c != oldConfigMap.get(c.id).UserProfile__c
               && relatedProfileMap.keySet().contains(c.UserProfile__c)){
                   c.UserProfileId__c = relatedProfileMap.get(c.UserProfile__c).id;
               }
            
            // Update the role
            if(c.UserRole__c != NULL
               && c.UserRole__c != oldConfigMap.get(c.id).UserRole__c
               && relatedRoleMap.keySet().contains(c.UserRole__c)){
                   c.UserRoleId__c = relatedRoleMap.get(c.UserRole__c).id;
               }
            
            // Update the permission set
            if(c.UserPermissionSet__c != NULL
               && c.UserPermissionSet__c != oldConfigMap.get(c.id).UserPermissionSet__c){
                   
                   // If there is more than one permission set
                   List<String> permissionList = c.UserPermissionSet__c.contains(';') ? 
                       c.UserPermissionSet__c.split(';') : new List<String>{c.UserPermissionSet__c};
                
                   c.UserPermissionSetId__c = '';
                   for(String s : permissionList){
                       if(relatedPermSetMap.keySet().contains(s)){
                           c.UserPermissionSetId__c += relatedPermSetMap.get(s).id + ';';
                       }
                   }
                   c.UserPermissionSetId__c = c.UserPermissionSetId__c.Substring(0, c.UserPermissionSetId__c.length() - 1);
               }
        }
    }
}