hubSide/force-app/main/default/objects/Account/fields/Compte_test__c.field-meta.xml
<CustomField>
    <fullName>Compte_test__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Signifie si le compte est utilisé seulement pour le test, et n&apos;est pas à afficher sur la community</description>
    <label>Compte de test ?</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Account/fields/Enseigne__c.field-meta.xml
<CustomField>
    <fullName>Enseigne__c</fullName>
    <inlineHelpText>Nom de l’enseigne de rattachement</inlineHelpText>
    <label>Enseigne</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SFAM</fullName>
            </value>
            <value>
                <fullName>INDEP</fullName>
            </value>
            <value>
                <fullName>FNAC</fullName>
            </value>
            <value>
                <fullName>Darty</fullName>
            </value>
            <value>
                <fullName>MEDIA ONE</fullName>
            </value>
            <value>
                <fullName>DARTY FRANCHISE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Account/fields/Magasin_central__c.field-meta.xml
<CustomField>
    <fullName>Magasin_central__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Magasin central</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Account/recordTypes/Distributeur.recordType-meta.xml
<RecordType>
    <fullName>Distributeur</fullName>
    <active>true</active>
    <label>Distributeur location</label>
</RecordType>

hubSide/force-app/main/default/objects/Emprunt__c/Emprunt__c.object-meta.xml
<CustomObject>
    <label>Emprunt</label>
    <nameField>
        <displayFormat>EMP-{000000}</displayFormat>
        <label>Emprunt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emprunts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_retour_prevu__c.field-meta.xml
<CustomField>
    <fullName>Date_retour_prevu__c</fullName>
    <description>Date prévisionnelle de retour pour vérifier le nombre de jours possible et gérer les stocks glissants par la suite</description>
    <label>Date du retour prévu</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <description>Date d&apos;emprunt de l&apos;objet</description>
    <label>Date de sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Nombre_jours_depassement__c.field-meta.xml
<CustomField>
    <fullName>Nombre_jours_depassement__c</fullName>
    <formula>IF(
    Nombre_jours_imputes__c - Nombre_de_jours_consommation__c - Contrat__r.Code_formule__r.Nombre_jours_carence__c &gt; 0,
    Nombre_jours_imputes__c - Nombre_de_jours_consommation__c - Contrat__r.Code_formule__r.Nombre_jours_carence__c,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre de jours en dépassement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Produit_emprunte__c.field-meta.xml
<CustomField>
    <fullName>Produit_emprunte__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Produit emprunté</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2 OR 3 OR 4)</booleanFilter>
        <errorMessage>Le produit emprunté doit être disponible pour être sélectionné.</errorMessage>
        <filterItems>
            <field>Stock_produit__c.Statut__c</field>
            <operation>equals</operation>
            <value>En stock, Réservé, Sortie client</value>
        </filterItems>
        <filterItems>
            <field>Stock_produit__c.Emprunt_actuel__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Reservation_origine__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>$Source.Status__c</field>
            <operation>equals</operation>
            <value>Retour sans défaut, Retour avec défaut</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Stock_produit__c</referenceTo>
    <relationshipLabel>Emprunts</relationshipLabel>
    <relationshipName>Emprunts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En magasin</fullName>
                <default>true</default>
                <label>En magasin</label>
            </value>
            <value>
                <fullName>Sortie</fullName>
            </value>
            <value>
                <fullName>Retourné</fullName>
                <label>Retour sans défaut</label>
            </value>
            <value>
                <fullName>Retour avec défaut</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
                <isActive>false</isActive>
                <label>Annulé</label>
            </value>
            <value>
                <fullName>Label.Location_StatusEmprunt1</fullName>
                <isActive>false</isActive>
                <label>Label.Location_StatusEmprunt1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/recordTypes/Emprunt.recordType-meta.xml
<RecordType>
    <fullName>Emprunt</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet emprunt une fois créé</description>
    <label>Emprunt</label>
</RecordType>

hubSide/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Objets Réservés sur le web / en boutique</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Numero de reservation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Reservation__c/fields/Date_retrait__c.field-meta.xml
<CustomField>
    <fullName>Date_retrait__c</fullName>
    <description>Date de début d’emprunt</description>
    <label>Date de début de location souhaitée</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Duree_emprunt__c.field-meta.xml
<CustomField>
    <fullName>Duree_emprunt__c</fullName>
    <description>Nombre de jours de l&apos;emprunt</description>
    <label>Duree de l&apos;emprunt (jours)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Produit_reserve__c.field-meta.xml
<CustomField>
    <fullName>Produit_reserve__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Produit réservé</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Stock_produit__c.Statut__c</field>
            <operation>equals</operation>
            <value>En stock, Sortie client, Réservé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Stock_produit__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Réservé</fullName>
            </value>
            <value>
                <fullName>Réservation_convertie</fullName>
                <label>Réservation convertie</label>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>Pré-réservé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/recordTypes/Reservation.recordType-meta.xml
<RecordType>
    <fullName>Reservation</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet Reservation</description>
    <label>Reservation</label>
</RecordType>

hubSide/force-app/main/default/objects/Stock_produit__c/Stock_produit__c.object-meta.xml
<CustomObject>
    <label>Stock magasin</label>
    <nameField>
        <label>Stock magasin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks magasin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Code_distributeur_stock__c.field-meta.xml
<CustomField>
    <fullName>Code_distributeur_stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code distributeur stock</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Stock_produits</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <label>Date sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Produit location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks magasin</relationshipLabel>
    <relationshipName>Stock_produits</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En stock</fullName>
                <default>true</default>
                <label>En stock</label>
            </value>
            <value>
                <fullName>Sortie client</fullName>
            </value>
            <value>
                <fullName>A transférer</fullName>
            </value>
            <value>
                <fullName>Destocke</fullName>
                <label>Déstocké</label>
            </value>
            <value>
                <fullName>Réservé</fullName>
            </value>
            <value>
                <fullName>Recyclé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/classes/Flow_OnlineReservation.cls
/***
* @author Ariane Tanguy (GFI)
* @date 26/05/2020
* @description Lightning Component Controller
*/

public without sharing class Flow_OnlineReservation {
    
    /***
	* @description Retrieve all available stock - Reservation web
	* @param productId - Product2 id selected on the previous screen
	* @param dateRetrait - Date chosen
	* @param dureeLocation - Number of days
	* @return List<Id> - List of available stock
	*/
    @AuraEnabled
    public static List<Id> retrieveStock(Id productId, Date dateRetrait, Integer dureeLocation, String enseigne, Boolean livraisonDomicile, boolean getStock){
                
        system.debug('-- here productId ' + productId);
        system.debug('-- here dateRetrait ' + dateRetrait);
        system.debug('-- here dureeLocation ' + dureeLocation);
        system.debug('-- here enseigne ' + enseigne);
        system.debug('-- here livraisonDomicile ' + livraisonDomicile);
        system.debug('-- here getStock ' + getStock);
                
        // Get all the available stocks
        List<Stock_Produit__c> allStockList = new List<Stock_Produit__c>();
        
        if(enseigne == 'SFAM'){
            if(!livraisonDomicile){
                allStockList = [SELECT id, Code_distributeur_stock__c, 
                                Code_distributeur_stock__r.Compte_test__c
                                FROM Stock_Produit__c
                                WHERE Produit__c =: productId
                                AND Statut__c IN ('En stock', 'Sortie client', 'Réservé')
                                AND Code_distributeur_stock__r.Compte_test__c = FALSE
                                AND Code_distributeur_stock__r.Enseigne__c =: enseigne
                                AND Code_distributeur_stock__r.Magasin_central__c =: livraisonDomicile];
            } else {
                allStockList = [SELECT id, Code_distributeur_stock__c, 
                                Code_distributeur_stock__r.Compte_test__c
                                FROM Stock_Produit__c
                                WHERE Produit__c =: productId
                                AND Statut__c IN ('En stock', 'Sortie client', 'Réservé')
                                AND Code_distributeur_stock__r.Compte_test__c = FALSE
                                AND (Code_distributeur_stock__r.Enseigne__c =: enseigne
                                OR Code_distributeur_stock__r.Magasin_central__c =: livraisonDomicile)];
            }
        } else {
            allStockList = [SELECT id, Code_distributeur_stock__c, 
                            Code_distributeur_stock__r.Compte_test__c
                            FROM Stock_Produit__c
                            WHERE Produit__c =: productId
                            AND Statut__c IN ('En stock', 'Sortie client', 'Réservé')
                            AND Code_distributeur_stock__r.Compte_test__c = FALSE
                            AND Code_distributeur_stock__r.Magasin_central__c = TRUE];
        }
        
        // Get all the related emprunts 
        List<Emprunt__c> currentEmpruntList = [SELECT id, Date_sortie__c, Date_retour_prevu__c, 
                                               Produit_emprunte__c, Nombre_jours_depassement__c
                                               FROM Emprunt__c
                                               WHERE Status__c IN ('Sortie', 'En magasin')
                                               AND Produit_emprunte__c IN : allStockList
                                               AND Date_sortie__c != NULL
                                               AND Date_retour_prevu__c != NULL];
        
        // Map it to the stock id
        Map<Id, Emprunt__c> stockIdEmpruntMap = new Map<Id, Emprunt__c>();
        for(Emprunt__c e : currentEmpruntList){
            stockIdEmpruntMap.put(e.Produit_emprunte__c, e);
        }
        
        // And all the related reservations
        List<Reservation__c> plannedReservationList = [SELECT id, Date_retrait__c, Duree_emprunt__c, 
                                                       Produit_reserve__c
                                                       FROM Reservation__c
                                                       WHERE Status__c = 'Réservé'
                                                       AND Produit_reserve__c IN : allStockList
                                                       AND Date_retrait__c != NULL
                                                       AND Duree_emprunt__c != NULL];
        
        // Map it to the stock id
        Map<Id, List<Reservation__c>> stockIdReservationMap = new Map<Id, List<Reservation__c>>();
        for(Reservation__c r : plannedReservationList){
            if(!stockIdReservationMap.keySet().contains(r.Produit_reserve__c)){
                List<Reservation__c> tmpList = new List<Reservation__c>();
                stockIdReservationMap.put(r.Produit_reserve__c, tmpList);
            }
            stockIdReservationMap.get(r.Produit_reserve__c).add(r);
        }
        
        system.debug('--- here stockIdEmpruntMap ' + stockIdEmpruntMap);
        system.debug('--- here stockIdReservationMap ' + stockIdReservationMap);
        
        Date dateRetour = dateRetrait.addDays(dureeLocation);
        
        // Check them all
        List<id> availableStockId = new List<Id>();
        List<id> availableDistribId = new List<Id>();
        for(Stock_Produit__c s : allStockList){
                
            system.debug('--- here s ' + s);
            
            Id empruntStockId, reservationStockId;
            
            // -- EMPRUNT 
            // Check whether that particular stock is free from any emprunt
            if(!stockIdEmpruntMap.keySet().contains(s.id)){
                empruntStockId = s.Id;
            } else {
                // Otherwise, check the dates
                Emprunt__c e = stockIdEmpruntMap.get(s.id);
                system.debug('--- here e ' + e);
                
                // If there is already an emprunt, exit the current iteration
                if(UtilityClassHelper.compareDate(dateRetrait, dateRetour, e.Date_sortie__c, e.Date_retour_prevu__c) ||
                   e.Nombre_jours_depassement__c > 0){
                       continue;
                   } else {
                       empruntStockId = s.Id;
                   }
            }
            
            // -- RESERVATION
            // Check whether that particular stock is free from any reservation
            if(!stockIdReservationMap.keySet().contains(s.id) && 
               s.id == empruntStockId &&
               !availableStockId.contains(s.id)){
                   system.debug('--- here found ' + s.id);
                   availableStockId.add(s.id);
                   availableDistribId.add(s.Code_distributeur_stock__c);
                   
               } else {
                   // Otherwise, check the dates for ALL reservations
                   List<Reservation__c> resList = stockIdReservationMap.get(s.id);
                   for(Reservation__c r : resList){
                       
                       system.debug('--- here r ' + r);
                       
                       // If there is already a reservation, exit the reservation loop
                       if(UtilityClassHelper.compareDate(dateRetrait, dateRetour, r.Date_retrait__c, r.Date_retrait__c.addDays((integer)r.Duree_emprunt__c))){
                           reservationStockId = null;
                           break;
                       } else {
                           reservationStockId = s.id;
                       }
                   }
                   
                   // Check if both values are same
                   if(empruntStockId == reservationStockId && 
                      ! availableStockId.contains(s.id)){
                          system.debug('--- here found ' + s.id);
                          availableStockId.add(s.id);
                          availableDistribId.add(s.Code_distributeur_stock__c);
                      }
               }
        }
        
        // Handle the case where there is no stock available, but somehow a reservation needs to be created
        if(availableStockId.size() == 0 &&
           dateRetrait > system.today() + 30){
               availableStockId.add(allStockList[0].id);
               availableDistribId.add(allStockList[0].Code_distributeur_stock__c);
           }
        
        if(getStock && availableStockId.size() > 0)
            return availableStockId;
        if(!getStock && availableDistribId.size() > 0)
            return availableDistribId;
        
        return null;
    }
    
    /***
	* @description Return available distributeur for the user to choose from - Reservation web
	* @param stockIdList - available stock
	* @param distributeurId - Chosen distributeur
	* @return selectedId - stock id
	*/
    @AuraEnabled
    public static List<Object> getAllDistributeur(Id productId, Date dateRetrait, Integer dureeLocation, String enseigne, Boolean livraisonDomicile){
        
        List<id> distributeurIdList = retrieveStock(productId, dateRetrait, dureeLocation, enseigne, livraisonDomicile, false);
        
        system.debug('--- here distributeurIdList ' + distributeurIdList);
        
        // Get all distributeur related information
        List<Object> lstObj = new List<Object>();
        for(Account a : [SELECT Id, Name, ShippingPostalCode, ShippingCity
                         FROM Account
                         WHERE id IN :distributeurIdList 
                         AND Compte_test__c = FALSE]){
                             
                             Map<String, Object> mapOfres = new Map<String, Object>();
                             mapOfres.put('id', a.id);
                             mapOfres.put('name', a.Name);
                             mapOfres.put('city', '' + a.ShippingPostalCode + ' - ' + a.ShippingCity);
                             
                             lstObj.add(mapOfres);
                         }
        
        system.debug('--- here lstObj ' + lstObj);
        return lstObj;
    }
    
    
    /***
	* @description Return one stock - Reservation web
	* @param stockIdList - available stock
	* @param distributeurId - Chosen distributeur
	* @return selectedId - stock id
	*/
    @AuraEnabled
    public static Id returnOneStockFromList(List<id> stockIdList, Id distributeurId){
        
        system.debug('--- here stockIdList ' + stockIdList);
        system.debug('--- here distributeurId ' + distributeurId);
                
        // Get all the stocks
        List<Stock_Produit__c> allStockList = [SELECT id 
                                               FROM Stock_Produit__c
                                               WHERE Id IN: stockIdList
                                               AND Code_distributeur_stock__c =: distributeurId
                                               AND Statut__c IN ('En stock', 'Sortie client', 'Réservé')];
        
        system.debug('--- here allStockList ' + allStockList);
        
        // Return the first id
        if(allStockList.size() > 0){
            return allStockList[0].id;
        }
        
        return null;
    }
    
    /***
	* @description Return one stock - Reservation en magasin
	* @param productId - Product2 id selected on the previous screen
	* @param dateRetrait - Date chosen
	* @param dureeLocation - Number of days
	* @param distributeurId - Chosen distributeur
	* @return selectedId - stock id
	*/
    @AuraEnabled
    public static Id returnOneStock(Id productId, Date dateRetrait, Integer dureeLocation, Id distributeurId, boolean isEmprunt){
        
        system.debug('--- here productId ' + productId);
        system.debug('--- here dateRetrait ' + dateRetrait);
        system.debug('--- here dureeLocation ' + dureeLocation);
        system.debug('--- here distributeurId ' + distributeurId);
        system.debug('--- here isEmprunt ' + isEmprunt);
        
        Date dateRetour = dateRetrait.addDays(dureeLocation);
                
        // Get all the available stocks
        List<Stock_Produit__c> allStockList = [SELECT id 
                                               FROM Stock_Produit__c
                                               WHERE Produit__c =: productId
                                               AND Code_distributeur_stock__c =: distributeurId
                                               AND Statut__c IN ('En stock', 'Sortie client', 'Réservé')];
        
        system.debug('--- here allStockList ' + allStockList);
        
        // Get all the related emprunts 
        List<Emprunt__c> currentEmpruntList = [SELECT id, Date_sortie__c, Date_retour_prevu__c, 
                                               Produit_emprunte__c, Nombre_jours_depassement__c
                                               FROM Emprunt__c
                                               WHERE Status__c IN ('Sortie', 'En magasin')
                                               AND Produit_emprunte__c IN : allStockList
                                               AND Date_sortie__c != NULL
                                               AND Date_retour_prevu__c != NULL];
        
        system.debug('--- here currentEmpruntList ' + currentEmpruntList);
        
        // Map it to the stock id
        Map<Id, Emprunt__c> stockIdEmpruntMap = new Map<Id, Emprunt__c>();
        for(Emprunt__c e : currentEmpruntList){
            stockIdEmpruntMap.put(e.Produit_emprunte__c, e);
        }
        
        // And all the related reservations
        List<Reservation__c> plannedReservationList = [SELECT id, Date_retrait__c, Duree_emprunt__c, 
                                                       Produit_reserve__c
                                                       FROM Reservation__c
                                                       WHERE Status__c = 'Réservé'
                                                       AND Produit_reserve__c IN : allStockList
                                                       AND Date_retrait__c != NULL
                                                       AND Duree_emprunt__c != NULL];
        
        system.debug('--- here plannedReservationList ' + plannedReservationList);
        
        // Map it to the stock id
        Map<Id, List<Reservation__c>> stockIdReservationMap = new Map<Id, List<Reservation__c>>();
        for(Reservation__c r : plannedReservationList){
            if(!stockIdReservationMap.keySet().contains(r.Produit_reserve__c)){
                List<Reservation__c> tmpList = new List<Reservation__c>();
                stockIdReservationMap.put(r.Produit_reserve__c, tmpList);
            }
            stockIdReservationMap.get(r.Produit_reserve__c).add(r);
        }
        
        // Quick check : is there a stock missing in both lists ? 
        for(Stock_Produit__c s : allStockList){
            if(stockIdEmpruntMap.get(s.id) == NULL &&
               stockIdReservationMap.get(s.id) == NULL){
                   system.debug('--- here quick win ' + s.id);
                   return s.id;
               }
        }
        
        // Too bad, the long check now
        for(Stock_Produit__c s : allStockList){
                
            system.debug('--- here s ' + s);
            
            Id empruntStockId, reservationStockId;
            
            // Check whether that particular stock is free from any emprunt
            if(!stockIdEmpruntMap.keySet().contains(s.id)){
                empruntStockId = s.Id;
            } else 
                // Only check the current emprunt if this is for a reservation
                if(isEmprunt == FALSE) {
                    
                    Emprunt__c e = stockIdEmpruntMap.get(s.id);
                    system.debug('--- here e ' + e);
                    
                    if(!UtilityClassHelper.compareDate(dateRetrait, dateRetour, e.Date_sortie__c, e.Date_retour_prevu__c) &&
                       e.Nombre_jours_depassement__c == 0){
                           empruntStockId = s.Id;
                       }
                }
            
            // Check whether that particular stock is free from any reservation
            if(!stockIdReservationMap.keySet().contains(s.id)){
                if(empruntStockId == s.id){
                    system.debug('--- here return ' + s.id);
                    return empruntStockId;
                }
            } else {
                List<Reservation__c> resList = stockIdReservationMap.get(s.id);
                for(Reservation__c r : resList){
                    
                    system.debug('--- here r ' + r);
                    
                    if(UtilityClassHelper.compareDate(dateRetrait, dateRetour, r.Date_retrait__c, r.Date_retrait__c.addDays((Integer)r.Duree_emprunt__c))){
                        reservationStockId = null; // here
                        break;
                    } else {
                        reservationStockId = s.id;
                    }
                }
                
                // Check if both values are same
                if(empruntStockId == reservationStockId && 
                   empruntStockId != null){
                       system.debug('--- here return ' + s.id);
                       return empruntStockId;
                   }
            }
        }
        
        system.debug('--- here return null');
        return null;
    }
    
}