hubSide/force-app/main/default/objects/Account/fields/Compte_test__c.field-meta.xml
<CustomField>
    <fullName>Compte_test__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Signifie si le compte est utilisé seulement pour le test, et n&apos;est pas à afficher sur la community</description>
    <label>Compte de test ?</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Account/recordTypes/Distributeur.recordType-meta.xml
<RecordType>
    <fullName>Distributeur</fullName>
    <active>true</active>
    <label>Distributeur location</label>
</RecordType>

hubSide/force-app/main/default/objects/Emprunt__c/Emprunt__c.object-meta.xml
<CustomObject>
    <label>Emprunt</label>
    <nameField>
        <displayFormat>EMP-{000000}</displayFormat>
        <label>Emprunt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emprunts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Caution_recue__c.field-meta.xml
<CustomField>
    <fullName>Caution_recue__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Caution reçue</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_retour_prevu__c.field-meta.xml
<CustomField>
    <fullName>Date_retour_prevu__c</fullName>
    <description>Date prévisionnelle de retour pour vérifier le nombre de jours possible et gérer les stocks glissants par la suite</description>
    <label>Date du retour prévu</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <description>Date d&apos;emprunt de l&apos;objet</description>
    <label>Date de sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Etat_sortie__c.field-meta.xml
<CustomField>
    <fullName>Etat_sortie__c</fullName>
    <label>Etat sortie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Heure_retour_prevue__c.field-meta.xml
<CustomField>
    <fullName>Heure_retour_prevue__c</fullName>
    <label>Heure de retour prevue</label>
    <type>Time</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Heure_sortie__c.field-meta.xml
<CustomField>
    <fullName>Heure_sortie__c</fullName>
    <description>Heure de sortie de l&apos;objet emprunté</description>
    <label>Heure de sortie</label>
    <type>Time</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Montant_caution_sortie__c.field-meta.xml
<CustomField>
    <fullName>Montant_caution_sortie__c</fullName>
    <description>Montant de la caution encaissée</description>
    <label>Montant de la caution sortie</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Motif_annulation__c.field-meta.xml
<CustomField>
    <fullName>Motif_annulation__c</fullName>
    <label>Motif de l&apos;annulation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En magasin</fullName>
                <default>true</default>
                <label>En magasin</label>
            </value>
            <value>
                <fullName>Sortie</fullName>
            </value>
            <value>
                <fullName>Retourné</fullName>
                <label>Retour sans défaut</label>
            </value>
            <value>
                <fullName>Retour avec défaut</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
                <isActive>false</isActive>
                <label>Annulé</label>
            </value>
            <value>
                <fullName>Label.Location_StatusEmprunt1</fullName>
                <isActive>false</isActive>
                <label>Label.Location_StatusEmprunt1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/recordTypes/Emprunt.recordType-meta.xml
<RecordType>
    <fullName>Emprunt</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet emprunt une fois créé</description>
    <label>Emprunt</label>
</RecordType>

hubSide/force-app/main/default/objects/Product2/fields/Disponibilite_stock__c.field-meta.xml
<CustomField>
    <fullName>Disponibilite_stock__c</fullName>
    <defaultValue>&apos;Votre produit n\&apos;est pas disponible actuellement.&apos;</defaultValue>
    <description>Affiche la disponibilité des stocks du produit en question.</description>
    <label>Disponibilité stock</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Objets Réservés sur le web / en boutique</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Numero de reservation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Reservation__c/fields/Date_retrait__c.field-meta.xml
<CustomField>
    <fullName>Date_retrait__c</fullName>
    <description>Date de début d’emprunt</description>
    <label>Date de début de location souhaitée</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Duree_emprunt__c.field-meta.xml
<CustomField>
    <fullName>Duree_emprunt__c</fullName>
    <description>Nombre de jours de l&apos;emprunt</description>
    <label>Duree de l&apos;emprunt (jours)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Motif_annulation__c.field-meta.xml
<CustomField>
    <fullName>Motif_annulation__c</fullName>
    <label>Motif de l&apos;annulation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Réservé</fullName>
            </value>
            <value>
                <fullName>Réservation_convertie</fullName>
                <label>Réservation convertie</label>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>Pré-réservé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/recordTypes/Reservation.recordType-meta.xml
<RecordType>
    <fullName>Reservation</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet Reservation</description>
    <label>Reservation</label>
</RecordType>

hubSide/force-app/main/default/objects/Stock_produit__c/Stock_produit__c.object-meta.xml
<CustomObject>
    <label>Stock magasin</label>
    <nameField>
        <label>Stock magasin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks magasin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Code_distributeur_stock__c.field-meta.xml
<CustomField>
    <fullName>Code_distributeur_stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code distributeur stock</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Stock_produits</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <label>Date sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Produit location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks magasin</relationshipLabel>
    <relationshipName>Stock_produits</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En stock</fullName>
                <default>true</default>
                <label>En stock</label>
            </value>
            <value>
                <fullName>Sortie client</fullName>
            </value>
            <value>
                <fullName>A transférer</fullName>
            </value>
            <value>
                <fullName>Destocke</fullName>
                <label>Déstocké</label>
            </value>
            <value>
                <fullName>Réservé</fullName>
            </value>
            <value>
                <fullName>Recyclé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/recordTypes/Stock_non_empruntable.recordType-meta.xml
<RecordType>
    <fullName>Stock_non_empruntable</fullName>
    <active>true</active>
    <description>Stock déjà emprunté,</description>
    <label>Stock non empruntable</label>
</RecordType>

hubSide/force-app/main/default/objects/Stock_produit__c/recordTypes/Stock_produit.recordType-meta.xml
<RecordType>
    <fullName>Stock_produit</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet Stock produit une fois créé</description>
    <label>Stock produit</label>
</RecordType>

hubSide/force-app/main/default/classes/StockProduitTriggerHandlerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 11/06/2020
* @description StockMagasin test class
* @Object Stock_Produit__c
*/

@isTest
public class StockProduitTriggerHandlerTest {
    
    /***
    * @description Update the record type on stock creation
    * @see updateRecordTypeOnCreation
    */
    @isTest
    public static void updateRecordTypeOnCreationTest(){
        
        // Create a stock
        Stock_Produit__c s = TestFactory.createStock();
        insert s;
        
        // Query product and check whether the record type has been correctly updated
        s = [SELECT id, Name, RecordType.DeveloperName FROM Stock_Produit__c WHERE id =: s.id];
        
        system.assertEquals(s.RecordType.DeveloperName, 'Stock_produit', 
                            'The record type should have been updated on the stock - This is wrong');
    }
    
    /***
    * @description Update the record type on stock update
    * @see updateRecordTypeOnUpdate
	*/
    @isTest
    public static void updateRecordTypeOnUpdateTest(){
        
        // Create a stock
        Stock_Produit__c s = TestFactory.createStock();
        insert s;
        
        s.Statut__c = 'Sortie client';
        update s;
        
        // Query product and check whether the record type has been correctly updated
        s = [SELECT id, Name, RecordType.DeveloperName FROM Stock_Produit__c WHERE id =: s.id];
        
        system.assertEquals(s.RecordType.DeveloperName, 'Stock_non_empruntable', 
                            'The record type should have been updated on the stock - This is wrong');
        
        s.Statut__c = 'En stock';
        update s;
        
        // Query product and check whether the record type has been correctly updated
        s = [SELECT id, Name, RecordType.DeveloperName FROM Stock_Produit__c WHERE id =: s.id];
        
        system.assertEquals(s.RecordType.DeveloperName, 'Stock_produit', 
                            'The record type should have been updated again on the stock - This is wrong');
    }
    
    /***
    * @description Update the product availability
    * @see updateRelatedProductAvailability
    */
    @isTest
    public static void updateRelatedProductAvailabilityTest(){
        
        // Create a distributeur
        Account a = TestFactory.createDistributeur();
        a.Name = 'Magasin';
        a.Compte_test__c = FALSE;
        insert a;
        
        // Create a stock
        Stock_Produit__c s = TestFactory.createStock();
        s.Code_distributeur_stock__c = a.id;
        insert s;
        
        Product2 p = [SELECT id, Disponibilite_stock__c FROM Product2 WHERE id =: s.Produit__c];
        system.assertEquals('Magasin : Votre produit est disponible.', p.Disponibilite_stock__c, 
                            'The product availability shouldve been initiated - This is wrong');
        
        // Create a reservation
        Reservation__c r = TestFactory.createReservation(s);
        r.Date_retrait__c = system.today() + 3;
        r.Duree_emprunt__c = 1;
        insert r;
        
        p = [SELECT id, Disponibilite_stock__c FROM Product2 WHERE id =: s.Produit__c];
        system.assertEquals('Magasin : Votre produit est disponible jusqu\'au ' + 
                            UtilityClassHelper.formatDate(r.Date_retrait__c), p.Disponibilite_stock__c, 
                            'The product availability shouldve been updated - This is wrong');
        
        Test.startTest();
        
        // Create an asset
        Asset c = TestFactory.createContract();
        insert c;
        
        // Create an emprunt
        Emprunt__c e = TestFactory.createEmprunt(c, s);
        e.Date_sortie__c = system.today();
        e.Date_retour_prevu__c = system.today() + 2;
        insert e;
        
        // Take it out
        e.Heure_sortie__c = system.now().time();
        e.Heure_retour_prevue__c = system.now().time();
        e.Etat_sortie__c = 'Neuf';
        e.Montant_caution_sortie__c = 100;
        e.Caution_recue__c = true;
        update e;
        
        // Check the related product
        p = [SELECT id, Disponibilite_stock__c FROM Product2 WHERE id =: s.Produit__c];
        system.assertEquals('Magasin : Votre produit est disponible à partir du ' + 
                            UtilityClassHelper.formatDate(e.Date_retour_prevu__c) + 
                            ' et jusqu\'au ' + 
                            UtilityClassHelper.formatDate(r.Date_retrait__c), p.Disponibilite_stock__c, 
                            'The product availability shouldve been updated - This is wrong');
        
        // Cancel the reservation
        r.Status__c = 'Annulé';
        r.Motif_annulation__c = 'Test casualty';
        update r;
        
        // Check the related product
        p = [SELECT id, Disponibilite_stock__c FROM Product2 WHERE id =: s.Produit__c];
        system.assertEquals('Magasin : Votre produit est disponible à partir du ' + 
                            UtilityClassHelper.formatDate(e.Date_retour_prevu__c), p.Disponibilite_stock__c, 
                            'The product availability shouldve been again updated - This is wrong');
        
        Test.stopTest();
    }
    
    /***
    * @description Update the product availability
    * @see updateRelatedProductAvailability
    */
    @isTest
    public static void updateRelatedProductAvailabilityTest_fakeDistributeur(){
        
        // Create a distributeur
        Account a = TestFactory.createDistributeur();
        a.Name = 'Magasin';
        a.Compte_test__c = FALSE;
        insert a;
        
        // Create another distributeur
        Account a1 = TestFactory.createDistributeur();
        a1.Name = 'FakeMagasin';
        a1.Compte_test__c = TRUE;
        insert a1;
        
        // Create a stock
        Stock_Produit__c s = TestFactory.createStock();
        s.Code_distributeur_stock__c = a.id;
        insert s;
        
        Product2 p = [SELECT id, Disponibilite_stock__c FROM Product2 WHERE id =: s.Produit__c];
        system.assertEquals('Magasin : Votre produit est disponible.', p.Disponibilite_stock__c, 
                            'The product availability shouldve been initiated - This is wrong');
        
        // Create another stock
        Stock_Produit__c s1 = TestFactory.createStock(s.Produit__c);
        s1.Code_distributeur_stock__c = a1.id;
        insert s1;
        
        p = [SELECT id, Disponibilite_stock__c FROM Product2 WHERE id =: s.Produit__c];
        system.assertEquals('Magasin : Votre produit est disponible.', p.Disponibilite_stock__c, 
                            'The product availability shouldve stayed the same - This is wrong');
        
        // Create again another stock
        Stock_Produit__c s2 = TestFactory.createStock(s.Produit__c);
        s2.Code_distributeur_stock__c = a.id;
        insert s2;
        
        p = [SELECT id, Disponibilite_stock__c FROM Product2 WHERE id =: s.Produit__c];
        system.assertEquals('Magasin : Votre produit est disponible.', p.Disponibilite_stock__c, 
                            'The product availability shouldve stayed the same - This is wrong');
    }
}