hubSide/force-app/main/default/objects/Account/fields/Compte_test__c.field-meta.xml
<CustomField>
    <fullName>Compte_test__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Signifie si le compte est utilisé seulement pour le test, et n&apos;est pas à afficher sur la community</description>
    <label>Compte de test ?</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Account/fields/Proprietaire_stock__c.field-meta.xml
<CustomField>
    <fullName>Proprietaire_stock__c</fullName>
    <description>Liste permettant de savoir si le distributeur possède un stock</description>
    <label>Propriétaire du stock</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non propriétaire du stock</fullName>
            </value>
            <value>
                <fullName>Propriétaire du stock</fullName>
            </value>
            <value>
                <fullName>Mixte</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Account/recordTypes/Distributeur.recordType-meta.xml
<RecordType>
    <fullName>Distributeur</fullName>
    <active>true</active>
    <label>Distributeur location</label>
</RecordType>

hubSide/force-app/main/default/objects/Product2/fields/Disponibilite_stock__c.field-meta.xml
<CustomField>
    <fullName>Disponibilite_stock__c</fullName>
    <defaultValue>&apos;Votre produit n\&apos;est pas disponible actuellement.&apos;</defaultValue>
    <description>Affiche la disponibilité des stocks du produit en question.</description>
    <label>Disponibilité stock</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Numero_serie__c.field-meta.xml
<CustomField>
    <fullName>Numero_serie__c</fullName>
    <label>Numero de serie</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Produit_avec_numero_de_serie__c.field-meta.xml
<CustomField>
    <fullName>Produit_avec_numero_de_serie__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Produit avec numéro de série ?</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/Stock_produit__c.object-meta.xml
<CustomObject>
    <label>Stock magasin</label>
    <nameField>
        <label>Stock magasin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks magasin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Code_distributeur_initial__c.field-meta.xml
<CustomField>
    <fullName>Code_distributeur_initial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code distributeur initial</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Stock_produits_DistribInitial</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Code_distributeur_stock__c.field-meta.xml
<CustomField>
    <fullName>Code_distributeur_stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code distributeur stock</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Stock_produits</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_retour__c.field-meta.xml
<CustomField>
    <fullName>Date_retour__c</fullName>
    <description>Date de retour de l&apos;emprunt actuel, si emprunt il y a.</description>
    <label>Date de retour</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_retrait_souhaitee__c.field-meta.xml
<CustomField>
    <fullName>Date_retrait_souhaitee__c</fullName>
    <description>Date de retrait souhaitée pour la réservation.</description>
    <label>Date de retrait souhaitée</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Numero_serie__c.field-meta.xml
<CustomField>
    <fullName>Numero_serie__c</fullName>
    <label>Numero de serie</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Numero_serie_genere__c.field-meta.xml
<CustomField>
    <fullName>Numero_serie_genere__c</fullName>
    <description>Dans le cas où le produit n&apos;a pas de numéro de série, crée un numéro de remplacement</description>
    <displayFormat>SER-{0000000}</displayFormat>
    <label>Numero de série généré</label>
    <type>AutoNumber</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Produit location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks magasin</relationshipLabel>
    <relationshipName>Stock_produits</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Proprietaire_Stock__c.field-meta.xml
<CustomField>
    <fullName>Proprietaire_Stock__c</fullName>
    <label>Proprietaire Stock</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Proprietaire_Stock</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En stock</fullName>
                <default>true</default>
                <label>En stock</label>
            </value>
            <value>
                <fullName>Sortie client</fullName>
            </value>
            <value>
                <fullName>A transférer</fullName>
            </value>
            <value>
                <fullName>Destocke</fullName>
                <label>Déstocké</label>
            </value>
            <value>
                <fullName>Réservé</fullName>
            </value>
            <value>
                <fullName>Recyclé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/User/fields/Distributeur_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Distributeur_de_reference__c</fullName>
    <description>ID ( SFDC 15 caractères ) du distributeur pour lequel travaille l&apos;employé</description>
    <label>Distributeur de reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Proprietaire_Stock.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Non propriétaire du stock</fullName>
    </customValue>
    <customValue>
        <fullName>Propriétaire du stock</fullName>
    </customValue>
    <customValue>
        <fullName>Mixte</fullName>
    </customValue>
    <masterLabel>Proprietaire Stock</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/StockProduitTriggerHandler.cls
/***
* @author Ariane Tanguy (GFI)
* @date 11/06/2020
* @description Handler class for StockMagasin
*/

public class StockProduitTriggerHandler {
    
    /***
	* @description Update the record type on stock creation
	* @param newStockList - list of all new stock
	* @param createdStockRecordType - stock record type id
	* @return NA
	*/
    public static void updateRecordTypeOnCreation(List<Stock_produit__c> newStockList, id createdStockRecordType){
        
        // For all new stocks
        for(Stock_produit__c s : newStockList){
            s.RecordTypeId = createdStockRecordType;
        }
    }
    
    /***
	* @description Update the record type on stock update
	* @param newStockList - list of all new stock
	* @param oldStockMap - map of old stock
	* @param createdStockRecordType - stock record type id
	* @param bookedStockRecordType - stock record type id without new emprunt button
	* @return NA
	*/
    public static void updateRecordTypeOnUpdate(List<Stock_produit__c> newStockList, 
                                                Map<id, Stock_produit__c> oldStockMap, 
                                                id createdStockRecordType, 
                                                id bookedStockRecordType){
                
        for(Stock_produit__c s : newStockList){
            
            // if the status becomes Sortie client
            if(s.Statut__c == 'Sortie client' && oldStockMap.get(s.id).Statut__c != 'Sortie client'){
                s.RecordTypeId = bookedStockRecordType;
            }
            
            // if the status is not Sortie client anymore
            if(s.Statut__c != 'Sortie client' && oldStockMap.get(s.id).Statut__c == 'Sortie client'){
                s.RecordTypeId = createdStockRecordType;
            }
        }
    }
    
    /***
	* @description Handle the before insert updates
	* @param newStockList - list of all new stock
	* @param u - related user info
	* @param relatedProductMap - related product map
	* @return NA
	*/
    public static void handleBeforeInsert(List<Stock_produit__c> newStockList, User u, Map<id, Product2> relatedProductMap){
        
        // For all new stocks
        for(Stock_produit__c s : newStockList){
            
            // Update distributeurs
            if(s.Code_distributeur_initial__c == NULL){
                s.Code_distributeur_initial__c = u.Distributeur_de_reference__c;
            }
            if(s.Code_distributeur_stock__c == NULL){
                s.Code_distributeur_stock__c = u.Distributeur_de_reference__c;
            }
            
            // Handle the numero de serie
            if(s.Numero_serie__c == NULL && 
               relatedProductMap.keySet().contains(s.Produit__c) &&
               relatedProductMap.get(s.Produit__c).Produit_avec_numero_de_serie__c == FALSE){
                   s.Numero_serie__c = s.Numero_serie_genere__c;
               }
            
            // Update the name
            if(relatedProductMap.keySet().contains(s.Produit__c)){
                s.Name = relatedProductMap.get(s.Produit__c).Name + ' - ' + s.Numero_serie__c;
            }
        }
    }
    
    /***
	* @description Handle the before insert updates - Part 2
	* @param newStockList - list of all new stock
	* @param distributeurMap - related distributeur map
	* @return NA
	*/
    public static void handleBeforeInsert(List<Stock_produit__c> newStockList, Map<id, Account> distributeurMap){
        
        // For all new stocks
        for(Stock_produit__c s : newStockList){
            
            // And the proprietaire stock
            if(distributeurMap.keySet().contains(s.Code_distributeur_stock__c)){
                s.Proprietaire_Stock__c = distributeurMap.get(s.Code_distributeur_stock__c).Proprietaire_stock__c;
            }
        }
    }
    
    /***
	* @description Update the related product on update
	* @param relatedProductMap - map of the related products
	* @param relatedStock - map od product id and related stock
	* @return NA
	*/
    public static void updateRelatedProductAvailability(List<Product2> relatedProductList, 
                                                        Map<id, List<Stock_Produit__c>> relatedStockMap, 
                                                        Map<id, Account> distributeurMap){
        
        // For all products, check whether the product is available, and in which store
        // Disponibilite_stock__c
        for(Product2 p : relatedProductList){
            
            if(relatedStockMap.keySet().contains(p.id)){
                
                // Map the stocks to their related distributeurs
                Map<String, List<Stock_Produit__c>> distribIdStockMap = new Map<String, List<Stock_Produit__c>>();
                for(Stock_Produit__c s : relatedStockMap.get(p.id)){
                    
                    String accName = s.Code_distributeur_stock__r.Name;
                    if(distributeurMap != NULL && 
                       distributeurMap.keySet().contains(s.Code_distributeur_stock__c)){
                           accName = distributeurMap.get(s.Code_distributeur_stock__c).Name;
                           
                           // Check whether the distributeur isn't a test one
                           if(distributeurMap.get(s.Code_distributeur_stock__c).Compte_test__c){
                               accName = NULL;
                           }
                       }
                    
                    if(accName == NULL){
                        continue;
                    }
                    
                    if(!distribIdStockMap.keySet().contains(accName)){
                        List<Stock_Produit__c> tmpList = new List<Stock_Produit__c>();
                        distribIdStockMap.put(accName, tmpList);
                    }
                    distribIdStockMap.get(accName).add(s);
                }
                
                system.debug('-- distribIdStockMap ' + distribIdStockMap);
                
                // Loop over the distributeurs
                Map<String, String> dispoStockMap = new Map<String, String>();
                for(String a : distribIdStockMap.keySet()){
                    
                    system.debug('-- a ' + a);
                    
                    // Check if the product is available for that distributeur
                    Date closestDateRetour = system.today() + 365;
                    Date furthestDateRetrait = system.today();
                    for(Stock_produit__c s : distribIdStockMap.get(a)){
                        
                        system.debug('-- s.Date_retour__c ' + s.Date_retour__c);
                        system.debug('-- s.Date_retrait_souhaitee__c ' + s.Date_retrait_souhaitee__c);
                        
                        // If there is a stock available right now
                        if(s.Date_retour__c == NULL && s.Date_retrait_souhaitee__c == NULL){
                            dispoStockMap.put(a, a + ' : Votre produit est disponible.');
                            system.debug('--  ' + a + ' : Votre produit est disponible.');
                            break;
                        }
                        
                        // If the stock isn't available, check what's the nearest available date
                        closestDateRetour = closestDateRetour > s.Date_retour__c ? 
                            s.Date_retour__c : closestDateRetour;
                        
                        furthestDateRetrait = furthestDateRetrait < s.Date_retrait_souhaitee__c ? 
                            s.Date_retrait_souhaitee__c : furthestDateRetrait;
                    }
                    
                    // If there was no easy stock, check the dates
                    if(!dispoStockMap.keySet().contains(a)){
                        if(closestDateRetour == system.today() + 365){
                            dispoStockMap.put(a, a + ' : Votre produit est disponible jusqu\'au ' + 
                                              UtilityClassHelper.formatDate(furthestDateRetrait));
                            system.debug('--  ' + a + ' : Votre produit est disponible jusqu\'au ' + 
                                         UtilityClassHelper.formatDate(furthestDateRetrait));
                            continue;
                        }
                        if(furthestDateRetrait == system.today()){
                            dispoStockMap.put(a, a + ' : Votre produit est disponible à partir du ' + 
                                         UtilityClassHelper.formatDate(closestDateRetour));
                            system.debug('--  ' + a + ' : Votre produit est disponible à partir du ' + 
                                         UtilityClassHelper.formatDate(closestDateRetour));
                            continue;
                        }
                        dispoStockMap.put(a, a + ' : Votre produit est disponible à partir du ' + 
                                          UtilityClassHelper.formatDate(closestDateRetour) +
                                          ' et jusqu\'au ' + 
                                          UtilityClassHelper.formatDate(furthestDateRetrait));
                        system.debug('-- ' + a + ' : Votre produit est disponible à partir du ' + 
                                          UtilityClassHelper.formatDate(closestDateRetour) +
                                          ' et jusqu\'au ' + 
                                          UtilityClassHelper.formatDate(furthestDateRetrait));
                    }
                }
                // Assign the availability to the product
                p.Disponibilite_stock__c = '';
                for(String a : dispoStockMap.keySet()){
                    p.Disponibilite_stock__c += dispoStockMap.get(a) + '\n';
                }
            }
        }
        
        update relatedProductList;
    }
}