hubSide/force-app/main/default/objects/Account/fields/Compte_test__c.field-meta.xml
<CustomField>
    <fullName>Compte_test__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Signifie si le compte est utilisé seulement pour le test, et n&apos;est pas à afficher sur la community</description>
    <label>Compte de test ?</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Account/fields/Proprietaire_stock__c.field-meta.xml
<CustomField>
    <fullName>Proprietaire_stock__c</fullName>
    <description>Liste permettant de savoir si le distributeur possède un stock</description>
    <label>Propriétaire du stock</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non propriétaire du stock</fullName>
            </value>
            <value>
                <fullName>Propriétaire du stock</fullName>
            </value>
            <value>
                <fullName>Mixte</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Account/recordTypes/Distributeur.recordType-meta.xml
<RecordType>
    <fullName>Distributeur</fullName>
    <active>true</active>
    <label>Distributeur location</label>
</RecordType>

hubSide/force-app/main/default/objects/Product2/fields/Disponibilite_stock__c.field-meta.xml
<CustomField>
    <fullName>Disponibilite_stock__c</fullName>
    <defaultValue>&apos;Votre produit n\&apos;est pas disponible actuellement.&apos;</defaultValue>
    <description>Affiche la disponibilité des stocks du produit en question.</description>
    <label>Disponibilité stock</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Produit_avec_numero_de_serie__c.field-meta.xml
<CustomField>
    <fullName>Produit_avec_numero_de_serie__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Produit avec numéro de série ?</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/Stock_produit__c.object-meta.xml
<CustomObject>
    <label>Stock magasin</label>
    <nameField>
        <label>Stock magasin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks magasin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Code_distributeur_stock__c.field-meta.xml
<CustomField>
    <fullName>Code_distributeur_stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code distributeur stock</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Stock_produits</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_retour__c.field-meta.xml
<CustomField>
    <fullName>Date_retour__c</fullName>
    <description>Date de retour de l&apos;emprunt actuel, si emprunt il y a.</description>
    <label>Date de retour</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_retrait_souhaitee__c.field-meta.xml
<CustomField>
    <fullName>Date_retrait_souhaitee__c</fullName>
    <description>Date de retrait souhaitée pour la réservation.</description>
    <label>Date de retrait souhaitée</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Produit location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stocks magasin</relationshipLabel>
    <relationshipName>Stock_produits</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Proprietaire_Stock__c.field-meta.xml
<CustomField>
    <fullName>Proprietaire_Stock__c</fullName>
    <label>Proprietaire Stock</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Proprietaire_Stock</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En stock</fullName>
                <default>true</default>
                <label>En stock</label>
            </value>
            <value>
                <fullName>Sortie client</fullName>
            </value>
            <value>
                <fullName>A transférer</fullName>
            </value>
            <value>
                <fullName>Destocke</fullName>
                <label>Déstocké</label>
            </value>
            <value>
                <fullName>Réservé</fullName>
            </value>
            <value>
                <fullName>Recyclé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/User/fields/Distributeur_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Distributeur_de_reference__c</fullName>
    <description>ID ( SFDC 15 caractères ) du distributeur pour lequel travaille l&apos;employé</description>
    <label>Distributeur de reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Proprietaire_Stock.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Non propriétaire du stock</fullName>
    </customValue>
    <customValue>
        <fullName>Propriétaire du stock</fullName>
    </customValue>
    <customValue>
        <fullName>Mixte</fullName>
    </customValue>
    <masterLabel>Proprietaire Stock</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/StockProduitTriggerHelper.cls
/***
* @author Ariane Tanguy (GFI)
* @date 14/08/2020
* @description Helper class for StockProduitTrigger
*/

public class StockProduitTriggerHelper {
    
    /***
	* @description Get current user info
	* @param newStockList - list of stock
	* @return Map<id, User>
	*/
    public static User getRelatedUserInfo(){
        
        // Get the related user info        
        return [SELECT id, Distributeur_de_reference__c
                FROM User
                WHERE id =: system.UserInfo.getUserId()];
    }
    
    /***
	* @description On create - Get all the product related to the new stock
	* @param newStockList - list of stock
	* @return Map<id, Product2>
	*/
    public static Map<id, Product2> getRelatedProduct(List<Stock_Produit__c> newStockList){
        
        // Get the related product ids
        Set<id> productIdSet = new Set<Id>();
        for(Stock_Produit__c s : newStockList){
            productIdSet.add(s.Produit__c);
        }
        
        Map<id, Product2> relatedProductMap = new Map<id, Product2>([SELECT id, 
                                                                     Name, 
                                                                     Disponibilite_stock__c, 
                                                                     Produit_avec_numero_de_serie__c
                                                                     FROM Product2
                                                                     WHERE id IN: productIdSet]);
        return relatedProductMap;
    }
    
    /***
	* @description On update - Get all the product related to the new stock
	* @param newStockList - list of stock
	* @return Map<id, Product2>
	*/
    public static Map<id, Product2> getRelatedProduct(List<Stock_Produit__c> newStockList, Map<id, Stock_Produit__c> oldStockMap){
        
        // Get the related product ids
        Set<id> productIdSet = new Set<Id>();
        for(Stock_Produit__c s : newStockList){
            
            if(s.Statut__c != oldStockMap.get(s.id).Statut__c ||
               s.Date_retrait_souhaitee__c != oldStockMap.get(s.id).Date_retrait_souhaitee__c ||
               s.Date_retour__c != oldStockMap.get(s.id).Date_retour__c){
                   productIdSet.add(s.Produit__c);
               }
        }
        
        if(productIdSet.size() == 0){
            return new Map<id, Product2>();
        }
        
        Map<id, Product2> relatedProductMap = new Map<id, Product2>([SELECT id, Disponibilite_stock__c
                                                                    FROM Product2
                                                                    WHERE id IN: productIdSet]);
        
        return relatedProductMap;        
    }
    
    /***
	* @description Get all the related stocks
	* @param newStockList - list of stock
	* @return Map<id, Stock_Produit__c>
	*/
    public static Map<id, List<Stock_Produit__c>> getRelatedStocks(Map<id, Product2> relatedProductMap, List<Stock_Produit__c> newStockList){
                
       	// Query the stock
        List<Stock_Produit__c> relatedStockList = [SELECT id, Produit__c, 
                                                   Code_distributeur_stock__c, Code_distributeur_stock__r.Name, 
                                                   Date_retour__c, Date_retrait_souhaitee__c
                                                   FROM Stock_Produit__c
                                                   WHERE Produit__c IN: relatedProductMap.keySet()
                                                   AND id NOT IN: newStockList];
        
        system.debug('-- relatedStockList ' + relatedStockList);
        
        // Add the new stocks to the already present ones
        for(Stock_produit__c s : newStockList){
            if(relatedProductMap.keySet().contains(s.Produit__c)){
                relatedStockList.add(s);
            }
        }
        
        // And map them to their related product
        Map<id, List<Stock_Produit__c>> productIdStockMap = new Map<id, List<Stock_Produit__c>>();
        for(Stock_Produit__c s : relatedStockList){
            if(!productIdStockMap.keySet().contains(s.Produit__c)){
                List<Stock_Produit__c> tmpList = new List<Stock_Produit__c>();
                productIdStockMap.put(s.Produit__c, tmpList);
            }
            productIdStockMap.get(s.Produit__c).add(s);
        }
        
        return productIdStockMap;        
    }
    
    /***
	* @description Get all the related distributeurs
	* @param productIdStockMap - map of stock
	* @return Map<id, Account>
	*/
    public static Map<id, Account> getDistributeur(Map<id, List<Stock_Produit__c>> productIdStockMap){
        
        // Get the distributeur ids
        Set<id> distribIdSet = new Set<id>();
        for(List<Stock_produit__c> sList : productIdStockMap.values()){
            for(Stock_produit__c s : sList){
                distribIdSet.add(s.Code_distributeur_stock__c);
            }
        }
        
        Map<id, Account> distributeurMap = new Map<id, Account>([SELECT id, Name, Compte_test__c, 
                                                                 Proprietaire_stock__c
                                                                 FROM Account
                                                                 WHERE id IN: distribIdSet]);
        return distributeurMap;        
    }
}