hubSide/force-app/main/default/objects/Account/fields/Enseigne__c.field-meta.xml
<CustomField>
    <fullName>Enseigne__c</fullName>
    <inlineHelpText>Nom de l’enseigne de rattachement</inlineHelpText>
    <label>Enseigne</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SFAM</fullName>
            </value>
            <value>
                <fullName>INDEP</fullName>
            </value>
            <value>
                <fullName>FNAC</fullName>
            </value>
            <value>
                <fullName>Darty</fullName>
            </value>
            <value>
                <fullName>MEDIA ONE</fullName>
            </value>
            <value>
                <fullName>DARTY FRANCHISE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Account/recordTypes/Distributeur.recordType-meta.xml
<RecordType>
    <fullName>Distributeur</fullName>
    <active>true</active>
    <label>Distributeur location</label>
</RecordType>

hubSide/force-app/main/default/objects/Asset/fields/Date_cloture__c.field-meta.xml
<CustomField>
    <fullName>Date_cloture__c</fullName>
    <description>Date résiliation souhaitée par le client</description>
    <inlineHelpText>Date résiliation souhaitée par le client</inlineHelpText>
    <label>Date de cloture</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Date_debut_contrat__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_contrat__c</fullName>
    <description>Date de début du contrat souscrit par le client.</description>
    <label>Date de début du contrat</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Enseigne__c.field-meta.xml
<CustomField>
    <fullName>Enseigne__c</fullName>
    <formula>TEXT(Id_distributeur__r.Enseigne__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enseigne</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Etat_paiement__c.field-meta.xml
<CustomField>
    <fullName>Etat_paiement__c</fullName>
    <label>Etat paiement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>unpaid</fullName>
                <label>Impayé</label>
            </value>
            <value>
                <fullName>valid</fullName>
                <label>Valide</label>
            </value>
            <value>
                <fullName>regularisedUnpaid</fullName>
                <label>Impayé régularisé</label>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Facture__c.field-meta.xml
<CustomField>
    <fullName>Facture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consommation</label>
    <referenceTo>Facture__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Formule__c.field-meta.xml
<CustomField>
    <fullName>Formule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Formule</label>
    <referenceTo>vlocity_ins__AssetCoverage__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Id_distributeur__c.field-meta.xml
<CustomField>
    <fullName>Id_distributeur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Id issu du Flux API (Si Id_distributeur__c n&apos;existe pas dans Account alors rattaché à l&apos;Account Distributeur générique &quot;Non Reconnu&quot;)</description>
    <label>Id Distributeur</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets (Distributeur)</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Motif_cloture__c.field-meta.xml
<CustomField>
    <fullName>Motif_cloture__c</fullName>
    <description>Motif lié à la résiliation demandée par le client</description>
    <label>Motif de clôture</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>clientCancellation</fullName>
                <label>Résiliation client</label>
            </value>
            <value>
                <fullName>unpaidCancellation</fullName>
                <label>Résiliation impayé</label>
            </value>
            <value>
                <fullName>fraudCancellation</fullName>
                <label>Résiliation fraude</label>
            </value>
            <value>
                <fullName>oppositionCancellation</fullName>
                <label>Résiliation opposition</label>
            </value>
            <value>
                <fullName>unknown</fullName>
                <label>Sans objet</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/TECH_CalculatorIndicLastChange__c.field-meta.xml
<CustomField>
    <fullName>TECH_CalculatorIndicLastChange__c</fullName>
    <label>TECH_CalculatorIndicLastChange</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/TECH_LastBirthDayContract__c.field-meta.xml
<CustomField>
    <fullName>TECH_LastBirthDayContract__c</fullName>
    <label>TECH_LastBirthDayContract</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/recordTypes/Contrat_assurance.recordType-meta.xml
<RecordType>
    <fullName>Contrat_assurance</fullName>
    <active>true</active>
    <label>Contrat assurance</label>
</RecordType>

hubSide/force-app/main/default/objects/Asset/recordTypes/Contrat_location.recordType-meta.xml
<RecordType>
    <fullName>Contrat_location</fullName>
    <active>true</active>
    <description>Lié aux contrats de location</description>
    <label>Contrat location</label>
</RecordType>

hubSide/force-app/main/default/objects/Case/fields/Attente_documents__c.field-meta.xml
<CustomField>
    <fullName>Attente_documents__c</fullName>
    <label>Attente documents</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
                <label>Reçu(s)</label>
            </value>
            <value>
                <fullName>Valid</fullName>
                <label>Valide(s)</label>
            </value>
            <value>
                <fullName>Expected</fullName>
                <default>true</default>
                <label>Attendu(s)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/Facture__c.object-meta.xml
<CustomObject>
    <description>Historique par période du nombre de jour consommé et des dépassements occasionnels. Justification historique facture client</description>
    <label>Consommation</label>
    <nameField>
        <displayFormat>FAC-{00000000}</displayFormat>
        <label>Facture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consommations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Facture__c/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contrat lié à la facture en cours</description>
    <label>Contrat</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contrat location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Consommations</relationshipLabel>
    <relationshipName>Consommations</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Facture__c/fields/Date_fin_periode__c.field-meta.xml
<CustomField>
    <fullName>Date_fin_periode__c</fullName>
    <label>Date de fin de période</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/classes/AssetTriggerHandlerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 12/05/2020
* @description AssetTrigger test class
* @Object Asset
*/

@isTest
public class AssetTriggerHandlerTest {
    
    /***
    * @description Update the account record type
    * @see updateAccountRecordType
    */
    @isTest
    public static void updateAccountRecordTypeTest(){
        
        // Create a client
        Account a = TestFactory.createClient();
        a.RecordTypeId = UtilityClassHelper.getCreatedRecordType('Client_SFAM');
        insert a;
        
        // Create a contract
        Asset c = TestFactory.createContract(a.id);
        insert c;
        
        // Query the account and check whether the record type is location
        a = [SELECT id, Record_Type_Name__c FROM Account WHERE id =: a.id];
        system.assertEquals('Client_location', a.Record_Type_Name__c, 
                            'The record type should have been updated after the asset creation - This is wrong');
        
        // Create another contract
        Asset c1 = TestFactory.createContract(a.id);
        c1.RecordTypeId = UtilityClassHelper.getCreatedRecordType('Contrat_assurance');
        insert c1;
        
        // Query the account and check whether the record type is now assurance
        a = [SELECT id, Record_Type_Name__c FROM Account WHERE id =: a.id];        
        system.assertEquals('Client_SFAM', a.Record_Type_Name__c, 
                            'The record type should have been updated after the asset creation - This is wrong');
    }
    
    /***
    * @description Update the record type
    * @see updateRecordTypeOnCreation
    */
    @isTest
    public static void updateRecordTypeOnCreationTest(){
        
        // Create a new Contract
        Asset c = TestFactory.createContract();
        insert c;
        
        // Query the contract and check whether the record type has been correctly updated
        c = [SELECT id, RecordType.DeveloperName FROM Asset WHERE id =: c.id];
        
        system.assertEquals(c.RecordType.DeveloperName, 'Contrat_location', 
                            'The record type should have been updated on the contract - This is wrong');
    }
    
    /***
    * @description Handle user creation
    * @see handleAccountActivation
    */
    @isTest
    public static void handlePassLocActivationTest(){
        
        // Create a SFAM distributeur
        Account d = TestFactory.createDistributeur();
        d.Enseigne__c = 'SFAM';
        insert d;
        
        // Create a new SFAM Contract
        Asset c = TestFactory.createContract();
        c.Id_distributeur__c = d.id;
        test.startTest();
        insert c;
        Test.stopTest();
        
        // Query the account
        Account a = [SELECT id, PersonContactId, IsCustomerPortal FROM Account WHERE id =: c.accountId];
        system.assertEquals(TRUE, a.IsCustomerPortal, 
                            'The account should now be portal enabled - This is wrong');
        User u = [SELECT id, Profile.Name FROM User WHERE ContactID =: a.PersonContactId];
        //replace Community Plus License by Community License >
        //system.assertEquals('Passloc Customer community Plus Login User', u.Profile.Name,
        system.assertEquals('Passloc Customer community Login User', u.Profile.Name,
        // <  
                            'The new user profile should be PassLoc - This is wrong');        
    }
    
    /***
    * @description Handle user creation
    * @see handleAccountActivation
    */
    @isTest
    public static void handleIlliPassActivationTest(){
        
        // Create a SFAM distributeur
        Account d = TestFactory.createDistributeur();
        d.Enseigne__c = 'INDEP';
        insert d;
        
        // Create a new SFAM Contract
        Asset c = TestFactory.createContract();
        c.Id_distributeur__c = d.id;
        test.startTest();
        insert c;
        Test.stopTest();
        
        // Query the account
        Account a = [SELECT id, PersonContactId, IsCustomerPortal FROM Account WHERE id =: c.accountId];
        system.assertEquals(TRUE, a.IsCustomerPortal, 
                            'The account should now be portal enabled - This is wrong');
        User u = [SELECT id, Profile.Name FROM User WHERE ContactID =: a.PersonContactId];
        //replace Community Plus License by Community License >
        //system.assertEquals('Illipass Customer community Plus Login User', u.Profile.Name,
        system.assertEquals('Illipass Customer community Login User', u.Profile.Name,
        // < 
                            'The new user profile should be PassLoc - This is wrong');        
    }
    
    /***
    * @description Handle resiliation
    * @see handleResiliation
    */
    @isTest
    public static void handleResiliationTest(){
        
        // Create a new Contract
        Asset c = TestFactory.createContract();
        insert c;
        
        // Stop it
        c.Motif_cloture__c = 'Résiliation client';
        c.Date_cloture__c = system.today();
        update c;
        
        // Query the Facture and check the contract status
        List<Facture__c> relatedFacture = [SELECT Date_fin_periode__c FROM Facture__c WHERE Contrat__c =: c.id];
        system.assertEquals(c.Date_cloture__c, relatedFacture[0].Date_fin_periode__c, 
                           'The related facture should have been updated - This is wrong');
        
        c = [SELECT Status FROM Asset WHERE id =: c.id];
        system.assertEquals('closed', c.Status, 
                           'The contract status should have been updated - this is wrong');
    }
    
    /***
    * @description Handle the etat paiement update
    * @see handleValidPayment
    */
    @isTest
    public static void handleValidPaymentTest(){
        
        // Create a new Contract
        Asset a = TestFactory.createAssuranceAsset();
        a.Etat_paiement__c = 'unpaid';
        insert a;
        
        // Create a new case
        Case c = TestFactory.createSinistre(a.AccountId);
        c.Attente_documents__c = 'Valid';
        c.Status = 'Incomplet';
        c.AssetId = a.Id;
        insert c;
        
        // Update the contract
        a.Etat_paiement__c = 'valid';
        update a;
        
        c = [SELECT id, Status FROM Case WHERE id =: c.id];
        system.assertEquals('En cours d\'examen', c.Status, 
                           'The status should have changed - This is wrong');
    }

    /***
    * @description Handle the CalculatorIndicLastChange
    * @see handleCalculatorIndicLastChange
    */
    @isTest
    public static void handleCalculatorIndicLastChange(){
        
        // Create a new Contract
        Asset a = TestFactory.createAssuranceAssetWithFormula();
        a.Date_debut_contrat__c = System.today().addDays(-1);
        update a;
        
        vlocity_ins__AssetCoverage__c formsous = [SELECT Id,Formule_options__r.NbMounthKPIContract__c FROM vlocity_ins__AssetCoverage__c WHERE Id = :a.Formule__c];

        Asset aUpdated = [SELECT Id,TECH_CalculatorIndicLastChange__c,TECH_LastBirthDayContract__c FROM Asset WHERE Id = :a.Id];
        system.assertEquals(System.today().addMonths((Integer)formsous.Formule_options__r.NbMounthKPIContract__c).addDays(-1), aUpdated.TECH_CalculatorIndicLastChange__c, 
                           'The TECH_CalculatorIndicLastChange__c not add month');
        system.assertEquals(System.today().addDays(-1), aUpdated.TECH_LastBirthDayContract__c, 
                           'The TECH_LastBirthDayContract__c is today');
    }
}