hubSide/force-app/main/default/objects/Account/fields/Enseigne__c.field-meta.xml
<CustomField>
    <fullName>Enseigne__c</fullName>
    <inlineHelpText>Nom de l’enseigne de rattachement</inlineHelpText>
    <label>Enseigne</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SFAM</fullName>
            </value>
            <value>
                <fullName>INDEP</fullName>
            </value>
            <value>
                <fullName>FNAC</fullName>
            </value>
            <value>
                <fullName>Darty</fullName>
            </value>
            <value>
                <fullName>MEDIA ONE</fullName>
            </value>
            <value>
                <fullName>DARTY FRANCHISE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Account/recordTypes/Distributeur.recordType-meta.xml
<RecordType>
    <fullName>Distributeur</fullName>
    <active>true</active>
    <label>Distributeur location</label>
</RecordType>

hubSide/force-app/main/default/objects/Asset/fields/Enseigne__c.field-meta.xml
<CustomField>
    <fullName>Enseigne__c</fullName>
    <formula>TEXT(Id_distributeur__r.Enseigne__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enseigne</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Id_distributeur__c.field-meta.xml
<CustomField>
    <fullName>Id_distributeur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Id issu du Flux API (Si Id_distributeur__c n&apos;existe pas dans Account alors rattaché à l&apos;Account Distributeur générique &quot;Non Reconnu&quot;)</description>
    <label>Id Distributeur</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets (Distributeur)</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/Emprunt__c.object-meta.xml
<CustomObject>
    <label>Emprunt</label>
    <nameField>
        <displayFormat>EMP-{000000}</displayFormat>
        <label>Emprunt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emprunts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_retour_prevu__c.field-meta.xml
<CustomField>
    <fullName>Date_retour_prevu__c</fullName>
    <description>Date prévisionnelle de retour pour vérifier le nombre de jours possible et gérer les stocks glissants par la suite</description>
    <label>Date du retour prévu</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <description>Date d&apos;emprunt de l&apos;objet</description>
    <label>Date de sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En magasin</fullName>
                <default>true</default>
                <label>En magasin</label>
            </value>
            <value>
                <fullName>Sortie</fullName>
            </value>
            <value>
                <fullName>Retourné</fullName>
                <label>Retour sans défaut</label>
            </value>
            <value>
                <fullName>Retour avec défaut</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
                <isActive>false</isActive>
                <label>Annulé</label>
            </value>
            <value>
                <fullName>Label.Location_StatusEmprunt1</fullName>
                <isActive>false</isActive>
                <label>Label.Location_StatusEmprunt1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Emprunt__c/recordTypes/Emprunt.recordType-meta.xml
<RecordType>
    <fullName>Emprunt</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet emprunt une fois créé</description>
    <label>Emprunt</label>
</RecordType>

hubSide/force-app/main/default/objects/Product2/fields/Famille_produit__c.field-meta.xml
<CustomField>
    <fullName>Famille_produit__c</fullName>
    <label>Famille produit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Famille_Produit</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Objets Réservés sur le web / en boutique</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Numero de reservation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Reservation__c/fields/Date_retrait__c.field-meta.xml
<CustomField>
    <fullName>Date_retrait__c</fullName>
    <description>Date de début d’emprunt</description>
    <label>Date de début de location souhaitée</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Duree_emprunt__c.field-meta.xml
<CustomField>
    <fullName>Duree_emprunt__c</fullName>
    <description>Nombre de jours de l&apos;emprunt</description>
    <label>Duree de l&apos;emprunt (jours)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Réservé</fullName>
            </value>
            <value>
                <fullName>Réservation_convertie</fullName>
                <label>Réservation convertie</label>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>Pré-réservé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Reservation__c/recordTypes/Reservation.recordType-meta.xml
<RecordType>
    <fullName>Reservation</fullName>
    <active>true</active>
    <description>Record type pour l&apos;objet Reservation</description>
    <label>Reservation</label>
</RecordType>

hubSide/force-app/main/default/objects/Stock_produit__c/Stock_produit__c.object-meta.xml
<CustomObject>
    <label>Stock magasin</label>
    <nameField>
        <label>Stock magasin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks magasin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Code_distributeur_stock__c.field-meta.xml
<CustomField>
    <fullName>Code_distributeur_stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code distributeur stock</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Stock_produits</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Stock_produit__c/fields/Date_sortie__c.field-meta.xml
<CustomField>
    <fullName>Date_sortie__c</fullName>
    <label>Date sortie</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Famille_Produit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Appareil photo</fullName>
    </customValue>
    <customValue>
        <fullName>Caméra sportive</fullName>
    </customValue>
    <customValue>
        <fullName>Casque VR</fullName>
    </customValue>
    <customValue>
        <fullName>Drone</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Enceinte</fullName>
    </customValue>
    <customValue>
        <fullName>Tablette</fullName>
    </customValue>
    <customValue>
        <fullName>Téléphone</fullName>
    </customValue>
    <customValue>
        <fullName>Autre</fullName>
    </customValue>
    <customValue>
        <fullName>Trottinette</fullName>
    </customValue>
    <customValue>
        <fullName>Home Cinema</fullName>
    </customValue>
    <customValue>
        <fullName>Décodeur</fullName>
    </customValue>
    <customValue>
        <fullName>Vidéoprojecteur</fullName>
    </customValue>
    <customValue>
        <fullName>Ordinateur</fullName>
    </customValue>
    <customValue>
        <fullName>Montre connectée</fullName>
    </customValue>
    <customValue>
        <fullName>Objets Connectés</fullName>
        <isActive>false</isActive>
        <label>Objets Connectés</label>
    </customValue>
    <customValue>
        <fullName>Télévision</fullName>
        <isActive>false</isActive>
        <label>Télévision</label>
    </customValue>
    <description>Regroupe toutes les grandes familles de produits mises à disposition dans la partie location</description>
    <masterLabel>Famille Produit</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/Flow_OnlineReservationTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 06/07/2020
* @description Flow_OnlineReservation test class
* @Class Flow_OnlineReservation
*/

@isTest
public class Flow_OnlineReservationTest {
    
    @testSetup
    public static void init(){
        
        //OPTIM>
        date currentdate = system.today();
        //<OPTIM
        
        // Create a distributeur
        Account d = TestFactory.createDistributeur();
        d.Enseigne__c = 'SFAM';
        insert d;
        
        // Create a client
        Account c = TestFactory.createClient();
        insert c;
        
        // Create a product
        Product2 p = TestFactory.createProduct();
        p.Famille_produit__c = 'Téléphone';
        insert p;
        
        // Create three stocks from this product
        List<Stock_Produit__c> createdStockList = new List<Stock_Produit__c>();
        for(Integer i = 0; i<3; i++){
            Stock_produit__c s = TestFactory.createStock(p.Id);
            //OPTIM>
            s.Code_distributeur_stock__c = d.id;
            //<OPTIM
            createdStockList.add(s);
        }
        insert createdStockList;
        
        test.startTest();
        
        //OPTIM>
        //for(Stock_Produit__c s : createdStockList){
        //    s.Code_distributeur_stock__c = d.id;
        //}
        //update createdStockList;
        //<OPTIM
        
        // Create a reservation
        List<Reservation__c> reservationList = new List<Reservation__c>();
        Reservation__c r = TestFactory.createReservation(c.id, createdStockList[0].id);
        //OPTIM>
        //r.Date_retrait__c = system.today();
        r.Date_retrait__c = currentdate;
        //<OPTIM
        r.Duree_emprunt__c = 1;
        reservationList.add(r);
        
        // And a pre reservation
        Reservation__c pr = TestFactory.createReservation(c.id, createdStockList[1].id);
        //OPTIM>
        pr.Date_retrait__c = system.today();
        pr.Date_retrait__c = currentdate;
        //<OPTIM
        pr.Duree_emprunt__c = 1;
        pr.Status__c = 'Pré-réservé';
        reservationList.add(pr);
        
        insert reservationList;
        
        // Create an emprunt
        Asset a = TestFactory.createContract(c.id);
        a.Id_distributeur__c = d.Id;
        insert a;
        
        //Test.stopTest();
        
        Emprunt__c e = TestFactory.createEmprunt(a, createdStockList[2]);
		//OPTIM>
        //e.Date_sortie__c = system.today();
        //e.Date_retour_prevu__c = system.today() + 2;
        e.Date_sortie__c = currentdate;
        e.Date_retour_prevu__c = currentdate;
        //<OPTIM
        insert e;
        
        Test.stopTest();
    }
    
    /***
	* @description From the flow, get all available stock
	* @LightningComponent Flow_SelectionStock
	*/
    @isTest
    public static void Flow_selectionStockTest(){
        
        test.startTest();
        
        Id selectedProductId = [SELECT id FROM Product2 LIMIT 1].id;
        Date choosenDate = system.today();
        Integer dureeLocation = 1;
        
        // Make the logic work
        List<id> availableStockIdList = Flow_OnlineReservation.RetrieveStock(selectedProductId, choosenDate, dureeLocation, 'SFAM', true, true);
        List<id> distributeurIdList = Flow_OnlineReservation.RetrieveStock(selectedProductId, choosenDate, dureeLocation, 'SFAM', true, false);
        
        // Check the result
        system.assertEquals(1, availableStockIdList.size(), 
                           'The returned list should have one stocks - This is wrong');
        
        // Get the distributeur for the user to choose from
        List<Object> objList = Flow_OnlineReservation.getAllDistributeur(selectedProductId, choosenDate, dureeLocation, 'SFAM', true);
        
        // Check the result
        system.assertEquals(1, objList.size(), 
                           'The returned list should have one distributeur - This is wrong');

        // The user chose the first distributeur, let's get one stock now
        Id choosenId = Flow_OnlineReservation.returnOneStockFromList(availableStockIdList, distributeurIdList[0]);
        
        // Check the result
        system.assertEquals(availableStockIdList[0], choosenId, 
                           'The returned list should have one distributeur - This is wrong');
        
        Test.stopTest();
    }
    
    /***
	* @description From the flow, get all available stock
	* @LightningComponent Flow_SelectionStockMagasin
	*/
    @isTest
    public static void Flow_selectionStockMagasinTest(){
        
        test.startTest();
        
        id distribId = [SELECT id FROM Account 
                        WHERE RecordTypeId =: UtilityClassHelper.getCreatedRecordType('Distributeur')][0].id;
        Id selectedProductId = [SELECT id FROM Product2 LIMIT 1].id;
        Date choosenDate = system.today();
        Integer dureeLocation = 1;
        
        // Make the logic work
        id chosenId = Flow_OnlineReservation.returnOneStock(selectedProductId, choosenDate, dureeLocation, distribId, false);
        
        // Check the result
        system.assert(chosenId != null, 'The returned id shouldnt be null - This is wrong');

        // Query the pre reservation
        Reservation__c r = [SELECT id, Status__c
                            FROM Reservation__c
                            WHERE Status__c = 'Pré-réservé'];
        r.Status__c = 'Réservé';
        update r;
        
        // Make the logic work again
        chosenId = Flow_OnlineReservation.returnOneStock(selectedProductId, choosenDate, dureeLocation, distribId, false);
        
        // Check the result
        system.assert(chosenId == null, 'The returned id should be null - This is wrong');
        
        Test.stopTest();
    }
    
}