hubSide/force-app/main/default/objects/Account/fields/Equipement_client__c.field-meta.xml
<CustomField>
    <fullName>Equipement_client__c</fullName>
    <label># Equipement client</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Email_Contact__c.field-meta.xml
<CustomField>
    <fullName>Email_Contact__c</fullName>
    <label>Email Contact</label>
    <type>Email</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Equipement_client__c.field-meta.xml
<CustomField>
    <fullName>Equipement_client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement client</label>
    <referenceTo>vlocity_ins__AssetInsuredItem__c</referenceTo>
    <relationshipLabel>Demandes associées</relationshipLabel>
    <relationshipName>Demandes_associees</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Montant_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Montant_sinistre__c</fullName>
    <label>Coût global</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/ClientChoiceDate__c.field-meta.xml
<CustomField>
    <fullName>ClientChoiceDate__c</fullName>
    <label>Date choix client</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Equipement_client__c.field-meta.xml
<CustomField>
    <fullName>Equipement_client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement client</label>
    <referenceTo>vlocity_ins__AssetInsuredItem__c</referenceTo>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/EquipmentAmount__c.field-meta.xml
<CustomField>
    <fullName>EquipmentAmount__c</fullName>
    <label>Valeur Echange</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Montant_equipement__c.field-meta.xml
<CustomField>
    <fullName>Montant_equipement__c</fullName>
    <label>Montant équipement</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/RealCost__c.field-meta.xml
<CustomField>
    <fullName>RealCost__c</fullName>
    <label>Coût Réel</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sous_statut__c.field-meta.xml
<CustomField>
    <fullName>Sous_statut__c</fullName>
    <label>Sous-statut</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Statut_equipement__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>EquipSin_SousStatut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Statut_equipement__c.field-meta.xml
<CustomField>
    <fullName>Statut_equipement__c</fullName>
    <label>Statut equipement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EquipSin_Statut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/Mouvements_financiers__c.object-meta.xml
<CustomObject>
    <label>Calcul Indemnisation</label>
    <nameField>
        <label>Nom du mouvement financier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calcul Indemnisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Cout_choisi__c.field-meta.xml
<CustomField>
    <fullName>Cout_choisi__c</fullName>
    <label>Coût choisi</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primes</fullName>
            </value>
            <value>
                <fullName>Echange</fullName>
            </value>
            <value>
                <fullName>Réparation</fullName>
            </value>
            <value>
                <fullName>Règlement par le client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Libelle__c.field-meta.xml
<CustomField>
    <fullName>Libelle__c</fullName>
    <description>Libéllé libre à saisir par le TC ou le GS</description>
    <label>Libellé</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <description>Identification du montant du mouvement</description>
    <label>Montant</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crée</fullName>
                <default>true</default>
                <label>Crée</label>
            </value>
            <value>
                <fullName>En cours d&apos;approbation</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Demande en cours</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Rejeté</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Terminé</label>
            </value>
            <value>
                <fullName>Invalidated</fullName>
                <label>Invalidé</label>
            </value>
            <value>
                <fullName>En attente d&apos;approbation</fullName>
                <isActive>false</isActive>
                <label>En attente d&apos;approbation</label>
            </value>
            <value>
                <fullName>Encaissé</fullName>
                <isActive>false</isActive>
                <label>Encaissé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Type_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Type_mouvement__c</fullName>
    <label>Type Coût</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cout_choisi__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prime pour echange</fullName>
                <label>Prime pour échange</label>
            </value>
            <value>
                <fullName>Geste commercial</fullName>
            </value>
            <value>
                <fullName>Indemnite retard suite à expertise</fullName>
                <label>Indemnité retard suite à expertise</label>
            </value>
            <value>
                <fullName>Prime pour reparation par le client</fullName>
                <label>Prime pour réparation par le client</label>
            </value>
            <value>
                <fullName>Prime pour communication frauduleuse</fullName>
            </value>
            <value>
                <fullName>Cout interne reparation</fullName>
                <label>Coût interne réparation</label>
            </value>
            <value>
                <fullName>Cout interne d&apos;echange</fullName>
                <label>Coût interne d&apos;échange</label>
            </value>
            <value>
                <fullName>Franchise</fullName>
            </value>
            <value>
                <fullName>Cout prime magasin</fullName>
                <label>Coût prime magasin</label>
            </value>
            <value>
                <fullName>Complément réparation</fullName>
            </value>
            <value>
                <fullName>Cout forfait de reparation</fullName>
                <isActive>false</isActive>
                <label>Coût forfait de réparation</label>
            </value>
            <value>
                <fullName>Remboursement client</fullName>
                <isActive>false</isActive>
                <label>Remboursement client</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/globalValueSets/EquipSin_SousStatut.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A stocker</fullName>
    </customValue>
    <customValue>
        <fullName>Stocké</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir - Retour client</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir - Retour SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir du stock</fullName>
    </customValue>
    <customValue>
        <fullName>Sortie PSM</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir PSM</fullName>
    </customValue>
    <customValue>
        <fullName>A retourner PSM</fullName>
    </customValue>
    <customValue>
        <fullName>A dispatcher</fullName>
    </customValue>
    <customValue>
        <fullName>En cours d&apos;expertise</fullName>
    </customValue>
    <customValue>
        <fullName>En attente GS</fullName>
    </customValue>
    <customValue>
        <fullName>En cours</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - A expédier</fullName>
    </customValue>
    <customValue>
        <fullName>Préparation</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - A conserver</fullName>
    </customValue>
    <customValue>
        <fullName>Retourné client</fullName>
    </customValue>
    <customValue>
        <fullName>Repaired</fullName>
        <label>Réparé</label>
    </customValue>
    <customValue>
        <fullName>Unrepairable</fullName>
        <label>Irréparable</label>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <label>Annulé</label>
    </customValue>
    <customValue>
        <fullName>Via prime</fullName>
    </customValue>
    <customValue>
        <fullName>Via prime magasin</fullName>
    </customValue>
    <customValue>
        <fullName>Réception client</fullName>
    </customValue>
    <customValue>
        <fullName>Conservé SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - à expédier (Irréparable)</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - à expédier (Annulé)</fullName>
    </customValue>
    <customValue>
        <fullName>Préparation - Irréparable/Annulé</fullName>
    </customValue>
    <customValue>
        <fullName>Retour Client</fullName>
    </customValue>
    <customValue>
        <fullName>Retour SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>Sorti PSM</fullName>
        <isActive>false</isActive>
        <label>Sorti PSM</label>
    </customValue>
    <description>Liste des sous-statuts de l&apos;équipement sinistré - Equipement sinistre sub status list</description>
    <masterLabel>EquipSin_SousStatut</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/CalculIndemnisationTriggerHandlerTest.cls
/***
* @author Nicolas Brancato (GFI)
* @date 12/03/2021
* @description Class test for CalculIndemnisationTriggerHandler
*/
@isTest
public class CalculIndemnisationTriggerHandlerTest {
    
    public static final String PROFILE_GS = 'SFAM GS';
    public static User GSUser;
    public static Account a;
    public static Asset c;
    public static Case s;
    public static Mouvements_financiers__c calCulIndemExchangeStorePremiumCost;
    public static Mouvements_financiers__c calCulIndemExchangeRepair;
    public static Mouvements_financiers__c calCulIndemFranchise;
    public static Equipement_sinistre__c eqs;
    public static Equipement_sinistre__c eqsRepair;
    
    /***
    * @description Static method to initialize all the datas for the test methods
    */
    static{
        
        List<Mouvements_financiers__c> lstMouv = new List<Mouvements_financiers__c>();
        List<Equipement_sinistre__c> lstEquip = new List<Equipement_sinistre__c>();
        
        Id profileGSId = [SELECT Id 
                          FROM Profile  
                          WHERE name =: PROFILE_GS].Id;
        
        GSUser = TestFactory.createUser();
        GSUser.ProfileId = profileGSId;
        GSUser.Email = 'guillaume.gs@yopmail.com';
        insert GSUser;
        
        // Create a new contract as system admin because the contract is sent by Bappli
        c = TestFactory.createAssuranceAssetWithFormula();
        
        // Create a insured item
        vlocity_ins__AssetInsuredItem__c InsuredItem = new vlocity_ins__AssetInsuredItem__c(Account__c = c.accountId, vlocity_ins__PolicyAssetId__c = c.id);
        insert InsuredItem;
        
        // Create a sinistre
        s = TestFactory.createSinistre(c.AccountId, c.id);
        s.Email_Contact__c = 'temp@yopmail.com';
        s.Equipement_client__c = InsuredItem.id;
        insert s;
        
        System.runAs(GSUser){
            
           //Create a calcul indemnisation type exchange
            calCulIndemExchangeStorePremiumCost = TestFactory.createMouvementFinancier(s.id);
            calCulIndemExchangeStorePremiumCost.Libelle__c = 'TEST';
            calCulIndemExchangeStorePremiumCost.Cout_choisi__c = 'Echange';
            calCulIndemExchangeStorePremiumCost.Montant__c = 100;
            calCulIndemExchangeStorePremiumCost.Type_mouvement__c = CalculIndemnisationTriggerHandler.COSTTYPE_STOREPRIMECOST;

            //Create a calcul indemnisation type repair
            calCulIndemExchangeRepair = TestFactory.createMouvementFinancier(s.id);
            calCulIndemExchangeRepair.Libelle__c = 'TEST';
            calCulIndemExchangeRepair.Cout_choisi__c = 'Réparation';
            calCulIndemExchangeRepair.Montant__c = 120;
            calCulIndemExchangeRepair.Type_mouvement__c = CalculIndemnisationTriggerHandler.COSTTYPE_REPAIR;
           
            //Create a calcul indemnisation type franchise
            calCulIndemFranchise = TestFactory.createMouvementFinancier(s.id);
            calCulIndemFranchise.Libelle__c = 'TEST';
            calCulIndemFranchise.Cout_choisi__c = 'Règlement par le client';
            calCulIndemFranchise.Type_mouvement__c = CalculIndemnisationTriggerHandler.COSTTYPE_FRANCHISE;
            calCulIndemFranchise.Montant__c = -55;
            
            lstMouv.add(calCulIndemExchangeStorePremiumCost);
            lstMouv.add(calCulIndemExchangeRepair);
            lstMouv.add(calCulIndemFranchise);
            insert lstMouv;
            
            // Create a damaged equipement
        	eqs = new Equipement_sinistre__c(Sinistre__c = s.id, EquipmentAmount__c = 12, RealCost__c = 0, Montant_equipement__c = 12, ClientChoiceDate__c = Date.today());
            lstEquip.add(eqs);
            

            // Create a damaged equipement
        	eqsRepair = new Equipement_sinistre__c(Sinistre__c = s.id, EquipmentAmount__c = 12, RealCost__c = 0, Montant_equipement__c = 12, ClientChoiceDate__c = Date.today());
            lstEquip.add(eqsRepair);
            insert lstEquip;
        }      
    }    

    /***
    * @description Test method for the handleBeforeUpdate method in CalculIndemnisationTriggerHandler
    */
    @isTest
    static void test_handleBeforeUpdate() {
        
        Test.startTest();
        System.runAs(GSUser){
            try{
                calCulIndemExchangeStorePremiumCost.Name = 'Test';
                update calCulIndemExchangeStorePremiumCost;
            }
            catch(Exception e){
                String message = e.getMessage();
                system.assert(message.contains(Label.Sinistre_ErrorMessageEditionNameCalculIndem), 'message=' + message);
                system.debug('message' + message);
            }
        }
        
        
        Test.stopTest();
        system.assertNotEquals('Test', [SELECT id, Name 
                                        FROM Mouvements_financiers__c 
                                        WHERE id =: calCulIndemExchangeStorePremiumCost.id].Name);
    }    

    /***
    * @description Checks whether the recently updated status on MF are closed - if so, proceeds to close the related case
    * @see updateRelatedCase
    */
    @isTest
    static void updateRelatedCaseTest() {
        
        List<Mouvements_financiers__c> lstMovToUpdate= new List<Mouvements_financiers__c>();

        test.startTest();
        
        // Create another MF
        Mouvements_financiers__c m = TestFactory.createMouvementFinancier(s.id);
        m.Cout_choisi__c = 'Echange';
        m.Type_mouvement__c = 'Cout prime magasin';
        insert m;
        
        // And close it
        m.Statut__c = 'Rejected';
        update m;
        
        // Check whether the case has been closed
        s = [SELECT id, Status FROM Case WHERE id =: s.id];
        system.assertEquals('Reception_dossier', s.Status, 
                            'The case shouldnt have been closed - This is wrong');
        
        // Close the previous MF
        calCulIndemExchangeRepair.Statut__c = 'Completed';

        // Then close the current MF
        calCulIndemExchangeStorePremiumCost.Cout_choisi__c = 'Primes';
        calCulIndemExchangeStorePremiumCost.Type_mouvement__c = 'Prime pour echange';
        calCulIndemExchangeStorePremiumCost.Statut__c = 'Completed';

        calCulIndemFranchise.Statut__c = 'Completed';

        lstMovToUpdate.add(calCulIndemExchangeRepair);
        lstMovToUpdate.add(calCulIndemExchangeStorePremiumCost);
        lstMovToUpdate.add(calCulIndemFranchise);
        update lstMovToUpdate;

        test.stopTest();
        
        // Check whether the case has been closed
        s = [SELECT id, Status, Equipement_client__c FROM Case WHERE id =: s.id]; 
        system.assertEquals('closed_exchange', s.Status, 
                            'The case shouldve been closed - This is wrong');
        
        // Check insured item status and reason
        vlocity_ins__AssetInsuredItem__c i = [SELECT id, Etat__c, Motif__c FROM vlocity_ins__AssetInsuredItem__c WHERE id =: s.Equipement_client__c]; 
        system.assertEquals(CalculIndemnisationTriggerHelper.INSUREDITEM_STATUS_INACTIVE, i.Etat__c, 
                            'The insured item shouldve been inactive - This is wrong');
        
        system.assertEquals(CalculIndemnisationTriggerHelper.INSUREDITEM_REASON_EXCHANGE, i.Motif__c, 
                            'The insured item state shouldve been Echange - This is wrong');
        
        // Check damaged equipment status and substatus
        Equipement_sinistre__c eq = [SELECT id, Statut_equipement__c, Sous_statut__c FROM Equipement_sinistre__c WHERE Sinistre__c =: s.id LIMIT 1]; 
        system.assertEquals(CalculIndemnisationTriggerHelper.EQUIPMENTSINISTRE_STATUS_EXCHANGE, eq.Statut_equipement__c, 
                            'The damaged equipment status shouldve been échangé - This is wrong');
        
        system.assertEquals(CalculIndemnisationTriggerHelper.EQUIPMENTSINISTRE_UNDERSTATUS_PRENIUM, eq.Sous_statut__c, 
                            'The damaged equipment sub status shouldve been "Via primes" - This is wrong');
    }    
    
    /***
    * @description Test method for the handleBeforeDelete method in CalculIndemnisationTriggerHandler
    */
    @isTest
    static void test_handleBeforeDelete() {
        
        Test.startTest();
        System.runAs(GSUser){
            calCulIndemExchangeStorePremiumCost.Statut__c = CalculIndemnisationTriggerHandler.STATUS_VALIDATED;
            update calCulIndemExchangeStorePremiumCost;
            try{
            	delete calCulIndemExchangeStorePremiumCost;
            }
            catch(Exception e){
         		String message = e.getMessage();
                system.assert(message.contains(Label.Sinistre_ErrorMessageDeletionCalculIndem), 'message=' + message);
        	}
        }
        Test.stopTest();
        system.assertNotEquals(null, [Select id, Name From Mouvements_financiers__c where id =: calCulIndemExchangeStorePremiumCost.id]);
    }
    
    /***
    * @description Test method for the handleAfterUpdate method in CalculIndemnisationTriggerHandler
    */
    @isTest
    static void test_handlerAfterUpdate() {
        
        Test.startTest();
        System.runAs(GSUser){
            Equipement_sinistre__c eqBefore = [Select Id,Statut_equipement__c,Sous_statut__c FROM Equipement_sinistre__c WHERE Id=:eqsRepair.Id];
            
            Id idRecordTypeRepairEquip = UtilityClassHelper.getCreatedRecordType(CalculIndemnisationTriggerHelper.EQUIPMENTRECORDTYPE_REPAIR);
            eqBefore.RecordTypeId = idRecordTypeRepairEquip;
            
            update eqBefore;
            
            calCulIndemExchangeRepair.Statut__c = CalculIndemnisationTriggerHandler.STATUS_DEMANDINPROGRESS;
            calCulIndemExchangeStorePremiumCost.Statut__c = CalculIndemnisationTriggerHandler.STATUS_DEMANDINPROGRESS;
            List<Mouvements_financiers__c> lstmv = new List<Mouvements_financiers__c>();
            lstmv.add(calCulIndemExchangeRepair);
            lstmv.add(calCulIndemExchangeStorePremiumCost);            
            
            update lstmv;
        }
        Test.stopTest();
        Equipement_sinistre__c eqAfter = [Select Id,Statut_equipement__c,Sous_statut__c FROM Equipement_sinistre__c WHERE Id=:eqsRepair.Id];
        Case caseAfter = [Select Id, Montant_sinistre__c FROM Case WHERE Id=:s.id];
        

        System.assertEquals(CalculIndemnisationTriggerHelper.EQUIPMENTSINISTRE_STATUS_INPROGRESSREPAIR,eqAfter.Statut_equipement__c);
        System.assertEquals(CalculIndemnisationTriggerHelper.EQUIPMENTSINISTRE_UNDERSTATUS_INPROGRESS,eqAfter.Sous_statut__c);
        System.assertEquals(165, caseAfter.Montant_sinistre__c);
        /*system.assertEquals(CalculIndemnisationTriggerHandler.STATUS_DEMANDINPROGRESS, [Select id, Statut__c 
                                                                                        From Mouvements_financiers__c 
                                                                                        where id =: calCulIndemExchangeStorePremiumCost.id].Statut__c);*/
    }
    
    /***
    * @description Test method for the handleAfterDelete method in CalculIndemnisationTriggerHandler
    */
    @isTest
    static void test_handleAfterDelete() {
        
        Test.startTest();
        System.runAs(GSUser){
            delete calCulIndemExchangeStorePremiumCost;
        }
        Test.stopTest();
        Equipement_sinistre__c eqAfter = [Select Id,ClientChoiceDate__c FROM Equipement_sinistre__c WHERE Id=:eqs.Id];
        System.assertEquals(eqAfter.ClientChoiceDate__c,null);
    }
}