hubSide/force-app/main/default/objects/Account/fields/Equipement_client__c.field-meta.xml
<CustomField>
    <fullName>Equipement_client__c</fullName>
    <label># Equipement client</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Equipement_client__c.field-meta.xml
<CustomField>
    <fullName>Equipement_client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement client</label>
    <referenceTo>vlocity_ins__AssetInsuredItem__c</referenceTo>
    <relationshipLabel>Demandes associées</relationshipLabel>
    <relationshipName>Demandes_associees</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>CASE(
    Record_Type_Name__c, 
    &apos;Sinistre&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;INS&quot; + &apos;&apos; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
        &quot;TMP&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;SinistreBApp&apos;, Num_sinistre_B_Appli__c,
    &apos;Sinistre clôturé&apos;, Subject, 
    &apos;Déclaration&apos;, CaseNumber, 
    &apos;SAV&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;SAV&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;), 
        &quot;DEM&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;Réclamation&apos;, &quot;REC&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
				&apos;Demande&apos;, &quot;DEM&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
    &apos;GED&apos; + &apos;&apos; + RIGHT(CaseNumber, 6)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro de la requête</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/ChooseEqp__c.field-meta.xml
<CustomField>
    <fullName>ChooseEqp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modèle-choisi</label>
    <referenceTo>Matrice_cout_equipement__c</referenceTo>
    <relationshipLabel>Equipement sinistre (Equipement C)</relationshipLabel>
    <relationshipName>Equipement_sinistre1</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/ClientChoiceDate__c.field-meta.xml
<CustomField>
    <fullName>ClientChoiceDate__c</fullName>
    <label>Date choix client</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Equipement_client__c.field-meta.xml
<CustomField>
    <fullName>Equipement_client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement client</label>
    <referenceTo>vlocity_ins__AssetInsuredItem__c</referenceTo>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/EquipmentAmount__c.field-meta.xml
<CustomField>
    <fullName>EquipmentAmount__c</fullName>
    <label>Valeur Echange</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Montant_equipement__c.field-meta.xml
<CustomField>
    <fullName>Montant_equipement__c</fullName>
    <label>Montant équipement</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>Sinistre__r.Numero_sinistre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro du sinistre</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/RealCost__c.field-meta.xml
<CustomField>
    <fullName>RealCost__c</fullName>
    <label>Coût Réel</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Statut_equipement__c.field-meta.xml
<CustomField>
    <fullName>Statut_equipement__c</fullName>
    <label>Statut equipement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EquipSin_Statut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/recordTypes/Equipement_vole_perdu.recordType-meta.xml
<RecordType>
    <fullName>Equipement_vole_perdu</fullName>
    <active>true</active>
    <description>Equipement non réparable car volé ou perdu</description>
    <label>Equipement Echange</label>
</RecordType>

hubSide/force-app/main/default/objects/Matrice_cout_equipement__c/Matrice_cout_equipement__c.object-meta.xml
<CustomObject>
    <label>Matrice coût equipement</label>
    <nameField>
        <label>Matrice coût equipement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matrice coût equipements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/Mouvements_financiers__c.object-meta.xml
<CustomObject>
    <label>Calcul Indemnisation</label>
    <nameField>
        <label>Nom du mouvement financier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calcul Indemnisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Calcul Indemnisations</relationshipLabel>
    <relationshipName>Mouvements_financiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Cout_choisi__c.field-meta.xml
<CustomField>
    <fullName>Cout_choisi__c</fullName>
    <label>Coût choisi</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primes</fullName>
            </value>
            <value>
                <fullName>Echange</fullName>
            </value>
            <value>
                <fullName>Réparation</fullName>
            </value>
            <value>
                <fullName>Règlement par le client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Libelle__c.field-meta.xml
<CustomField>
    <fullName>Libelle__c</fullName>
    <description>Libéllé libre à saisir par le TC ou le GS</description>
    <label>Libellé</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <description>Identification du montant du mouvement</description>
    <label>Montant</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crée</fullName>
                <default>true</default>
                <label>Crée</label>
            </value>
            <value>
                <fullName>En cours d&apos;approbation</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Demande en cours</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Rejeté</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Terminé</label>
            </value>
            <value>
                <fullName>Invalidated</fullName>
                <label>Invalidé</label>
            </value>
            <value>
                <fullName>En attente d&apos;approbation</fullName>
                <isActive>false</isActive>
                <label>En attente d&apos;approbation</label>
            </value>
            <value>
                <fullName>Encaissé</fullName>
                <isActive>false</isActive>
                <label>Encaissé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Type_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Type_mouvement__c</fullName>
    <label>Type Coût</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cout_choisi__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prime pour echange</fullName>
                <label>Prime pour échange</label>
            </value>
            <value>
                <fullName>Geste commercial</fullName>
            </value>
            <value>
                <fullName>Indemnite retard suite à expertise</fullName>
                <label>Indemnité retard suite à expertise</label>
            </value>
            <value>
                <fullName>Prime pour reparation par le client</fullName>
                <label>Prime pour réparation par le client</label>
            </value>
            <value>
                <fullName>Prime pour communication frauduleuse</fullName>
            </value>
            <value>
                <fullName>Cout interne reparation</fullName>
                <label>Coût interne réparation</label>
            </value>
            <value>
                <fullName>Cout interne d&apos;echange</fullName>
                <label>Coût interne d&apos;échange</label>
            </value>
            <value>
                <fullName>Franchise</fullName>
            </value>
            <value>
                <fullName>Cout prime magasin</fullName>
                <label>Coût prime magasin</label>
            </value>
            <value>
                <fullName>Complément réparation</fullName>
            </value>
            <value>
                <fullName>Cout forfait de reparation</fullName>
                <isActive>false</isActive>
                <label>Coût forfait de réparation</label>
            </value>
            <value>
                <fullName>Remboursement client</fullName>
                <isActive>false</isActive>
                <label>Remboursement client</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/classes/EquipementSinistreTriggerHandlerTest.cls
/***
* @author Nicolas Brancato (GFI)
* @date 22/02/2021
* @description Class test for EquipementSinistreTriggerHandler
*/
@isTest
public class EquipementSinistreTriggerHandlerTest {    
    
    public static final String PROFILE_GS = 'SFAM GS';
    public static final String PROFILE_LOGISTIQUE = 'SFAM Logistique';
    public static User LogisticUser;
    public static User GSUser;
    public static Account a;
    public static Asset c;
    public static Case s;
    public static Mouvements_financiers__c calCulIndemExchange;
    public static Equipement_sinistre__c eqsExchangeWithNoCalculIndemExch;
    public static Equipement_sinistre__c eqs;
    public static Case SinistreNoCalculIndem;
    public static Matrice_cout_equipement__c matrice;
    
    /***
    * @description Static method to initialize all the datas for the test methods
	*/
    static{
        
        // Create two users
        Id profileGSId = [SELECT Id 
                          FROM Profile  
                          WHERE name =: PROFILE_GS].Id;
        Id profileLogisticId = [SELECT Id 
                                FROM Profile  
                                WHERE name =: PROFILE_LOGISTIQUE].Id;
        
        List<User> userToInsert = new List<User>();
        
        GSUser = TestFactory.createUser();
        GSUser.ProfileId = profileGSId;
        GSUser.Email = 'guillaume.gs@yopmail.com';
        userToInsert.add(GSUser);
        
        LogisticUser = TestFactory.createUser();
        LogisticUser.ProfileId = profileLogisticId;
        LogisticUser.Email = 'didier.logistique@yopmail.com';
        LogisticUser.Username = 'didier.logistique@yopmail.com.test';
        userToInsert.add(LogisticUser);
        
        insert userToInsert;

        // Create a new contract as system admin because the contract is sent by Bappli
        c = TestFactory.createAssuranceAssetWithFormula();
        
        // Create two sinistre
        List<Case> caseToInsert = new List<Case>();
        SinistreNoCalculIndem = TestFactory.createSinistre(c.AccountId, c.id);
        caseToInsert.add(SinistreNoCalculIndem);
        s = TestFactory.createSinistre(c.AccountId, c.id);
        caseToInsert.add(s);
        insert caseToInsert;

        matrice = TestFactory.createMatrice(null, true);
        insert matrice;
        
        System.runAs(GSUser){
            
            //Create a calcul indemnisation type exchange
            calCulIndemExchange = TestFactory.createMouvementFinancier(s.id);
            calCulIndemExchange.Libelle__c = 'TEST';
            calCulIndemExchange.Cout_choisi__c = 'Echange';
            calCulIndemExchange.case__c = s.id;
            calCulIndemExchange.Type_mouvement__c = CalculIndemnisationTriggerHandler.COSTTYPE_INTERNCOSTEXCHANGE;
            insert calCulIndemExchange;
            
            // Create an insured item
            vlocity_ins__AssetInsuredItem__c i = new vlocity_ins__AssetInsuredItem__c();
            i.vlocity_ins__PolicyAssetId__c = c.id;
            insert i;
            
            // Create two equipement sinistre - a damaged one and one with no calcul indemnisation exchange type
            List<Equipement_sinistre__c> equipSinToInsert = new List<Equipement_sinistre__c>();
            
            eqs = new Equipement_sinistre__c(Sinistre__c = s.id, 
                                             EquipmentAmount__c = 12, 
                                             RealCost__c = 0, 
                                             Montant_equipement__c = 12, 
                                             equipement_client__c = i.id, 
                                             RecordTypeId = UtilityClassHelper.getCreatedRecordType('Equipement_vole_perdu'));
            equipSinToInsert.add(eqs);
            eqsExchangeWithNoCalculIndemExch = new Equipement_sinistre__c(Sinistre__c = SinistreNoCalculIndem.id);
            equipSinToInsert.add(eqsExchangeWithNoCalculIndemExch);
            insert equipSinToInsert;
        }      
    }
    
    /***
    * @description Update the equipSin name on insert
    * @see handleBeforeInsert
    */
    @isTest
    public static void handleBeforeInsertTest(){
        
        // Get the sinistre and equipSin
        s = [SELECT id, Numero_sinistre__c
             FROM Case
             WHERE id =: s.id];
        eqs = [SELECT id, Name 
               FROM Equipement_sinistre__c
               WHERE id =: eqs.id];
        
        system.assertEquals(true, eqs.Name.contains(s.Numero_sinistre__c), 
                           'The equipSin name shouldve been updated with the sinistres number - This is wrong');        
    }
    
    /***
    * @description Update some insured item fields on equipement sinistre update
    * @see handleEquipSinReparation
    */
    @isTest
    public static void handleEquipSinReparationTest(){
        
        test.startTest();
        
        // Get the equipSin
        eqs = [SELECT id, Sinistre__c, 
               Statut_equipement__c, Equipement_client__c
               FROM Equipement_sinistre__c
               WHERE id =: eqs.id];
        
        // Create a calcul indemnisation
        Mouvements_financiers__c m = new Mouvements_financiers__c();
        m.Case__c = eqs.Sinistre__c;
        m.Cout_choisi__c = 'Echange';
        m.Montant__c = 100;
        insert m;
        
        // Update its status
        eqs.Statut_equipement__c = 'CustomerReception';
        update eqs;
        
        // Get the updated insured item
        vlocity_ins__AssetInsuredItem__c i = [SELECT id, Etat__c, Motif__c, Dernier_sinistre__c, LastReparationDate__c, ReparationCount__c
                                             FROM vlocity_ins__AssetInsuredItem__c
                                             WHERE id =: eqs.Equipement_client__c];
        
        system.assertEquals('inactive', i.Etat__c, 
                           'The insured item status shouldve been updated - This is wrong');
        
        // Get the updated calcul indemnisation
        m = [SELECT id, Statut__c
             FROM Mouvements_financiers__c
             WHERE id =: m.id];
        
        test.stopTest();
        
        system.assertEquals('Completed', m.Statut__c, 
                           'The calc indemn status shouldve been updated - This is wrong');
        
        // Check the new insured item created
        /*vlocity_ins__AssetInsuredItem__c newI = [SELECT id, Dernier_sinistre__c
                                                 FROM vlocity_ins__AssetInsuredItem__c
                                                 WHERE id !=: eqs.Equipement_client__c];
        system.assertEquals(eqs.Sinistre__c, newI.Dernier_sinistre__c, 
                           'A new insured item shouldve been created - This is wrong');*/
    }
    
    /***
    * @description Test method for the handleAfterUpdate method in EquipementSinistreTriggerHandler
    */
    @isTest
    static void test_handlerAfterUpdate() {
        
        Test.startTest();
        System.runAs(GSUser){
            calCulIndemExchange.Statut__c = CalculIndemnisationTriggerHandler.STATUS_DEMANDINPROGRESS;
            update calCulIndemExchange;
            
        	eqs.ClientChoiceDate__c = Date.today();
            eqs.ChooseEqp__c = matrice.Id;
            eqs.EquipmentAmount__c = 10;
            update eqs;
            
            eqsExchangeWithNoCalculIndemExch.ClientChoiceDate__c = Date.today();
            update eqsExchangeWithNoCalculIndemExch;
        }
        Test.stopTest();
        
        // Check whether the calc indemn has been updated with the equipSin real cost
        calCulIndemExchange = [SELECT id, Montant__c 
                               FROM Mouvements_financiers__c 
                               WHERE id =: calCulIndemExchange.id];
        eqs = [SELECT id, RealCost__c FROM Equipement_sinistre__c WHERE id =: eqs.id];
        
        system.assertEquals(eqs.RealCost__c, calCulIndemExchange.Montant__c,
                           'The calcIndemn montant shouldve been updated - This is wrong');
        
        /*TO REFACTORING 
            system.assertEquals(CalculIndemnisationTriggerHandler.STATUS_DEMANDINPROGRESS, 
                            [SELECT id, Statut__c 
                             FROM Mouvements_financiers__c 
                             WHERE id =: calCulIndemExchange.id].Statut__c);*/
    }
    
    
    /***
    * @description Test method for the getStockAfterOrderReception method in EquipementSinistreTriggerHelper
    */
    @isTest
    static void test_getStockAfterOrderReception() {
        
        Test.startTest();
        System.runAs(LogisticUser){
            EquipementSinistreTriggerHelper.getStockAfterOrderReception(new list<id>{eqs.id});
        }
        Test.stopTest();
    }
}