hubSide/force-app/main/default/objects/Account/fields/Equipement_client__c.field-meta.xml
<CustomField>
    <fullName>Equipement_client__c</fullName>
    <label># Equipement client</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Casse__c.field-meta.xml
<CustomField>
    <fullName>Casse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Casse</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Oxydation__c.field-meta.xml
<CustomField>
    <fullName>Oxydation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Oxydation</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Vol_Caracterise__c.field-meta.xml
<CustomField>
    <fullName>Vol_Caracterise__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vol Caractérisé</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Vol_toute_cause__c.field-meta.xml
<CustomField>
    <fullName>Vol_toute_cause__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vol toute cause</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Equipement_client__c.field-meta.xml
<CustomField>
    <fullName>Equipement_client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement client</label>
    <referenceTo>vlocity_ins__AssetInsuredItem__c</referenceTo>
    <relationshipLabel>Demandes associées</relationshipLabel>
    <relationshipName>Demandes_associees</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/tech_numsin__c.field-meta.xml
<CustomField>
    <fullName>tech_numsin__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Champ technique servant à la numérotation des dossiers qui doit garantir sinistre doit garantir :
- l&apos;unicité (aucun doublon)
- la chronologie des numéros (format du numéro de sinistre: SINXXXXXX, &quot;SIN&quot; préfixe invariable et &quot;XXXXXX&quot; séquence incrémentale et choronologique sur 6 chiffres
- la séquentialité (pas de numéro manquant)</description>
    <label>tech_numsin</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Typologie_Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Typologie_Sinistre__c</fullName>
    <label>Typologie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Case_Typologie</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/vlocity_ins__Verified__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verified</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Document__c/fields/Related_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Related_sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Equipement_client__c.field-meta.xml
<CustomField>
    <fullName>Equipement_client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement client</label>
    <referenceTo>vlocity_ins__AssetInsuredItem__c</referenceTo>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/Types_piece_justificative__c.object-meta.xml
<CustomObject>
    <label>Types pièce justificative</label>
    <nameField>
        <label>Types pièce justificative name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types pièce justificative</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/fields/Casse__c.field-meta.xml
<CustomField>
    <fullName>Casse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Casse</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/fields/LongTitle__c.field-meta.xml
<CustomField>
    <fullName>LongTitle__c</fullName>
    <description>Intitulé complet de la pièce justificative à destination des communications clients</description>
    <label>Intitulé</label>
    <length>500</length>
    <type>Html</type>
</CustomField>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/fields/NoTradable__c.field-meta.xml
<CustomField>
    <fullName>NoTradable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non négociable</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/fields/Oxydation__c.field-meta.xml
<CustomField>
    <fullName>Oxydation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Oxydation</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/fields/Perte__c.field-meta.xml
<CustomField>
    <fullName>Perte__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Perte</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/fields/Vol_caracterise__c.field-meta.xml
<CustomField>
    <fullName>Vol_caracterise__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vol caractérisé</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/fields/Vol_toute_cause__c.field-meta.xml
<CustomField>
    <fullName>Vol_toute_cause__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vol toute cause</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Case_Typologie.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Broken</fullName>
        <label>Casse</label>
    </customValue>
    <customValue>
        <fullName>Pickpocketed</fullName>
        <label>Vol toute cause</label>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
        <label>Perte</label>
    </customValue>
    <customValue>
        <fullName>Oxidised</fullName>
        <label>Oxydation</label>
    </customValue>
    <customValue>
        <fullName>Robbed</fullName>
        <label>Vol Caractérisé</label>
    </customValue>
    <customValue>
        <fullName>ReturnedByCarrier</fullName>
        <label>Retour transporteur</label>
    </customValue>
    <customValue>
        <fullName>LostByCarrier</fullName>
        <label>Perte transporteur</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterRepair</fullName>
        <label>Dysfonctionnement suite à réparation</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterExchange</fullName>
        <label>Dysfonctionnement suite à échange</label>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <label>Autres</label>
    </customValue>
    <customValue>
        <fullName>ClaimCreation</fullName>
        <label>Création Réclamation</label>
    </customValue>
    <customValue>
        <fullName>ClaimFollowUp</fullName>
        <label>Suivi Réclamation</label>
    </customValue>
    <customValue>
        <fullName>AccidentCreation</fullName>
        <label>Création Sinistre</label>
    </customValue>
    <description>Liste de toutes les typologies possibles (Sinistre, SAV, Demande)</description>
    <masterLabel>Case_Typologie</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/CaseTriggerHelper.cls
/***
* @author Ariane Tanguy (GFI)
* @date 27/08/2020
* @description Helper class for CaseTrigger
*/

public class CaseTriggerHelper {
    
    /***
	* @description Check all the case tech_numsin__c and assign the max
	* @return Decimal
	*/
    public static Map<String, Decimal> getMaxNumber(List<Case> newCaseList){
        
        // Get the recordTypes
        Set<String> caseRTIdSet = new Set<String>();
        for(Case c : newCaseList){
            caseRTIdSet.add(c.Record_type_Name__c);
            if(c.Record_type_Name__c == 'Sinistre'){
                caseRTIdSet.add('Sinistre clôturé');
            }
        }
        
        Map<String, Decimal> maxNumberMap = new Map<String, Decimal>();
        for(String cId : caseRTIdSet){
            List<Case> c = [SELECT id, tech_numsin__c 
                            FROM Case 
                            WHERE Record_type_name__c =: cId
                            AND vlocity_ins__Verified__c = FALSE
                            ORDER BY tech_numsin__c DESC LIMIT 1];
            if(c.size() > 0){
                maxNumberMap.put(cId, c[0].tech_numsin__c);
            }
        }
        
        return maxNumberMap;
    }

    /***
	* @description get id dispatch sinistre
	* @return Id
	*/
    public static Id getQueueIdDispatchSin(){
        Group gr = [SELECT Id FROM Group WHERE DeveloperName = 'Dispatch_sinistre' and Type = 'Queue' LIMIT 1];
        return gr.Id;
    }
    
    /***
	* @description Get the asset's related account
	* @return Map<id, Account>
	*/
    public static Map<id, Asset> getRelatedAccount(List<Case> newCaseList){
        
        // Get the account ids
        Set<id> assetIdSet = new Set<id>();
        for(Case c : newCaseList){
            assetIdSet.add(c.AssetId);
        }
        
        Map<id, Asset> relatedAssetMap = new Map<id, Asset>([SELECT id, AccountId
                                                             FROM Asset
                                                             WHERE id IN: assetIdSet]);
        return relatedAssetMap;
    }
    
    /***
	* @description Get the related documents
	* @return Map<id, List<Document__c>>
	*/
    public static Map<id, List<Document__c>> getRelatedDocument(List<Case> newCaseList){
        
        // Get the related documents
        List<Document__c> relatedDocumentList = [SELECT id, Related_sinistre__c
                                                FROM Document__c
                                                WHERE Related_sinistre__c IN: newCaseList];
        
        Map<id, List<Document__c>> caseIdDocumentMap = new Map<id, List<Document__c>>();
        for(Document__c d : relatedDocumentList){
            if(!caseIdDocumentMap.keySet().contains(d.Related_sinistre__c)){
                List<Document__c> tmpList = new List<Document__c>();
                caseIdDocumentMap.put(d.Related_sinistre__c, tmpList);
            }
            caseIdDocumentMap.get(d.Related_sinistre__c).add(d);
        }        
        
        return caseIdDocumentMap;
    }
    
    /***
	* @description Get all the related pieces justificatives
	* @param newCaseList - list of new cases
	* @return Map<String, List<Types_piece_justificative__c>>
	*/
    public static Map<String, List<Types_piece_justificative__c>> getRelatedPieceJustificative(List<Case> newCaseList){
                       
        // Query the sinistre cases
        List<Types_piece_justificative__c> relatedPieceJustificativeList = [SELECT id, Name, 
                                                                            LongTitle__c, 
                                                                            Oxydation__c, 
                                                                            Casse__c, 
                                                                            Vol_caracterise__c, 
                                                                            Vol_toute_cause__c, 
                                                                            Perte__c,
                                                                            NoTradable__c
                                                                            FROM Types_piece_justificative__c];
        
        // Map the whole thing 
        Map<String, List<Types_piece_justificative__c>> typologyPieceJustificativeMap = new Map<String, List<Types_piece_justificative__c>>();
        for(Case c : newCaseList){
            
            if(!typologyPieceJustificativeMap.keySet().contains(c.Typologie_Sinistre__c) &&
               c.Typologie_Sinistre__c != NULL){
                   List<Types_piece_justificative__c> tmpList = new List<Types_piece_justificative__c>();
                   typologyPieceJustificativeMap.put(c.Typologie_Sinistre__c, tmpList);
               } else {
                   continue;
               }
            
            for(Types_piece_justificative__c t : relatedPieceJustificativeList){
                
                if((t.Oxydation__c && c.Typologie_Sinistre__c.contains('Oxidised')) ||
                   (t.Casse__c && c.Typologie_Sinistre__c == 'Broken') ||
                   (t.Vol_caracterise__c && c.Typologie_Sinistre__c == 'Robbed') ||
                   (t.Vol_toute_cause__c && c.Typologie_Sinistre__c == 'Pickpocketed') ||
                   (t.Perte__c && c.Typologie_Sinistre__c == 'Lost')){
                       typologyPieceJustificativeMap.get(c.Typologie_Sinistre__c).add(t);
                   }
            }
        }
        
        return typologyPieceJustificativeMap;
    }
    
    /***
	* @description Get all related equipement sinistre
	* @return Map<id, List<Equipement_sinistre__c>>
	*/
    public static Map<id, List<Equipement_sinistre__c>> getRelatedEquipSin(List<Case> newCaseList){
        
        List<Equipement_sinistre__c> relatedEquipSinList = [SELECT id, Name, Equipement_client__r.Name, Sinistre__c
                                                            FROM Equipement_sinistre__c
                                                            WHERE Sinistre__c IN: newCaseList];
        
        Map<id, List<Equipement_sinistre__c>> relatedEquipSinMap = new Map<id, List<Equipement_sinistre__c>>();
        for(Equipement_sinistre__c e : relatedEquipSinList){
            if(!relatedEquipSinMap.keySet().contains(e.Sinistre__c)){
                List<Equipement_sinistre__c> tmpList = new List<Equipement_sinistre__c>();
                relatedEquipSinMap.put(e.Sinistre__c, tmpList);
            }
            relatedEquipSinMap.get(e.Sinistre__c).add(e);
        }
        
        return relatedEquipSinMap;
    }
}