hubSide/force-app/main/default/objects/Account/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <description>Id externe pour l&apos;intégration API</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Id_contrat_B_appli__c.field-meta.xml
<CustomField>
    <fullName>Id_contrat_B_appli__c</fullName>
    <label>Id contrat B-appli</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <description>Id Externe utilisé par les interfaces pour l&apos;Upsert et stocké l&apos;Id du sytème source</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/CalloutErrorsManagement__c.object-meta.xml
<CustomObject>
    <description>This object allows to store all information from callout of Salesforce platform.</description>
    <label>Management of Callout Errors</label>
    <nameField>
        <label>Callout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management of Callout Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/fields/CalloutErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>CalloutErrorMessage__c</fullName>
    <description>Message to identify the error. Link to the error code</description>
    <label>Error message in the callout</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/fields/CalloutStatusCode__c.field-meta.xml
<CustomField>
    <fullName>CalloutStatusCode__c</fullName>
    <description>Status code to identify the answer.</description>
    <label>Status code in the callout</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/fields/CaseRecord__c.field-meta.xml
<CustomField>
    <fullName>CaseRecord__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the case</description>
    <label>Case Record</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Management of Callout Errors</relationshipLabel>
    <relationshipName>ManagementCalloutErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <description>Id externe pour l&apos;intégration API</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Demande.recordType-meta.xml
<RecordType>
    <fullName>Demande</fullName>
    <active>true</active>
    <businessProcess>Demande</businessProcess>
    <description>Demande relative à de nouveaux documents client</description>
    <label>Demande</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/BAppliStockFluctuationRef__c.field-meta.xml
<CustomField>
    <fullName>BAppliStockFluctuationRef__c</fullName>
    <label>Numéro de mouvement de stock BAppli</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/ClientChoiceDate__c.field-meta.xml
<CustomField>
    <fullName>ClientChoiceDate__c</fullName>
    <label>Date choix client</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Id externe pour l&apos;intégration API qui est l&apos;Id du Case parent via le Web et est alimenté en post default value à Id si vide</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/SerieNumberEC__c.field-meta.xml
<CustomField>
    <fullName>SerieNumberEC__c</fullName>
    <label>Numero de serie (IMEI)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Statut_equipement__c.field-meta.xml
<CustomField>
    <fullName>Statut_equipement__c</fullName>
    <label>Statut equipement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EquipSin_Statut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/Mouvements_financiers__c.object-meta.xml
<CustomObject>
    <label>Calcul Indemnisation</label>
    <nameField>
        <label>Nom du mouvement financier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calcul Indemnisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Calcul Indemnisations</relationshipLabel>
    <relationshipName>Mouvements_financiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Cout_choisi__c.field-meta.xml
<CustomField>
    <fullName>Cout_choisi__c</fullName>
    <label>Coût choisi</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primes</fullName>
            </value>
            <value>
                <fullName>Echange</fullName>
            </value>
            <value>
                <fullName>Réparation</fullName>
            </value>
            <value>
                <fullName>Règlement par le client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <description>Identification du montant du mouvement</description>
    <label>Montant</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Paiement_Versement__c.field-meta.xml
<CustomField>
    <fullName>Paiement_Versement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paiement Versement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Paiement_Versement__c.Case__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Paiement_Versement__c</referenceTo>
    <relationshipName>Mouvements_financiers</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Sens_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Sens_mouvement__c</fullName>
    <label>Sens du mouvement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paiement vers le client</fullName>
            </value>
            <value>
                <fullName>Règlement par le client</fullName>
            </value>
            <value>
                <fullName>Interne reparation</fullName>
                <label>Interne réparation</label>
            </value>
            <value>
                <fullName>Interne échange</fullName>
            </value>
            <value>
                <fullName>Interne</fullName>
                <isActive>false</isActive>
                <label>Interne</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crée</fullName>
                <default>true</default>
                <label>Crée</label>
            </value>
            <value>
                <fullName>En cours d&apos;approbation</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Demande en cours</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Rejeté</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Terminé</label>
            </value>
            <value>
                <fullName>Invalidated</fullName>
                <label>Invalidé</label>
            </value>
            <value>
                <fullName>En attente d&apos;approbation</fullName>
                <isActive>false</isActive>
                <label>En attente d&apos;approbation</label>
            </value>
            <value>
                <fullName>Encaissé</fullName>
                <isActive>false</isActive>
                <label>Encaissé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Type_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Type_mouvement__c</fullName>
    <label>Type Coût</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cout_choisi__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prime pour echange</fullName>
                <label>Prime pour échange</label>
            </value>
            <value>
                <fullName>Geste commercial</fullName>
            </value>
            <value>
                <fullName>Indemnite retard suite à expertise</fullName>
                <label>Indemnité retard suite à expertise</label>
            </value>
            <value>
                <fullName>Prime pour reparation par le client</fullName>
                <label>Prime pour réparation par le client</label>
            </value>
            <value>
                <fullName>Prime pour communication frauduleuse</fullName>
            </value>
            <value>
                <fullName>Cout interne reparation</fullName>
                <label>Coût interne réparation</label>
            </value>
            <value>
                <fullName>Cout interne d&apos;echange</fullName>
                <label>Coût interne d&apos;échange</label>
            </value>
            <value>
                <fullName>Franchise</fullName>
            </value>
            <value>
                <fullName>Cout prime magasin</fullName>
                <label>Coût prime magasin</label>
            </value>
            <value>
                <fullName>Complément réparation</fullName>
            </value>
            <value>
                <fullName>Cout forfait de reparation</fullName>
                <isActive>false</isActive>
                <label>Coût forfait de réparation</label>
            </value>
            <value>
                <fullName>Remboursement client</fullName>
                <isActive>false</isActive>
                <label>Remboursement client</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/Paiement_Versement__c.object-meta.xml
<CustomObject>
    <label>Paiement Versement</label>
    <nameField>
        <label>Paiement Versement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paiement Versement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/BAppliEventId__c.field-meta.xml
<CustomField>
    <fullName>BAppliEventId__c</fullName>
    <externalId>true</externalId>
    <label>BAppliEventId</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Paiement Versement</relationshipLabel>
    <relationshipName>Paiement_Versement</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Paiement_Versement__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demande Paiement</fullName>
            </value>
            <value>
                <fullName>Payé Client</fullName>
            </value>
            <value>
                <fullName>Demande Versement</fullName>
            </value>
            <value>
                <fullName>Versé Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/classes/BAppliCalloutTest.cls
/***
* @author Nicolas Brancato (GFI)
* @date 20/01/2021
* @description Callout class test for outbound call with BAppli services
* DATE          DEV         DESCRIPTION
*/
@isTest
public class BAppliCalloutTest {    
    
	static final String STATUS_TRANSFER = 'Demande Versement';
    public static final String PROFILE_GS = 'SFAM GS';
    public static User GSUser;
    public static Asset c;
    public static Asset wrongContract;
    public static Case s;
    public static Case wrongSinistre;
    public static Mouvements_financiers__c mf;
    public static Mouvements_financiers__c calCulIndemExchange;
    public static Mouvements_financiers__c calCulIndemExchangeWithNoDamagedEquipmentExch;
    public static Equipement_sinistre__c eqs;
    
    /***
    * @description Static method to initialize all the datas for the test methods
    */
    static{
        
        GSUser = TestFactory.createUser();
        GSUser.ProfileId = [SELECT Id FROM Profile WHERE name =: PROFILE_GS].Id;
        GSUser.Email = 'guillaume.gs@yopmail.com';
        insert GSUser;
        
        // Create two contracts
        List<Asset> assetList = TestFactory.createAssuranceAssetList(2);
        
        // Create a new contract as system admin because the contract is sent by Bappli        
        c = assetList[0];
        c.Name = '0220010102';
        c.Id_externe__c = 'INS0220010102';
        c.Id_contrat_B_appli__c = '5343473';
        
        // Create a wrong contract which is not existing in Bappli
        wrongContract = assetList[1];
        wrongContract.Name = '0220010102';
        wrongContract.Id_externe__c = 'INS0220010103';
        wrongContract.Id_contrat_B_appli__c = '000000';
        insert assetList;
        
        List<Account> accList = [SELECT id FROM Account];
        
        // Create two cases
        List<Case> caseList = TestFactory.createSinistreList(accList, assetList, 2);
        s = caseList[0];
        wrongSinistre = caseList[1];
        insert caseList;
        
        System.runAs(GSUser){
            
            // Create three calcul indemnisation
            List<Mouvements_financiers__c> mvtFinToInsertList = new List<Mouvements_financiers__c>();
            
            mf = TestFactory.createMouvementFinancier(s.id);
			mf.Sens_mouvement__c = 'Règlement par le client';
            mf.Type_mouvement__c = null;
			mvtFinToInsertList.add(mf); 
            
            //Create a calcul indemnisation type exchange
            calCulIndemExchange = TestFactory.createMouvementFinancier(s.id);
            calCulIndemExchange.Cout_choisi__c = 'Echange';
            calCulIndemExchange.Type_mouvement__c = CalculIndemnisationTriggerHandler.COSTTYPE_INTERNCOSTEXCHANGE;
            mvtFinToInsertList.add(calCulIndemExchange);
            
            //Create a calcul indemnisation type exchange with no damaged equipment
            calCulIndemExchangeWithNoDamagedEquipmentExch = TestFactory.createMouvementFinancier(wrongSinistre.id);
            calCulIndemExchangeWithNoDamagedEquipmentExch.Cout_choisi__c = 'Echange';
            calCulIndemExchangeWithNoDamagedEquipmentExch.Type_mouvement__c = CalculIndemnisationTriggerHandler.COSTTYPE_INTERNCOSTEXCHANGE;
            mvtFinToInsertList.add(calCulIndemExchangeWithNoDamagedEquipmentExch);
            insert mvtFinToInsertList;
            
            Id rtId = UtilityClassHelper.getCreatedRecordType(CalculIndemnisationTriggerHelper.DAMAGEDEQUIPMENTRECORDTYPE_ECHANGE);
            // Create a damaged equipement
        	eqs = new Equipement_sinistre__c(Sinistre__c = s.id, ClientChoiceDate__c = Date.today(), RecordTypeId = rtId );
        	insert eqs;
        }      
    }
    
    
    /***
    * @description Test method for the CalculIndemnisationTrigger and the getFROMStock method in BAppliCallout class. 
    * This test method mocks a fake response with a success in return.
    * The body returns an imei number, a stock fluctuation reference and the cost of material removed FROM storage.
    */
    @isTest
    static void test_getFromStock200() {
        
        HttpMockFactory mock = new HttpMockFactory(200, '', 
                                                   '{"imei":"355328086961253","stockFluctuationRef":"NUM_99999999","cost":"100"}', 
                                                   new Map<String,String>{'Keep-Alive' => 'yes'});
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        
        System.runAs(GSUser){
        	calCulIndemExchange.Statut__c = CalculIndemnisationTriggerHandler.STATUS_DEMANDINPROGRESS;
            update calCulIndemExchange;
        }
        Test.stopTest();
        
        system.assertEquals(BAppliCallout.DAMAGEDEQUIPMENTSTATUS_DESTOCK, [SELECT id, Statut_equipement__c 
                                                                           FROM Equipement_sinistre__c 
                                                                           WHERE id =: eqs.id].Statut_equipement__c);
        system.assertEquals('355328086961253', [SELECT id, SerieNumberEC__c 
                                                FROM Equipement_sinistre__c 
                                                WHERE id =: eqs.id].SerieNumberEC__c);
        system.assertEquals('NUM_99999999', [SELECT id, BAppliStockFluctuationRef__c 
                                             FROM Equipement_sinistre__c 
                                             WHERE id =: eqs.id].BAppliStockFluctuationRef__c);
        system.assertEquals(null, [SELECT id, CalloutErrorMessage__c 
                                   FROM CalloutErrorsManagement__c 
                                   WHERE CaseRecord__c =: s.id].CalloutErrorMessage__c);
        system.assertEquals(200, Integer.valueOf([SELECT id, CalloutStatusCode__c 
                                                  FROM CalloutErrorsManagement__c 
                                                  WHERE CaseRecord__c =: s.id].CalloutStatusCode__c));
    }
    
    /***
    * @description Test method for the CalculIndemnisationTrigger and the getFromStock method in BAppliCallout class. 
    * This test method mocks a fake response with a 404 error in return.
    * A 404 error from Bappli means the error is functional. 
    * Possible message is « imei not available ».
    */
    @isTest
    static void test_getFromStock404() {
        
        HttpMockFactory mock = new HttpMockFactory(404,'Bad Request', 'imei not available', new Map<String,String>{'Keep-Alive' => 'yes'});
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        
        System.runAs(GSUser){
        	calCulIndemExchange.Statut__c = CalculIndemnisationTriggerHandler.STATUS_DEMANDINPROGRESS;
            update calCulIndemExchange;
        }
        Test.stopTest();
        
        system.assertEquals(BAppliCallout.DAMAGEDEQUIPMENTSTATUS_ORDER, [SELECT id, Statut_equipement__c 
                                                                         FROM Equipement_sinistre__c 
                                                                         WHERE id =: eqs.id].Statut_equipement__c);
        system.assertEquals(null, [SELECT id, BAppliStockFluctuationRef__c 
                                   FROM Equipement_sinistre__c 
                                   WHERE id =: eqs.id].BAppliStockFluctuationRef__c);
        system.assert([SELECT id, CalloutErrorMessage__c 
                       FROM CalloutErrorsManagement__c 
                       WHERE CaseRecord__c =: s.id].CalloutErrorMessage__c.contains('imei not available'));
        system.assertEquals(404, Integer.valueOf([SELECT id, CalloutStatusCode__c 
                                                  FROM CalloutErrorsManagement__c 
                                                  WHERE CaseRecord__c =: s.id].CalloutStatusCode__c));
    }
    
    /***
    * @description Test method for the CalculIndemnisationTrigger and the getFromStock method in BAppliCallout class. 
    * This test method mock a fake response with a 500 error in return.
    * A 500 error from Bappli means the error is technical. Possible message can be « erreur interne ».
    */
    @isTest
    static void test_getFromStock500() {
        
        HttpMockFactory mock = new HttpMockFactory(500,'Bad Request', 'erreur interne', new Map<String,String>{'Keep-Alive' => 'yes'});
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        System.runAs(GSUser){
        	calCulIndemExchange.Statut__c = CalculIndemnisationTriggerHandler.STATUS_DEMANDINPROGRESS;
            update calCulIndemExchange;
        }
        Test.stopTest();
        system.assertEquals(null, [SELECT id, SerieNumberEC__c 
                                   FROM Equipement_sinistre__c 
                                   WHERE id =: eqs.id].SerieNumberEC__c);
        system.assertEquals(null, [SELECT id, BAppliStockFluctuationRef__c 
                                   FROM Equipement_sinistre__c 
                                   WHERE id =: eqs.id].BAppliStockFluctuationRef__c);
        system.assert([SELECT id, CalloutErrorMessage__c 
                       FROM CalloutErrorsManagement__c 
                       WHERE CaseRecord__c =: s.id].CalloutErrorMessage__c.contains('erreur interne'));
        system.assertEquals(500, Integer.valueOf([SELECT id, CalloutStatusCode__c 
                                                  FROM CalloutErrorsManagement__c 
                                                  WHERE CaseRecord__c =: s.id].CalloutStatusCode__c));
    }
    
    
    /***
    * @description Test method for the CalculIndemnisationTrigger and the getFromStock method in BAppliCallout class. This test method mock a catch exception.
    */
    @isTest
    static void test_getFromStockCatchTest() {
        
        HttpMockFactory mock = new HttpMockFactory(200,'', '{\'imei\' => \'355328086961253\',\'stockFluctuationRef\' => \'NUM_99999999\',\'cost\' => \'100\'}',
                                                   new Map<String,String>{'Keep-Alive' => 'yes'});
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        System.runAs(GSUser){
        	calCulIndemExchange.Statut__c = CalculIndemnisationTriggerHandler.STATUS_DEMANDINPROGRESS;
            update calCulIndemExchange;
        }
        Test.stopTest();
        system.assertEquals(null, [SELECT id, SerieNumberEC__c 
                                   FROM Equipement_sinistre__c 
                                   WHERE id =: eqs.id].SerieNumberEC__c);
        system.assertEquals(null, [SELECT id, BAppliStockFluctuationRef__c 
                                   FROM Equipement_sinistre__c 
                                   WHERE id =: eqs.id].BAppliStockFluctuationRef__c);
        system.assertNotEquals(null, [SELECT id, CalloutErrorMessage__c 
                                      FROM CalloutErrorsManagement__c 
                                      WHERE CaseRecord__c =: s.id].CalloutErrorMessage__c);
        system.assertEquals(200, Integer.valueOf([SELECT id, CalloutStatusCode__c 
                                                  FROM CalloutErrorsManagement__c 
                                                  WHERE CaseRecord__c =: s.id].CalloutStatusCode__c));
    }
    
    
	/***
    * @description Test method for the PaiementVersementTrigger and the sendPayment method in BAppliCallout class.
    * This test method mock a fake response with a success in return.
    * The Bappli event identifiant is returned in the body.
    */
    @isTest
    static void test_sendPayment200() {
        
        HttpMockFactory mock = new HttpMockFactory(200,'', '1860219693', new Map<String,String>{'Keep-Alive' => 'yes'});
        Test.setMock(HttpCalloutMock.class, mock);
        Paiement_Versement__c pv;
        Test.startTest();
        System.runAs(GSUser){
            pv = new Paiement_Versement__c(Case__c = s.id, 
                                           Montant__c = mf.Montant__c, 
                                           Name = 'REG' +'-'+ string.valueof(DateTime.Now())+' - GMT', Statut__c = STATUS_TRANSFER);
            insert pv;            
        }
        Test.stopTest();
        system.assertEquals('1860219693', [SELECT id, BAppliEventId__c FROM Paiement_Versement__c WHERE id =: pv.id].BAppliEventId__c);
        system.assertEquals(null, [SELECT id, CalloutErrorMessage__c 
                                   FROM CalloutErrorsManagement__c 
                                   WHERE PaiementVersementLink__c =: pv.id].CalloutErrorMessage__c);
        system.assertEquals(200, Integer.valueOf([SELECT id, CalloutStatusCode__c 
                                                  FROM CalloutErrorsManagement__c 
                                                  WHERE PaiementVersementLink__c =: pv.id].CalloutStatusCode__c));
    }
    
    
    /***
    * @description Test method for the PaiementVersementTrigger and the sendPayment method in BAppliCallout class. 
    * This test method mock a fake response with a 400 error in return.
    * A 400 error from Bappli means the error is functional. 
    * Possible messages can be « type not found », « contract not found », « user not found », « invalid amount ».
    */
    @isTest
    static void test_sendPayment400() {
        
        HttpMockFactory mock = new HttpMockFactory(400,'Bad Request', 'contract not found', new Map<String,String>{'Keep-Alive' => 'yes'});
        Test.setMock(HttpCalloutMock.class, mock);
        Paiement_Versement__c pv;
        Test.startTest();
        System.runAs(GSUser){
            pv = new Paiement_Versement__c(Case__c = wrongSinistre.id, 
                                           Montant__c = mf.Montant__c, 
                                           Name = 'REG' +'-'+ string.valueof(DateTime.Now())+' - GMT', 
                                           Statut__c = STATUS_TRANSFER);
            insert pv;
        }
        Test.stopTest();
        system.assertEquals(null, [SELECT id, BAppliEventId__c FROM Paiement_Versement__c WHERE id =: pv.id].BAppliEventId__c);
        system.assert([SELECT id, CalloutErrorMessage__c 
                       FROM CalloutErrorsManagement__c 
                       WHERE PaiementVersementLink__c =: pv.id].CalloutErrorMessage__c.contains('contract not found'));
        system.assertEquals(400, Integer.valueOf([SELECT id, CalloutStatusCode__c 
                                                  FROM CalloutErrorsManagement__c 
                                                  WHERE PaiementVersementLink__c =: pv.id].CalloutStatusCode__c));
    }
    
    
    /***
    * @description Test method for the PaiementVersementTrigger and the sendPayment method in BAppliCallout class. 
    * This test method mock a fake response with a 500 error in return.
    * A 500 error from Bappli means the error is technical. Possible message can be « erreur interne de création du paiement ».
    */
    @isTest
    static void test_sendPayment500() {
        
        HttpMockFactory mock = new HttpMockFactory(500,'Bad Request', 'erreur interne de création du paiement', new Map<String,String>{'Keep-Alive' => 'yes'});
        Test.setMock(HttpCalloutMock.class, mock);
        Paiement_Versement__c pv;
        Test.startTest();
        System.runAs(GSUser){
            pv = new Paiement_Versement__c(Case__c = wrongSinistre.id, 
                                           Montant__c = mf.Montant__c, 
                                           Name = 'REG' +'-'+ string.valueof(DateTime.Now())+' - GMT', 
                                           Statut__c = STATUS_TRANSFER);
            insert pv;
        }
        Test.stopTest();
        system.assertEquals(null, [SELECT id, BAppliEventId__c FROM Paiement_Versement__c WHERE id =: pv.id].BAppliEventId__c);
        system.assert([SELECT id, CalloutErrorMessage__c 
                       FROM CalloutErrorsManagement__c 
                       WHERE PaiementVersementLink__c =: pv.id].CalloutErrorMessage__c.contains('erreur interne de création du paiement'));
        system.assertEquals(500, Integer.valueOf([SELECT id, CalloutStatusCode__c 
                                                  FROM CalloutErrorsManagement__c 
                                                  WHERE PaiementVersementLink__c =: pv.id].CalloutStatusCode__c));
    }
    
    /***
    * @description Test method for the PaiementVersementTrigger and the sendPayment method in BAppliCallout class. 
    * This test method mock a catch exception.
    */
    @isTest
    static void test_sendPaymentCatchTest() {
        
        HttpMockFactory mock = new HttpMockFactory(null,'', null, new Map<String,String>{'Keep-Alive' => 'yes'});
        Test.setMock(HttpCalloutMock.class, mock);
        Paiement_Versement__c pv;
        Test.startTest();
        System.runAs(GSUser){
            pv = new Paiement_Versement__c(Case__c = wrongSinistre.id, 
                                           Montant__c = mf.Montant__c, 
                                           Name = 'REG' +'-'+ string.valueof(DateTime.Now())+' - GMT', 
                                           Statut__c = STATUS_TRANSFER);
            insert pv;
        }
        Test.stopTest();
        system.assertEquals(null, [SELECT id, BAppliEventId__c FROM Paiement_Versement__c WHERE id =: pv.id].BAppliEventId__c);
        system.assert([SELECT id, CalloutErrorMessage__c 
                       FROM CalloutErrorsManagement__c 
                       WHERE PaiementVersementLink__c =: pv.id].CalloutErrorMessage__c.contains('Argument 1 cannot be null'));
    }  
}