hubSide/force-app/main/default/objects/Account/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <description>Id externe pour l&apos;intégration API</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <description>Id Externe utilisé par les interfaces pour l&apos;Upsert et stocké l&apos;Id du sytème source</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/ClosedDateBappli__c.field-meta.xml
<CustomField>
    <fullName>ClosedDateBappli__c</fullName>
    <description>Date de cloture du sinistre dans le système externe (B-Appli)</description>
    <label>Date de clôture B-Appli</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <description>Id externe pour l&apos;intégration API</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Montant_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Montant_sinistre__c</fullName>
    <label>Coût global</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/TECH_StorePremium__c.field-meta.xml
<CustomField>
    <fullName>TECH_StorePremium__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Renvoie en lookup vers le magasin choisi par le client pour prime d&apos;échange</description>
    <label>Magasin</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Distributeur location</value>
        </filterItems>
        <filterItems>
            <field>Account.StorePremiumEligible__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Demande.recordType-meta.xml
<RecordType>
    <fullName>Demande</fullName>
    <active>true</active>
    <businessProcess>Demande</businessProcess>
    <description>Demande relative à de nouveaux documents client</description>
    <label>Demande</label>
</RecordType>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Contact/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <description>Id externe pour l&apos;intégration API</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/ChooseEqp__c.field-meta.xml
<CustomField>
    <fullName>ChooseEqp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modèle-choisi</label>
    <referenceTo>Matrice_cout_equipement__c</referenceTo>
    <relationshipLabel>Equipement sinistre (Equipement C)</relationshipLabel>
    <relationshipName>Equipement_sinistre1</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/ClientChoiceDate__c.field-meta.xml
<CustomField>
    <fullName>ClientChoiceDate__c</fullName>
    <label>Date choix client</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GradeEquipSin</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Id externe pour l&apos;intégration API qui est l&apos;Id du Case parent via le Web et est alimenté en post default value à Id si vide</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <description>Telephony operator</description>
    <label>Opérateur</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OperatorCountry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Operators</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sous_statut__c.field-meta.xml
<CustomField>
    <fullName>Sous_statut__c</fullName>
    <label>Sous-statut</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Statut_equipement__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>EquipSin_SousStatut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Statut_equipement__c.field-meta.xml
<CustomField>
    <fullName>Statut_equipement__c</fullName>
    <label>Statut equipement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EquipSin_Statut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/recordTypes/Equipement_a_reparer.recordType-meta.xml
<RecordType>
    <fullName>Equipement_a_reparer</fullName>
    <active>true</active>
    <description>Equipement à réparer parce que cassé ou oxydé</description>
    <label>Equipement Réparation</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/recordTypes/Equipement_vole_perdu.recordType-meta.xml
<RecordType>
    <fullName>Equipement_vole_perdu</fullName>
    <active>true</active>
    <description>Equipement non réparable car volé ou perdu</description>
    <label>Equipement Echange</label>
</RecordType>

hubSide/force-app/main/default/objects/Matrice_cout_equipement__c/Matrice_cout_equipement__c.object-meta.xml
<CustomObject>
    <label>Matrice coût equipement</label>
    <nameField>
        <label>Matrice coût equipement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matrice coût equipements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Matrice_cout_equipement__c/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <description>Utilisé pour la jointure avec le catalogue équipement et par les API sortants de Déstockage.</description>
    <externalId>true</externalId>
    <label>Id Externe B-appli Equipement Echange</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/Mouvements_financiers__c.object-meta.xml
<CustomObject>
    <label>Calcul Indemnisation</label>
    <nameField>
        <label>Nom du mouvement financier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calcul Indemnisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Calcul Indemnisations</relationshipLabel>
    <relationshipName>Mouvements_financiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Cout_choisi__c.field-meta.xml
<CustomField>
    <fullName>Cout_choisi__c</fullName>
    <label>Coût choisi</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primes</fullName>
            </value>
            <value>
                <fullName>Echange</fullName>
            </value>
            <value>
                <fullName>Réparation</fullName>
            </value>
            <value>
                <fullName>Règlement par le client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Indemnisation_date__c.field-meta.xml
<CustomField>
    <fullName>Indemnisation_date__c</fullName>
    <label>Date Indemnisation</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <description>Identification du montant du mouvement</description>
    <label>Montant</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crée</fullName>
                <default>true</default>
                <label>Crée</label>
            </value>
            <value>
                <fullName>En cours d&apos;approbation</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Demande en cours</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Rejeté</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Terminé</label>
            </value>
            <value>
                <fullName>Invalidated</fullName>
                <label>Invalidé</label>
            </value>
            <value>
                <fullName>En attente d&apos;approbation</fullName>
                <isActive>false</isActive>
                <label>En attente d&apos;approbation</label>
            </value>
            <value>
                <fullName>Encaissé</fullName>
                <isActive>false</isActive>
                <label>Encaissé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/TECH_AssetID__c.field-meta.xml
<CustomField>
    <fullName>TECH_AssetID__c</fullName>
    <formula>Case__r.AssetId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_AssetID</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Type_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Type_mouvement__c</fullName>
    <label>Type Coût</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cout_choisi__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prime pour echange</fullName>
                <label>Prime pour échange</label>
            </value>
            <value>
                <fullName>Geste commercial</fullName>
            </value>
            <value>
                <fullName>Indemnite retard suite à expertise</fullName>
                <label>Indemnité retard suite à expertise</label>
            </value>
            <value>
                <fullName>Prime pour reparation par le client</fullName>
                <label>Prime pour réparation par le client</label>
            </value>
            <value>
                <fullName>Prime pour communication frauduleuse</fullName>
            </value>
            <value>
                <fullName>Cout interne reparation</fullName>
                <label>Coût interne réparation</label>
            </value>
            <value>
                <fullName>Cout interne d&apos;echange</fullName>
                <label>Coût interne d&apos;échange</label>
            </value>
            <value>
                <fullName>Franchise</fullName>
            </value>
            <value>
                <fullName>Cout prime magasin</fullName>
                <label>Coût prime magasin</label>
            </value>
            <value>
                <fullName>Complément réparation</fullName>
            </value>
            <value>
                <fullName>Cout forfait de reparation</fullName>
                <isActive>false</isActive>
                <label>Coût forfait de réparation</label>
            </value>
            <value>
                <fullName>Remboursement client</fullName>
                <isActive>false</isActive>
                <label>Remboursement client</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Name__c/Name__c.object-meta.xml
<CustomObject>
    <label>Historique</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historique</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Name__c/fields/Equipement_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Equipement_sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement sinistré</label>
    <referenceTo>Equipement_sinistre__c</referenceTo>
    <relationshipLabel>Historique</relationshipLabel>
    <relationshipName>Historique</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/globalValueSets/EquipSin_SousStatut.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A stocker</fullName>
    </customValue>
    <customValue>
        <fullName>Stocké</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir - Retour client</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir - Retour SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir du stock</fullName>
    </customValue>
    <customValue>
        <fullName>Sortie PSM</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir PSM</fullName>
    </customValue>
    <customValue>
        <fullName>A retourner PSM</fullName>
    </customValue>
    <customValue>
        <fullName>A dispatcher</fullName>
    </customValue>
    <customValue>
        <fullName>En cours d&apos;expertise</fullName>
    </customValue>
    <customValue>
        <fullName>En attente GS</fullName>
    </customValue>
    <customValue>
        <fullName>En cours</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - A expédier</fullName>
    </customValue>
    <customValue>
        <fullName>Préparation</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - A conserver</fullName>
    </customValue>
    <customValue>
        <fullName>Retourné client</fullName>
    </customValue>
    <customValue>
        <fullName>Repaired</fullName>
        <label>Réparé</label>
    </customValue>
    <customValue>
        <fullName>Unrepairable</fullName>
        <label>Irréparable</label>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <label>Annulé</label>
    </customValue>
    <customValue>
        <fullName>Via prime</fullName>
    </customValue>
    <customValue>
        <fullName>Via prime magasin</fullName>
    </customValue>
    <customValue>
        <fullName>Réception client</fullName>
    </customValue>
    <customValue>
        <fullName>Conservé SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - à expédier (Irréparable)</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - à expédier (Annulé)</fullName>
    </customValue>
    <customValue>
        <fullName>Préparation - Irréparable/Annulé</fullName>
    </customValue>
    <customValue>
        <fullName>Retour Client</fullName>
    </customValue>
    <customValue>
        <fullName>Retour SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>Sorti PSM</fullName>
        <isActive>false</isActive>
        <label>Sorti PSM</label>
    </customValue>
    <description>Liste des sous-statuts de l&apos;équipement sinistré - Equipement sinistre sub status list</description>
    <masterLabel>EquipSin_SousStatut</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/globalValueSets/GradeEquipSin.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NEUF</fullName>
        <label>Neuf</label>
    </customValue>
    <customValue>
        <fullName>GRADE1</fullName>
        <label>Grade 1</label>
    </customValue>
    <customValue>
        <fullName>GRADE2</fullName>
        <label>Grade 2</label>
    </customValue>
    <customValue>
        <fullName>GRADE3</fullName>
        <label>Grade 3</label>
    </customValue>
    <customValue>
        <fullName>Grade 2temp</fullName>
        <isActive>false</isActive>
        <label>Grade 2temp</label>
    </customValue>
    <customValue>
        <fullName>Grade 1temp</fullName>
        <isActive>false</isActive>
        <label>Grade 1temp</label>
    </customValue>
    <customValue>
        <fullName>Neuftemp</fullName>
        <isActive>false</isActive>
        <label>Neuftemp</label>
    </customValue>
    <customValue>
        <fullName>Grade 3temp</fullName>
        <isActive>false</isActive>
        <label>Grade 3temp</label>
    </customValue>
    <description>Grades des équipements sinistrés - Equipement rank values</description>
    <masterLabel>Grade équipement sinistré</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/globalValueSets/Operators.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BASE</fullName>
    </customValue>
    <customValue>
        <fullName>BEANDYOU</fullName>
        <label>BE AND  YOU</label>
    </customValue>
    <customValue>
        <fullName>BOUYGUES</fullName>
    </customValue>
    <customValue>
        <fullName>CORIOLIS</fullName>
    </customValue>
    <customValue>
        <fullName>CREDITMUTUEL</fullName>
        <label>CREDIT MUTUEL</label>
    </customValue>
    <customValue>
        <fullName>FREE</fullName>
    </customValue>
    <customValue>
        <fullName>JOMOBILE</fullName>
    </customValue>
    <customValue>
        <fullName>LAPOSTEMOBILE</fullName>
        <label>LA POSTE MOBILE</label>
    </customValue>
    <customValue>
        <fullName>NRJ</fullName>
    </customValue>
    <customValue>
        <fullName>ORANGE</fullName>
    </customValue>
    <customValue>
        <fullName>REDSFR</fullName>
        <label>RED SFR</label>
    </customValue>
    <customValue>
        <fullName>SFR</fullName>
    </customValue>
    <customValue>
        <fullName>SIMPLEO</fullName>
    </customValue>
    <customValue>
        <fullName>SOSH</fullName>
    </customValue>
    <customValue>
        <fullName>VIRGIN</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER</fullName>
        <label>AUTRE</label>
    </customValue>
    <description>Telephony operators</description>
    <masterLabel>Operators</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/CalculIndemnisationTriggerHelper.cls
/***
* @author Nicolas Brancato (GFI)
* @date 11/02/2020
* @description Helper class for CalculIndemnisationTrigger
*/


public class CalculIndemnisationTriggerHelper {    
    
    public static final String DAMAGEDEQUIPMENTRECORDTYPE_ECHANGE = 'Equipement_vole_perdu';
    public static final String EQUIPMENTRECORDTYPE_REPAIR = 'Equipement_a_reparer';
    public static final String TASKCOMMUNICATIONCHANNEL_OUTBOUNDEMAIL = 'Mail sortant';
    public static final String EQUIPMENTSINISTRE_STATUS_INPROGRESSREPAIR = 'En Cours de Réparation';
    public static final String EQUIPMENTSINISTRE_UNDERSTATUS_INPROGRESS = 'En cours';
    public static final String EQUIPMENTSINISTRE_STATUS_EXCHANGE = 'Echangé';
    public static final String EQUIPMENTSINISTRE_UNDERSTATUS_PRENIUM = 'Via prime';
    public static final String TASK_SUBJECT_REPAIRVALID = 'Réparation validée';
    public static final String STATUS_CREATED = 'Crée';
    public static final String INSUREDITEM_STATUS_INACTIVE = 'inactive';
    public static final String INSUREDITEM_REASON_EXCHANGE = 'Echange';
    
	/***
	* @description Get datas on the Equipement_sinistre__c to trigger destock to BAppli
	* @param Cal Mouvements_financiers__c with Type_mouvement__c equal to 'Cout interne d'echange' 
	* and Statut__c equal to 'Demande en cours'
	* @return Equipement_sinistre__c with the Id Externe B-appli Equipement Echange(Id_externe__c) 
	* on the Matrice_cout_equipement__c object, Grade__c and Operator__c on the Equipement_sinistre__c
	*/
    public static Equipement_sinistre__c GetDatasToTriggerDestockToBAppli(Mouvements_financiers__c Cal){  
        
        Equipement_sinistre__c eq = [SELECT id, 
                                     ChooseEqp__r.Id_externe__c, 
                                     Grade__c, 
                                     Operator__c, 
                                     Sinistre__c, 
                                     ClientChoiceDate__c
                                     FROM Equipement_sinistre__c
                                     WHERE Sinistre__c =: Cal.Case__c 
                                     AND RecordType.DeveloperName =: DAMAGEDEQUIPMENTRECORDTYPE_ECHANGE
                                     LIMIT 1];
        
        return eq;
    }

    /***
	* @description Get datas on the Equipement_sinistre__c to trigger destock to BAppli
	* @param Cal Mouvements_financiers__c with Type_mouvement__c equal to 'Cout interne reparation' and Statut__c equal to 'Demande en cours'
	* @return Equipement_sinistre__c reparation
	*/
    public static List<Equipement_sinistre__c> GetEquipSinistreRepair(Set<Id> listIdSinistre){  
        
        List<Equipement_sinistre__c> listEq = [SELECT id, 
                                               Statut_equipement__c,
                                               Sous_statut__c,
                                               OwnerId
                                               FROM Equipement_sinistre__c
                                               WHERE Sinistre__c =: listIdSinistre
                                               AND RecordType.DeveloperName =: EQUIPMENTRECORDTYPE_REPAIR];
        
        return listEq;
    }
    
    /***
	* @description Sum all amount of calcul indemnisation rows linked to the same case
	* @param set<id> idSin
	* @return nul
	* @exception none
    */
    public static void SumCalculIndemAmount(set<id> idSin){  
        
        List<Case> ListCaseToUpdate = new list<Case>();
        List<Mouvements_financiers__c> lstCal = new List<Mouvements_financiers__c>([SELECT id, Case__c, Montant__c 
                                                                                    FROM Mouvements_financiers__c 
                                                                                    WHERE Statut__c NOT IN ('Invalidated','Rejected') 
                                                                                    AND Case__c IN: idSin]);
        
        Map<id,List<Mouvements_financiers__c>> mapIdCaseListCalIndem = new map<Id,List<Mouvements_financiers__c>>();        
        if(!lstCal.isEmpty()){
            for(Mouvements_financiers__c j: lstCal){
                if(mapIdCaseListCalIndem.get(j.Case__c) != null){
                    mapIdCaseListCalIndem.get(j.Case__c).add(j);                    
                }else{
                    mapIdCaseListCalIndem.put(j.Case__c, new list<Mouvements_financiers__c>{j});    
                }
            }
            for(Id id: mapIdCaseListCalIndem.keyset()){
                decimal sum = 0;
                for(Mouvements_financiers__c cal: mapIdCaseListCalIndem.get(id)){
                     sum = sum + cal.Montant__c;
                }
                ListCaseToUpdate.add(new Case(id = id, Montant_sinistre__c = sum));
            }
        }else{
            for(Id i: idSin){
                ListCaseToUpdate.add(new Case(id = i, Montant_sinistre__c = 0));        
            }   
        }
        if(!ListCaseToUpdate.isEmpty()){
            update ListCaseToUpdate;
        }
    }
    
    /***
	* @description send email to customer and dealer 
	* @param List<id> lstCalforStoreCostPrime
	* @return nul
	* @exception none
    */
    public static void sendEmailToCustomerAndDealer(List<Mouvements_financiers__c> lstCalforStoreCostPrime){  
        
        List<Task> TaskToInsert = new list<Task>();
        
        // Only one Mouvements_financiers__c row can be updated to 'Demande en cours' at a time
        for(Mouvements_financiers__c i: lstCalforStoreCostPrime){
            task t = new task();
            t.ActivityDate = date.today();
            t.Canal_communication__c = TASKCOMMUNICATIONCHANNEL_OUTBOUNDEMAIL;
            t.Code_template__c = Label.SinistreEmailTemplatePremiumExchange;
            t.WhatId = i.Case__c;
            TaskToInsert.add(t);
            
            string relatedTemplate = Label.SinistreEmailTemplatePremiumExchangeDealer + '%';
            Id templateDealerId = [SELECT id, developername 
                                   FROM EmailTemplate 
                                   WHERE developername LIKE: relatedTemplate].id;
            String dealerEmail = [SELECT id, TECH_StorePremium__r.vlocity_ins__Email__c 
                                  FROM Case 
                                  WHERE id =: i.Case__c].TECH_StorePremium__r.vlocity_ins__Email__c;
            
			// Create the dealer email to be sent 
			Messaging.SingleEmailMessage dealerMail = UtilityClassHelper.createEmail(i.Case__c, dealerEmail, templateDealerId); 
            
            if(dealerEmail != null){
                Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{dealerMail});
                Contact c = [SELECT id, LastName 
                             FROM Contact 
                             WHERE LastName =: dealerEmail];
                delete c;
            }
            if(!TaskToInsert.isEmpty()){
                insert TaskToInsert;
            }
        }
    }
    
    /***
	* @description Get the asset's related account
	* @return Map<id, Account>
	*/
    public static Map<id, List<Mouvements_financiers__c>> getOtherCalcIndem(List<Mouvements_financiers__c> newCalcIndemnList){
        
        // Get the related case ids
        Set<id> caseIdSet = new Set<id>();
        for(Mouvements_financiers__c c : newCalcIndemnList){
            caseIdSet.add(c.Case__c);
        }
        
        List<Mouvements_financiers__c> relatedMFList = [SELECT id, Case__c, Statut__c, Cout_choisi__c
                                                        FROM Mouvements_financiers__c
                                                        WHERE Case__c IN: caseIdSet
                                                        AND id NOT IN: newCalcIndemnList];
        
        // Map the mouvement financiers to their cases
        Map<id, List<Mouvements_financiers__c>> caseIdMFMap = new Map<id, List<Mouvements_financiers__c>>();
        for(Mouvements_financiers__c m : relatedMFList){
            if(!caseIdMFMap.keySet().contains(m.Case__c)){
                List<Mouvements_financiers__c> tmpList = new List<Mouvements_financiers__c>();
                caseIdMFMap.put(m.Case__c, tmpList);
            }
            caseIdMFMap.get(m.Case__c).add(m);
        }
        return caseIdMFMap;
    }

    /***
    * @description update amount Case
    * @param lstNewCal list of new Mouvements_financiers__c
    * @return nul
    * @exception none
    */
    public static void blockDeleteCalculIndemStatusCreated(List<Mouvements_financiers__c> lstOldCal){
        for(integer i=0; i<lstOldCal.size(); i++){
            if(lstOldCal[i].Statut__c != STATUS_CREATED) { 
                lstOldCal[i].addError(Label.Sinistre_ErrorMessageDeletionCalculIndem);
            }
        }
    }

    /***
    * @description Checks whether the recently updated status on MF are closed - if so, proceeds to close the related case
    * @param newMFList - list of new Mouvements_financiers__c
    * @param oldMFMap - map of old Mouvements_financiers__c
    * @param caseIdMFMap - related MF mapped to their case id
    * @return null
    * @exception none
    */
    public static void updateRelatedCase(List<Mouvements_financiers__c> newMFList, Map<id, Mouvements_financiers__c> oldMFMap, Map<id, List<Mouvements_financiers__c>> caseIdMFMap){
        
        Map<id, String> caseToUpdate = new Map<id, String>();
        List<Id> lstAssetId = new List<Id>();
        
        // Loop over the new mouvements financiers
        for(Mouvements_financiers__c m : newMFList){
            
            // If the status is now closed
            if(m.Statut__c != oldMFMap.get(m.id).Statut__c &&
                m.Statut__c == 'Completed'){
                    
                    // Set the validation date
                    m.Indemnisation_date__c = system.today();
            
                    // And if there is no other open MF, but at least a completed one
                    boolean isThereAnOpenMF = FALSE;
                    boolean isThereACompletedMF = m.Statut__c == 'Completed';
                    boolean isThereOnlyReglCli = FALSE;
                    integer countOtherMF = 0;

                    if(m.Cout_choisi__c == 'Règlement par le client'){
                    	isThereOnlyReglCli = TRUE;
                    }
                    
                    if(caseIdMFMap.keySet().contains(m.Case__c)){
                        for(Mouvements_financiers__c relM : caseIdMFMap.get(m.Case__c)){
                            if(relM.Cout_choisi__c == 'Règlement par le client' && countOtherMF!=0){
                                isThereOnlyReglCli = TRUE;
                            }
                            if(relM.Statut__c == 'Crée' ||
                               relM.Statut__c == 'En cours d\'approbation' ||
                               relM.Statut__c == 'Validé' ||
                               relM.Statut__c == 'Demande en cours' ){
                                   isThereAnOpenMF = TRUE;
                                   break;
                               }
                            if(relM.Statut__c == 'Completed'){
                                isThereACompletedMF = TRUE;
                            }
                            if(relM.Cout_choisi__c != 'Règlement par le client'){
                                isThereOnlyReglCli = FALSE;
                                countOtherMF++;
                            }
                        }
                    }
                    
                    // Then close the case
                    if(!isThereAnOpenMF && isThereACompletedMF && !isThereOnlyReglCli){
                        if(m.TECH_AssetID__c != null || String.isNotBlank(m.TECH_AssetID__c)){
                            lstAssetId.add(m.TECH_AssetID__c);
                        }
                        if(m.Type_mouvement__c == 'Prime pour reparation par le client' ||
                           m.Cout_choisi__c == 'Réparation'){
                               caseToUpdate.put(m.Case__c, 'closed_repaired');
                           }
                        else{
                            caseToUpdate.put(m.Case__c, 'closed_exchange');
                            
                            if(m.Cout_choisi__c == 'Primes') {
                                // Update Insured Item (state and reason)
                            	updateInsuredItemForClosedExchange(m.Case__c);
                                // Update damaged equipment (status and sub status)
                                updateEquipeSinistreForClosedExchange(m.Case__c);
                            }
                        }
                    }
                }
        }
        if(caseToUpdate.keySet().size() > 0){
            updateCase(new List<id>(caseToUpdate.keySet()), caseToUpdate.values(),lstAssetId);
        }
    }
    
    /***
	* @description Update the metadata - future method
	* @param Case
	* @return NA
	*/
    @future
    private static void updateCase(List<id> caseIdList, List<String> caseStatusList, List<Id> lstAssetId){
        
        List<Case> caseToUpdate = new List<Case>();
        
        for(Integer i=0; i<caseIdList.size(); i++){
            Case c = new Case(id = caseIdList[i], 
                              ClosedDateBappli__c = system.today());
            if(caseStatusList[i] != ''){
                c.Status = caseStatusList[i];
            }
            caseToUpdate.add(c);
        }
        
        update caseToUpdate;
        CaseTriggerHandler.nofuturCalculatorProcess(lstAssetId,null);
    }

    /***
    * @description update status equipment sinistre
    * @param lstEquiToUpdate list of equipementSinistre to updated
    * @return nul
    * @exception none
    */
    public static void updateEquipeSinistreStatus(List<Equipement_sinistre__c> lstEquiToUpdate){
        List<Equipement_sinistre__c> lstEquToUpdate = new List<Equipement_sinistre__c>();

        for(Equipement_sinistre__c eq : lstEquiToUpdate){
            eq.Statut_equipement__c = EQUIPMENTSINISTRE_STATUS_INPROGRESSREPAIR; 
            eq.Sous_statut__c = EQUIPMENTSINISTRE_UNDERSTATUS_INPROGRESS;
            lstEquToUpdate.add(eq);
        }

        update lstEquToUpdate;
    }

    /***
    * @description create task to start repair
    * @param lstEquiToUpdate list of equipementSinistre to created task
    * @return nul
    * @exception none
    */
    public static void createHistoToStartRepair(List<Equipement_sinistre__c> lstEquiToUpdate){
        List<Equipement_sinistre__c> lstEquToUpdate = new List<Equipement_sinistre__c>();

        List<Name__c> lstHistoToCreated = new List<Name__c>();

        for(Equipement_sinistre__c eq : lstEquiToUpdate){
            Name__c histo = new Name__c();
            histo.Name = TASK_SUBJECT_REPAIRVALID;
            histo.OwnerId = eq.OwnerId;
            histo.Equipement_sinistre__c = eq.Id;
            lstHistoToCreated.add(histo);
        }

        insert lstHistoToCreated;
    }

    /***
	* @description Clean choice in EquipementSinistre
	* @param caseIdList Case Ids
	* @return NA
	*/
    public static void updateEquipeSinistreChoice(Set<id> caseIdList){
        
        List<Equipement_sinistre__c> equiSinToUpdate = [SELECT Id,
                                                                FirstChoice__c,
                                                                SecondChoice__c,
                                                                ThirdChoice__c,
                                                                ChosenEquip__c,
                                                                ClientChoiceDate__c,
                                                                Statut_equipement__c,
                                                                Grade__c,
                                                                FirstChoiceRank__c,
                                                                SecondChoiceRank__c,
                                                                ThirdChoiceRank__c
                                                                 FROM Equipement_sinistre__c WHERE Sinistre__c IN: caseIdList];
        List<Equipement_sinistre__c> equiSinUpdate = new List<Equipement_sinistre__c>();

        if(equiSinToUpdate != null && equiSinToUpdate.size()>0){
            for(Equipement_sinistre__c eq : equiSinToUpdate){
                eq.FirstChoice__c = null;
                eq.SecondChoice__c = null;
                eq.ThirdChoice__c = null;
                eq.ChosenEquip__c = null;
                eq.ClientChoiceDate__c = null;
                eq.Grade__c = null;
                eq.FirstChoiceRank__c = null;
                eq.SecondChoiceRank__c = null;
                eq.ThirdChoiceRank__c = null;
                eq.Statut_equipement__c = 'En Analyse';
                equiSinUpdate.add(eq);
            }
        }

        if(equiSinUpdate.size()>0){
            update equiSinUpdate;
        }
    }
    
    /***
    * @description update insured item
    * @param itemToUpdate Insured item to updated
    * @return nul
    * @exception none
    */
    public static void updateInsuredItemForClosedExchange(Id CaseId){
        List<Case> CaseList = [SELECT Equipement_client__c FROM Case WHERE id =: CaseId];
        
        if(CaseList.size() == 1){
            id InsuredItemId = CaseList[0].Equipement_client__c;
                
        	vlocity_ins__AssetInsuredItem__c InsuredItem = new vlocity_ins__AssetInsuredItem__c(
                id = InsuredItemId,
                Etat__c = INSUREDITEM_STATUS_INACTIVE,
                Motif__c = INSUREDITEM_REASON_EXCHANGE
            );
        
        	update InsuredItem;
        }
    }
    
    /***
    * @description update status equipment sinistre for closed exchange
    * @param lstEquiToUpdate equipementSinistre to updated
    * @return nul
    * @exception none
    */
    public static void updateEquipeSinistreForClosedExchange(Id CaseId){
        Equipement_sinistre__c eq = [SELECT id
                                    FROM Equipement_sinistre__c
                                    WHERE Sinistre__c =: CaseId
                                    AND RecordType.DeveloperName =: DAMAGEDEQUIPMENTRECORDTYPE_ECHANGE
                                    LIMIT 1];
            
        if(eq != null){
            eq.Statut_equipement__c = EQUIPMENTSINISTRE_STATUS_EXCHANGE;
            eq.Sous_statut__c = EQUIPMENTSINISTRE_UNDERSTATUS_PRENIUM;
        
        	update eq;
        }
    }
}