hubSide/force-app/main/default/objects/Account/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <description>Id externe pour l&apos;intégration API</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Date_debut_contrat__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_contrat__c</fullName>
    <description>Date de début du contrat souscrit par le client.</description>
    <label>Date de début du contrat</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Id_contrat_B_appli__c.field-meta.xml
<CustomField>
    <fullName>Id_contrat_B_appli__c</fullName>
    <label>Id contrat B-appli</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <description>Id Externe utilisé par les interfaces pour l&apos;Upsert et stocké l&apos;Id du sytème source</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Asset/recordTypes/Contrat_assurance.recordType-meta.xml
<RecordType>
    <fullName>Contrat_assurance</fullName>
    <active>true</active>
    <label>Contrat assurance</label>
</RecordType>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/CalloutErrorsManagement__c.object-meta.xml
<CustomObject>
    <description>This object allows to store all information from callout of Salesforce platform.</description>
    <label>Management of Callout Errors</label>
    <nameField>
        <label>Callout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management of Callout Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/fields/CalloutErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>CalloutErrorMessage__c</fullName>
    <description>Message to identify the error. Link to the error code</description>
    <label>Error message in the callout</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/fields/CaseRecord__c.field-meta.xml
<CustomField>
    <fullName>CaseRecord__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the case</description>
    <label>Case Record</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Management of Callout Errors</relationshipLabel>
    <relationshipName>ManagementCalloutErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <description>Id externe pour l&apos;intégration API</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Adresse_de_livraison__c.field-meta.xml
<CustomField>
    <fullName>Adresse_de_livraison__c</fullName>
    <label>Adresse de livraison</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/DeliveryMode__c.field-meta.xml
<CustomField>
    <fullName>DeliveryMode__c</fullName>
    <label>Mode de Livraison</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A domicile</fullName>
            </value>
            <value>
                <fullName>En magasin Hubside</fullName>
                <isActive>false</isActive>
                <label>En magasin Hubside</label>
            </value>
            <value>
                <fullName>En point relais</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Id_externe__c.field-meta.xml
<CustomField>
    <fullName>Id_externe__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Id externe pour l&apos;intégration API qui est l&apos;Id du Case parent via le Web et est alimenté en post default value à Id si vide</description>
    <externalId>true</externalId>
    <label>Id externe</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/RelayPointIdExterne__c.field-meta.xml
<CustomField>
    <fullName>RelayPointIdExterne__c</fullName>
    <label>Identifiant Point Relais</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/classes/PickUpSearchControllerTest.cls
/***
* @author Nicolas Brancato (GFI)
* @date 09/02/2021
* @description Controller class test for PickUpSearchController and ChronopostCallout apex class
*/
@isTest
public class PickUpSearchControllerTest {
    
    
    public static final String PROFILE_GS = 'SFAM GS';
    public static User GSUser;
    public static Account a;
    public static Asset c;
    public static Case s;
    public static Equipement_sinistre__c eqs;
    public static string res;
    public static cxfRecherchebtSoapChronopostFr.pointCHRResult calloutRes;
    
    /***
    * @description Static method to initialize all the datas for the test methods
    */
    static{
        
        Id profileGSId = [Select Id From Profile  
                          Where name =: PROFILE_GS
                         ].Id;
        
        GSUser = TestFactory.createUser();
        GSUser.ProfileId = profileGSId;
        GSUser.Email = 'guillaume.gs@yopmail.com';
        insert GSUser;
        
        // Create a new account as system admin because the account is sent by Bappli
        a = TestFactory.createClient();
        insert a;
        
        // Create a new contract as system admin because the contract is sent by Bappli
        c = new Asset();
        c.Name = '0220010102';
        c.RecordTypeId = UtilityClassHelper.getCreatedRecordType('Contrat_assurance');
        c.AccountId = a.id;
        c.Date_debut_contrat__c = System.today();
        c.Id_externe__c = 'INS0220010102';
        c.Id_contrat_B_appli__c = '5343473';
        insert c;
        
        // Create a sinistre
        s = TestFactory.createSinistre(a.id, c.id);
        insert s;
        
        // Create a damaged equipement
        eqs = new Equipement_sinistre__c(Sinistre__c = s.id);
        insert eqs;          
    }
    
    
    /***
    * @description Test method for the searchPickUp method in the PickUpSearchController apex class. 
    * This test method mocks a fake response with a success in return, that is to say with an errorCode equal to 0.
    */
    @isTest
    public static void searchPickUpSuccessTest(){
        
        // This causes a fake response to be generated
        Test.setMock(WebServiceMock.class, new recherchePointChronopostInterCalloutMock(0, null));
        
        Test.startTest();
        System.runAs(GSUser){
            calloutRes = PickUpSearchController.searchPickUp('test address','test zipCode','test city', s.id);
        }
        Test.stopTest();
        system.assertEquals(0, calloutRes.errorCode);
        system.assertEquals(null, [SELECT id, CalloutErrorMessage__c 
                                   FROM CalloutErrorsManagement__c 
                                   WHERE CaseRecord__c =: s.id].CalloutErrorMessage__c);        
    }
    
    
    /***
    * @description Test method for the searchPickUp method in the PickUpSearchController apex class. 
    * This test method mocks a fake response with an error in return, that is to say with an errorCode equal to 601.
    */
    @isTest
    public static void searchPickUpErrorTest(){
        
        // This causes a fake response to be generated
        Test.setMock(WebServiceMock.class, new recherchePointChronopostInterCalloutMock(601, 'Pas de points CHR trouvés'));
        
        Test.startTest();
        System.runAs(GSUser){
            calloutRes = PickUpSearchController.searchPickUp('test address','test zipCode','test city', s.id);
        }
        Test.stopTest();
        system.assertEquals(601, calloutRes.errorCode);
        system.assert([SELECT id, CalloutErrorMessage__c 
                       FROM CalloutErrorsManagement__c 
                       WHERE CaseRecord__c =: s.id].CalloutErrorMessage__c.contains('Pas de points CHR trouvés'));
    }
    
    
    /***
    * @description Test method for the savePickUpAddress method in the PickUpSearchController apex class. 
    * This test method tries a sucessful update of the Equipement_sinistre__c.
    */
    @isTest
    public static void savePickUpAddressTest(){
        
        string identifierTest = '1234';
        string addressTest = '7 Russell Street, Wanaka 9305, Nouvelle-Zélande';
        string IdExterneAndAddressTest = identifierTest + ' Address:' +  addressTest;
        Test.startTest();
        System.runAs(GSUser){
            res = PickUpSearchController.savePickUpAddress(eqs.id,IdExterneAndAddressTest);
        }
        Test.stopTest();
        system.assertEquals(null, res);
        system.assertEquals(addressTest, [Select id, Adresse_de_livraison__c From Equipement_sinistre__c where id =: eqs.id].Adresse_de_livraison__c);
        system.assertEquals(identifierTest, [Select id, RelayPointIdExterne__c From Equipement_sinistre__c where id =: eqs.id].RelayPointIdExterne__c);
        system.assertEquals('En point relais', [Select id, DeliveryMode__c From Equipement_sinistre__c where id =: eqs.id].DeliveryMode__c);
    }
    
    
    /***
    * @description Test method for the savePickUpAddress method in the PickUpSearchController apex class. This test method tries a failed update of the Equipement_sinistre__c.
    */
    @isTest
    public static void savePickUpAddressCatchTest(){
        
        string addressTest = 'address test';
        Test.startTest();
        System.runAs(GSUser){
            res = PickUpSearchController.savePickUpAddress(s.id,addressTest);  
        }
        Test.stopTest();
        system.assertNotEquals(null, res);
        system.assertNotEquals('address test', [Select id, Adresse_de_livraison__c From Equipement_sinistre__c where id =: eqs.id].Adresse_de_livraison__c);
        system.assertNotEquals('En point relais', [Select id, DeliveryMode__c From Equipement_sinistre__c where id =: eqs.id].DeliveryMode__c);
    }
}