hubSide/force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <description>Object use to save control for the fields and approvals</description>
    <label>Alert</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Alert__c/fields/BusinessRulesNumber__c.field-meta.xml
<CustomField>
    <fullName>BusinessRulesNumber__c</fullName>
    <label>Business rules number</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SalesDiscountMotif__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RGSIN10</fullName>
            </value>
            <value>
                <fullName>RGSIN11</fullName>
            </value>
            <value>
                <fullName>RGSIN12</fullName>
            </value>
            <value>
                <fullName>RGSIN13</fullName>
            </value>
            <value>
                <fullName>RGSIN15</fullName>
            </value>
            <value>
                <fullName>RGSIN14</fullName>
            </value>
            <value>
                <fullName>RGSIN16</fullName>
            </value>
            <value>
                <fullName>RGSIN17</fullName>
            </value>
            <value>
                <fullName>RGSIN18</fullName>
            </value>
            <value>
                <fullName>RGSIN19</fullName>
            </value>
            <value>
                <fullName>RGSIN20</fullName>
            </value>
            <value>
                <fullName>RGSIN21</fullName>
            </value>
            <value>
                <fullName>RGSIN22</fullName>
            </value>
            <value>
                <fullName>RGSIN23</fullName>
            </value>
            <value>
                <fullName>RGSIN24</fullName>
            </value>
            <value>
                <fullName>RGSIN00</fullName>
                <isActive>false</isActive>
                <label>RGSIN00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Alert__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Alerts</relationshipLabel>
    <relationshipName>Alerts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/TECH_MissingDocs__c.field-meta.xml
<CustomField>
    <fullName>TECH_MissingDocs__c</fullName>
    <description>Liste des pièces justificatives attendues</description>
    <label>TECH_MissingDocs</label>
    <length>2000</length>
    <type>Html</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Document__c/fields/Related_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Related_sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/Piece_justificative_Sinistre__c.object-meta.xml
<CustomObject>
    <label>Pièce justificative Sinistre</label>
    <nameField>
        <label>Pièce justificative Sinistre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pièces justificatives Sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Technique Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/ContentDocumentId__c.field-meta.xml
<CustomField>
    <fullName>ContentDocumentId__c</fullName>
    <description>Store the Id of the object ContentDocument when a file is uploaded in ContentVersion and ContentDocument by the Web or Salesforce in order to get the Id immediately without traversing all relationship until ContentDocument</description>
    <label>ContentDocumentId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/ContentVersionId__c.field-meta.xml
<CustomField>
    <fullName>ContentVersionId__c</fullName>
    <description>Store the Id of the object ContentVersion when a file is uploaded in ContentVersion by the Web or Salesforce in order to get the Id immediately without traversing all relationship until ContentVersion</description>
    <label>ContentVersionId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document__c.Related_sinistre__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/LongTitle__c.field-meta.xml
<CustomField>
    <fullName>LongTitle__c</fullName>
    <description>Intitulé complet de la pièce justificative à destination des communications clients</description>
    <label>Intitulé</label>
    <length>400</length>
    <type>LongTextArea</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Types_piece_justificative__c.field-meta.xml
<CustomField>
    <fullName>Types_piece_justificative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Types pièce justificative</label>
    <referenceTo>Types_piece_justificative__c</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Validite_document__c.field-meta.xml
<CustomField>
    <fullName>Validite_document__c</fullName>
    <label>Validité du document</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expected</fullName>
                <default>true</default>
                <label>1-Attendue</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <label>2-Reçu</label>
            </value>
            <value>
                <fullName>Valid</fullName>
                <label>3-Valide</label>
            </value>
            <value>
                <fullName>NotNeeded</fullName>
                <label>4-Plus réclamé</label>
            </value>
            <value>
                <fullName>Invalid</fullName>
                <label>5-Non valide</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/Types_piece_justificative__c.object-meta.xml
<CustomObject>
    <label>Types pièce justificative</label>
    <nameField>
        <label>Types pièce justificative name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types pièce justificative</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/fields/LongTitle__c.field-meta.xml
<CustomField>
    <fullName>LongTitle__c</fullName>
    <description>Intitulé complet de la pièce justificative à destination des communications clients</description>
    <label>Intitulé</label>
    <length>500</length>
    <type>Html</type>
</CustomField>

hubSide/force-app/main/default/classes/PieceJustificativeTriggerHandlerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 23/09/2020
* @description PieceJustificative test class
* @Object Piece_justificative_Sinistre__c
*/

@isTest
public class PieceJustificativeTriggerHandlerTest {
    
    @testSetup 
    public static void testSetup(){
        
        // Create two types de piece justificative
        Types_piece_justificative__c t = TestFactory.createTypePJ('Permis de chasse');
        insert t;
        
        Types_piece_justificative__c t1 = TestFactory.createTypePJ('Licence de bouliste');
        insert t1;
        
        // Create a sinistre
        Case c = TestFactory.createSinistre();
        insert c;
        
        // Create a document
        Document__c d = new Document__c();
        d.Related_sinistre__c = c.id;
        insert d;
        
        // Create a new content version
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        cv.FirstPublishLocationId = d.id;
        insert cv;
    }
    
    /***
    * @description Update the case on pj creation
    * @see updateCaseOnCreate
    */
    @isTest
    public static void updateCaseOnCreateTest(){
        
        // Get a sinistre
        Case c = [SELECT id, TECH_MissingDocs__c FROM Case LIMIT 1];
        
        // Query the piece justificative
        List<Piece_justificative_Sinistre__c> pList = [SELECT id, Validite_document__c, LongTitle__c
                                                       FROM Piece_justificative_Sinistre__c 
                                                       WHERE Case__c =: c.id];
        
        String longTitle = pList[0].LongTitle__c;
        for(Integer i = 1; i<pList.size(); i++){
            longTitle += '\n' + pList[i].LongTitle__c ;
        }
        
        system.assertEquals(longTitle, c.TECH_MissingDocs__c, 
                            'The missing docs string shouldve been udpated - this is wrong');
        
        // Update the status
        pList[0].Validite_document__c = 'valid';        
        pList[1].Validite_document__c = 'valid';
        update pList;
        
        c = [SELECT id, Status
             FROM Case
             WHERE id =: c.id];
        system.assertEquals('En cours d\'examen', c.Status, 
                           'The case status should have been updated - This is wrong');
        
        // Add another PJ
        Types_piece_justificative__c t = TestFactory.createTypePJ('CNI');
        insert t;
        Piece_justificative_Sinistre__c pj = TestFactory.createPJ(t);
        pj.Case__c = c.id;
        insert pj;
        
        c = [SELECT id, Status FROM Case WHERE id =: c.id];
        system.assertEquals('Incomplet', c.Status, 
                           'The case status should have been changed to incomplete - This is wrong');
    }
    
    /***
    * @description Update the PJ on creation
    * @see updateCaseOnCreate
    */
    @isTest
    public static void updatePJOnCreateTest(){
        
        // Get a sinistre
        Case c = [SELECT id FROM Case LIMIT 1];
        
        // Get a document
        ContentVersion cv = [SELECT id, FirstPublishLocationId 
                             FROM ContentVersion LIMIT 1];
        
        // Query the piece justificative
        Piece_justificative_Sinistre__c pj = [SELECT id, Validite_document__c 
                                              FROM Piece_justificative_Sinistre__c 
                                              WHERE Name = 'Permis de chasse'];
        
        // Add the document
        pj.Document__c = cv.FirstPublishLocationId;
        update pj;
        
        pj = [SELECT id, ContentDocumentId__c, ContentVersionId__c
             FROM Piece_justificative_Sinistre__c
             WHERE id =: pj.id];
        system.assertEquals(cv.id, pj.ContentVersionId__c, 
                           'The PJ shouldve been updated with ContentVersion info - This is wrong');
    }
    
    /***
    * @description Update the Case on update
    * @see updateCaseOnUpdate
    */
    @isTest
    public static void updateCaseOnUpdateTest(){
        
        // Get a sinistre
        Case c = [SELECT id FROM Case LIMIT 1];
        c.Status = 'Attribué';
        update c;
        
        // Get a document
        Document__c d = [SELECT id FROM Document__c LIMIT 1];
        
        // Query the piece justificative
        Piece_justificative_Sinistre__c pj = [SELECT id, Validite_document__c 
                                              FROM Piece_justificative_Sinistre__c 
                                              WHERE Name = 'Permis de chasse'];
        
        // Add the document
        pj.Document__c = d.id;
        pj.Validite_document__c = 'received';
        update pj;
        
        c = [SELECT id, Status
             FROM Case
             WHERE id =: c.id];
        system.assertEquals('Incomplet', c.Status, 
                           'The case status should have been changed to incomplete - This is wrong');
    }
    
    /***
    * @description Update the case on pj modification
    * @see createNewPJ
    */
    @isTest
    public static void createNewPJTest(){
                
        // Query the piece justificative
        Piece_justificative_Sinistre__c pj = [SELECT id, Validite_document__c 
                                              FROM Piece_justificative_Sinistre__c 
                                              WHERE Name = 'Permis de chasse'];
        
        // The current pj is not valid
        pj.Validite_document__c = 'invalid';
        update pj;
        
        List<Piece_justificative_Sinistre__c> pjList = [SELECT id, Validite_document__c
                                                        FROM Piece_justificative_Sinistre__c
                                                        WHERE Name = 'Permis de chasse'];
        
        system.assertEquals('Invalid', pjList[0].Validite_document__c, 
                            'The previous pj shouldnt be valid anymore - This is wrong');
        system.assertEquals('Expected', pjList[1].Validite_document__c, 
                            'The new pj should be needed - This is wrong');
    }
    
    /***
    * @description Update the case on pj modification
    * @see updateSinistreOnUpdate
    */
    @isTest
    public static void updateSinistreOnUpdateTest(){
        
        test.startTest();
        
        // Get a sinistre
        Case c = [SELECT id FROM Case LIMIT 1];
        
        // Set an owner
        c.Status = 'Attribué';
        update c;
        
        // Query the piece justificative
        List<Piece_justificative_Sinistre__c> pList = [SELECT id, Validite_document__c 
                                                       FROM Piece_justificative_Sinistre__c 
                                                       WHERE Case__c =: c.id];
        pList[0].Validite_document__c = 'received';
        update pList;
        
        test.stopTest();
        
        // Update the status again
        for(Piece_justificative_Sinistre__c p : pList){
            p.Validite_document__c = 'valid';
        }
        update pList;
        
        c = [SELECT id, Status
             FROM Case
             WHERE id =: c.id];
        system.assertEquals('En cours d\'examen', c.Status, 
                           'The case status should have been updated - This is wrong');
    }

    /***
    * @description Update the case on pj modification
    * @see updateSinistreOnUpdate
    */
    @isTest
    public static void manageAlertNotNeededTest(){
        
        test.startTest();
        
        // Get a sinistre
        Case c = [SELECT id FROM Case LIMIT 1];
        
        // Set an owner
        c.Status = 'Attribué';
        update c;
        
        // Query the piece justificative
        List<Piece_justificative_Sinistre__c> pList = [SELECT id, Validite_document__c,Case__c
                                                       FROM Piece_justificative_Sinistre__c 
                                                       WHERE Case__c =: c.id];
        pList[0].Validite_document__c = 'NotNeeded';
        update pList;
        
        test.stopTest();
        
        Alert__c al = [SELECT Id,BusinessRulesNumber__c
                FROM Alert__c 
                WHERE Case__c =: c.id
                AND BusinessRulesNumber__c='RGSIN24'];
        system.assertEquals('RGSIN24', al.BusinessRulesNumber__c, 
                           'Not alert created');
    }
}