hubSide/force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <description>Object use to save control for the fields and approvals</description>
    <label>Alert</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Alert__c/fields/BusinessRulesNumber__c.field-meta.xml
<CustomField>
    <fullName>BusinessRulesNumber__c</fullName>
    <label>Business rules number</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SalesDiscountMotif__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RGSIN10</fullName>
            </value>
            <value>
                <fullName>RGSIN11</fullName>
            </value>
            <value>
                <fullName>RGSIN12</fullName>
            </value>
            <value>
                <fullName>RGSIN13</fullName>
            </value>
            <value>
                <fullName>RGSIN15</fullName>
            </value>
            <value>
                <fullName>RGSIN14</fullName>
            </value>
            <value>
                <fullName>RGSIN16</fullName>
            </value>
            <value>
                <fullName>RGSIN17</fullName>
            </value>
            <value>
                <fullName>RGSIN18</fullName>
            </value>
            <value>
                <fullName>RGSIN19</fullName>
            </value>
            <value>
                <fullName>RGSIN20</fullName>
            </value>
            <value>
                <fullName>RGSIN21</fullName>
            </value>
            <value>
                <fullName>RGSIN22</fullName>
            </value>
            <value>
                <fullName>RGSIN23</fullName>
            </value>
            <value>
                <fullName>RGSIN24</fullName>
            </value>
            <value>
                <fullName>RGSIN00</fullName>
                <isActive>false</isActive>
                <label>RGSIN00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Alert__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Alerts</relationshipLabel>
    <relationshipName>Alerts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Alert__c/fields/SalesDiscountMotif__c.field-meta.xml
<CustomField>
    <fullName>SalesDiscountMotif__c</fullName>
    <label>Motif de geste commercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Motif_Geste_commercial</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Alert__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Approval status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>En Attente</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Dérogation acceptée</label>
            </value>
            <value>
                <fullName>Refused</fullName>
                <label>Dérogation refusée</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Clos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Alert__c/fields/Type_Alert__c.field-meta.xml
<CustomField>
    <fullName>Type_Alert__c</fullName>
    <label>Type Alert</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bloquant</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Alert__c/fields/Validation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Validation_Reason__c</fullName>
    <description>Picklist to hold the validation reason of the alert.</description>
    <label>Motif de validation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepté processus métier</fullName>
            </value>
            <value>
                <fullName>Accepté Geste commercial</fullName>
            </value>
            <value>
                <fullName>Validation par défaut car warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/AlertText__c.field-meta.xml
<CustomField>
    <fullName>AlertText__c</fullName>
    <description>Use this field to save alert description in the approval process</description>
    <label>Alertes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Attente_client_final__c.field-meta.xml
<CustomField>
    <fullName>Attente_client_final__c</fullName>
    <formula>&apos;&apos; 
&amp;
IF(
    AND(TEXT(Asset.Etat_paiement__c) = &quot;unpaid&quot;, Pouss_par_Salesforce__c = false),
    IMAGE(&quot;/resource/AttentePaiement&quot;, &quot;Paiement&quot; , 32, 32) &amp; &apos; &apos;, 
    &apos;&apos;
) 
&amp;
IF(
    TEXT(Attente_Prime__c) = &quot;Oui&quot;,
    IMAGE(&quot;/resource/Franchise&quot;, &quot;Prime&quot;, 32, 32) &amp; &apos; &apos;, 
    &apos;&apos;
)
&amp;
IF(
    AND(TEXT(Attente_documents__c) != &quot;Valid&quot;,TEXT(Attente_documents__c) != &quot;Received&quot;),
    IMAGE(&quot;/resource/AttenteDocument&quot;, &quot;Document&quot;, 32, 32) &amp; &apos; &apos;,
    &apos;&apos;
) 
&amp;
IF(
    TEXT(Autre_attente__c) = &quot;Oui&quot;,
    IMAGE(&quot;/resource/AutreAttente&quot;, &quot;Autre&quot;, 32, 32),
    &apos;&apos;
)
&amp;
IF(
     Attente_colis__c  = True,
    IMAGE(&quot;/resource/Livraison&quot;, &quot;Livraison&quot;, 32, 32),
    &apos;&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attente client</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Attente_documents__c.field-meta.xml
<CustomField>
    <fullName>Attente_documents__c</fullName>
    <label>Attente documents</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
                <label>Reçu(s)</label>
            </value>
            <value>
                <fullName>Valid</fullName>
                <label>Valide(s)</label>
            </value>
            <value>
                <fullName>Expected</fullName>
                <default>true</default>
                <label>Attendu(s)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/TECH_MissingDocs__c.field-meta.xml
<CustomField>
    <fullName>TECH_MissingDocs__c</fullName>
    <description>Liste des pièces justificatives attendues</description>
    <label>TECH_MissingDocs</label>
    <length>2000</length>
    <type>Html</type>
</CustomField>

hubSide/force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Document__c/fields/Valideur__c.field-meta.xml
<CustomField>
    <fullName>Valideur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Id du valideur</description>
    <label>Valideur</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/Piece_justificative_Sinistre__c.object-meta.xml
<CustomObject>
    <label>Pièce justificative Sinistre</label>
    <nameField>
        <label>Pièce justificative Sinistre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pièces justificatives Sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Technique Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/ContentDocumentId__c.field-meta.xml
<CustomField>
    <fullName>ContentDocumentId__c</fullName>
    <description>Store the Id of the object ContentDocument when a file is uploaded in ContentVersion and ContentDocument by the Web or Salesforce in order to get the Id immediately without traversing all relationship until ContentDocument</description>
    <label>ContentDocumentId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/ContentVersionId__c.field-meta.xml
<CustomField>
    <fullName>ContentVersionId__c</fullName>
    <description>Store the Id of the object ContentVersion when a file is uploaded in ContentVersion by the Web or Salesforce in order to get the Id immediately without traversing all relationship until ContentVersion</description>
    <label>ContentVersionId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document__c.Related_sinistre__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/LongTitle__c.field-meta.xml
<CustomField>
    <fullName>LongTitle__c</fullName>
    <description>Intitulé complet de la pièce justificative à destination des communications clients</description>
    <label>Intitulé</label>
    <length>400</length>
    <type>LongTextArea</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/NoTradable__c.field-meta.xml
<CustomField>
    <fullName>NoTradable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non négociable</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Types_piece_justificative__c.field-meta.xml
<CustomField>
    <fullName>Types_piece_justificative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Types pièce justificative</label>
    <referenceTo>Types_piece_justificative__c</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Valideur__c.field-meta.xml
<CustomField>
    <fullName>Valideur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Personne ayant validé le document</description>
    <label>Valideur</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Validite_document__c.field-meta.xml
<CustomField>
    <fullName>Validite_document__c</fullName>
    <label>Validité du document</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expected</fullName>
                <default>true</default>
                <label>1-Attendue</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <label>2-Reçu</label>
            </value>
            <value>
                <fullName>Valid</fullName>
                <label>3-Valide</label>
            </value>
            <value>
                <fullName>NotNeeded</fullName>
                <label>4-Plus réclamé</label>
            </value>
            <value>
                <fullName>Invalid</fullName>
                <label>5-Non valide</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/Types_piece_justificative__c.object-meta.xml
<CustomObject>
    <label>Types pièce justificative</label>
    <nameField>
        <label>Types pièce justificative name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types pièce justificative</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/fields/LongTitle__c.field-meta.xml
<CustomField>
    <fullName>LongTitle__c</fullName>
    <description>Intitulé complet de la pièce justificative à destination des communications clients</description>
    <label>Intitulé</label>
    <length>500</length>
    <type>Html</type>
</CustomField>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/fields/NoTradable__c.field-meta.xml
<CustomField>
    <fullName>NoTradable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non négociable</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/User/fields/Montant_approbation__c.field-meta.xml
<CustomField>
    <fullName>Montant_approbation__c</fullName>
    <label>Montant approbation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Motif_Geste_commercial.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Typologie sinistre différente du contrat</fullName>
    </customValue>
    <customValue>
        <fullName>Date du sinistre inférieure au contrat</fullName>
    </customValue>
    <customValue>
        <fullName>Plafond dépassé</fullName>
    </customValue>
    <customValue>
        <fullName>Annulation de pièces justificatives majeures</fullName>
    </customValue>
    <customValue>
        <fullName>Date de survenance du sinistre de plus de 3 mois</fullName>
    </customValue>
    <customValue>
        <fullName>Mauvaise interprétation du contrat par un GS/Erreur humaine</fullName>
    </customValue>
    <customValue>
        <fullName>Date de survenance du sinistre supérieure à 10 jours de la date de déclaration</fullName>
    </customValue>
    <customValue>
        <fullName>Date de sinistre supérieure à la date du contrat</fullName>
    </customValue>
    <customValue>
        <fullName>Dépassement d&apos;échange</fullName>
    </customValue>
    <customValue>
        <fullName>Demande contournement Règlement Contrat</fullName>
    </customValue>
    <customValue>
        <fullName>A la demande des assureurs</fullName>
    </customValue>
    <customValue>
        <fullName>Geste Commercial financier demandé</fullName>
    </customValue>
    <customValue>
        <fullName>Dépassement des réparations</fullName>
    </customValue>
    <customValue>
        <fullName>PrimaryDocNotClaim</fullName>
        <label>Pièce majeure plus réclamée</label>
    </customValue>
    <customValue>
        <fullName>Pièces non réclamée</fullName>
        <isActive>false</isActive>
        <label>Pièces non réclamée</label>
    </customValue>
    <customValue>
        <fullName>Date du sinistre inférieure à 10 jours de la date de déclaration</fullName>
        <isActive>false</isActive>
        <label>Date du sinistre inférieure à 10 jours de la date de déclaration</label>
    </customValue>
    <customValue>
        <fullName>Une mauvaise interprétation du contrat par un gestionnaire sinistre / erreur humaine</fullName>
        <isActive>false</isActive>
        <label>Une mauvaise interprétation du contrat par un gestionnaire sinistre / erreur humaine</label>
    </customValue>
    <customValue>
        <fullName>Autres</fullName>
        <isActive>false</isActive>
        <label>Autres</label>
    </customValue>
    <description>Rassemble les différents motifs de gestes commerciaux exceptionnels.</description>
    <masterLabel>Motif Geste commercial</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/PieceJustificativeTriggerHandler.cls
/***
* @author Ariane Tanguy (GFI)
* @date 23/09/2020
* @description Handler class for PieceJustificative
*/

public class PieceJustificativeTriggerHandler {
    
    /***
	* @description Check whether there should be a case update on create
	* @param newPJList - new pj
	* @param relatedCaseMap - related case map
	* @return NA
	*/
    public static void updateCaseOnCreate(List<Piece_justificative_Sinistre__c> newPJList, Map<id, Case> relatedCaseMap){
     
        // Loop over the newly created PJs to clear TECH_MissingDocs__c
        for(Piece_justificative_Sinistre__c pj : newPJList){
            if(relatedCaseMap.get(pj.Case__c).TECH_MissingDocs__c == null) {
            	relatedCaseMap.get(pj.Case__c).TECH_MissingDocs__c = ''; 
            }
        }
        
        for(Piece_justificative_Sinistre__c pj : newPJList){            
            if(relatedCaseMap.get(pj.Case__c).Status == 'En cours d\'examen'){
                relatedCaseMap.get(pj.Case__c).Status = 'Incomplet';
            }
            relatedCaseMap.get(pj.Case__c).Attente_documents__c = 'Expected';
            
            Types_piece_justificative__c tpj = [SELECT LongTitle__c FROM Types_piece_justificative__c WHERE Name = :pj.Name];
            relatedCaseMap.get(pj.Case__c).TECH_MissingDocs__c += tpj.LongTitle__c + '\n';
        }
        
        update relatedCaseMap.values();
    }
    
    /***
	* @description Check whether there should be a case update on create
	* @param newPJList - new pj
	* @param relatedCaseMap - related case map
	* @return NA
	*/
    public static void updatePJOnCreate(List<Piece_justificative_Sinistre__c> newPJList, 
                                        Map<id, List<id>> documentIdContentIdMap){
        
        // Loop over the newly update PJs
        for(Piece_justificative_Sinistre__c pj : newPJList){
            
            if(pj.Document__c != NULL &&
               documentIdContentIdMap.keySet().contains(pj.Document__c)){
                   pj.ContentDocumentId__c = documentIdContentIdMap.get(pj.Document__c)[0];
                   pj.ContentVersionId__c = documentIdContentIdMap.get(pj.Document__c)[1];
               } else {
                   pj.ContentDocumentId__c = NULL;
                   pj.ContentVersionId__c = NULL;
               }
        }
    }
    
    /***
	* @description Check whether there should be a case update
	* @param newPJList - new pj
	* @param relatedCaseMap - related case map
	* @return NA
	*/
    public static void updateCaseOnUpdate(List<Piece_justificative_Sinistre__c> newPJList, 
                                          Map<id, Piece_justificative_Sinistre__c> oldPJMap, 
                                          Map<id, Case> relatedCaseMap, 
                                          Map<id, List<Piece_justificative_Sinistre__c>> otherRelatedPJMap){
        
        // Loop over the newly update PJs
        List<Case> caseToUpdate = new List<Case>();
        for(Piece_justificative_Sinistre__c pj : newPJList){
            
            // Change the case status
            if((pj.Validite_document__c != oldPJMap.get(pj.id).Validite_document__c ||
               pj.Document__c != oldPJMap.get(pj.id).Document__c) &&
               relatedCaseMap.get(pj.Case__c).Status == 'Attribué'){
                   relatedCaseMap.get(pj.Case__c).Status = 'Incomplet';
            }
            
            // Update the Attente document checkbox
            if(pj.Validite_document__c != oldPJMap.get(pj.id).Validite_document__c && 
               (pj.Validite_document__c == 'Invalid' ||
                pj.Validite_document__c == 'Expected')){
                    relatedCaseMap.get(pj.Case__c).Attente_documents__c = 'Expected';
                }
            
            // Update the case TECH_MissingDocs__c 
            if(pj.Validite_document__c != oldPJMap.get(pj.id).Validite_document__c){
                
                relatedCaseMap.get(pj.Case__c).TECH_MissingDocs__c = '';
                
                // Otherwise, loop over expected PJ
                if(otherRelatedPJMap.keySet().contains(pj.Case__c)){
                    for(Piece_justificative_Sinistre__c p : otherRelatedPJMap.get(pj.Case__c)){
                        if(p.Validite_document__c == 'Expected'){
                            Types_piece_justificative__c tpj = [SELECT LongTitle__c FROM Types_piece_justificative__c WHERE Name = :p.Name];
                            relatedCaseMap.get(pj.Case__c).TECH_MissingDocs__c += tpj.LongTitle__c + '\n';
                        }
                    }
                }
            }  
        }
                                              
        update relatedCaseMap.values();
    }
    
    /***
	* @description Create new PJ when the status becomes not valid
	* @param newPJList - new pj
	* @param oldPJMap - old pj
	* @return NA
	*/
    public static void createNewPJ(List<Piece_justificative_Sinistre__c> newPJList, Map<id, Piece_justificative_Sinistre__c> oldPJMap){
        
        // Loop over the newly updated PJ
        List<Piece_justificative_Sinistre__c> pjToInsert = new List<Piece_justificative_Sinistre__c>();
        for(Piece_justificative_Sinistre__c pj : newPJList){
            
            // If the PJ status is now Not Valid
            if(pj.Validite_document__c != oldPJMap.get(pj.id).Validite_document__c &&
               pj.Validite_document__c == 'invalid'){
                   
                   // Create another PJ
                   Piece_justificative_Sinistre__c newPJ = new Piece_justificative_Sinistre__c();
                   newPJ.Validite_document__c = 'expected';
                   newPJ.Case__c = pj.Case__c;
                   newPJ.Name = pj.Name;
                   newPJ.Valideur__c = UserInfo.getUserId();
                   pjToInsert.add(newPJ);
               }
        }
        if(pjToInsert.size() > 0){
            insert pjToInsert;
        }
    }
    
    /***
	* @description Update the Case
	* @param validityCaseIdMap - map of case id / validity
	* @param caseToUpdateMap - map of case id / case
	* @return NA
	*/
    public static void updateSinistreOnUpdate(Map<id, Case> relatedCaseIdMap, List<Piece_justificative_Sinistre__c> relatedPJList){
        
        // Map the pj with their related case and check that all are received
        Map<String, List<Boolean>> caseIdPJMap = new Map<String, List<Boolean>>();
        //Init Tab
        for(Case c : relatedCaseIdMap.values()){
            List<Boolean> validityList = new List<Boolean>{FALSE, FALSE};
            caseIdPJMap.put(c.Id, validityList);
        }

        for(Piece_justificative_Sinistre__c p : relatedPJList){
            Boolean allReceived = p.Validite_document__c != 'Expected';
            Boolean allValid = p.Validite_document__c == 'Valid' || (p.NoTradable__c == true && p.Validite_document__c == 'NotNeeded');
            caseIdPJMap.put(p.Case__c, new List<Boolean>{allReceived, allValid});
        }
        
        // Get only the cases to be updated
        Map<Id, String> validityCaseIdMap = new Map<Id, String>();
        for(id caseId : caseIdPJMap.keySet()){
            
            if(caseIdPJMap.get(caseId)[0]){
                relatedCaseIdMap.get(caseId).Attente_documents__c = 'Received';
            }
            if(caseIdPJMap.get(caseId)[1]){
                relatedCaseIdMap.get(caseId).Attente_documents__c = 'Valid';
                if(relatedCaseIdMap.get(caseId).Attente_client_final__c == NULL && 
                   (relatedCaseIdMap.get(caseId).Status == 'Incomplet' ||
                    relatedCaseIdMap.get(caseId).Status == 'Attribué')){
                        relatedCaseIdMap.get(caseId).Status = 'En cours d\'examen';
                    }
            }
        }
        
        update relatedCaseIdMap.values();
    }

    /***
	* @description add alert if not needed piece
	* @param listPieces - List piece justificative 
	* @return NA
	*/
    public static void manageAlertNotNeeded(List<Piece_justificative_Sinistre__c> listPieces){

        List<Id> idsCaseAlertCreated = new List<Id>();
        List<Alert__c> lstAlertToCreated = new List<Alert__c>();

        for(Piece_justificative_Sinistre__c pjs : listPieces){
            if(pjs.Validite_document__c == 'NotNeeded' && pjs.NoTradable__c){
                if(!idsCaseAlertCreated.contains(pjs.Case__c)){
                    idsCaseAlertCreated.add(pjs.Case__c);
                }
            }
        }

        if(idsCaseAlertCreated.size()>0){
            List<Alert__c> alertExist = [SELECT Id,Case__c FROM Alert__c WHERE BusinessRulesNumber__c = 'RGSIN24' AND Case__c IN:idsCaseAlertCreated];
            List<Approval.ProcessSubmitRequest> lstApprovalProcessRequest = new List<Approval.ProcessSubmitRequest>();
            Map<Id,Alert__c> mapSinAlert = new Map<Id,Alert__c>();
            User currentUser = [SELECT Id,Montant_approbation__c FROM User WHERE Id=:UserInfo.getUserId()];
            for(Alert__c alert : alertExist){
                mapSinAlert.put(alert.Case__c,alert);
            }
            for(Id CaseId : idsCaseAlertCreated){
                if(!mapSinAlert.containsKey(CaseId)){
                    if(currentUser.Montant_approbation__c == 0){
                        lstAlertToCreated.add(new Alert__c(BusinessRulesNumber__c='RGSIN24',
                                                    Case__c = CaseId,
                                                    SalesDiscountMotif__c  = 'PrimaryDocNotClaim'));
                        
                        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                        req.setObjectId(CaseId);
                        req.setProcessDefinitionNameOrId('AP01_CS_AlertToValidated');
                        req.setSkipEntryCriteria(true);
                        lstApprovalProcessRequest.add(req);
                    }
                    else{
                        lstAlertToCreated.add(new Alert__c(BusinessRulesNumber__c='RGSIN24',
                                                    Case__c = CaseId,
                                                    Status__c = 'Approved',
                                                    Type_Alert__c = 'Warning',
                                                    Validation_Reason__c = 'Validation par défaut car warning',
                                                    SalesDiscountMotif__c  = 'PrimaryDocNotClaim'));
                    }
                }
            }
            if(lstAlertToCreated.size()>0){
                insert lstAlertToCreated;
                List<Case> casetoUpdated = [SELECT Id,AlertText__c FROM Case WHERE Id IN :idsCaseAlertCreated];
                List<Case> caseUpdated = new List<Case>();
                for(Case cs : casetoUpdated){
                    if(String.isBlank(cs.AlertText__c)){
                        cs.AlertText__c = 'Pièce majeure plus réclamée';
                    }
                    else{
                        cs.AlertText__c = cs.AlertText__c + '\n' + 'Pièce majeure plus réclamée';
                    }
                    caseUpdated.add(cs);
                }
                if(caseUpdated.size()>0){
                    update caseUpdated;
                }
                if(currentUser.Montant_approbation__c == 0 && lstApprovalProcessRequest.size()>0){
                    List<Approval.ProcessResult> results = Approval.process(lstApprovalProcessRequest);
                }
            }
        }
    }
}