hubSide/force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <description>Object use to save control for the fields and approvals</description>
    <label>Alert</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Alert__c/fields/BusinessRulesNumber__c.field-meta.xml
<CustomField>
    <fullName>BusinessRulesNumber__c</fullName>
    <label>Business rules number</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SalesDiscountMotif__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RGSIN10</fullName>
            </value>
            <value>
                <fullName>RGSIN11</fullName>
            </value>
            <value>
                <fullName>RGSIN12</fullName>
            </value>
            <value>
                <fullName>RGSIN13</fullName>
            </value>
            <value>
                <fullName>RGSIN15</fullName>
            </value>
            <value>
                <fullName>RGSIN14</fullName>
            </value>
            <value>
                <fullName>RGSIN16</fullName>
            </value>
            <value>
                <fullName>RGSIN17</fullName>
            </value>
            <value>
                <fullName>RGSIN18</fullName>
            </value>
            <value>
                <fullName>RGSIN19</fullName>
            </value>
            <value>
                <fullName>RGSIN20</fullName>
            </value>
            <value>
                <fullName>RGSIN21</fullName>
            </value>
            <value>
                <fullName>RGSIN22</fullName>
            </value>
            <value>
                <fullName>RGSIN23</fullName>
            </value>
            <value>
                <fullName>RGSIN24</fullName>
            </value>
            <value>
                <fullName>RGSIN00</fullName>
                <isActive>false</isActive>
                <label>RGSIN00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Alert__c/fields/SalesDiscountMotif__c.field-meta.xml
<CustomField>
    <fullName>SalesDiscountMotif__c</fullName>
    <label>Motif de geste commercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Motif_Geste_commercial</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Pouss_par_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>Pouss_par_Salesforce__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Forcer le paiement</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Demande.recordType-meta.xml
<RecordType>
    <fullName>Demande</fullName>
    <active>true</active>
    <businessProcess>Demande</businessProcess>
    <description>Demande relative à de nouveaux documents client</description>
    <label>Demande</label>
</RecordType>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/globalValueSets/Motif_Geste_commercial.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Typologie sinistre différente du contrat</fullName>
    </customValue>
    <customValue>
        <fullName>Date du sinistre inférieure au contrat</fullName>
    </customValue>
    <customValue>
        <fullName>Plafond dépassé</fullName>
    </customValue>
    <customValue>
        <fullName>Annulation de pièces justificatives majeures</fullName>
    </customValue>
    <customValue>
        <fullName>Date de survenance du sinistre de plus de 3 mois</fullName>
    </customValue>
    <customValue>
        <fullName>Mauvaise interprétation du contrat par un GS/Erreur humaine</fullName>
    </customValue>
    <customValue>
        <fullName>Date de survenance du sinistre supérieure à 10 jours de la date de déclaration</fullName>
    </customValue>
    <customValue>
        <fullName>Date de sinistre supérieure à la date du contrat</fullName>
    </customValue>
    <customValue>
        <fullName>Dépassement d&apos;échange</fullName>
    </customValue>
    <customValue>
        <fullName>Demande contournement Règlement Contrat</fullName>
    </customValue>
    <customValue>
        <fullName>A la demande des assureurs</fullName>
    </customValue>
    <customValue>
        <fullName>Geste Commercial financier demandé</fullName>
    </customValue>
    <customValue>
        <fullName>Dépassement des réparations</fullName>
    </customValue>
    <customValue>
        <fullName>PrimaryDocNotClaim</fullName>
        <label>Pièce majeure plus réclamée</label>
    </customValue>
    <customValue>
        <fullName>Pièces non réclamée</fullName>
        <isActive>false</isActive>
        <label>Pièces non réclamée</label>
    </customValue>
    <customValue>
        <fullName>Date du sinistre inférieure à 10 jours de la date de déclaration</fullName>
        <isActive>false</isActive>
        <label>Date du sinistre inférieure à 10 jours de la date de déclaration</label>
    </customValue>
    <customValue>
        <fullName>Une mauvaise interprétation du contrat par un gestionnaire sinistre / erreur humaine</fullName>
        <isActive>false</isActive>
        <label>Une mauvaise interprétation du contrat par un gestionnaire sinistre / erreur humaine</label>
    </customValue>
    <customValue>
        <fullName>Autres</fullName>
        <isActive>false</isActive>
        <label>Autres</label>
    </customValue>
    <description>Rassemble les différents motifs de gestes commerciaux exceptionnels.</description>
    <masterLabel>Motif Geste commercial</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/AlertTriggerHandlerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 06/04/2021
* @description User test class
* @Object User
*/

@isTest
public class AlertTriggerHandlerTest {
    
    /***
    * @description Checks the user's profile before delete
    * @see isDeleteAuthorized
    */
    @isTest
    static void isDeleteAuthorizedTest(){
        
         // Create a sinistre
        Case c = TestFactory.createSinistre();
        insert c;
        
        // Create a user
        User u = TestFactory.createUser();
        u.ProfileId = [SELECT Id FROM Profile WHERE Name = 'SFAM GS'].id;
        u.email = 'michael.jockson@123.com';
        insert u;
        
         // Create an alert
        Alert__c a = TestFactory.createAlert(c.id);
        insert a;
        
        // Try deleting the alert as a GS
        system.runAs(u){
            try{
                delete a;
                system.assert(false, 
                              'The alert shouldnt have been deleted - This is wrong');
            }
            catch(Exception e){
                system.assert(e.getMessage().contains('pas les droits suffisants pour supprimer'), 
                              'The error message isnt the expected one - This is wrong' + e);
            }
        }
        
        // Try again, as a super admin
        delete a;        
        system.assertEquals(0, [SELECT id FROM Alert__c].size(), 
                            'The alert shouldve been deleted - This is wrong');
    }
    
    /***
    * @description Check if Poussé par Salesforce is checked
    * @see isDeleteAuthorized
    */
    @isTest
    static void isPushedBySalesforceCheckedTest(){
        
         // Create a sinistre
        Case c = TestFactory.createSinistre();
        insert c;
                
         // Create an alert
        Alert__c a = TestFactory.createAlert(c.id);
        a.SalesDiscountMotif__c = 'Demande contournement Règlement Contrat';
       	a.BusinessRulesNumber__c = 'RGSIN19';
        insert a;
        system.assertEquals(false, 
                                c.Pouss_par_Salesforce__c);
        
        
    }
}