hubSide/force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <description>Object use to save control for the fields and approvals</description>
    <label>Alert</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Alert__c/fields/BusinessRulesNumber__c.field-meta.xml
<CustomField>
    <fullName>BusinessRulesNumber__c</fullName>
    <label>Business rules number</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SalesDiscountMotif__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RGSIN10</fullName>
            </value>
            <value>
                <fullName>RGSIN11</fullName>
            </value>
            <value>
                <fullName>RGSIN12</fullName>
            </value>
            <value>
                <fullName>RGSIN13</fullName>
            </value>
            <value>
                <fullName>RGSIN15</fullName>
            </value>
            <value>
                <fullName>RGSIN14</fullName>
            </value>
            <value>
                <fullName>RGSIN16</fullName>
            </value>
            <value>
                <fullName>RGSIN17</fullName>
            </value>
            <value>
                <fullName>RGSIN18</fullName>
            </value>
            <value>
                <fullName>RGSIN19</fullName>
            </value>
            <value>
                <fullName>RGSIN20</fullName>
            </value>
            <value>
                <fullName>RGSIN21</fullName>
            </value>
            <value>
                <fullName>RGSIN22</fullName>
            </value>
            <value>
                <fullName>RGSIN23</fullName>
            </value>
            <value>
                <fullName>RGSIN24</fullName>
            </value>
            <value>
                <fullName>RGSIN00</fullName>
                <isActive>false</isActive>
                <label>RGSIN00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Alert__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Alerts</relationshipLabel>
    <relationshipName>Alerts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Alert__c/fields/couldDeleted__c.field-meta.xml
<CustomField>
    <fullName>couldDeleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>couldDeleted</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Alert__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Approval status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>En Attente</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Dérogation acceptée</label>
            </value>
            <value>
                <fullName>Refused</fullName>
                <label>Dérogation refusée</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Clos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Number_of_Alert_plafond_depasse__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Alert_plafond_depasse__c</fullName>
    <label>Nombre Alert plafond depasse</label>
    <summaryFilterItems>
        <field>Alert__c.SalesDiscountMotif__c</field>
        <operation>equals</operation>
        <value>Plafond dépassé</value>
    </summaryFilterItems>
    <summaryForeignKey>Alert__c.Case__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Pouss_par_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>Pouss_par_Salesforce__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Forcer le paiement</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/TECH_Montant_Plafond__c.field-meta.xml
<CustomField>
    <fullName>TECH_Montant_Plafond__c</fullName>
    <formula>Asset.Indemnisation_contrat_restante__c - Montant_sinistre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_Montant_Plafond</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/classes/AlertTriggerHandler.cls
/***
* @author Ariane Tanguy (GFI)
* @date 06/04/2021
* @description Handler class for AlertTrigger
*/

public class AlertTriggerHandler {
    
    /***
	* @description Checks the user's profile before delete
	* @param alertList - list of alert to be deleted
	* @return NA
	*/
    public static void isDeleteAuthorized(List<Alert__c> alertList, Map<id, Case> relatedCaseMap){
        
        // Get the current user's profile
        String currentUserProfile = [SELECT Name 
                                     FROM Profile 
                                     WHERE id =: System.UserInfo.getProfileId()].Name;
        
        for(Alert__c a : alertList){
            system.debug('--alertList : ' + a);
            if(currentUserProfile != 'System Administrator' && a.couldDeleted__c != true
               /*!(relatedCaseMap.get(a.Case__c).TECH_Montant_Plafond__c > 0 &&
                 relatedCaseMap.get(a.Case__c).Number_of_Alert_plafond_depasse__c >= 1)*/ ){
                     throw new DeleteNotAuthorizedException('Vous n\'avez pas les droits suffisants pour supprimer cette alerte' + '\n' + 
                                                            'You don\'t have the permission to delete the current record.');
            }
        }
    }
    
      /***
	* @description Update Pouss_par_Salesforce__c field if alert is approved
	* @param alertList - list of alert
	* @return NA
	*/
    public static void updateCaseFields(List<Alert__c> alertList, Map<id, Case> relatedCaseMap){
        
        system.debug('--updateCaseFields');
        
        List<Case> caseToUpdate = new List<Case>();
        
        for(Alert__c a : alertList){
            
            system.debug('--Status__c'+a.Status__c);
            system.debug('--BusinessRulesNumber__c'+a.BusinessRulesNumber__c);
            
            if( a.Status__c == 'Approved' &&
                a.BusinessRulesNumber__c == 'RGSIN19'
               ){
                relatedCaseMap.get(a.Case__c).Pouss_par_Salesforce__c = true;
                caseToUpdate.add(relatedCaseMap.get(a.Case__c));
            }
        }

        update caseToUpdate;
    }
    
    public class DeleteNotAuthorizedException extends Exception {}
}