hubSide/force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <description>Object use to save control for the fields and approvals</description>
    <label>Alert</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Alert__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Alerts</relationshipLabel>
    <relationshipName>Alerts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Number_of_Alert_plafond_depasse__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Alert_plafond_depasse__c</fullName>
    <label>Nombre Alert plafond depasse</label>
    <summaryFilterItems>
        <field>Alert__c.SalesDiscountMotif__c</field>
        <operation>equals</operation>
        <value>Plafond dépassé</value>
    </summaryFilterItems>
    <summaryForeignKey>Alert__c.Case__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/TECH_Montant_Plafond__c.field-meta.xml
<CustomField>
    <fullName>TECH_Montant_Plafond__c</fullName>
    <formula>Asset.Indemnisation_contrat_restante__c - Montant_sinistre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_Montant_Plafond</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/classes/AlertTriggerHelper.cls
/***
* @author Ariane Tanguy (GFI)
* @date 16/04/2021
* @description Helper class for AlertTrigger
*/

public class AlertTriggerHelper {
    
    /***
	* @description Get the related case
	* @return Map<id, Case>
	*/
    public static Map<id, Case> getRelatedCase(List<Alert__c> alertList){
        
        // Get the related case id
        Set<id> relatedCaseIdSet = new Set<id>();
        for(Alert__c a : alertList){
            relatedCaseIdSet.add(a.Case__c);
        }
        
        Map<id, Case> relatedCaseMap = new Map<id, Case>([SELECT id, TECH_Montant_Plafond__c, Number_of_Alert_plafond_depasse__c
                                                          FROM Case
                                                          WHERE id IN: relatedCaseIdSet]);
        
        return relatedCaseMap;
    }
}