hubSide/force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <description>Object use to save control for the fields and approvals</description>
    <label>Alert</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Alert__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Alerts</relationshipLabel>
    <relationshipName>Alerts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Alert__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Approval status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>En Attente</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Dérogation acceptée</label>
            </value>
            <value>
                <fullName>Refused</fullName>
                <label>Dérogation refusée</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Clos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Date_debut_contrat__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_contrat__c</fullName>
    <description>Date de début du contrat souscrit par le client.</description>
    <label>Date de début du contrat</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Etat_paiement__c.field-meta.xml
<CustomField>
    <fullName>Etat_paiement__c</fullName>
    <label>Etat paiement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>unpaid</fullName>
                <label>Impayé</label>
            </value>
            <value>
                <fullName>valid</fullName>
                <label>Valide</label>
            </value>
            <value>
                <fullName>regularisedUnpaid</fullName>
                <label>Impayé régularisé</label>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Montant_indemnisation__c.field-meta.xml
<CustomField>
    <fullName>Montant_indemnisation__c</fullName>
    <label>Montant indemnisation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Plafond__c.field-meta.xml
<CustomField>
    <fullName>Plafond__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Plafond</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Sinistre_declares_asset__c.field-meta.xml
<CustomField>
    <fullName>Sinistre_declares_asset__c</fullName>
    <label>#Sinistre declares</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/AnswerNature__c.field-meta.xml
<CustomField>
    <fullName>AnswerNature__c</fullName>
    <description>Indique si la réponse à la réclamation est favorable ou non</description>
    <label>Nature de la réponse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Favorable</fullName>
            </value>
            <value>
                <fullName>PartiallyFavorable</fullName>
                <label>Favorable partiellement</label>
            </value>
            <value>
                <fullName>Refused</fullName>
                <label>Refus</label>
            </value>
            <value>
                <fullName>NotApplicable</fullName>
                <label>Sans objet</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/AssociatedSinister__c.field-meta.xml
<CustomField>
    <fullName>AssociatedSinister__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dossier Sinistre concerné par la Réclamation, Demande</description>
    <label>Sinistre associé</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sinistre clôturé, Sinistre, SinistreBApp</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Dossiers associés</relationshipLabel>
    <relationshipName>AssociatedCase</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Attente_documents__c.field-meta.xml
<CustomField>
    <fullName>Attente_documents__c</fullName>
    <label>Attente documents</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
                <label>Reçu(s)</label>
            </value>
            <value>
                <fullName>Valid</fullName>
                <label>Valide(s)</label>
            </value>
            <value>
                <fullName>Expected</fullName>
                <default>true</default>
                <label>Attendu(s)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Date_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Date_sinistre__c</fullName>
    <description>JJ/MM/AAAA</description>
    <label>Date du sinistre</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Montant_geste_co__c.field-meta.xml
<CustomField>
    <fullName>Montant_geste_co__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Montant du geste commercial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Montant_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Montant_sinistre__c</fullName>
    <label>Coût global</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>CASE(
    Record_Type_Name__c, 
    &apos;Sinistre&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;INS&quot; + &apos;&apos; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
        &quot;TMP&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;SinistreBApp&apos;, Num_sinistre_B_Appli__c,
    &apos;Sinistre clôturé&apos;, Subject, 
    &apos;Déclaration&apos;, CaseNumber, 
    &apos;SAV&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;SAV&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;), 
        &quot;DEM&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;Réclamation&apos;, &quot;REC&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
				&apos;Demande&apos;, &quot;DEM&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
    &apos;GED&apos; + &apos;&apos; + RIGHT(CaseNumber, 6)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro de la requête</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/TECH_ApprovalProcessStatus__c.field-meta.xml
<CustomField>
    <fullName>TECH_ApprovalProcessStatus__c</fullName>
    <description>Field use to know if there are an approval process in progress, use it in approval process</description>
    <label>TECH_ApprovalProcessStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalProcess_Status</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/tech_numsin__c.field-meta.xml
<CustomField>
    <fullName>tech_numsin__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Champ technique servant à la numérotation des dossiers qui doit garantir sinistre doit garantir :
- l&apos;unicité (aucun doublon)
- la chronologie des numéros (format du numéro de sinistre: SINXXXXXX, &quot;SIN&quot; préfixe invariable et &quot;XXXXXX&quot; séquence incrémentale et choronologique sur 6 chiffres
- la séquentialité (pas de numéro manquant)</description>
    <label>tech_numsin</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <description>Thème principal de la réclamation</description>
    <label>Thème</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InternalSubscription</fullName>
                <label>Souscription Interne</label>
            </value>
            <value>
                <fullName>ExternalSubscription</fullName>
                <label>Souscription Externe</label>
            </value>
            <value>
                <fullName>Termination</fullName>
                <label>Résiliation</label>
            </value>
            <value>
                <fullName>Sinister</fullName>
                <label>Sinistre</label>
            </value>
            <value>
                <fullName>Gestion du Contrat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Typologie_Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Typologie_Sinistre__c</fullName>
    <label>Typologie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Case_Typologie</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/vlocity_ins__Verified__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verified</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Declaration.recordType-meta.xml
<RecordType>
    <fullName>Declaration</fullName>
    <active>true</active>
    <businessProcess>Declaration Web</businessProcess>
    <label>Déclaration</label>
</RecordType>

hubSide/force-app/main/default/objects/Case/recordTypes/Demande.recordType-meta.xml
<RecordType>
    <fullName>Demande</fullName>
    <active>true</active>
    <businessProcess>Demande</businessProcess>
    <description>Demande relative à de nouveaux documents client</description>
    <label>Demande</label>
</RecordType>

hubSide/force-app/main/default/objects/Case/recordTypes/Reclamation.recordType-meta.xml
<RecordType>
    <fullName>Reclamation</fullName>
    <active>true</active>
    <businessProcess>Reclamation</businessProcess>
    <description>Record Type pour les dossiers de réclamation</description>
    <label>Réclamation</label>
</RecordType>

hubSide/force-app/main/default/objects/Case/recordTypes/SAV.recordType-meta.xml
<RecordType>
    <fullName>SAV</fullName>
    <active>true</active>
    <businessProcess>SAV</businessProcess>
    <description>Case créé après un sinistre, dans le cas où l&apos;équipement sinistré n&apos;ait pas été correctement réparé/remplacé.</description>
    <label>SAV</label>
</RecordType>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>Sinistre__r.Numero_sinistre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro du sinistre</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/Mouvements_financiers__c.object-meta.xml
<CustomObject>
    <label>Calcul Indemnisation</label>
    <nameField>
        <label>Nom du mouvement financier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calcul Indemnisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Mouvements_financiers__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Calcul Indemnisations</relationshipLabel>
    <relationshipName>Mouvements_financiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/Piece_justificative_Sinistre__c.object-meta.xml
<CustomObject>
    <label>Pièce justificative Sinistre</label>
    <nameField>
        <label>Pièce justificative Sinistre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pièces justificatives Sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Technique Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Types_piece_justificative__c.field-meta.xml
<CustomField>
    <fullName>Types_piece_justificative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Types pièce justificative</label>
    <referenceTo>Types_piece_justificative__c</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/Types_piece_justificative__c.object-meta.xml
<CustomObject>
    <label>Types pièce justificative</label>
    <nameField>
        <label>Types pièce justificative name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types pièce justificative</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/fields/Perte__c.field-meta.xml
<CustomField>
    <fullName>Perte__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Perte</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/globalValueSets/ApprovalProcess_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Approval</fullName>
        <default>true</default>
        <label>Not Approval</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <description>used this field to managed approval process status on record</description>
    <masterLabel>ApprovalProcess_Status</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/globalValueSets/Case_Typologie.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Broken</fullName>
        <label>Casse</label>
    </customValue>
    <customValue>
        <fullName>Pickpocketed</fullName>
        <label>Vol toute cause</label>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
        <label>Perte</label>
    </customValue>
    <customValue>
        <fullName>Oxidised</fullName>
        <label>Oxydation</label>
    </customValue>
    <customValue>
        <fullName>Robbed</fullName>
        <label>Vol Caractérisé</label>
    </customValue>
    <customValue>
        <fullName>ReturnedByCarrier</fullName>
        <label>Retour transporteur</label>
    </customValue>
    <customValue>
        <fullName>LostByCarrier</fullName>
        <label>Perte transporteur</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterRepair</fullName>
        <label>Dysfonctionnement suite à réparation</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterExchange</fullName>
        <label>Dysfonctionnement suite à échange</label>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <label>Autres</label>
    </customValue>
    <customValue>
        <fullName>ClaimCreation</fullName>
        <label>Création Réclamation</label>
    </customValue>
    <customValue>
        <fullName>ClaimFollowUp</fullName>
        <label>Suivi Réclamation</label>
    </customValue>
    <customValue>
        <fullName>AccidentCreation</fullName>
        <label>Création Sinistre</label>
    </customValue>
    <description>Liste de toutes les typologies possibles (Sinistre, SAV, Demande)</description>
    <masterLabel>Case_Typologie</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/CaseTriggerHandlerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 28/07/2020
* @description Case test class
* @Object Case
*/

@isTest
public class CaseTriggerHandlerTest {

    /***
    * @description Update the record type on formule creation
    * @see setSinistreNumber
    */
    @isTest
    public static void setSinistreNumberOnCreationTest(){
        
        Account a = TestFactory.createClient();
        insert a;
        
        id caseSinistreId = UtilityClassHelper.getCreatedRecordType('Sinistre');
        Case c = new Case();
        c.AccountId = a.id;
        c.RecordTypeId = caseSinistreId;
        insert c;

        List<Case> lstCase = [SELECT id, tech_numsin__c,AccountId FROM Case WHERE RecordTypeId =: caseSinistreId];
        system.assertEquals(1, lstCase[0].tech_numsin__c, 
                            'The field doesnt have the correct tech number - This is wrong');
        
        system.assertEquals(1, lstCase.size());
        
        // Create another sinistre
        Case c1 = new Case();
        c1.RecordTypeId = caseSinistreId;
        c1.AccountId = lstCase[0].AccountId;
        insert c1;
        Test.startTest();
        c1 = [SELECT id, tech_numsin__c, Numero_sinistre__c FROM Case WHERE id =: c1.id];
        system.assertEquals(2, c1.tech_numsin__c, 
                            'The field shouldnt have been incremented - This is wrong');
        system.assertEquals('INS000002', c1.Numero_sinistre__c, 
                            'The number is not the expected one - This is wrong');
        
        // Close the first sinistre
        lstCase[0].Status = 'closed_exchange';
        update lstCase[0];
        Case c1update = [SELECT id, tech_numsin__c, Numero_sinistre__c, Record_Type_Name__c FROM Case WHERE id =: lstCase[0].id];
        system.assertEquals('Sinistre clôturé', c1update.Record_Type_Name__c, 
                            'The number is not the expected one - This is wrong');
        system.assertEquals('INS000001', c1update.Numero_sinistre__c, 
                            'The number is not the expected one - This is wrong');
        
        // Create a last sinistre, unvalidated
        Case c2 = new Case();
        c2.RecordTypeId = caseSinistreId;
        c2.AccountId = lstCase[0].AccountId;
        c2.vlocity_ins__Verified__c = true;
        insert c2;
        
        c2 = [SELECT id, tech_numsin__c, Numero_sinistre__c FROM Case WHERE id =: c2.id];
        system.assertEquals(1, c2.tech_numsin__c, 
                            'The field shouldnt have been incremented - This is wrong');
        system.assert(c2.Numero_sinistre__c.contains('TMP'), 
                            'The number is not the expected one - This is wrong');
        
        // The last sinistre is actually ok
        c2.vlocity_ins__Verified__c = false;
        update c2;
        
        c2 = [SELECT id, tech_numsin__c, Numero_sinistre__c FROM Case WHERE id =: c2.id];
        system.assertEquals(3, c2.tech_numsin__c, 
                            'The field should have been incremented - This is wrong');
        system.assertEquals('INS000003', c2.Numero_sinistre__c, 
                            'The number is not the expected one - This is wrong');
        Test.stopTest();
    }
    
    /***
    * @description Set the Reclamation Number on Reclamation creation
    * @see setReclamationNumber
    */
    @isTest
    public static void setReclamationNumberOnCreationTest(){
        
        // Create an account 
        Account a = TestFactory.createClient();
        insert a;
        
        // Create a Contract
        Asset c = TestFactory.createAssuranceAsset(a.id);
        insert c;
        
        // Create a Reclamation
        Case r = TestFactory.createReclamation(a.id, c.id);
        insert r;
        
        r = [SELECT id, tech_numsin__c, Numero_sinistre__c FROM Case WHERE id =: r.id];
        system.assertEquals(1, r.tech_numsin__c, 
                            'The field doesnt have the correct tech number - This is wrong');
        system.assertEquals('REC000001', r.Numero_sinistre__c, 
                            'The field doesnt have the correct reclamation number - This is wrong');
        
        // Create a second Reclamation
        Case c1 = TestFactory.createReclamation(a.id, c.id);
        insert c1;
        
        c1 = [SELECT id, tech_numsin__c, Numero_sinistre__c  FROM Case WHERE id =: c1.id];
        system.assertEquals(2, c1.tech_numsin__c, 
                            'The field doesnt have the correct tech number - This is wrong');
        system.assertEquals('REC000002', c1.Numero_sinistre__c, 
                            'The field doesnt have the correct reclamation number - This is wrong');
    }

    /***
    * @description Update the account if needed
    * @see updateAccountOnAssetUpdate
    */
    @isTest
    public static void updateAccountOnAssetUpdateTest(){
        
        // Create an asset
        Asset a = TestFactory.createAssuranceAsset();
        insert a;
        
        // Create a sinistre
        id caseSinistreId = UtilityClassHelper.getCreatedRecordType('Sinistre');
        Case c = new Case();
        c.AssetId = a.id;
        c.RecordTypeId = caseSinistreId;
        insert c;
        
        a = [SELECT id, AccountId FROM Asset WHERE id =: a.id];
        c = [SELECT id, AccountId FROM Case WHERE id =: c.id];
        system.assertEquals(a.AccountId, c.AccountId, 
                            'The case doesnt have the correct accountId - This is wrong');
        
        // Create another asset
        Asset a1 = TestFactory.createAssuranceAsset();
        insert a1;
        
        c.AssetId = a1.id;
        update c;
        
        a1 = [SELECT id, AccountId FROM Asset WHERE id =: a1.id];
        c = [SELECT id, AccountId FROM Case WHERE id =: c.id];
        system.assertEquals(a1.AccountId, c.AccountId, 
                            'The case doesnt have the correct accountId - This is wrong');
    }

    /***
    * @description Update the related sinistre if needed
    * @see updateSinistreOnReclaUpdate
    */
    @isTest
    public static void updateSinistreOnReclaUpdateTest(){
        
        // Create an account
        Account acc = TestFactory.createClient();
        insert acc;
        
        // Create an asset
        Asset a = TestFactory.createAssuranceAsset(acc.id);
        insert a;        
        
        // Create a sinistre
        Case c = TestFactory.createSinistre(acc.id, a.id);
        insert c;
        
        // Create its related reclamation
        Case r = TestFactory.createReclamation(acc.id, a.id);
        r.Theme__c = 'Sinister';
        r.AssociatedSinister__c = c.id;
        insert r;
        
        // Update the reclamation
        r.AnswerNature__c = 'Favorable';
        update r;
        
        c = [SELECT id, Status, RecordTypeId FROM Case WHERE id =: c.id];
        system.assertEquals('En cours d\'examen', c.Status, 
                            'The sinistre status hasnt been updated - This is wrong');
        system.assertEquals(UtilityClassHelper.getCreatedRecordType('Sinistre'), c.RecordTypeId, 
                            'The sinistre record type hasnt been updated - This is wrong');
    }

    /***
    * @description Update the related equipement sinistre on case (sinistre + sav) validation
    * @see updateEquipSinOnCaseValidation
    */
    @isTest
    public static void updateEquipSinOnCaseValidationTest(){
        
        // Create an account
        Account acc = TestFactory.createClient();
        insert acc;
        
        // Create an asset
        Asset a = TestFactory.createAssuranceAsset(acc.id);
        insert a;
        
        // Create a sinistre
        Case c = TestFactory.createSinistre(acc.id, a.id);
        insert c;
        
        // Create another sinistre
        Case c1 = TestFactory.createSinistre(acc.id, a.id);
        c1.vlocity_ins__Verified__c = true;
        insert c1;
        
        // Create an equipement sinistre
        Equipement_Sinistre__c e = new Equipement_Sinistre__c();
        e.sinistre__c = c1.id;
        insert e;
        
        c1 = [SELECT id, Numero_sinistre__c FROM Case WHERE id =: c1.id];
        e = [SELECT id, Name FROM Equipement_Sinistre__c WHERE id =: e.id];
        system.assert(e.Name.contains('TMP'), 
                            'The equipSin name shouldve been initiated with the case TMP number - This is wrong');
        
        // Actually, the sinistre is validated
        c1.vlocity_ins__Verified__c = false;
        update c1;
        
        c1 = [SELECT id, Numero_sinistre__c FROM Case WHERE id =: c1.id];
        system.assertEquals('INS000002', c1.Numero_sinistre__c, 
                            'The number is not the expected one - This is wrong');
        
        e = [SELECT id, Name FROM Equipement_Sinistre__c WHERE id =: e.id];
        system.assert(e.Name.contains('INS000002'), 
                            'The equipSin name shouldve been updated with the case INS number - This is wrong');        
    }
    
    /***
    * @description Checks the user's profile before delete
    * @see isDeleteAuthorized
    */
    @isTest
    public static void isDeleteAuthorizedTest(){
        
        // Create a sinistre
        Case c = TestFactory.createSinistre();
        insert c;
        
        // Create a user
        User u = TestFactory.createUser();
        u.ProfileId = [SELECT Id FROM Profile WHERE Name = 'SFAM GS'].id;
        u.email = 'michael.jockson@123.com';
        insert u;
        
        // Try deleting the case as a GS
        system.runAs(u){
            try{
                delete c;
                system.assert(false, 
                              'The case shouldnt have been deleted - This is wrong');
            }
            catch(Exception e){
                system.assert(e.getMessage().contains('pas les droits suffisants pour supprimer'), 
                              'The error message isnt the expected one - This is wrong' + e);
            }
        }
        
        // Try again, as a super admin
        delete c;        
        system.assertEquals(0, [SELECT id FROM Case].size(), 
                            'The case shouldve been deleted - This is wrong');
    }

    /***
    * @description Convert a decla web into sinistre
    * @see setSinistreNumber
    * @see createNecessaryDocs
    */
    @isTest
    public static void convertDeclaWebTest(){
        
        // Create a type de piece justificative
        Types_piece_justificative__c t = new Types_piece_justificative__c();
        t.Perte__c = TRUE;
        t.Name = 'Permis de chasse';
        insert t;
        
        // Create a client
        Account a = TestFactory.createClient();
        insert a;
        
        // Create a decla web
        Case c = new Case();
        c.AccountId = a.id;
        c.RecordTypeId = UtilityClassHelper.getCreatedRecordType('Declaration');
        c.Typologie_Sinistre__c = 'lost';
        insert c;
        
        // Check whether a piece justificative has been created
        List<Piece_justificative_Sinistre__c> pList = [SELECT id, Case__c FROM Piece_justificative_Sinistre__c WHERE Case__c =: c.id];
        system.assertEquals(1, pList.size(), 
                           'There should have been at least one pj created - This is wrong');
        
        // Convert the declaration into a sinitre
        c.RecordTypeId = UtilityClassHelper.getCreatedRecordType('Sinistre');
        update c;
        
        c = [SELECT id, tech_numsin__c, Numero_sinistre__c FROM Case WHERE id =: c.id];
        system.assertEquals(1, c.tech_numsin__c, 
                            'The field should have been incremented - This is wrong');
        system.assertEquals('INS000001', c.Numero_sinistre__c, 
                            'The number is not the expected one - This is wrong');
        
        pList = [SELECT id, Case__c FROM Piece_justificative_Sinistre__c WHERE Case__c =: c.id];
        system.assertEquals(1, pList.size(), 
                           'There should have been at least one pj created - This is wrong');
    }
    
    /***
    * @description Check whether empty piece justificatives are created on case creation
    * @see createNecessaryDocs
    */
    @isTest
    public static void createNecessaryDocsTest(){
        
        // Create a type de piece justificative
        Types_piece_justificative__c t = new Types_piece_justificative__c();
        t.Perte__c = TRUE;
        t.Name = 'Permis de chasse';
        insert t;
        
        // Create an account
        Account a = TestFactory.createClient();
        insert a;
        
        // Create a case
        id caseSinistreId = UtilityClassHelper.getCreatedRecordType('Sinistre');
        Case c = new Case();
        c.AccountId = a.id;
        c.RecordTypeId = caseSinistreId;
        c.Typologie_Sinistre__c = 'lost';
        insert c;
        
        // Check whether a piece justificative has been created
        Piece_justificative_Sinistre__c p = [SELECT id, Case__c FROM Piece_justificative_Sinistre__c WHERE Case__c =: c.id];
        system.assertEquals(c.id, p.Case__c, 
                           'There should have been at least one pj created - This is wrong');
    }

    /***
    * @description test method Alert use initUpdateAlertOnUpdate to init data
    */
    @isTest
    public static void updateAlertOnUpdate(){
        
        // Create an account
        Account a = TestFactory.createClient();
        insert a;
        
        Asset cSinitre = TestFactory.createAssuranceAsset(a.Id);
        cSinitre.Etat_paiement__c = 'valid';
        insert cSinitre;

        id caseSinistreId = UtilityClassHelper.getCreatedRecordType('Sinistre');
        Case c = new Case();
        c.AccountId = a.id;
        c.RecordTypeId = caseSinistreId;
        c.Typologie_Sinistre__c = 'lost';
        c.Attente_documents__c = 'Received';
        c.AssetId = cSinitre.Id;
        insert c;

        Alert__c al = TestFactory.createAlert(c.Id);
        insert al;

        Approval.ProcessSubmitRequest req1 = 
            new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(c.id); 
        req1.setProcessDefinitionNameOrId('AP01_CS_AlertToValidated');
        req1.setSkipEntryCriteria(true);
        Approval.ProcessResult result = Approval.process(req1);
        
        c = [SELECT id, TECH_ApprovalProcessStatus__c
             FROM Case 
             WHERE id =: c.id];

        Map<Id,ProcessInstance> listProcessInstance = new Map<Id,ProcessInstance>([SELECT Id, CreatedBy.Name, Status, 
                                                                                   TargetObject.Name, TargetObject.Id 
                                                                                   FROM ProcessInstance]);
        List<Id> setIds = new List<Id>(listProcessInstance.keySet());
        List<String> idsProcess = (List<String>) setIds;
        idsProcess.addAll(setIds);
        String comment = 'Commentaire ';
        
        Test.StartTest();
        List<ProcessInstanceWorkItem> pIWItem = [SELECT Id 
                                                 FROM ProcessInstanceWOrkItem 
                                                 WHERE ProcessInstanceId IN :setIds];
        if(pIWItem.size() > 0){
            
            //Manage approval process request
            List<Approval.ProcessWorkitemRequest> listApproval = new List<Approval.ProcessWorkitemRequest>();
            
            for(ProcessInstanceWorkItem record : pIWItem){
                Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                req.setComments(comment);
                req.setWorkitemId(record.Id);
                req.setAction('Approve');
                listApproval.add(req);
            }
            Approval.ProcessResult[] listResultApproval =  Approval.process(listApproval);
        }

        ProcessInstance processInstance = [SELECT Id,Status FROM ProcessInstance LIMIT 1 ]; // HERE
        system.assertEquals('Approved', processInstance.Status, 
        'Approval process is not Approved');
        Test.StopTest();

        al = [SELECT Id,Status__c FROM Alert__c LIMIT 1];
        system.assertEquals('Approved', al.Status__c, 
        'Alert record is not updated');
    }

    /***
    * @description test method Alert use initUpdateAlertOnUpdate to init data
    */
    @isTest
    public static void updateAssetKPITest(){
        
        // Create an asset
        Asset a = TestFactory.createAssuranceAssetWithFormula();
        
        // Create a sinistre
        Case c = TestFactory.createSinistre(a.AccountId, a.Id);
        c.Date_sinistre__c = System.today().addMonths(-11);
        c.Montant_sinistre__c = 2600;
        c.Status = 'closed_exchange';
        
        Test.StartTest();
        insert c;
        Test.StopTest();
        
        // Check whether the asset has been updated
        a = [SELECT Sinistre_declares_asset__c, Montant_indemnisation__c, Plafond__c, AccountId
            FROM Asset 
            WHERE id =: a.id];
        
        system.assertEquals(a.Sinistre_declares_asset__c, 1, 
                            'The number of declared sinistre shouldve been updated - This is wrong');
        system.assertEquals(a.Montant_indemnisation__c, c.Montant_sinistre__c, 
                            'The montant indemn shouldve been updated - This is wrong');
        
        // Check whether the geste co has been updated on the sinistre
        c = [SELECT Montant_geste_co__c, Montant_sinistre__c
            FROM Case
            WHERE id =: c.id];
        system.assertEquals(-(a.Plafond__c - c.Montant_sinistre__c), c.Montant_geste_co__c, 
                            'The montant indemn shouldve been updated - This is wrong');
    }

    
    /***
    * @description tes method to test ForceValueApprovalProcess method
    */
    @isTest
    public static void testForceValueApprovalProcess(){
        id caseSinistreId = UtilityClassHelper.getCreatedRecordType('Sinistre');
        // Create an asset
        Asset ast = TestFactory.createAssuranceAssetWithFormula();
        Case cs = TestFactory.createSinistre(ast.AccountId,ast.Id);
        cs.Date_sinistre__c = System.today().addMonths(-11);
        cs.Montant_sinistre__c = 200;
        cs.RecordTypeId = caseSinistreId;
        cs.TECH_ApprovalProcessStatus__c = 'In Progress';
    
        Test.StartTest();
        insert cs;
        cs.TECH_ApprovalProcessStatus__c = 'Approved';
        update cs;
        Test.StopTest();
        Case csAfter = [SELECT Id,TECH_ApprovalProcessStatus__c FROM Case WHERE Id =:cs.Id];
        system.assertEquals('Not Approval',csAfter.TECH_ApprovalProcessStatus__c, 
        'TECH_ApprovalProcessStatus__c updated');
    }
    
     /***
    * @description test method to test createAlertOnUpdate method
    */
    @isTest
    public static void createAlertOnUpdate(){
        // Create an account
        Account a = TestFactory.createClient();
        insert a;
        
        // Create an asset
        Asset cSinistre = TestFactory.createAssuranceAsset(a.Id);
        cSinistre.Etat_paiement__c = 'valid';
        cSinistre.Date_debut_contrat__c = Date.valueOf('2022-07-07 00:00:00');
        cSinistre.Date_cloture__c = Date.valueOf('2021-07-07 00:00:00');
        insert cSinistre;

        // Create Case (Sinistre)
        id caseSinistreId = UtilityClassHelper.getCreatedRecordType('Sinistre');
        Case c = new Case();
        c.AccountId = a.id;
        c.RecordTypeId = caseSinistreId;
        c.Typologie_Sinistre__c = 'lost';
        c.Attente_documents__c = 'Received';
        c.AssetId = cSinistre.Id;
        c.Date_sinistre__c = Date.valueOf('2021-07-05 00:00:00');
        c.ClientDeclarationValidationDate__c = Date.valueOf('2021-07-10 00:00:00');
        insert c;

        // Update Date Sinistre
        c.Date_sinistre__c = Date.valueOf('2021-07-02 00:00:00');
        update c;
        
        Test.StartTest();
        
        List<Alert__c> CaseAlert = [SELECT Id FROM Alert__c WHERE Case__c =: c.Id AND BusinessRulesNumber__c = 'RGSIN11'];
        system.assert(CaseAlert.size() > 0, 'No RGSIN11 alert on case');

        // Update Date Sinistre
        c.Date_sinistre__c = Date.valueOf('2021-07-08 00:00:00');
        update c;

        List<Alert__c>CaseAlert2 = [SELECT Id FROM Alert__c WHERE Case__c =: c.Id AND BusinessRulesNumber__c = 'RGSIN17'];
        system.assert(CaseAlert2.size() > 0, 'No RGSIN17 alert on case');

        // Update Date Sinistre
        c.Date_sinistre__c = Date.valueOf('2021-07-10 00:00:00');
        c.ClientDeclarationValidationDate__c = Date.valueOf('2021-07-25 00:00:00');
        update c;

        List<Alert__c> CaseAlert3 = [SELECT Id FROM Alert__c WHERE Case__c =: c.Id AND BusinessRulesNumber__c = 'RGSIN16'];
        system.assert(CaseAlert3.size() > 0, 'No RGSIN16 alert on case');

        // Update Date Sinistre
        c.ClientDeclarationValidationDate__c = Date.valueOf('2021-11-10 00:00:00');
        update c;

        List<Alert__c> CaseAlert4 = [SELECT Id FROM Alert__c WHERE Case__c =: c.Id AND BusinessRulesNumber__c = 'RGSIN15'];
        system.assert(CaseAlert4.size() > 0, 'No RGSIN15 alert on case');
    }
    
    /***
    * @description test method to test updateCalculIndemnisationOnUpdate method
    */
    @isTest
    public static void updateCalculIndemnisationOnUpdateTest(){
       // Create an account
       Account a = TestFactory.createClient();
       insert a;
       
       Asset cSinitre = TestFactory.createAssuranceAsset(a.Id);
       cSinitre.Etat_paiement__c = 'valid';
       insert cSinitre;

       id caseSinistreId = UtilityClassHelper.getCreatedRecordType('Sinistre');
       Case c = new Case();
       c.AccountId = a.id;
       c.RecordTypeId = caseSinistreId;
       c.Typologie_Sinistre__c = 'lost';
       c.Attente_documents__c = 'Received';
       c.AssetId = cSinitre.Id;
       insert c;

       Mouvements_financiers__c cal = TestFactory.createMouvementFinancier(c.Id);
       insert cal;
       cal.Statut__c = 'En cours d\'approbation';
       update cal;

       Approval.ProcessSubmitRequest req1 = 
           new Approval.ProcessSubmitRequest();
       req1.setComments('Submitting request for approval.');
       req1.setObjectId(c.id); 
       req1.setProcessDefinitionNameOrId('AP01_CS_AlertToValidated');
       req1.setSkipEntryCriteria(true);
       Approval.ProcessResult result = Approval.process(req1);
       
       c = [SELECT id, TECH_ApprovalProcessStatus__c
            FROM Case 
            WHERE id =: c.id];

       Map<Id,ProcessInstance> listProcessInstance = new Map<Id,ProcessInstance>([SELECT Id, CreatedBy.Name, Status, 
                                                                                  TargetObject.Name, TargetObject.Id 
                                                                                  FROM ProcessInstance]);
       List<Id> setIds = new List<Id>(listProcessInstance.keySet());
       List<String> idsProcess = (List<String>) setIds;
       idsProcess.addAll(setIds);
       String comment = 'Commentaire ';
       
       Test.StartTest();
       List<ProcessInstanceWorkItem> pIWItem = [SELECT Id 
                                                FROM ProcessInstanceWOrkItem 
                                                WHERE ProcessInstanceId IN :setIds];
       if(pIWItem.size() > 0){
           
           //Manage approval process request
           List<Approval.ProcessWorkitemRequest> listApproval = new List<Approval.ProcessWorkitemRequest>();
           
           for(ProcessInstanceWorkItem record : pIWItem){
               Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
               req.setComments(comment);
               req.setWorkitemId(record.Id);
               req.setAction('Approve');
               listApproval.add(req);
           }
           Approval.ProcessResult[] listResultApproval =  Approval.process(listApproval);
       }

       ProcessInstance processInstance = [SELECT Id,Status FROM ProcessInstance LIMIT 1 ]; // HERE
       system.assertEquals('Approved', processInstance.Status, 
       'Approval process is not Approved');
       Test.StopTest();

       cal = [SELECT Id,Statut__c FROM Mouvements_financiers__c WHERE Case__c = :c.Id LIMIT 1];
       system.assertEquals('Demande en cours', cal.Statut__c, 
       'Calcul indemnisation record is not updated');
    }
}