hubSide/force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <description>Object use to save control for the fields and approvals</description>
    <label>Alert</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Alert__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Alerts</relationshipLabel>
    <relationshipName>Alerts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/Formule__c.field-meta.xml
<CustomField>
    <fullName>Formule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Formule</label>
    <referenceTo>vlocity_ins__AssetCoverage__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Asset/fields/TECH_CalculatorIndicLastChange__c.field-meta.xml
<CustomField>
    <fullName>TECH_CalculatorIndicLastChange__c</fullName>
    <label>TECH_CalculatorIndicLastChange</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/AnswerNature__c.field-meta.xml
<CustomField>
    <fullName>AnswerNature__c</fullName>
    <description>Indique si la réponse à la réclamation est favorable ou non</description>
    <label>Nature de la réponse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Favorable</fullName>
            </value>
            <value>
                <fullName>PartiallyFavorable</fullName>
                <label>Favorable partiellement</label>
            </value>
            <value>
                <fullName>Refused</fullName>
                <label>Refus</label>
            </value>
            <value>
                <fullName>NotApplicable</fullName>
                <label>Sans objet</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/AssociatedSinister__c.field-meta.xml
<CustomField>
    <fullName>AssociatedSinister__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dossier Sinistre concerné par la Réclamation, Demande</description>
    <label>Sinistre associé</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sinistre clôturé, Sinistre, SinistreBApp</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Dossiers associés</relationshipLabel>
    <relationshipName>AssociatedCase</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Attente_client_final__c.field-meta.xml
<CustomField>
    <fullName>Attente_client_final__c</fullName>
    <formula>&apos;&apos; 
&amp;
IF(
    AND(TEXT(Asset.Etat_paiement__c) = &quot;unpaid&quot;, Pouss_par_Salesforce__c = false),
    IMAGE(&quot;/resource/AttentePaiement&quot;, &quot;Paiement&quot; , 32, 32) &amp; &apos; &apos;, 
    &apos;&apos;
) 
&amp;
IF(
    TEXT(Attente_Prime__c) = &quot;Oui&quot;,
    IMAGE(&quot;/resource/Franchise&quot;, &quot;Prime&quot;, 32, 32) &amp; &apos; &apos;, 
    &apos;&apos;
)
&amp;
IF(
    AND(TEXT(Attente_documents__c) != &quot;Valid&quot;,TEXT(Attente_documents__c) != &quot;Received&quot;),
    IMAGE(&quot;/resource/AttenteDocument&quot;, &quot;Document&quot;, 32, 32) &amp; &apos; &apos;,
    &apos;&apos;
) 
&amp;
IF(
    TEXT(Autre_attente__c) = &quot;Oui&quot;,
    IMAGE(&quot;/resource/AutreAttente&quot;, &quot;Autre&quot;, 32, 32),
    &apos;&apos;
)
&amp;
IF(
     Attente_colis__c  = True,
    IMAGE(&quot;/resource/Livraison&quot;, &quot;Livraison&quot;, 32, 32),
    &apos;&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attente client</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Attente_documents__c.field-meta.xml
<CustomField>
    <fullName>Attente_documents__c</fullName>
    <label>Attente documents</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
                <label>Reçu(s)</label>
            </value>
            <value>
                <fullName>Valid</fullName>
                <label>Valide(s)</label>
            </value>
            <value>
                <fullName>Expected</fullName>
                <default>true</default>
                <label>Attendu(s)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Date_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Date_sinistre__c</fullName>
    <description>JJ/MM/AAAA</description>
    <label>Date du sinistre</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Equipement_client__c.field-meta.xml
<CustomField>
    <fullName>Equipement_client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement client</label>
    <referenceTo>vlocity_ins__AssetInsuredItem__c</referenceTo>
    <relationshipLabel>Demandes associées</relationshipLabel>
    <relationshipName>Demandes_associees</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Montant_geste_co__c.field-meta.xml
<CustomField>
    <fullName>Montant_geste_co__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Montant du geste commercial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Montant_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Montant_sinistre__c</fullName>
    <label>Coût global</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>CASE(
    Record_Type_Name__c, 
    &apos;Sinistre&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;INS&quot; + &apos;&apos; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
        &quot;TMP&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;SinistreBApp&apos;, Num_sinistre_B_Appli__c,
    &apos;Sinistre clôturé&apos;, Subject, 
    &apos;Déclaration&apos;, CaseNumber, 
    &apos;SAV&apos;, 
    if(
        !vlocity_ins__Verified__c, 
        &quot;SAV&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;), 
        &quot;DEM&quot; + &apos;&apos; + RIGHT(CaseNumber, 6)
    ),
    &apos;Réclamation&apos;, &quot;REC&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
				&apos;Demande&apos;, &quot;DEM&quot; + LPAD(TEXT(tech_numsin__c), 6, &apos;0&apos;),
    &apos;GED&apos; + &apos;&apos; + RIGHT(CaseNumber, 6)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro de la requête</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/TECH_ApprovalProcessStatus__c.field-meta.xml
<CustomField>
    <fullName>TECH_ApprovalProcessStatus__c</fullName>
    <description>Field use to know if there are an approval process in progress, use it in approval process</description>
    <label>TECH_ApprovalProcessStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalProcess_Status</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/tech_numsin__c.field-meta.xml
<CustomField>
    <fullName>tech_numsin__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Champ technique servant à la numérotation des dossiers qui doit garantir sinistre doit garantir :
- l&apos;unicité (aucun doublon)
- la chronologie des numéros (format du numéro de sinistre: SINXXXXXX, &quot;SIN&quot; préfixe invariable et &quot;XXXXXX&quot; séquence incrémentale et choronologique sur 6 chiffres
- la séquentialité (pas de numéro manquant)</description>
    <label>tech_numsin</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Typologie_Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Typologie_Sinistre__c</fullName>
    <label>Typologie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Case_Typologie</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/vlocity_ins__Verified__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verified</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Demande.recordType-meta.xml
<RecordType>
    <fullName>Demande</fullName>
    <active>true</active>
    <businessProcess>Demande</businessProcess>
    <description>Demande relative à de nouveaux documents client</description>
    <label>Demande</label>
</RecordType>

hubSide/force-app/main/default/objects/Case/recordTypes/Reclamation.recordType-meta.xml
<RecordType>
    <fullName>Reclamation</fullName>
    <active>true</active>
    <businessProcess>Reclamation</businessProcess>
    <description>Record Type pour les dossiers de réclamation</description>
    <label>Réclamation</label>
</RecordType>

hubSide/force-app/main/default/objects/Case/recordTypes/SAV.recordType-meta.xml
<RecordType>
    <fullName>SAV</fullName>
    <active>true</active>
    <businessProcess>SAV</businessProcess>
    <description>Case créé après un sinistre, dans le cas où l&apos;équipement sinistré n&apos;ait pas été correctement réparé/remplacé.</description>
    <label>SAV</label>
</RecordType>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Equipement_client__c.field-meta.xml
<CustomField>
    <fullName>Equipement_client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipement client</label>
    <referenceTo>vlocity_ins__AssetInsuredItem__c</referenceTo>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Numero_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Numero_sinistre__c</fullName>
    <formula>Sinistre__r.Numero_sinistre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro du sinistre</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/Piece_justificative_Sinistre__c.object-meta.xml
<CustomObject>
    <label>Pièce justificative Sinistre</label>
    <nameField>
        <label>Pièce justificative Sinistre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pièces justificatives Sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Technique Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document__c.Related_sinistre__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/LongTitle__c.field-meta.xml
<CustomField>
    <fullName>LongTitle__c</fullName>
    <description>Intitulé complet de la pièce justificative à destination des communications clients</description>
    <label>Intitulé</label>
    <length>400</length>
    <type>LongTextArea</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/NoTradable__c.field-meta.xml
<CustomField>
    <fullName>NoTradable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non négociable</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Types_piece_justificative__c.field-meta.xml
<CustomField>
    <fullName>Types_piece_justificative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Types pièce justificative</label>
    <referenceTo>Types_piece_justificative__c</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/Types_piece_justificative__c.object-meta.xml
<CustomObject>
    <label>Types pièce justificative</label>
    <nameField>
        <label>Types pièce justificative name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types pièce justificative</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/fields/LongTitle__c.field-meta.xml
<CustomField>
    <fullName>LongTitle__c</fullName>
    <description>Intitulé complet de la pièce justificative à destination des communications clients</description>
    <label>Intitulé</label>
    <length>500</length>
    <type>Html</type>
</CustomField>

hubSide/force-app/main/default/objects/Types_piece_justificative__c/fields/NoTradable__c.field-meta.xml
<CustomField>
    <fullName>NoTradable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non négociable</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/globalValueSets/ApprovalProcess_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Approval</fullName>
        <default>true</default>
        <label>Not Approval</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <description>used this field to managed approval process status on record</description>
    <masterLabel>ApprovalProcess_Status</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/globalValueSets/Case_Typologie.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Broken</fullName>
        <label>Casse</label>
    </customValue>
    <customValue>
        <fullName>Pickpocketed</fullName>
        <label>Vol toute cause</label>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
        <label>Perte</label>
    </customValue>
    <customValue>
        <fullName>Oxidised</fullName>
        <label>Oxydation</label>
    </customValue>
    <customValue>
        <fullName>Robbed</fullName>
        <label>Vol Caractérisé</label>
    </customValue>
    <customValue>
        <fullName>ReturnedByCarrier</fullName>
        <label>Retour transporteur</label>
    </customValue>
    <customValue>
        <fullName>LostByCarrier</fullName>
        <label>Perte transporteur</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterRepair</fullName>
        <label>Dysfonctionnement suite à réparation</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterExchange</fullName>
        <label>Dysfonctionnement suite à échange</label>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <label>Autres</label>
    </customValue>
    <customValue>
        <fullName>ClaimCreation</fullName>
        <label>Création Réclamation</label>
    </customValue>
    <customValue>
        <fullName>ClaimFollowUp</fullName>
        <label>Suivi Réclamation</label>
    </customValue>
    <customValue>
        <fullName>AccidentCreation</fullName>
        <label>Création Sinistre</label>
    </customValue>
    <description>Liste de toutes les typologies possibles (Sinistre, SAV, Demande)</description>
    <masterLabel>Case_Typologie</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/CaseTriggerHandler.cls
/***
* @author Ariane Tanguy (GFI)
* @date 28/07/2020
* @description Handler class for Case
* DATE          DEV         DESCRIPTION
* 10/12/2020    PMB         add updateAlertOnUpdate
* 24/02/2021    KRE         add setReclamationNumber
*/

public class CaseTriggerHandler {
    
    /***
    * @description Update the Case technumber on create
    * @param newCaseList - list of all new cases
    * @param maxNumberMap - max number of all the already created cases per record type
    * @return NA
    */
    public static void setTechNumber(List<Case> newCaseList, Map<String, Decimal> maxNumberMap) {
        
        // For all the newly created cases
        for (Case c : newCaseList) {
            
            c.tech_numsin__c = 1;
            
            if(!c.vlocity_ins__Verified__c){
                
                if (maxNumberMap.keySet().contains(c.Record_type_Name__c)) {
                    
                    if(c.Record_type_Name__c == 'Sinistre' && maxNumberMap.keyset().contains('Sinistre clôturé')){
                        List<Decimal> whichIsMax = new List<Decimal>{maxNumberMap.get(c.Record_type_Name__c) + 1, 
                            maxNumberMap.get('Sinistre clôturé') + 1};
                                whichIsMax.sort();
                        c.tech_numsin__c = whichIsMax[1];
                    } else {
                        c.tech_numsin__c = maxNumberMap.get(c.Record_type_Name__c) + 1;
                    }
                    
                    maxNumberMap.put(c.Record_type_Name__c, c.tech_numsin__c);
                } else {
                    maxNumberMap.put(c.Record_type_Name__c, c.tech_numsin__c);
                }
            }
        }
    }
    
    /***
    * @description Update the Case record type
    * @param newCaseList - list of all new cases
    * @param maxNumber - max number of all the already created cases
    * @return NA
    */
    public static void setTechNumber(List<Case> newCaseList, Map<id, Case> oldCaseMap, Map<String, Decimal> maxNumberMap) {
        
        // For the newly created cases
        for (Case c : newCaseList) {
            
            // If the record type has just been changed
            if ((c.Record_type_Name__c != oldCaseMap.get(c.Id).Record_type_Name__c &&
                 c.tech_numsin__c == oldCaseMap.get(c.Id).tech_numsin__c) ||
                (c.vlocity_ins__Verified__c != oldCaseMap.get(c.Id).vlocity_ins__Verified__c)) {
                    
                    if(c.Record_type_Name__c == 'Sinistre clôturé'){
                        continue;
                    }
                    
                    if (maxNumberMap.keySet().contains(c.Record_type_Name__c)) {
                        
                        if(c.Record_type_Name__c == 'Sinistre' && maxNumberMap.keyset().contains('Sinistre clôturé')){
                            List<Decimal> whichIsMax = new List<Decimal>{maxNumberMap.get(c.Record_type_Name__c) + 1, 
                                maxNumberMap.get('Sinistre clôturé') + 1};
                                    whichIsMax.sort();
                            c.tech_numsin__c = whichIsMax[1];
                        } else {
                            c.tech_numsin__c = maxNumberMap.get(c.Record_type_Name__c) + 1;
                        }
                        
                        maxNumberMap.put(c.Record_type_Name__c, maxNumberMap.get(c.Record_type_Name__c) + 1);
                    }
                }
        }
    }
    
    /***
    * @description Update the Case technumber on create
    * @param newCaseList - list of all new cases
    * @param maxNumberMap - max number of all the already created cases per record type
    * @return NA
    */
    public static void updateAccountOnAssetUpdate(List<Case> newCaseList, Map<id, Asset> relatedAssetMap) {
        
        // For all the newly created cases
        for (Case c : newCaseList) {
            if (relatedAssetMap.keySet().contains(c.AssetId)) {
                c.AccountId = relatedAssetMap.get(c.AssetId).AccountId;
            }
        }
    }
    
    /***
    * @description Update the Case technumber on create
    * @param newCaseList - list of all new cases
    * @param maxNumberMap - max number of all the already created cases per record type
    * @return NA
    */
    public static void updateAccountOnAssetUpdate(List<Case> newCaseList, Map<id, Case> oldCaseMap, Map<id, Asset> relatedAssetMap) {
        
        // For all the newly created cases
        for (Case c : newCaseList) {
            if (c.AssetId != oldCaseMap.get(c.id).AssetId &&
                relatedAssetMap.keySet().contains(c.AssetId)) {
                    c.AccountId = relatedAssetMap.get(c.AssetId).AccountId;
                }
        }
    }
    
    /***
    * @description Update the related sinistre on reclamation update
    * @param newCaseList - list of new cases
    * @param oldCaseMap - map of old cases
    * @return NA
    */
    public static void updateSinistreOnReclaUpdate(List<Case> newCaseList, Map<id, Case> oldCaseMap){
        
        id caseSinistreId = UtilityClassHelper.getCreatedRecordType('Sinistre');
        
        // For all the newly created cases
        List<Case> sinistreToUpdate = new List<Case>();
        for (Case c : newCaseList){
            if (c.AnswerNature__c != oldCaseMap.get(c.id).AnswerNature__c &&
                c.AnswerNature__c == 'Favorable' &&
                c.Record_Type_Name__c == 'Réclamation'){
                    
                    if(caseSinistreId == NULL){
                        caseSinistreId = UtilityClassHelper.getCreatedRecordType('Sinistre');
                    }
                    
                    Case s = new Case(id = c.AssociatedSinister__c, 
                                      Status = 'En cours d\'examen', 
                                     RecordTypeId = caseSinistreId);
                    sinistreToUpdate.add(s);
                }
        }
        update sinistreToUpdate;
    }
    
    /***
    * @description Update the related equipement sinistre on case (sinistre + sav) validation
    * @param newCaseList - list of new cases
    * @param oldCaseMap - map of old cases
    * @param relatedEquipSinMap - related equip sin map
    * @return NA
    */
    public static void updateEquipSinOnCaseValidation(List<Case> newCaseList, Map<id, Case> oldCaseMap, Map<id, List<Equipement_sinistre__c>> relatedEquipSinMap){
        
        // For all the newly updated cases
        List<Equipement_sinistre__c> equipSinToUpdate = new List<Equipement_sinistre__c>();
        for (Case c : newCaseList){
            if (c.vlocity_ins__Verified__c != oldCaseMap.get(c.id).vlocity_ins__Verified__c &&
                (c.Record_Type_Name__c == 'Sinistre' ||
                 c.Record_Type_Name__c == 'SAV') &&
                relatedEquipSinMap.keySet().contains(c.id)){
                    for(Equipement_sinistre__c e : relatedEquipSinMap.get(c.id)){
                        e.Name = c.Numero_sinistre__c + '-' + e.Equipement_client__r.Name;
                        equipSinToUpdate.add(e);
                    }
                }
        }
        if(equipSinToUpdate.size() > 0){
            update equipSinToUpdate;
        }
    }
    
    /***
    * @description Checks the user's profile before delete
    * @param caseList - list of case to be deleted
    * @return NA
    */
    public static void isDeleteAuthorized(List<Case> caseList){
        
        // Get the current user's profile
        String currentUserProfile = [SELECT Name 
                                     FROM Profile 
                                     WHERE id =: System.UserInfo.getProfileId()].Name;
        
        if(currentUserProfile != 'System Administrator'){
            throw new DeleteNotAuthorizedException('Vous n\'avez pas les droits suffisants pour supprimer cette requête' + '\n' + 
                                                   'You don\'t have the permission to delete the current record.');
        }
    }
    
    public class DeleteNotAuthorizedException extends Exception {}
    
    /***
    * @description Update the Case on update
    * @param newCaseList - list of all new cases
    * @param oldCaseMap - map of all old cases
    * @return NA
    */
    public static void updateSinistreOnUpdate(List<Case> newCaseList, Map<id, Case> oldCaseMap, Map<id, List<Document__c>> caseIdDocumentMap, Id idDispatchSin) {
        
        // For the newly created cases
        for (Case c : newCaseList) {
            
            // If the case is a sinistre one
            if ((c.Record_Type_Name__c == 'Sinistre' &&
                 c.Attente_documents__c == 'Valid' &&
                 (c.Attente_client_final__c != oldCaseMap.get(c.id).Attente_client_final__c ||
                  c.RecordTypeId != oldCaseMap.get(c.id).RecordTypeId ||
                  c.OwnerId != oldCaseMap.get(c.Id).OwnerId)) &&
                ((c.Attente_client_final__c == '' ||
                 c.Attente_client_final__c == null) && c.OwnerId != idDispatchSin)) {
                     c.Status = 'En cours d\'examen';
                 }
            
            if (c.Record_Type_Name__c == 'Sinistre' &&
                caseIdDocumentMap.keySet().contains(c.Id) &&
                c.Status == 'Reception_dossier') {
                    c.Status = 'A attribuer';
                }
        }
    }
    
    /***
    * @description Update the Case
    * @param newCaseList - list of all new cases
    * @param Map<String, List<Types_piece_justificative__c>> - map
    * @return NA
    */
    public static void createNecessaryDocs(List<Case> newCaseList, Map<String, List<Types_piece_justificative__c>> typologyPieceJustificativeMap) {
        
        List<Piece_justificative_Sinistre__c> PJToCreateList = new List<Piece_justificative_Sinistre__c>();
        List<Case> caseToUpdate = new List<Case>();
        
        // Loop over the new cases
        for (Case c : newCaseList) {
            
            if (typologyPieceJustificativeMap.keySet().contains(c.Typologie_Sinistre__c)) {
                
                for (Types_piece_justificative__c t : typologyPieceJustificativeMap.get(c.Typologie_Sinistre__c)) {
                    
                    Piece_justificative_Sinistre__c p = new Piece_justificative_Sinistre__c();
                    p.Case__c = c.id;
                    p.Name = t.Name;
                    p.LongTitle__c = t.LongTitle__c;
                    p.NoTradable__c = t.NoTradable__c;
                    PJToCreateList.add(p);
                }
            }
        }
        
        insert PJToCreateList;
    }
    
    /***
    * @description Update the Case on update
    * @param newCaseList - list of all new cases
    * @param oldCaseMap - map of all old cases
    * @return NA
    */
    public static void updateAlertOnUpdate(List<Case> newCaseList, Map<id, Case> oldCaseMap) {
        
        List<String> idSinistreAlertToUpdateApprouved = new List<String>();
        List<String> idSinistreAlertToUpdateRejected = new List<String>();
        
        // For the newly created cases
        for (Case c : newCaseList) {
            
            // If the case is a sinistre one
            if (c.Record_Type_Name__c == 'Sinistre' &&
                oldCaseMap.get(c.id).TECH_ApprovalProcessStatus__c != null &&
                c.TECH_ApprovalProcessStatus__c !=
                oldCaseMap.get(c.id).TECH_ApprovalProcessStatus__c) {
                    
                    if (c.TECH_ApprovalProcessStatus__c == 'Approved') {
                        idSinistreAlertToUpdateApprouved.add(c.Id);
                    } else if (c.TECH_ApprovalProcessStatus__c == 'Rejected') {
                        idSinistreAlertToUpdateRejected.add(c.Id);
                    }
                }
        }
        
        if (idSinistreAlertToUpdateApprouved.size() > 0) {
            //send true in parameters if we should update alert to approuved
            UtilityClassHelper.updateAlert(idSinistreAlertToUpdateApprouved, true);
        }
        if (idSinistreAlertToUpdateRejected.size() > 0) {
            //send true in parameters if we should update alert to rejected
            UtilityClassHelper.updateAlert(idSinistreAlertToUpdateRejected, false);
        }
    }
    
    /***
    * @description Update the Case on update
    * @param newCaseList - list of all new cases
    * @param oldCaseMap - map of all old cases
    * @return NA
    */
    public static void updateAssetKPI(List<Case> newCaseList, Map<id, Case> oldCaseMap) {
        
        system.debug('-- newCaseList ' + newCaseList);
        system.debug('-- oldCaseMap ' + oldCaseMap);
        
        List<Id> lstContractToUpdate = new List<Id>();
        List<Id> lstCaseCurrentClosed = new List<Id>();
        
        for (Case c : newCaseList) {
            if (c.AssetId != null && 
                c.Record_Type_Name__c.contains('Sinistre')) {
                    lstContractToUpdate.add(c.AssetId);
                }
            if(c.AssetId != null &&
                c.Record_Type_Name__c.contains('Sinistre') &&
                oldCaseMap != null && oldCaseMap.get(c.Id).Status != c.Status &&
                (c.Status == 'closed_repaired' || c.Status == 'closed_exchange')){
                    lstCaseCurrentClosed.add(c.Id);
            }
        }
        
        if (lstContractToUpdate.size() > 0 &&
            !System.isBatch() &&
            !System.isFuture()) {
                system.debug('-- go calculatorProcess');
                calculatorProcess(lstContractToUpdate,lstCaseCurrentClosed);
            }
    }
    
    /***
    * @description future method to optimized process
    * @param newCaseList - list of asset ids
    * @return NA
    */
    @future
    public static void calculatorProcess(List<Id> assetId,List<Id> lstCaseCurrentClosed) {
        
        system.debug('-- assetId ' + assetId);
        
        List<Case> listCase = [SELECT Id, AssetId, IsDeleted, Montant_sinistre__c,
                               Date_sinistre__c, Status, Montant_geste_co__c,
                               Asset.Formule__r.Formule_options__r.NbMounthKPIContract__c, 
                               Asset.TECH_CalculatorIndicLastChange__c,
                               Asset.TECH_CalculatorIndicNextChange__c,
                               Asset.Date_debut_contrat__c,
                               Asset.TECH_LastBirthDayContract__c,
                               Asset.Plafond__c,
                               LastModifiedDate
                               FROM Case
                               WHERE AssetId IN :assetId
                               AND Record_Type_Name__c LIKE 'Sinistre%'
                               ORDER BY LastModifiedDate DESC
                               ALL ROWS];
                               
        UtilityClassHelper.assetKPICalculator(listCase,lstCaseCurrentClosed);
    }

        /***
    * @description future method to optimized process
    * @param newCaseList - list of asset ids
    * @return NA
    */
    public static void nofuturCalculatorProcess(List<Id> assetId,List<Id> lstCaseCurrentClosed) {
        
        system.debug('-- assetId ' + assetId);
        
        List<Case> listCase = [SELECT Id, AssetId, IsDeleted, Montant_sinistre__c,
                               Date_sinistre__c, Status, Montant_geste_co__c,
                               Asset.Formule__r.Formule_options__r.NbMounthKPIContract__c, 
                               Asset.TECH_CalculatorIndicLastChange__c,
                               Asset.TECH_CalculatorIndicNextChange__c,
                               Asset.Date_debut_contrat__c,
                               Asset.TECH_LastBirthDayContract__c,
                               Asset.Plafond__c,
                               LastModifiedDate
                               FROM Case
                               WHERE AssetId IN :assetId
                               AND Record_Type_Name__c LIKE 'Sinistre%'
                               ORDER BY LastModifiedDate DESC
                               ALL ROWS];
                               
        UtilityClassHelper.assetKPICalculator(listCase,lstCaseCurrentClosed);
    }

    /***
    * @description Force value to not approval to manage issue 
    * @param newCaseList - list of case update
    * @param oldCaseMap - Map of old case update
    * @return NA
    */
    public static void forceValueApprovalProcess(List<Case> newCaseList, Map<id, Case> oldCaseMap){
        
        for(Case c : newCaseList){
            if(oldCaseMap.get(c.Id).Id != null &&
               c.Record_Type_Name__c == 'Sinistre' &&
               ((c.TECH_ApprovalProcessStatus__c == 'Approved' ||
                 c.TECH_ApprovalProcessStatus__c == 'Rejected')
                ||
                (oldCaseMap.get(c.Id).TECH_ApprovalProcessStatus__c == 'Approved' ||
                 oldCaseMap.get(c.Id).TECH_ApprovalProcessStatus__c == 'Rejected')) 
               &&
               c.TECH_ApprovalProcessStatus__c != 'Not Approval'){
                   c.TECH_ApprovalProcessStatus__c = 'Not Approval';
               }
        }
    }
    
    /***
    * @description Create contract alert on case update
    * @param newCaseList - list of all new cases
    * @param oldCaseMap - map of all old cases
    * @return NA
    */
    public static void createAlertOnUpdate(List<Case> newCaseList, Map<id, Case> oldCaseMap) {        
        // For the newly created cases
        for (Case c : newCaseList) {            
            // If the case is a sinistre one
           // system.debug('--ForcerPaiement : '+ c.Pouss_par_Salesforce__c);
            if (c.Record_Type_Name__c == 'Sinistre' 
                && (
                    (oldCaseMap.get(c.id).Date_sinistre__c != null && c.Date_sinistre__c != oldCaseMap.get(c.id).Date_sinistre__c) 
                    || (oldCaseMap.get(c.id).ClientDeclarationValidationDate__c != null && c.ClientDeclarationValidationDate__c != oldCaseMap.get(c.id).ClientDeclarationValidationDate__c)
                    || c.Pouss_par_Salesforce__c == true 
                )) {
                    Asset a = [SELECT Date_debut_contrat__c, Date_cloture__c FROM Asset WHERE Id = :c.AssetId LIMIT 1];
                    List<Alert__c> listAlertToCreate = new List<Alert__c>();
                    if (a != null) {
                        if (c.Date_sinistre__c <= a.Date_debut_contrat__c) {
                            listAlertToCreate.add(new Alert__c(BusinessRulesNumber__c = 'RGSIN11', SalesDiscountMotif__c  = 'Date du sinistre inférieure au contrat'));
                        }

                        if (c.Date_sinistre__c > a.Date_cloture__c) {
                            listAlertToCreate.add(new Alert__c(BusinessRulesNumber__c = 'RGSIN17', SalesDiscountMotif__c  = 'Date de sinistre supérieure à la date du contrat'));
                        }
                        
                        system.debug('++++++'+  (c.Date_sinistre__c).daysBetween(c.ClientDeclarationValidationDate__c));
                   
                        if (
                            (c.Date_sinistre__c).daysBetween(c.ClientDeclarationValidationDate__c) > 10
                            || (c.Date_sinistre__c).daysBetween(c.ClientDeclarationValidationDate__c) < -10
                        ) {
                            if (
                                (c.Date_sinistre__c).daysBetween(c.ClientDeclarationValidationDate__c) >= 90
                                || (c.Date_sinistre__c).daysBetween(c.ClientDeclarationValidationDate__c) <= -90
                            ) {
                                listAlertToCreate.add(new Alert__c(BusinessRulesNumber__c = 'RGSIN15', SalesDiscountMotif__c  = 'Date de survenance du sinistre de plus de 3 mois'));
                            } else {
                                listAlertToCreate.add(new Alert__c(BusinessRulesNumber__c = 'RGSIN16', SalesDiscountMotif__c  = 'Date de survenance du sinistre supérieure à 10 jours de la date de déclaration'));
                            }
                        }
                        
                        if (
                            c.Pouss_par_Salesforce__c == true 
                        ) {
                             listAlertToCreate.add(new Alert__c(BusinessRulesNumber__c = 'RGSIN19', SalesDiscountMotif__c  = 'Demande contournement Règlement Contrat'));
                        }
                    } 
                    
                    system.debug('+++++++'+listAlertToCreate);
                    
                    UtilityClassHelper.createDateAlertIfNotExist(listAlertToCreate, c.id);
                }
        }
    }
    
     /***
    * @description Update calcul indemnisation on update
    * @param newCaseList - list of all new cases
    * @param oldCaseMap - map of all old cases
    * @return NA
    */
    public static void updateCalculIndemnisationOnUpdate(List<Case> newCaseList, Map<id, Case> oldCaseMap) {
        
        List<String> CaseCalculIndemToUpdateApprouved = new List<String>();
        List<String> CaseCalculIndemToUpdateRejected = new List<String>();
        
        // For the newly updated cases
        for (Case c : newCaseList) {
            
            // If the case is a sinistre one
            if (c.Record_Type_Name__c == 'Sinistre' &&
                oldCaseMap.get(c.id).TECH_ApprovalProcessStatus__c != null &&
                c.TECH_ApprovalProcessStatus__c !=
                oldCaseMap.get(c.id).TECH_ApprovalProcessStatus__c) {
                    
                    if (c.TECH_ApprovalProcessStatus__c == 'Approved') {
                        CaseCalculIndemToUpdateApprouved.add(c.Id);
                    } else if (c.TECH_ApprovalProcessStatus__c == 'Rejected') {
                        CaseCalculIndemToUpdateRejected.add(c.Id);
                    }
                }
        }
        
        if (CaseCalculIndemToUpdateApprouved.size() > 0) {
            //send true in parameters if we should update calcul indemn to approuved
            UtilityClassHelper.updateCalculIndemnisationInProgress(CaseCalculIndemToUpdateApprouved, true);
        }
        if (CaseCalculIndemToUpdateRejected.size() > 0) {
            //send true in parameters if we should update calcul indemnisation to rejected
            UtilityClassHelper.updateCalculIndemnisationInProgress(CaseCalculIndemToUpdateRejected, false);
        }
    }
}