hubSide/force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Document__c/fields/Related_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Related_sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Document__c/fields/Valideur__c.field-meta.xml
<CustomField>
    <fullName>Valideur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Id du valideur</description>
    <label>Valideur</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/Piece_justificative_Sinistre__c.object-meta.xml
<CustomObject>
    <label>Pièce justificative Sinistre</label>
    <nameField>
        <label>Pièce justificative Sinistre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pièces justificatives Sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Technique Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Commentaire__c.field-meta.xml
<CustomField>
    <fullName>Commentaire__c</fullName>
    <description>Commentaire sur le statut de la pièce justificative fournie.</description>
    <label>Commentaire</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document__c.Related_sinistre__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>Pièces justificatives Sinistre</relationshipLabel>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/ValidationDate__c.field-meta.xml
<CustomField>
    <fullName>ValidationDate__c</fullName>
    <description>Date à laquelle la pièce justificative a été considérée valide - Field saving the date when the Piece justificative was marked as valid</description>
    <label>Date de validation</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Valideur__c.field-meta.xml
<CustomField>
    <fullName>Valideur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Personne ayant validé le document</description>
    <label>Valideur</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pieces_justificatives_Sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Piece_justificative_Sinistre__c/fields/Validite_document__c.field-meta.xml
<CustomField>
    <fullName>Validite_document__c</fullName>
    <label>Validité du document</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expected</fullName>
                <default>true</default>
                <label>1-Attendue</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <label>2-Reçu</label>
            </value>
            <value>
                <fullName>Valid</fullName>
                <label>3-Valide</label>
            </value>
            <value>
                <fullName>NotNeeded</fullName>
                <label>4-Plus réclamé</label>
            </value>
            <value>
                <fullName>Invalid</fullName>
                <label>5-Non valide</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/classes/LWC_PJManageStatus.cls
/***
* @author Pierre-Mickael BARRAL (INETUM)
* @date 10/11/2020
* @description GED CLWC Controller
* DATE          DEV         DESCRIPTION
* 12/07/2021    PMB         Inital version
*/
public with sharing class LWC_PJManageStatus {
    @AuraEnabled(cacheable=true)
    public static List<WrapperManageStatus> getPJ(Id fileId){
        //Use Wrapper class to manage element to send to lwc component
        List<WrapperManageStatus> listWrapper = new List<WrapperManageStatus>();
        //Get Id sinistre
        Document__c doc = [SELECT Related_sinistre__c FROM Document__c WHERE Id=:fileId];

        //Get all Piece
        if(doc != null && doc.Related_sinistre__c != null){
            List<Piece_justificative_Sinistre__c> listPJ = [SELECT Id,Name,Commentaire__c,Document__r.Name,Validite_document__c FROM Piece_justificative_Sinistre__c WHERE Case__c =:doc.Related_sinistre__c];
       
            listWrapper = LWC_PJManageStatus.populateWrapper(listPJ);
        }
       
        return listWrapper;
    }

    public static List<WrapperManageStatus> populateWrapper(List<Piece_justificative_Sinistre__c> listPJ){
        List<WrapperManageStatus> listWrapper = new List<WrapperManageStatus>();

        for(Piece_justificative_Sinistre__c pj : listPJ){
            WrapperManageStatus wrm = new WrapperManageStatus();
            wrm.Id = pj.Id;
            wrm.namePJ = pj.Name;
            wrm.documentLink = pj.Document__r.Name;
            wrm.status = pj.Validite_document__c;
            wrm.commentaire = pj.Commentaire__c == null ? '' : pj.Commentaire__c;
            wrm.documentLinkId = pj.Document__c == null ? '' : pj.Document__c; 
            listWrapper.add(wrm);
        }
        return listWrapper;
    }

    @AuraEnabled
    public static String updatePJ(List<WrapperManageStatus> listPJUpdated, String IdDocument){
        String result = '';

        List<Piece_justificative_Sinistre__c> listPjToUpdated = new List<Piece_justificative_Sinistre__c>();

        for(WrapperManageStatus pjUpdated : listPJUpdated){
            Piece_justificative_Sinistre__c pj = new Piece_justificative_Sinistre__c();
            pj.Id = pjUpdated.Id;
            pj.Validite_document__c = pjUpdated.status;
            pj.Commentaire__c = pjUpdated.commentaire;
            pj.Document__c = null;
            pj.ValidationDate__c = null;
            pj.Valideur__c= null;
            if(pjUpdated.status == 'Valid' || pjUpdated.status == 'Received'){
                pj.Document__c = String.isEmpty(pjUpdated.documentLinkId) ? null : pjUpdated.documentLinkId;
                if(pjUpdated.status == 'Valid'){
                    pj.ValidationDate__c = System.today();
                    pj.Valideur__c= UserInfo.getUserId();
                }
            }
            listPjToUpdated.add(pj);
        }
        try{
            update listPjToUpdated;
            result = 'OK';
        }
        catch(Exception ex){
            result = 'error :' + ex.getMessage();
        }
        return result;
    }

    public class WrapperManageStatus {
        @AuraEnabled
        public String Id {get;set;}
        @AuraEnabled
        public String namePJ {get;set;}
        @AuraEnabled
        public String documentLink {get;set;}
        @AuraEnabled
        public String status {get;set;}
        @AuraEnabled
        public String commentaire {get;set;}
        @AuraEnabled
        public String documentLinkId {get;set;}
    }
}