hubSide/force-app/main/default/objects/EquipmentCostType__c/EquipmentCostType__c.object-meta.xml
<CustomObject>
    <description>This object contains all the different equipment cost type. This object is maintained by an administrator.</description>
    <label>Type de Coût Equipement</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Type de Coût Equipement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Types de Coût Equipement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/EquipmentCostType__c/fields/ChangeableCost__c.field-meta.xml
<CustomField>
    <fullName>ChangeableCost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Coût Modifiable</label>
    <type>Checkbox</type>
</CustomField>

hubSide/force-app/main/default/objects/EquipmentCostType__c/fields/ManpowerCost__c.field-meta.xml
<CustomField>
    <fullName>ManpowerCost__c</fullName>
    <label>Coût Main d&apos;œuvre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/EquipmentCostType__c/fields/UnitCost__c.field-meta.xml
<CustomField>
    <fullName>UnitCost__c</fullName>
    <label>Coût Unitaire</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/EquipmentCostType__c/fields/ValueLevel__c.field-meta.xml
<CustomField>
    <fullName>ValueLevel__c</fullName>
    <label>Niveau de Valeur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ValueLevel</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/EquipmentCostType__c/recordTypes/Exchange.recordType-meta.xml
<RecordType>
    <fullName>Exchange</fullName>
    <active>true</active>
    <label>Echange</label>
</RecordType>

hubSide/force-app/main/default/globalValueSets/ValueLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Haute Valeur</fullName>
    </customValue>
    <customValue>
        <fullName>Moyenne Valeur</fullName>
    </customValue>
    <customValue>
        <fullName>Basse Valeur</fullName>
    </customValue>
    <customValue>
        <fullName>SAV DEBIT</fullName>
    </customValue>
    <customValue>
        <fullName>IPHONE 8+ / 11 / XR</fullName>
    </customValue>
    <customValue>
        <fullName>Iphone X / XS / 11 Pro / 12 Pro</fullName>
    </customValue>
    <customValue>
        <fullName>Iphone XS Max / 11 Pro Max / 12 Pro Max</fullName>
    </customValue>
    <customValue>
        <fullName>Iphone 12</fullName>
    </customValue>
    <customValue>
        <fullName>Iphone 12 Mini</fullName>
    </customValue>
    <customValue>
        <fullName>Ipad *</fullName>
    </customValue>
    <customValue>
        <fullName>Macbook / IMAC *</fullName>
    </customValue>
    <customValue>
        <fullName>APPLE</fullName>
    </customValue>
    <customValue>
        <fullName>Autres marques</fullName>
    </customValue>
    <customValue>
        <fullName>Plasturgie *</fullName>
    </customValue>
    <customValue>
        <fullName>Carte mère *</fullName>
    </customValue>
    <customValue>
        <fullName>Set écran *</fullName>
    </customValue>
    <customValue>
        <fullName>Console *</fullName>
    </customValue>
    <customValue>
        <fullName>APN</fullName>
    </customValue>
    <customValue>
        <fullName>Autre *</fullName>
    </customValue>
    <customValue>
        <fullName>Camera</fullName>
    </customValue>
    <customValue>
        <fullName>Bras</fullName>
    </customValue>
    <customValue>
        <fullName>Flex</fullName>
    </customValue>
    <masterLabel>Niveau de Valeur</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/Flow_CustomPicklistObjectEquipCostTest.cls
/***
* @author Nicolas Brancato (GFI)
* @date 17/02/2021
* @description Controller class test for Flow_CustomPicklistObjectEquipmentCost apex class
*/

@isTest
public class Flow_CustomPicklistObjectEquipCostTest {
    
    
    public static final String PROFILE_GS = 'SFAM GS';
    public static User GSUser;
    public static Id EQUIPMENTCOSTTYPERTID_EXCHANGE;
    public static List<EquipmentCostType__c> equipCostTypeList;
    public static List<String> customListOfStrings;
    
     /***
    * @description Static method to initialize all the datas for the test methods
    */
    static{
        
        Id profileGSId = [Select Id From Profile  
                          Where name =: PROFILE_GS
                         ].Id;
        
        GSUser = TestFactory.createUser();
        GSUser.ProfileId = profileGSId;
        GSUser.Email = 'guillaume.gs@yopmail.com';
        insert GSUser;
        
        EQUIPMENTCOSTTYPERTID_EXCHANGE = [Select id from RecordType where DeveloperName =: 'Exchange'].id;
        
        equipCostTypeList = new list<EquipmentCostType__c>{new EquipmentCostType__c(RecordTypeId = EQUIPMENTCOSTTYPERTID_EXCHANGE, Object__c = 'Accessoire', ValueLevel__c = 'Basse Valeur', UnitCost__c = 10,ManpowerCost__c = 30, ChangeableCost__c = false),
            												new EquipmentCostType__c(RecordTypeId = EQUIPMENTCOSTTYPERTID_EXCHANGE, Object__c = 'Accessoire', ValueLevel__c = 'Haute Valeur', UnitCost__c = 45,ManpowerCost__c = 50, ChangeableCost__c = true),
            												new EquipmentCostType__c(RecordTypeId = EQUIPMENTCOSTTYPERTID_EXCHANGE, Object__c = 'Mode Livraison', ValueLevel__c = 'Haute Valeur', UnitCost__c = 120,ManpowerCost__c = 0, ChangeableCost__c = false)};
        insert equipCostTypeList;
    }
    
    
    /***
    * @description Test method for the createPicklist method in the Flow_CustomPicklistObjectEquipmentCost apex class.
    */
    @isTest
    public static void createPicklistTest(){
        
        
        Test.startTest();
        System.runAs(GSUser){
            customListOfStrings = Flow_CustomPicklistObjectEquipmentCost.createPicklist(EQUIPMENTCOSTTYPERTID_EXCHANGE);
        }
        Test.stopTest();
        system.assertNotEquals(null, customListOfStrings);
        system.assertEquals(new list<String>{'Accessoire','Mode Livraison'}, customListOfStrings);
    }
}