hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sous_statut__c.field-meta.xml
<CustomField>
    <fullName>Sous_statut__c</fullName>
    <label>Sous-statut</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Statut_equipement__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>EquipSin_SousStatut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Statut_equipement__c.field-meta.xml
<CustomField>
    <fullName>Statut_equipement__c</fullName>
    <label>Statut equipement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EquipSin_Statut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/recordTypes/Equipement_a_reparer.recordType-meta.xml
<RecordType>
    <fullName>Equipement_a_reparer</fullName>
    <active>true</active>
    <description>Equipement à réparer parce que cassé ou oxydé</description>
    <label>Equipement Réparation</label>
</RecordType>

hubSide/force-app/main/default/objects/SFAMConfig__c/SFAMConfig__c.object-meta.xml
<CustomObject>
    <description>Custom object defining the permission / profile / role to assign to a user when created.</description>
    <label>Config SFAM</label>
    <nameField>
        <label>Config SFAM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configs SFAM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/Equipement_sinistre_Sous_statut__c.field-meta.xml
<CustomField>
    <fullName>Equipement_sinistre_Sous_statut__c</fullName>
    <label>EquipSin - Sous-statut</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EquipSin_SousStatut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/Equipement_sinistre_Statut_equipement__c.field-meta.xml
<CustomField>
    <fullName>Equipement_sinistre_Statut_equipement__c</fullName>
    <description>Statut de l&apos;équipement sinistré - Equipement sinistré status</description>
    <label>EquipSin - Statut</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EquipSin_Statut</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserBusinessProfile__c.field-meta.xml
<CustomField>
    <fullName>UserBusinessProfile__c</fullName>
    <description>Profil métier - User&apos;s business profile</description>
    <label>Utilisateur - Profil métier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UserBusinessProfile</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/SFAMConfig__c/fields/UserProfile__c.field-meta.xml
<CustomField>
    <fullName>UserProfile__c</fullName>
    <description>Profil tel que défini dans salesforce - Profile as defined in Salesforce</description>
    <label>Utilisateur - Profil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SFAM Expertise</fullName>
            </value>
            <value>
                <fullName>SFAM Stock</fullName>
            </value>
            <value>
                <fullName>SFAM Reparation</fullName>
            </value>
            <value>
                <fullName>SFAM Logistique</fullName>
            </value>
            <value>
                <fullName>SFAM API</fullName>
            </value>
            <value>
                <fullName>SFAM GS</fullName>
            </value>
            <value>
                <fullName>SFAM Qualite</fullName>
            </value>
            <value>
                <fullName>SFAM TC</fullName>
            </value>
            <value>
                <fullName>SFAM Vendeur TC</fullName>
            </value>
            <value>
                <fullName>Profil TC</fullName>
            </value>
            <value>
                <fullName>Profil GS</fullName>
            </value>
            <value>
                <fullName>SFAM ADM</fullName>
            </value>
            <value>
                <fullName>SFAM Vendeur</fullName>
            </value>
            <value>
                <fullName>SFAM Manager</fullName>
            </value>
            <value>
                <fullName>SFAM Admin Produit</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Standard User</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/User/fields/BusinessProfile__c.field-meta.xml
<CustomField>
    <fullName>BusinessProfile__c</fullName>
    <description>Profil métier - User&apos;s business profile</description>
    <label>Profil métier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UserBusinessProfile</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/globalValueSets/EquipSin_SousStatut.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A stocker</fullName>
    </customValue>
    <customValue>
        <fullName>Stocké</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir - Retour client</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir - Retour SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir du stock</fullName>
    </customValue>
    <customValue>
        <fullName>Sortie PSM</fullName>
    </customValue>
    <customValue>
        <fullName>A sortir PSM</fullName>
    </customValue>
    <customValue>
        <fullName>A retourner PSM</fullName>
    </customValue>
    <customValue>
        <fullName>A dispatcher</fullName>
    </customValue>
    <customValue>
        <fullName>En cours d&apos;expertise</fullName>
    </customValue>
    <customValue>
        <fullName>En attente GS</fullName>
    </customValue>
    <customValue>
        <fullName>En cours</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - A expédier</fullName>
    </customValue>
    <customValue>
        <fullName>Préparation</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - A conserver</fullName>
    </customValue>
    <customValue>
        <fullName>Retourné client</fullName>
    </customValue>
    <customValue>
        <fullName>Repaired</fullName>
        <label>Réparé</label>
    </customValue>
    <customValue>
        <fullName>Unrepairable</fullName>
        <label>Irréparable</label>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <label>Annulé</label>
    </customValue>
    <customValue>
        <fullName>Via prime</fullName>
    </customValue>
    <customValue>
        <fullName>Via prime magasin</fullName>
    </customValue>
    <customValue>
        <fullName>Réception client</fullName>
    </customValue>
    <customValue>
        <fullName>Conservé SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - à expédier (Irréparable)</fullName>
    </customValue>
    <customValue>
        <fullName>Réceptionné - à expédier (Annulé)</fullName>
    </customValue>
    <customValue>
        <fullName>Préparation - Irréparable/Annulé</fullName>
    </customValue>
    <customValue>
        <fullName>Retour Client</fullName>
    </customValue>
    <customValue>
        <fullName>Retour SFAM</fullName>
    </customValue>
    <customValue>
        <fullName>Sorti PSM</fullName>
        <isActive>false</isActive>
        <label>Sorti PSM</label>
    </customValue>
    <description>Liste des sous-statuts de l&apos;équipement sinistré - Equipement sinistre sub status list</description>
    <masterLabel>EquipSin_SousStatut</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/Flow_HandleDependantPicklistTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 15/04/2021
* @description Flow_HandleDependantPicklist test class
* @Class Flow_HandleDependantPicklist
*/

@isTest
public class Flow_HandleDependantPicklistTest {
    
    @testSetup 
    public static void testSetup(){
        
        // Create a SFAMConfig
        SFAMConfig__c c = new SFAMConfig__c();
        c.Name = 'DirectionQualiteSinistre';
        c.UserBusinessProfile__c = 'DirectionQualiteSinistre';
        c.UserProfile__c = 'SFAM Stock';
        c.Equipement_sinistre_Statut_equipement__c = 'En Analyse;CustomerReception';
        c.Equipement_sinistre_Sous_statut__c = 'Retourné client;Repaired';
        insert c;
        
        // Create a user
        User u = TestFactory.createUser();
        u.LastName = 'MistaDirecta';
        u.businessProfile__c = 'DirectionQualiteSinistre';
        insert u;
    }
    
    /***
	* @description Get the current user's business profile
	* @LightningComponent Flow_HandleDependantPicklist
	*/
    @isTest
    public static void getUserBusinessProfileTest(){
        
        User u = [SELECT id, businessProfile__c 
                  FROM User
                  WHERE LastName = 'MistaDirecta'];
        
        String businessProfile;
        system.runAs(u){
            businessProfile = Flow_HandleDependantPicklist.getUserBusinessProfile();
        }
        
        // Check the result
        system.assertEquals(u.businessProfile__c, businessProfile, 
                           'The business profile doesnt match the users - This is wrong');
    }
    
    /***
	* @description Get the business profile filtered controlling picklist map
	* @LightningComponent Flow_HandleDependantPicklist
	*/
    @isTest
    public static void getBusinessProfileControllingPicklistFilteredTest(){
        
        User u = [SELECT id, businessProfile__c 
                  FROM User
                  WHERE LastName = 'MistaDirecta'];
        
        Map<String, String> ctrPkFiltered;
                
        // Play the flow
        system.runAs(u){
            ctrPkFiltered = Flow_HandleDependantPicklist.getControllingPicklistFiltered('Equipement_sinistre__c', 
                                                                                        'Statut_equipement__c', 
                                                                                        Flow_HandleDependantPicklist.getUserBusinessProfile(), 
                                                                                        NULL);
        }
        
        List<String> filteredStatusList = [SELECT Equipement_sinistre_Statut_equipement__c
                                           FROM SFAMConfig__c].Equipement_sinistre_Statut_equipement__c.split(';');
        
        for(String s : ctrPkFiltered.values()){
            system.assert(filteredStatusList.contains(s), 
                          'The value ' + s + ' is missing in the business profile controlling filtered picklist - This is wrong');
        }
    }
    
    /***
	* @description Get the RT filtered controlling picklist map
	* @LightningComponent Flow_HandleDependantPicklist
	*/
    @isTest
    public static void getRTControllingPicklistFilteredTest(){
        
        User u = [SELECT id, businessProfile__c 
                  FROM User
                  WHERE LastName = 'MistaDirecta'];
        
        // Create another SFAMConfig
        SFAMConfig__c c = new SFAMConfig__c();
        c.Name = 'Equipement_a_reparer';
        c.Equipement_sinistre_Statut_equipement__c = 'CustomerReception';
        insert c;
        
        Map<String, String> ctrPkFiltered;
                
        // Play the flow
        system.runAs(u){
            ctrPkFiltered = Flow_HandleDependantPicklist.getControllingPicklistFiltered('Equipement_sinistre__c', 
                                                                                        'Statut_equipement__c', 
                                                                                        Flow_HandleDependantPicklist.getUserBusinessProfile(), 
                                                                                        'Equipement_a_reparer');
        }
        
        List<String> filteredStatusList = [SELECT Equipement_sinistre_Statut_equipement__c
                                           FROM SFAMConfig__c
                                           WHERE Name = 'Equipement_a_reparer'].Equipement_sinistre_Statut_equipement__c.split(';');
        
        for(String s : ctrPkFiltered.values()){
            system.assert(filteredStatusList.contains(s), 
                          'The value ' + s + ' is missing in the RT controlling filtered picklist - This is wrong');
        }
        
        // Check whether the result stays the same with the business profile removed
        c = [SELECT id FROM SFAMConfig__c WHERE Name = 'DirectionQualiteSinistre'];
        delete c;
        
        // Play the flow
        system.runAs(u){
            ctrPkFiltered = Flow_HandleDependantPicklist.getControllingPicklistFiltered('Equipement_sinistre__c', 
                                                                                        'Statut_equipement__c', 
                                                                                        Flow_HandleDependantPicklist.getUserBusinessProfile(), 
                                                                                        'Equipement_a_reparer');
        }
        
        for(String s : ctrPkFiltered.values()){
            system.assert(filteredStatusList.contains(s), 
                          'The value ' + s + ' is missing in the RT controlling filtered picklist - This is wrong');
        }
    }
    
    /***
	* @description Get the dependant picklist map
	* @LightningComponent Flow_HandleDependantPicklist
	*/
    @isTest
    public static void getDependantPicklistFilteredTest(){
        
        User u = [SELECT id, businessProfile__c 
                  FROM User
                  WHERE LastName = 'MistaDirecta'];
        
        Map<String, String> dpdPkFiltered;
                
        // Play the flow
        system.runAs(u){
            dpdPkFiltered = Flow_HandleDependantPicklist.getDependantPicklistFiltered('Equipement_sinistre__c', 
                                                                                      'Statut_equipement__c', 
                                                                                      'Sous_statut__c', 
                                                                                      'CustomerReception',
                                                                                      Flow_HandleDependantPicklist.getUserBusinessProfile());
        }
        
        List<String> filteredStatusList = [SELECT Equipement_sinistre_Sous_statut__c
                                           FROM SFAMConfig__c].Equipement_sinistre_Sous_statut__c.split(';');
        
        for(String s : dpdPkFiltered.values()){
            system.assert(filteredStatusList.contains(s), 
                          'The value ' + s + ' is missing in the dependant filtered picklist - This is wrong');
        }
    }
}