hubSide/force-app/main/default/objects/Gamme__c/Gamme__c.object-meta.xml
<CustomObject>
    <description>Gamme de produit et d&apos;offre</description>
    <label>Gamme</label>
    <nameField>
        <label>Gamme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gammes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Gamme__c/fields/Valeur_Maximale_Produit__c.field-meta.xml
<CustomField>
    <fullName>Valeur_Maximale_Produit__c</fullName>
    <description>Valeur maximale du produit</description>
    <label>Valeur Maximale Produit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Gamme__c/fields/Valeur_Minimale_Produit__c.field-meta.xml
<CustomField>
    <fullName>Valeur_Minimale_Produit__c</fullName>
    <description>Valeur minimale du produit</description>
    <label>Valeur Minimale Produit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Gamme__c/recordTypes/Gamme_produit.recordType-meta.xml
<RecordType>
    <fullName>Gamme_produit</fullName>
    <active>true</active>
    <description>Gamme liée aux différentes gammes de produits</description>
    <label>Gamme produit</label>
</RecordType>

hubSide/force-app/main/default/objects/Product2/fields/Prix_indicatif__c.field-meta.xml
<CustomField>
    <fullName>Prix_indicatif__c</fullName>
    <label>Prix indicatif</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/classes/ProductTriggerHelper.cls
/***
* @author Ariane Tanguy (GFI)
* @date 05/05/2020
* @description Helper class for ProductTrigger
*/

public class ProductTriggerHelper {
    
    /***
	* @description Get all the gammes related to the newly created product
	* @param newProductList - list of products
	* @return List<Gamme__c>
	*/
    public static List<Gamme__c> getRelatedGamme(List<Product2> newProductList){
        
        // Get the max and min prices
        Decimal minPrice = 1000000;
        Decimal maxPrice = 0;
        for(Product2 p : newProductList){
            minPrice = minPrice > p.Prix_indicatif__c ? p.Prix_indicatif__c : minPrice;
            maxPrice = maxPrice < p.Prix_indicatif__c ? p.Prix_indicatif__c : maxPrice;
        }
        
        // Query the gamme produit
        List<Gamme__c> relatedGammeList = [SELECT id, Valeur_Minimale_Produit__c, Valeur_Maximale_Produit__c 
                                           FROM Gamme__c
                                           WHERE RecordType.DeveloperName = 'Gamme_produit'
                                           AND Valeur_Minimale_Produit__c <= : minPrice
                                           AND Valeur_Maximale_Produit__c >= : maxPrice];
        
        return relatedGammeList;
    }

}