hubSide/force-app/main/default/objects/Gamme__c/Gamme__c.object-meta.xml
<CustomObject>
    <description>Gamme de produit et d&apos;offre</description>
    <label>Gamme</label>
    <nameField>
        <label>Gamme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gammes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Gamme__c/fields/Valeur_Maximale_Produit__c.field-meta.xml
<CustomField>
    <fullName>Valeur_Maximale_Produit__c</fullName>
    <description>Valeur maximale du produit</description>
    <label>Valeur Maximale Produit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Gamme__c/fields/Valeur_Minimale_Produit__c.field-meta.xml
<CustomField>
    <fullName>Valeur_Minimale_Produit__c</fullName>
    <description>Valeur minimale du produit</description>
    <label>Valeur Minimale Produit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Gamme_produit__c.field-meta.xml
<CustomField>
    <fullName>Gamme_produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Gamme produit</description>
    <label>Gamme produit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Gamme__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Gamme produit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Gamme__c</referenceTo>
    <relationshipLabel>Produits location</relationshipLabel>
    <relationshipName>Products_produit</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Prix_indicatif__c.field-meta.xml
<CustomField>
    <fullName>Prix_indicatif__c</fullName>
    <label>Prix indicatif</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/recordTypes/Produit_location.recordType-meta.xml
<RecordType>
    <fullName>Produit_location</fullName>
    <active>true</active>
    <label>Produit location</label>
</RecordType>

hubSide/force-app/main/default/classes/ProductTriggerHandlerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 05/05/2020
* @description ProductTrigger test class
* @Object Product2
*/

@isTest
public class ProductTriggerHandlerTest {
    
    /***
	* @description Update the record type
	* @see updateRecordTypeOnCreation
	*/
    @isTest
    public static void updateRecordTypeOnCreationTest(){
        
        // Create a Product
        Product2 p = TestFactory.createProduct();
        insert p;
        
        // Query emprunt and check whether the record type has been correctly updated
        p = [SELECT id, RecordType.DeveloperName FROM Product2 WHERE id =: p.id];
        
        system.assertEquals('Produit_location', p.RecordType.DeveloperName, 
                            'The record type should have been updated on the product - This is wrong');
    }
    
    /***
	* @description Update the gamme
	* @see updateGamme
	*/
    @isTest
    public static void updateGammeTest(){
        
        // Create a Gamme
        Gamme__c g = TestFactory.createGammeProduit();
        g.Valeur_Minimale_Produit__c = 10;
        g.Valeur_Maximale_Produit__c = 100;
        insert g;
        
        // Create a Product
        Product2 p = TestFactory.createProduct();
        p.Prix_indicatif__c = 59;
        insert p;
        
        // Check that the gamme has been updated on the product
        p = [SELECT Gamme_produit__c FROM Product2 WHERE id =: p.id];
        system.assertEquals(g.id, p.Gamme_produit__c, 
                           'The gamme field should have been updated on the product - This is wrong');
        
    }
}