hubSide/force-app/main/default/objects/Gamme__c/Gamme__c.object-meta.xml
<CustomObject>
    <description>Gamme de produit et d&apos;offre</description>
    <label>Gamme</label>
    <nameField>
        <label>Gamme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gammes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Gamme__c/fields/Valeur_Maximale_Produit__c.field-meta.xml
<CustomField>
    <fullName>Valeur_Maximale_Produit__c</fullName>
    <description>Valeur maximale du produit</description>
    <label>Valeur Maximale Produit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Gamme__c/fields/Valeur_Minimale_Produit__c.field-meta.xml
<CustomField>
    <fullName>Valeur_Minimale_Produit__c</fullName>
    <description>Valeur minimale du produit</description>
    <label>Valeur Minimale Produit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Caution__c.field-meta.xml
<CustomField>
    <fullName>Caution__c</fullName>
    <label>Caution</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Gamme_produit__c.field-meta.xml
<CustomField>
    <fullName>Gamme_produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Gamme produit</description>
    <label>Gamme produit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Gamme__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Gamme produit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Gamme__c</referenceTo>
    <relationshipLabel>Produits location</relationshipLabel>
    <relationshipName>Products_produit</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/fields/Prix_indicatif__c.field-meta.xml
<CustomField>
    <fullName>Prix_indicatif__c</fullName>
    <label>Prix indicatif</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Product2/recordTypes/Produit_location.recordType-meta.xml
<RecordType>
    <fullName>Produit_location</fullName>
    <active>true</active>
    <label>Produit location</label>
</RecordType>

hubSide/force-app/main/default/classes/ProductTriggerHandler.cls
/***
* @author Ariane Tanguy (GFI)
* @date 05/05/2020
* @description Handler class for ProductTrigger
*/

public class ProductTriggerHandler {
    
    /***
	* @description Automatically set the gamme on the products (not the offre)
	* @param newProductList - list of product
	* @param relatedGammeMap - related gamme map
	* @return NA
	*/
    public static void updateGamme(List<Product2> newProductList, List<Gamme__c> relatedGammeMap){
    
        id productLocRTId = UtilityClassHelper.getCreatedRecordType('Produit_location');
        
        // Update the Gamme on each product
        for(Product2 p : newProductList){
            
            // If the product is location
            if(p.RecordTypeId == productLocRTId){
                
                p.Caution__c = p.Prix_indicatif__c / 2;
                
                for(Gamme__c g : relatedGammeMap){
                    if(g.Valeur_Minimale_Produit__c <= p.Prix_indicatif__c &&
                       p.Prix_indicatif__c <= g.Valeur_Maximale_Produit__c){
                           p.Gamme_produit__c = g.id;
                           break;
                       }
                }
            }
        }
    }
}