hubSide/force-app/main/default/objects/Reception_colis__c/Reception_colis__c.object-meta.xml
<CustomObject>
    <description>Table permettant d&apos;avoir une idée du nombre de colis reçu dans la journée / dans un batch donné</description>
    <label>Réception colis</label>
    <nameField>
        <label>Réception colis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Réceptions colis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Reception_colis__c/fields/Nom_transporteur__c.field-meta.xml
<CustomField>
    <fullName>Nom_transporteur__c</fullName>
    <description>Nom du transporteur ayant délivré les colis</description>
    <label>Nom transporteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nom_transporteur</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Reception_colis__c/fields/Tech_BatchNumber__c.field-meta.xml
<CustomField>
    <fullName>Tech_BatchNumber__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Numéro s&apos;incrémentant pour distinguer les différents lots reçu lors d&apos;une même journée - Incrementing integer to differentiate batches received on a same day.</description>
    <label>Tech_NumeroLot</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Nom_transporteur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ChronopostSav</fullName>
        <label>Chronopost - SAV</label>
    </customValue>
    <customValue>
        <fullName>ChronopostReparation</fullName>
        <label>Chronopost - Réparation</label>
    </customValue>
    <customValue>
        <fullName>LaPosteSav</fullName>
        <label>La Poste -  SAV</label>
    </customValue>
    <customValue>
        <fullName>LaPosteReparation</fullName>
        <label>La Poste -  Réparation</label>
    </customValue>
    <customValue>
        <fullName>BulkParcelsSav</fullName>
        <label>Colis en vrac - SAV</label>
    </customValue>
    <customValue>
        <fullName>BulkParcelsReparation</fullName>
        <label>Colis en vrac - Réparation</label>
    </customValue>
    <customValue>
        <fullName>Chronopost</fullName>
        <isActive>false</isActive>
        <label>Chronopost</label>
    </customValue>
    <customValue>
        <fullName>La Poste</fullName>
        <isActive>false</isActive>
        <label>La Poste</label>
    </customValue>
    <masterLabel>Nom transporteur</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/ReceptionColisTriggerHandler.cls
/***
* @author Ariane Tanguy (GFI)
* @date 01/06/2021
* @description Handler class for ReceptionColisTrigger
*/

public class ReceptionColisTriggerHandler {
    
    /***
	* @description Set batchNumber field
	* @param newReceptionColisList - list of new Reception_colis__c
	* @param maxBatchNumber - today's max batch  number
	*/
    public static void setBatchNumber(List<Reception_colis__c> newReceptionColisList, Map<String, Decimal> maxBatchNumberMap){
        
        // Loop over the new Reception colis
        for(Reception_colis__c r : newReceptionColisList){
            if(maxBatchNumberMap.keySet().contains(r.Nom_transporteur__c)){
                Decimal maxBatchNumber = maxBatchNumberMap.get(r.Nom_transporteur__c);
                maxBatchNumber ++;
                r.tech_batchNumber__c = maxBatchNumber;
                maxBatchNumberMap.put(r.Nom_transporteur__c, maxBatchNumber);
            }
        }
    }
}