hubSide/force-app/main/default/objects/Colis__c/Colis__c.object-meta.xml
<CustomObject>
    <label>Colis</label>
    <nameField>
        <label>Colis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Colis__c/fields/Date_reception__c.field-meta.xml
<CustomField>
    <fullName>Date_reception__c</fullName>
    <label>Date réception</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Nom_transporteur__c.field-meta.xml
<CustomField>
    <fullName>Nom_transporteur__c</fullName>
    <label>Nom transporteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nom_transporteur</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Reception_colis__c.field-meta.xml
<CustomField>
    <fullName>Reception_colis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Réception colis</label>
    <referenceTo>Reception_colis__c</referenceTo>
    <relationshipLabel>Colis</relationshipLabel>
    <relationshipName>Colis</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Colis_Status</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/recordTypes/Colis_reception.recordType-meta.xml
<RecordType>
    <fullName>Colis_reception</fullName>
    <active>true</active>
    <description>Dédié à la réception des colis</description>
    <label>Colis réception</label>
</RecordType>

hubSide/force-app/main/default/objects/Reception_colis__c/Reception_colis__c.object-meta.xml
<CustomObject>
    <description>Table permettant d&apos;avoir une idée du nombre de colis reçu dans la journée / dans un batch donné</description>
    <label>Réception colis</label>
    <nameField>
        <label>Réception colis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Réceptions colis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Reception_colis__c/fields/Date_reception__c.field-meta.xml
<CustomField>
    <fullName>Date_reception__c</fullName>
    <description>Date de réception du batch de colis</description>
    <label>Date de réception</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Reception_colis__c/fields/Nom_transporteur__c.field-meta.xml
<CustomField>
    <fullName>Nom_transporteur__c</fullName>
    <description>Nom du transporteur ayant délivré les colis</description>
    <label>Nom transporteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nom_transporteur</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Colis_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Reçu</fullName>
    </customValue>
    <customValue>
        <fullName>Transféré/Emis</fullName>
    </customValue>
    <customValue>
        <fullName>Transféré/Reçu</fullName>
    </customValue>
    <customValue>
        <fullName>Affecté</fullName>
    </customValue>
    <customValue>
        <fullName>Rattaché</fullName>
    </customValue>
    <customValue>
        <fullName>Non identifiable</fullName>
    </customValue>
    <customValue>
        <fullName>Invalid</fullName>
        <label>Invalidé</label>
    </customValue>
    <customValue>
        <fullName>Retourner colis</fullName>
    </customValue>
    <customValue>
        <fullName>Colis Retourné</fullName>
    </customValue>
    <masterLabel>Colis_Status</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/globalValueSets/Nom_transporteur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ChronopostSav</fullName>
        <label>Chronopost - SAV</label>
    </customValue>
    <customValue>
        <fullName>ChronopostReparation</fullName>
        <label>Chronopost - Réparation</label>
    </customValue>
    <customValue>
        <fullName>LaPosteSav</fullName>
        <label>La Poste -  SAV</label>
    </customValue>
    <customValue>
        <fullName>LaPosteReparation</fullName>
        <label>La Poste -  Réparation</label>
    </customValue>
    <customValue>
        <fullName>BulkParcelsSav</fullName>
        <label>Colis en vrac - SAV</label>
    </customValue>
    <customValue>
        <fullName>BulkParcelsReparation</fullName>
        <label>Colis en vrac - Réparation</label>
    </customValue>
    <customValue>
        <fullName>Chronopost</fullName>
        <isActive>false</isActive>
        <label>Chronopost</label>
    </customValue>
    <customValue>
        <fullName>La Poste</fullName>
        <isActive>false</isActive>
        <label>La Poste</label>
    </customValue>
    <masterLabel>Nom transporteur</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/Flow_CreateUpdateColisInvokable.cls
/***
* @author Ariane Tanguy (GFI)
* @date 02/11/2020
* @description Lightning Component Controller
*/

public class Flow_CreateUpdateColisInvokable {
    
    // Input details that comes to apex from flow
    public class FlowInputs{
        
        @InvocableVariable
        public String barcodeString;
        
        @InvocableVariable
        public Integer colisQuantity;
        
        @InvocableVariable
        public String receptionColisId;
        
        @InvocableVariable
        public Date receptionDate;
        
        @InvocableVariable
        public String senderName;
        
        @InvocableVariable
        public Boolean createColis;
    }
    
    // Output details which goes from apex to flow
    public class FlowOutputs{
        
        @InvocableVariable
        public Integer barcodeCount;
        
        @InvocableVariable
        public Integer barcodeProcessed;
    }
    
    /***
    * @description Create n colis + m other colis
    * @param barcodeString - List ids
    * @param colisQuantity - Number of other colis to create
    * @param receptionDate - reception date
    * @param newStats - new status
    * @return Integer - Number of colis created
    */
    @InvocableMethod(label = 'Create / Update colis' 
                     description = 'Split flow string and create / update colis accordingly.')
    
    public static List<FlowOutputs> processBarcode(List<FlowInputs> requestList) {
        
        List<FlowOutputs> resultList = new List<FlowOutputs>();
        List<Colis__c> colisToUpsert = new List<Colis__c>();
        
        for(FlowInputs f : requestList){
            
            FlowOutputs r = new FlowOutputs();
            
            // Split the barcodes
            List<String> barcodeList = new List<String>();
            if(f.barcodeString != NULL && f.barcodeString.contains('\n')){
                barcodeList = f.barcodeString.replace(' ', '').split('\n');
            }
            else if(f.barcodeString != NULL && f.barcodeString.contains('\r\n')){
                barcodeList = f.barcodeString.replace(' ', '').split('\r\n');
            }
            else if(f.barcodeString != NULL){
                barcodeList = f.barcodeString.replace(' ', '').split('\r\n');
            }
            
            // Check for duplicates
            Set<String> barcodeSet = new Set<String>();
            for(String b : barcodeList){
                barcodeSet.add(b);
            }
            
            r.barcodeProcessed = barcodeSet.size();
            r.barcodeCount = barcodeList.size();
            resultList.add(r);
            
            // Create colis
            if(f.CreateColis){
                createColis(barcodeSet, f.colisQuantity, f.receptionDate, f.senderName, f.receptionColisId);
            }
        }
        
        return resultList;
    }
    
    /***
    * @description Create n colis + m other colis
    * @param barcodeString - List ids
    * @param colisQuantity - Number of other colis to create
    * @param receptionDate - reception date
    * @return Integer - Number of colis created
    */
    private static void createColis(Set<String> barcodeSet, integer colisQuantity, date receptionDate, string senderName, string RCId){
        
        id receivedColisRT = UtilityClassHelper.getCreatedRecordType('Colis_reception');
        List<Colis__c> colisToInsert = new List<Colis__c>();
        
 		if(senderName.contains('Chronopost') || senderName.contains('LaPoste')){
            // Loop over the barcodes
            for(String barcode : barcodeSet) {
                Colis__c c = new Colis__c();
                c.Name = barcode;
                c.Date_reception__c = receptionDate;
                c.Nom_transporteur__c = senderName;
                c.Reception_colis__c = RCId;
                c.RecordTypeId = receivedColisRT;
                c.Statut__c = 'Reçu';
                colisToInsert.add(c);
            }
        }
        
        if(senderName.contains('BulkParcels')) {
            // and over the colis to create
            for(integer i = 0; i<colisQuantity; i++){
                Colis__c c = new Colis__c();
                c.Name = receptionDate + senderName + i;
                c.Date_reception__c = receptionDate;
                c.Nom_transporteur__c = senderName;
                c.Reception_colis__c = RCId;
                c.RecordTypeId = receivedColisRT;
                c.Statut__c = 'Reçu';
                colisToInsert.add(c);
            }
        }
        
        insert colisToInsert;
    }
}