hubSide/force-app/main/default/objects/Colis__c/Colis__c.object-meta.xml
<CustomObject>
    <label>Colis</label>
    <nameField>
        <label>Colis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Colis__c/fields/Date_reception__c.field-meta.xml
<CustomField>
    <fullName>Date_reception__c</fullName>
    <label>Date réception</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Nom_transporteur__c.field-meta.xml
<CustomField>
    <fullName>Nom_transporteur__c</fullName>
    <label>Nom transporteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nom_transporteur</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Reception_colis__c.field-meta.xml
<CustomField>
    <fullName>Reception_colis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Réception colis</label>
    <referenceTo>Reception_colis__c</referenceTo>
    <relationshipLabel>Colis</relationshipLabel>
    <relationshipName>Colis</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Reception_colis__c/Reception_colis__c.object-meta.xml
<CustomObject>
    <description>Table permettant d&apos;avoir une idée du nombre de colis reçu dans la journée / dans un batch donné</description>
    <label>Réception colis</label>
    <nameField>
        <label>Réception colis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Réceptions colis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Reception_colis__c/fields/Date_reception__c.field-meta.xml
<CustomField>
    <fullName>Date_reception__c</fullName>
    <description>Date de réception du batch de colis</description>
    <label>Date de réception</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Reception_colis__c/fields/Nom_transporteur__c.field-meta.xml
<CustomField>
    <fullName>Nom_transporteur__c</fullName>
    <description>Nom du transporteur ayant délivré les colis</description>
    <label>Nom transporteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nom_transporteur</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Reception_colis__c/fields/Nombre_colis_scannes__c.field-meta.xml
<CustomField>
    <fullName>Nombre_colis_scannes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Nombre de colis scannés par la SFAM</description>
    <label>Nombre de colis scannés</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/objects/User/fields/BusinessProfile__c.field-meta.xml
<CustomField>
    <fullName>BusinessProfile__c</fullName>
    <description>Profil métier - User&apos;s business profile</description>
    <label>Profil métier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UserBusinessProfile</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Nom_transporteur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ChronopostSav</fullName>
        <label>Chronopost - SAV</label>
    </customValue>
    <customValue>
        <fullName>ChronopostReparation</fullName>
        <label>Chronopost - Réparation</label>
    </customValue>
    <customValue>
        <fullName>LaPosteSav</fullName>
        <label>La Poste -  SAV</label>
    </customValue>
    <customValue>
        <fullName>LaPosteReparation</fullName>
        <label>La Poste -  Réparation</label>
    </customValue>
    <customValue>
        <fullName>BulkParcelsSav</fullName>
        <label>Colis en vrac - SAV</label>
    </customValue>
    <customValue>
        <fullName>BulkParcelsReparation</fullName>
        <label>Colis en vrac - Réparation</label>
    </customValue>
    <customValue>
        <fullName>Chronopost</fullName>
        <isActive>false</isActive>
        <label>Chronopost</label>
    </customValue>
    <customValue>
        <fullName>La Poste</fullName>
        <isActive>false</isActive>
        <label>La Poste</label>
    </customValue>
    <masterLabel>Nom transporteur</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/Sinistre_BordereauColisController.cls
/***
* @author Ariane Tanguy (GFI)
* @date 05/11/2020
* @description Sinistre_BordereauColis controller
*/

public class Sinistre_BordereauColisController {
    
    private final Reception_colis__c rc;
    private String businessProfileName;
    private final List<Colis__c> colisColumn1, colisColumn2, colisColumn3;
        
    /***
	* @description VFP Init
	*/
    public Sinistre_BordereauColisController() {

        businessProfileName = [SELECT BusinessProfile__c FROM User WHERE Id = :UserInfo.getUserId()][0].BusinessProfile__c;
        
        // Get the Reception Colis infos
        rc = [SELECT Id, Name, Date_reception__c, 
              Nombre_colis_scannes__c, 
              CreatedBy.FirstName, CreatedBy.LastName, toLabel(Nom_transporteur__c)
              FROM Reception_colis__c 
              WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
        
        // Get the colis infos
        List<Colis__c> colisList = [SELECT id, Name
                                    FROM Colis__c
                                    WHERE Reception_colis__c =: rc.Id];
        
        colisColumn1 = new List<Colis__c>();
        colisColumn2 = new List<Colis__c>();
        colisColumn3 = new List<Colis__c>();
        Integer i = 0;
        for(Colis__c c : colisList){
            switch on math.mod(i, 3) {
                when 0 {
                    colisColumn1.add(c);
                }
                when 1 {
                    colisColumn2.add(c);
                }
                when 2 {
                    colisColumn3.add(c);
                }
            }
            i = i + 1;
        }
    }
    
    // Return rc
    public Reception_colis__c getRC() {
        return rc;
    }
    
    // Return colis1
    public List<Colis__c> getColisColumn1() {
        return colisColumn1;
    }
    
    // Return colis2
    public List<Colis__c> getColisColumn2() {
        return colisColumn2;
    }
    
    // Return colis3
    public List<Colis__c> getColisColumn3() {
        return colisColumn3;
    }

    public String getBusinessProfileName(){
        return businessProfileName;
    }
}