hubSide/force-app/main/default/objects/Colis__c/Colis__c.object-meta.xml
<CustomObject>
    <label>Colis</label>
    <nameField>
        <label>Colis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Colis__c/fields/Date_reception__c.field-meta.xml
<CustomField>
    <fullName>Date_reception__c</fullName>
    <label>Date réception</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Nom_transporteur__c.field-meta.xml
<CustomField>
    <fullName>Nom_transporteur__c</fullName>
    <label>Nom transporteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nom_transporteur</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Reception_colis__c.field-meta.xml
<CustomField>
    <fullName>Reception_colis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Réception colis</label>
    <referenceTo>Reception_colis__c</referenceTo>
    <relationshipLabel>Colis</relationshipLabel>
    <relationshipName>Colis</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Reception_colis__c/Reception_colis__c.object-meta.xml
<CustomObject>
    <description>Table permettant d&apos;avoir une idée du nombre de colis reçu dans la journée / dans un batch donné</description>
    <label>Réception colis</label>
    <nameField>
        <label>Réception colis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Réceptions colis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Reception_colis__c/fields/Date_reception__c.field-meta.xml
<CustomField>
    <fullName>Date_reception__c</fullName>
    <description>Date de réception du batch de colis</description>
    <label>Date de réception</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Reception_colis__c/fields/Nom_transporteur__c.field-meta.xml
<CustomField>
    <fullName>Nom_transporteur__c</fullName>
    <description>Nom du transporteur ayant délivré les colis</description>
    <label>Nom transporteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nom_transporteur</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Reception_colis__c/fields/Nombre_colis_scannes__c.field-meta.xml
<CustomField>
    <fullName>Nombre_colis_scannes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Nombre de colis scannés par la SFAM</description>
    <label>Nombre de colis scannés</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Nom_transporteur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ChronopostSav</fullName>
        <label>Chronopost - SAV</label>
    </customValue>
    <customValue>
        <fullName>ChronopostReparation</fullName>
        <label>Chronopost - Réparation</label>
    </customValue>
    <customValue>
        <fullName>LaPosteSav</fullName>
        <label>La Poste -  SAV</label>
    </customValue>
    <customValue>
        <fullName>LaPosteReparation</fullName>
        <label>La Poste -  Réparation</label>
    </customValue>
    <customValue>
        <fullName>BulkParcelsSav</fullName>
        <label>Colis en vrac - SAV</label>
    </customValue>
    <customValue>
        <fullName>BulkParcelsReparation</fullName>
        <label>Colis en vrac - Réparation</label>
    </customValue>
    <customValue>
        <fullName>Chronopost</fullName>
        <isActive>false</isActive>
        <label>Chronopost</label>
    </customValue>
    <customValue>
        <fullName>La Poste</fullName>
        <isActive>false</isActive>
        <label>La Poste</label>
    </customValue>
    <masterLabel>Nom transporteur</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/Sinistre_EtiquetteControllerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 02/12/2020
* @description Sinistre_EtiquetteController test class
* @VFP Sinistre_Etiquette
*/

@isTest
public class Sinistre_EtiquetteControllerTest {
    
    /***
    * @description Check whether the custom controller does the job
    * @see Sinistre_Etiquette
    */
    @isTest
    public static void Sinistre_BordereauEquipSinTest(){
        
        // Create a Reception Colis
        Reception_colis__c rc = new Reception_colis__c();
        rc.Name = 'La Poste - SAV - ' +  system.today();
        rc.Date_reception__c = system.today();
        rc.Nombre_colis_scannes__c = 1;
        insert rc;
        
        // Create three colis
        List<Colis__c> colisList = new List<Colis__c>();
        for(integer i=0; i<3; i++){
            Colis__c c = new Colis__c();
            c.Reception_colis__c = rc.id;
            c.Nom_transporteur__c = 'LaPosteSav';
            c.Date_reception__c = system.today();
            colisList.add(c);
        }
        insert colisList;
                        
        // Create a VFP
        PageReference pageRef = Page.Sinistre_Etiquette;
        Test.setCurrentPage(pageRef);
        
        // Verify that page fails without parameter
        Sinistre_EtiquetteController sC;
        try {
            sC = new Sinistre_EtiquetteController();
            System.assert(false, 'The controller has been created - This is wrong');
        } catch(NullPointerException e) {
            System.assert(e.getMessage().contains('null'), 'The controller shouldnt find any reception colis - This is wrong');
        }
        
        // Add parameters to page URL
        String dateReception = String.valueOf(system.today().day()) + '/' + String.valueOf(system.today().month() + '/' + String.valueOf(system.today().year()));
        ApexPages.currentPage().getParameters().put('transporteur', 'LaPosteSav');
        ApexPages.currentPage().getParameters().put('dateReception', dateReception);
    	ApexPages.currentPage().getParameters().put('nbrColis', '0');
        
        
        sC = new Sinistre_EtiquetteController();
        
        // Check the display column
        system.assertEquals(1, sC.getColisList1().size(), 
                            sC.getColisList1() + ' The first display column should contain the created colis - This is wrong');
        system.assertEquals(1, sC.getColisList1().size(), 
                            sC.getColisList2() + ' The second display column should contain the created colis - This is wrong');
        system.assertEquals(1, sC.getColisList1().size(), 
                            sC.getColisList3() + ' The third display column should contain the created colis - This is wrong');
    }
}