hubSide/force-app/main/default/objects/Colis__c/Colis__c.object-meta.xml
<CustomObject>
    <label>Colis</label>
    <nameField>
        <label>Colis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Colis__c/fields/BarCode__c.field-meta.xml
<CustomField>
    <fullName>BarCode__c</fullName>
    <formula>IMAGE(&apos;https://barcode.tec-it.com/barcode.ashx?data=&apos; + BarCodeData__c + &apos;&amp;code=Code128&apos;, &apos;colisBarCode&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ColisBarCode</label>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Date_reception__c.field-meta.xml
<CustomField>
    <fullName>Date_reception__c</fullName>
    <label>Date réception</label>
    <type>Date</type>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Nom_transporteur__c.field-meta.xml
<CustomField>
    <fullName>Nom_transporteur__c</fullName>
    <label>Nom transporteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nom_transporteur</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Nom_transporteur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ChronopostSav</fullName>
        <label>Chronopost - SAV</label>
    </customValue>
    <customValue>
        <fullName>ChronopostReparation</fullName>
        <label>Chronopost - Réparation</label>
    </customValue>
    <customValue>
        <fullName>LaPosteSav</fullName>
        <label>La Poste -  SAV</label>
    </customValue>
    <customValue>
        <fullName>LaPosteReparation</fullName>
        <label>La Poste -  Réparation</label>
    </customValue>
    <customValue>
        <fullName>BulkParcelsSav</fullName>
        <label>Colis en vrac - SAV</label>
    </customValue>
    <customValue>
        <fullName>BulkParcelsReparation</fullName>
        <label>Colis en vrac - Réparation</label>
    </customValue>
    <customValue>
        <fullName>Chronopost</fullName>
        <isActive>false</isActive>
        <label>Chronopost</label>
    </customValue>
    <customValue>
        <fullName>La Poste</fullName>
        <isActive>false</isActive>
        <label>La Poste</label>
    </customValue>
    <masterLabel>Nom transporteur</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/Sinistre_EtiquetteController.cls
/***
* @author Ariane Tanguy (GFI)
* @date 27/11/2020
* @description Lightning Component Controller
*/

public class Sinistre_EtiquetteController {
    
    private final String dateReception;
    private final String transporteur;
    private final Integer nbrColis; 
    private final List<Colis__c> colisList1, colisList2, colisList3;
        
    /***
	* @description VFP Init
	*/
    public Sinistre_EtiquetteController() {        
        
        // Get the equipement sinistre
        transporteur = ApexPages.currentPage().getParameters().get('transporteur');
        dateReception = ApexPages.currentPage().getParameters().get('dateReception');
        nbrColis= integer.valueof(ApexPages.currentPage().getParameters().get('nbrColis'));
        
        
        Date receptionDate = date.newinstance(Integer.valueOf(dateReception.split('/')[2]), 
                                              Integer.valueOf(dateReception.split('/')[1]), 
                                              Integer.valueOf(dateReception.split('/')[0]));
        
        List<Colis__c> colisList;
        if(System.test.isRunningTest())
            colisList = [SELECT id, Name, BarCode__c, Nom_transporteur__c
                                    FROM Colis__c
                                    WHERE Nom_transporteur__c =: transporteur
                                    AND Date_reception__c =: receptionDate];

        else {
            colisList = [SELECT id, Name, BarCode__c, Nom_transporteur__c
                                    FROM Colis__c
                                    WHERE toLabel(Nom_transporteur__c) =: transporteur
                                    AND Date_reception__c =: receptionDate Order by CreatedDate DESC LIMIT :nbrColis] ;

        }

        
        colisList1 = new List<Colis__c>();
        colisList2 = new List<Colis__c>();
        colisList3 = new List<Colis__c>();
        Integer i = 0;
        for(Colis__c c : colisList){
            switch on math.mod(i, 3) {
                when 0 {
                    colisList1.add(c);
                }
                when 1 {
                    colisList2.add(c);
                }
                when 2 {
                    colisList3.add(c);
                }
            }
            i = i + 1;
        }
    }
    
    // Return colisList1
    public List<Colis__c> getColisList1() {
        return colisList1;
    }
    
    // Return colisList2
    public List<Colis__c> getColisList2() {
        return colisList2;
    }
    
    // Return colisList3
    public List<Colis__c> getColisList3() {
        return colisList3;
    }
}