hubSide/force-app/main/default/objects/AssociatedCost__c/AssociatedCost__c.object-meta.xml
<CustomObject>
    <description>This object allows to link a cost to the damaged equipment.</description>
    <label>Coût Associé</label>
    <nameField>
        <label>Objet Associé</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coûts Associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/AssociatedCost__c/fields/DamagedEquipment__c.field-meta.xml
<CustomField>
    <fullName>DamagedEquipment__c</fullName>
    <label>Equipement Sinistré</label>
    <referenceTo>Equipement_sinistre__c</referenceTo>
    <relationshipLabel>Coûts Associés</relationshipLabel>
    <relationshipName>AssociatedCosts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hubSide/force-app/main/default/objects/AssociatedCost__c/fields/ManpowerCost__c.field-meta.xml
<CustomField>
    <fullName>ManpowerCost__c</fullName>
    <label>Coût Main d&apos;Œuvre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Montant_sinistre__c.field-meta.xml
<CustomField>
    <fullName>Montant_sinistre__c</fullName>
    <label>Coût global</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/recordTypes/Sinistre.recordType-meta.xml
<RecordType>
    <fullName>Sinistre</fullName>
    <active>true</active>
    <businessProcess>Sinistre</businessProcess>
    <label>Sinistre</label>
</RecordType>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/Equipement_sinistre__c.object-meta.xml
<CustomObject>
    <label>Equipement sinistré</label>
    <nameField>
        <label>Equipement sinistré</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipement sinistre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/RealCost__c.field-meta.xml
<CustomField>
    <fullName>RealCost__c</fullName>
    <label>Coût Réel</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hubSide/force-app/main/default/objects/Equipement_sinistre__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Déclaration, Sinistre, SAV, Sinistre clôturé</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Equipement sinistré</relationshipLabel>
    <relationshipName>Equipement_sinistre</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/classes/AssociatedCostTriggerHandlerTest.cls
/***
* @author Ariane Tanguy (GFI)
* @date 08/06/2021
* @description Test class for AssociatedCostTrigger
*/
@isTest
public class AssociatedCostTriggerHandlerTest {
    
    /***
    * @description Update the equipSin name on insert
    * @see handleBeforeInsert
    */
    @isTest
    public static void updateCoutReelOnUpdateTest(){
        
        // Create a sinistre
        Case s = TestFactory.createSinistre();
        insert s;
        
        // Create an equipement sinistre
        Equipement_Sinistre__c e = new Equipement_Sinistre__c();
        e.sinistre__c = s.id;
        insert e;
        
        // Create two associated cost
        AssociatedCost__c a1 = new AssociatedCost__c(Name = 'Chassis', UnitCost__c = 10, ManpowerCost__c = 10, DamagedEquipment__c = e.id);
        AssociatedCost__c a2 = new AssociatedCost__c(Name = 'Ecran', UnitCost__c = 100, ManpowerCost__c = 20, DamagedEquipment__c = e.id);
        insert new List<AssociatedCost__c>{a1, a2};
        
        // Update one of them
        a2.UnitCost__c = 20;
        update a2;
        
        // Check whether the case and equipSin got updated
        s = [SELECT id, Montant_sinistre__c FROM Case WHERE id =: s.id];
        e = [SELECT id, RealCost__c FROM Equipement_Sinistre__c WHERE id =: e.id];
        
        Decimal expectedMontant = a1.UnitCost__c + a2.UnitCost__c + a2.ManpowerCost__c;
   
        system.assertEquals(expectedMontant, e.RealCost__c, 
                            'The equipSin realCost shouldve been updated - This is wrong');
        
        // Update again
        a2.UnitCost__c = 200;
        update a2;
        
        // Check whether the case and equipSin got updated
        s = [SELECT id, Montant_sinistre__c FROM Case WHERE id =: s.id];
        e = [SELECT id, RealCost__c FROM Equipement_Sinistre__c WHERE id =: e.id];
        
        expectedMontant = a1.UnitCost__c + a2.UnitCost__c + a2.ManpowerCost__c;
    }
    
    /***
    * @description Update the equipSin name on insert
    * @see handleBeforeInsert
    */
    @isTest
    public static void updateCoutReelOnDeleteTest(){
        
        // Create a sinistre
        Case s = TestFactory.createSinistre();
        insert s;
        
        // Create an equipement sinistre
        Equipement_Sinistre__c e = new Equipement_Sinistre__c();
        e.sinistre__c = s.id;
        insert e;
        
        // Create three associated cost
        AssociatedCost__c a1 = new AssociatedCost__c(Name = 'Chassis', UnitCost__c = 10, ManpowerCost__c = 10, DamagedEquipment__c = e.id);
        AssociatedCost__c a2 = new AssociatedCost__c(Name = 'Ecran', UnitCost__c = 100, ManpowerCost__c = 20, DamagedEquipment__c = e.id);
        AssociatedCost__c a3 = new AssociatedCost__c(Name = 'Autre', UnitCost__c = 20, ManpowerCost__c = 10, DamagedEquipment__c = e.id);
        insert new List<AssociatedCost__c>{a1, a2, a3};
        
        // Delete one of them
        delete a3;
        
        // Check whether the case and equipSin got updated
        s = [SELECT id, Montant_sinistre__c FROM Case WHERE id =: s.id];
        e = [SELECT id, RealCost__c FROM Equipement_Sinistre__c WHERE id =: e.id];
        
        Decimal expectedMontant = a1.UnitCost__c + a2.UnitCost__c + a2.ManpowerCost__c;

        system.assertEquals(expectedMontant, e.RealCost__c, 
                            'The equipSin realCost shouldve been updated - This is wrong');
        
        // Delete another one
        delete a2;
        
        // Check whether the case and equipSin got updated
        s = [SELECT id, Montant_sinistre__c FROM Case WHERE id =: s.id];
        e = [SELECT id, RealCost__c FROM Equipement_Sinistre__c WHERE id =: e.id];
        
        expectedMontant = a1.UnitCost__c + a1.ManpowerCost__c;

        system.assertEquals(expectedMontant, e.RealCost__c, 
                            'The equipSin realCost shouldve been updated - This is wrong');
        
        // Delete the last one
        delete a1;
        
        // Check whether the case and equipSin got updated
        s = [SELECT id, Montant_sinistre__c FROM Case WHERE id =: s.id];
        e = [SELECT id, RealCost__c FROM Equipement_Sinistre__c WHERE id =: e.id];
        
        expectedMontant = 0;

        system.assertEquals(expectedMontant, e.RealCost__c, 
                            'The equipSin realCost shouldve been updated - This is wrong');
    }
}