hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/CalloutErrorsManagement__c.object-meta.xml
<CustomObject>
    <description>This object allows to store all information from callout of Salesforce platform.</description>
    <label>Management of Callout Errors</label>
    <nameField>
        <label>Callout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management of Callout Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/fields/CalloutErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>CalloutErrorMessage__c</fullName>
    <description>Message to identify the error. Link to the error code</description>
    <label>Error message in the callout</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/fields/CalloutStatusCode__c.field-meta.xml
<CustomField>
    <fullName>CalloutStatusCode__c</fullName>
    <description>Status code to identify the answer.</description>
    <label>Status code in the callout</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/fields/CaseRecord__c.field-meta.xml
<CustomField>
    <fullName>CaseRecord__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the case</description>
    <label>Case Record</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Management of Callout Errors</relationshipLabel>
    <relationshipName>ManagementCalloutErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/fields/DocumentLink__c.field-meta.xml
<CustomField>
    <fullName>DocumentLink__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Link</label>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>Management of Callout Errors</relationshipLabel>
    <relationshipName>ManagementCalloutErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/fields/JSONSOAPBodySent__c.field-meta.xml
<CustomField>
    <fullName>JSONSOAPBodySent__c</fullName>
    <description>Details of the JSON or SOAP body sent</description>
    <label>JSON or SOAP body sent</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/fields/PaiementVersementLink__c.field-meta.xml
<CustomField>
    <fullName>PaiementVersementLink__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Paiement Versement linked to the callout</description>
    <label>Paiement Versement Link</label>
    <referenceTo>Paiement_Versement__c</referenceTo>
    <relationshipLabel>Management of Callout Errors</relationshipLabel>
    <relationshipName>ManagementCalloutErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Paiement_Versement__c/Paiement_Versement__c.object-meta.xml
<CustomObject>
    <label>Paiement Versement</label>
    <nameField>
        <label>Paiement Versement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paiement Versement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/classes/LogCallout.cls
/***
* @author Nicolas Brancato (GFI)
* @date 19/01/2021
* @description Log Callout class for outbound call
*/
public class LogCallout {
    
    /***
    * @description Log the answer of a callout as a success in the CalloutErrorsManagement__c object
    * @param string calloutName Concatenation of the name of the external system and the name of the external services called
    * @param id caseId Case id linked to the record that triggers the callout
    * @param id documentId Document__c id if the record that triggers the callout is a Document__c
    * @param id paiementVersementId Paiement_Versement__c id if the record that triggers the callout is a Paiement_Versement__c
    * @param string bodySent Body of the performed callout
    * @param httpResponse response Response of the performed callout
    * @return null
    */
    public static void logSuccess(string calloutName, id caseId, id documentId, id paiementVersementId, string bodySent, httpResponse response){
                
        CalloutErrorsManagement__c newCallSucLog = new CalloutErrorsManagement__c();
        newCallSucLog.Name = calloutName;
        newCallSucLog.CaseRecord__c = caseId;
        newCallSucLog.DocumentLink__c = documentId <> null ? documentId : null;
        newCallSucLog.PaiementVersementLink__c = paiementVersementId <> null ? paiementVersementId : null;
        newCallSucLog.JSONSOAPBodySent__c = response == NULL ? bodySent : bodySent + '\r\n' + 'response : ' + response.getBody();
        newCallSucLog.JSONSOAPBodySent__c = newCallSucLog.JSONSOAPBodySent__c.length() > 32768 ? newCallSucLog.JSONSOAPBodySent__c.left(32767) : newCallSucLog.JSONSOAPBodySent__c;
        newCallSucLog.CalloutStatusCode__c = string.valueOf(response?.getStatusCode());
        insert newCallSucLog; 
    }
    
    /***
    * @description Log the answer of a callout as an error in the CalloutErrorsManagement__c object. The message error is stored is the field CalloutErrorMessage__c
    * @param string calloutName Concatenation of the name of the external system and the name of the external services called
    * @param id caseId Case id linked to the record that triggers the callout
    * @param id documentId Document__c id if the record that triggers the callout is a Document__c
    * @param id paiementVersementId Paiement_Versement__c id if the record that triggers the callout is a Paiement_Versement__c
    * @param string bodySent Body of the performed callout
    * @param httpResponse response Response of the performed callout
    * @param string catchError Exception thrown by the try catch if the code is not entirely performed
    * @return null
    */
    public static void logError(string calloutName, id caseId, id documentId, id paiementVersementId, String bodySent, httpResponse response, string catchError){
        
        String resp = '';
        
        if(response != null){
            resp = response.getBody();
            if(resp == NULL){
                resp = 'No Response';
            }
        }
        
        CalloutErrorsManagement__c newCallErrLog = new CalloutErrorsManagement__c();
        newCallErrLog.Name = calloutName;
        newCallErrLog.CaseRecord__c = caseId;
        newCallErrLog.DocumentLink__c = documentId <> null ? documentId : null;
        newCallErrLog.PaiementVersementLink__c = paiementVersementId <> null ? paiementVersementId : null;
        newCallErrLog.JSONSOAPBodySent__c = bodySent;
        newCallErrLog.JSONSOAPBodySent__c = newCallErrLog.JSONSOAPBodySent__c.length() > 32768 ? newCallErrLog.JSONSOAPBodySent__c.left(32767) : newCallErrLog.JSONSOAPBodySent__c;
        newCallErrLog.CalloutStatusCode__c = string.valueOf(response?.getStatusCode());
        if(catchError == null){
            newCallErrLog.CalloutErrorMessage__c = response.getStatus() + '\r\n' + 'response : ' + resp;
        }else{
            newCallErrLog.CalloutErrorMessage__c = 'response : ' + resp + catchError;     
        }
        insert newCallErrLog; 
    }
}