hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/CalloutErrorsManagement__c.object-meta.xml
<CustomObject>
    <description>This object allows to store all information from callout of Salesforce platform.</description>
    <label>Management of Callout Errors</label>
    <nameField>
        <label>Callout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management of Callout Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/fields/CalloutErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>CalloutErrorMessage__c</fullName>
    <description>Message to identify the error. Link to the error code</description>
    <label>Error message in the callout</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/fields/CalloutStatusCode__c.field-meta.xml
<CustomField>
    <fullName>CalloutStatusCode__c</fullName>
    <description>Status code to identify the answer.</description>
    <label>Status code in the callout</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hubSide/force-app/main/default/objects/CalloutErrorsManagement__c/fields/CaseRecord__c.field-meta.xml
<CustomField>
    <fullName>CaseRecord__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the case</description>
    <label>Case Record</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Management of Callout Errors</relationshipLabel>
    <relationshipName>ManagementCalloutErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/ContactPhone__c.field-meta.xml
<CustomField>
    <fullName>ContactPhone__c</fullName>
    <label>Téléphone de contact</label>
    <type>Phone</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Email_Contact__c.field-meta.xml
<CustomField>
    <fullName>Email_Contact__c</fullName>
    <label>Email Contact</label>
    <type>Email</type>
</CustomField>

hubSide/force-app/main/default/objects/Case/fields/Typologie_Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Typologie_Sinistre__c</fullName>
    <label>Typologie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Case_Typologie</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/Colis__c.object-meta.xml
<CustomObject>
    <label>Colis</label>
    <nameField>
        <label>Colis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hubSide/force-app/main/default/objects/Colis__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Colis</relationshipLabel>
    <relationshipName>Colis</relationshipName>
    <type>Lookup</type>
</CustomField>

hubSide/force-app/main/default/objects/Colis__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Colis_Status</valueSetName>
    </valueSet>
</CustomField>

hubSide/force-app/main/default/globalValueSets/Case_Typologie.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Broken</fullName>
        <label>Casse</label>
    </customValue>
    <customValue>
        <fullName>Pickpocketed</fullName>
        <label>Vol toute cause</label>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
        <label>Perte</label>
    </customValue>
    <customValue>
        <fullName>Oxidised</fullName>
        <label>Oxydation</label>
    </customValue>
    <customValue>
        <fullName>Robbed</fullName>
        <label>Vol Caractérisé</label>
    </customValue>
    <customValue>
        <fullName>ReturnedByCarrier</fullName>
        <label>Retour transporteur</label>
    </customValue>
    <customValue>
        <fullName>LostByCarrier</fullName>
        <label>Perte transporteur</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterRepair</fullName>
        <label>Dysfonctionnement suite à réparation</label>
    </customValue>
    <customValue>
        <fullName>DysfonctionsAfterExchange</fullName>
        <label>Dysfonctionnement suite à échange</label>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <label>Autres</label>
    </customValue>
    <customValue>
        <fullName>ClaimCreation</fullName>
        <label>Création Réclamation</label>
    </customValue>
    <customValue>
        <fullName>ClaimFollowUp</fullName>
        <label>Suivi Réclamation</label>
    </customValue>
    <customValue>
        <fullName>AccidentCreation</fullName>
        <label>Création Sinistre</label>
    </customValue>
    <description>Liste de toutes les typologies possibles (Sinistre, SAV, Demande)</description>
    <masterLabel>Case_Typologie</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/globalValueSets/Colis_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Reçu</fullName>
    </customValue>
    <customValue>
        <fullName>Transféré/Emis</fullName>
    </customValue>
    <customValue>
        <fullName>Transféré/Reçu</fullName>
    </customValue>
    <customValue>
        <fullName>Affecté</fullName>
    </customValue>
    <customValue>
        <fullName>Rattaché</fullName>
    </customValue>
    <customValue>
        <fullName>Non identifiable</fullName>
    </customValue>
    <customValue>
        <fullName>Invalid</fullName>
        <label>Invalidé</label>
    </customValue>
    <customValue>
        <fullName>Retourner colis</fullName>
    </customValue>
    <customValue>
        <fullName>Colis Retourné</fullName>
    </customValue>
    <masterLabel>Colis_Status</masterLabel>
</GlobalValueSet>

hubSide/force-app/main/default/classes/Flow_ColisRattacheSendSMSTest.cls
@isTest
private class Flow_ColisRattacheSendSMSTest {
    
    static final String EXTERNALSYSTEM_ORANGE = 'Orange';
    static final String ENDPOINTNAME_AUTHORANGE = 'Oauth';
    static final String ENDPOINTNAME_SMSORANGE = 'Diffusion-requests';
    static final String COLIS_STATUT = 'Rattaché';
    public static final String PROFILE_TC = 'SFAM Reparation';
    public static User RepUser;
    public static Case s;
    
    /***
    * @description Static method to initialize all the data for the test methods
    */
    static{
       
        Id profileTCId = [Select Id From Profile  
                             Where name =: PROFILE_TC
                            ].Id;
        
        RepUser = TestFactory.createUser();
        RepUser.ProfileId = profileTCId;
        insert RepUser;
    
        s = TestFactory.createSinistre();
        s.ContactPhone__c = '0600000000';
        s.Typologie_Sinistre__c = 'Broken';
        s.Email_Contact__c ='test@test.fr.invalid';
        insert s;
        
        // Create 1 colis
        List<Colis__c> colisList = TestFactory.createColis(1);
        insert colisList;
    }
    
    
    /***
    * @description Test method for the flow ColisAfterUpdate and the sendSMS method in OrangeCallout class. 
    * This test method mocks a fake response with a success for the authentication callout in return.
    */
    @isTest
    static void test_sendSMS200() {
        
        String fakeBody = '{"access_token":"123","token_type":"bearer","scope":"api","ttl":3600}';
        HttpMockFactory mock = new HttpMockFactory(200,'', fakeBody, new Map<String,String>{'Keep-Alive' => 'yes'});
        Test.setMock(HttpCalloutMock.class, mock);
        Colis__c cl;
        Test.startTest();
        System.runAs(RepUser){
            Case sin =  [SELECT Id FROM Case limit 1];
            cl = [SELECT Id FROM Colis__c limit 1];
            cl.Sinistre__c = sin.Id;
            cl.Statut__c = COLIS_STATUT;
            update cl;
                      
        }
        Test.stopTest();
        system.assertEquals(null, [SELECT id, CalloutErrorMessage__c 
                                   FROM CalloutErrorsManagement__c
                                   WHERE CaseRecord__c =: cl.Sinistre__c 
                                   AND Name =: EXTERNALSYSTEM_ORANGE + ' ' + ENDPOINTNAME_AUTHORANGE].CalloutErrorMessage__c);
        system.assertEquals(200, Integer.valueOf([SELECT id, CalloutStatusCode__c 
                                                  FROM CalloutErrorsManagement__c 
                                                  WHERE CaseRecord__c =: cl.Sinistre__c 
                                                  AND Name =: EXTERNALSYSTEM_ORANGE + ' ' + ENDPOINTNAME_AUTHORANGE].CalloutStatusCode__c));
    }
    
    
    /***
    * @description Test method for the flow ColisAfterUpdate and the sendSMS method in OrangeCallout class. 
    * This test method mocks a fake response with a 401 error for the authentication callout in return.
    */
    @isTest
    static void test_sendSMS401() {
        
        HttpMockFactory mock = new HttpMockFactory(401,'Unauthorized', '', new Map<String,String>{'Keep-Alive' => 'yes'});
        Test.setMock(HttpCalloutMock.class, mock);
        Colis__c cl;
        Test.startTest();
        System.runAs(RepUser){
            Case sin =  [SELECT Id FROM Case limit 1];
            cl = [SELECT Id FROM Colis__c limit 1];
            cl.Sinistre__c = sin.Id;
            cl.Statut__c = COLIS_STATUT;
            update cl;
        }
        Test.stopTest();
        List <CalloutErrorsManagement__c> Call = [SELECT id, CalloutErrorMessage__c 
        FROM CalloutErrorsManagement__c 
        WHERE CaseRecord__c =: cl.Sinistre__c
        AND Name =: EXTERNALSYSTEM_ORANGE + ' ' + ENDPOINTNAME_AUTHORANGE];
        System.debug(Call);
        system.assert([SELECT id, CalloutErrorMessage__c 
                       FROM CalloutErrorsManagement__c 
                       WHERE CaseRecord__c =: cl.Sinistre__c
                       AND Name =: EXTERNALSYSTEM_ORANGE + ' ' + ENDPOINTNAME_AUTHORANGE].CalloutErrorMessage__c.contains('Unauthorized'));
        system.assertEquals(401, Integer.valueOf([SELECT id, CalloutStatusCode__c 
            FROM CalloutErrorsManagement__c 
            WHERE CaseRecord__c =: cl.Sinistre__c 
            AND Name =: EXTERNALSYSTEM_ORANGE + ' ' + ENDPOINTNAME_AUTHORANGE].CalloutStatusCode__c));
    }
}